import React,{Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,Camera,Check,Compass,Gem,Globe2,HelpCircle,KeyRound,MapPin,MessageCircle,RefreshCw,Settings2,ShieldCheck,Sparkles,Trash2,Volume2,VolumeX,X} from 'lucide-react';
import {Button,Modal} from '../../design-system/index.jsx';
import {INVISIBLE_EPISODES,INVISIBLE_CONVERGENCE,INVISIBLE_REALMS,getInvisibleEpisode} from './catalog.js';
import {invisibleEpisodeProgress,invisibleCampaignSummary} from './progression.js';
import InvisibleMap from './InvisibleMap.jsx';
import WalkCheck from './WalkCheck.jsx';
import GuardianPanel from './GuardianPanel.jsx';
import CooperationPanel from './CooperationPanel.jsx';
import useInvisibleAudio from './useInvisibleAudio.js';
import './campaign.css';
const LensExperience=React.lazy(()=>import('./LensExperience.jsx'));
const InvisiblePortal=React.lazy(()=>import('./InvisiblePortal.jsx'));
const views=[['adventure','Aventure',Compass],['realms','Royaumes',Globe2],['journal','Journal',BookOpen],['missions','Missions',Sparkles]];

export default function CampaignExperience({uid,save,loaded,loadBlocked,saving,status,saveMessage,error,notice,selected,answer,onAnswerChange,onSelectPoint,onSelectEpisode,onStart,onSubmit,onChest,onPortal,onMode,onMemory,onForget,onConverge,onSync,onRecover,goTo,view:requestedView,onViewChange}){
 const state=save.invisible,episode=getInvisibleEpisode(state.activeEpisode),progress=invisibleEpisodeProgress(state,episode.id),summary=invisibleCampaignSummary(state);
 const point=episode.points.find(item=>!progress.solved.includes(item.id));
 const nextEpisode=INVISIBLE_EPISODES.find(item=>item.id!==episode.id&&!invisibleEpisodeProgress(state,item.id).portalOpened);
 const [localView,setLocalView]=useState('adventure'),[panel,setPanel]=useState(null),[lens,setLens]=useState(false),[finalAnswer,setFinalAnswer]=useState(''),[mapSelection,setMapSelection]=useState(episode.points[0].id);
 const view=views.some(row=>row[0]===requestedView)?requestedView:localView;
 const content=useRef(null),pendingFocus=useRef(false),previousView=useRef(view);
 const audio=useInvisibleAudio(episode.realm);
 const closePanel=useCallback(()=>setPanel(null),[]);
 const stage=!progress.started?'start':point?'riddle':!progress.chestOpened?'chest':!progress.portalOpened?'portal':summary.convergenceReady&&!summary.convergenceCompleted?'finale':nextEpisode?'next':'complete';
 const saveLabel=loadBlocked?'Compte à récupérer':saving?'Synchronisation…':status?.outcome==='synced'?'Compte synchronisé':status?.outcome==='pending'?'Synchronisation en attente':loaded?'Sauvegarde locale':'Chargement…';
 function switchView(next){setPanel(null);pendingFocus.current=true;if(onViewChange)onViewChange(next);else setLocalView(next);}
 function selectRealm(id){if(id!==episode.id)onSelectEpisode(id);switchView('adventure');}
 useEffect(()=>{setFinalAnswer('');setPanel(null);setLens(false);setMapSelection(episode.points[0].id);},[episode.id,uid]);
 useEffect(()=>{if(point&&selected!==point.id)onSelectPoint(point.id);},[point?.id,selected,onSelectPoint]);
 useEffect(()=>{
  if(previousView.current===view)return;
  previousView.current=view;pendingFocus.current=true;setPanel(null);setLens(false);
 },[view]);
 useEffect(()=>{
  if(!pendingFocus.current||panel||lens)return;
  const target=view==='adventure'?(content.current?.querySelector('input')||content.current?.querySelector('[data-primary-action]')||content.current):(content.current?.querySelector('h2')||content.current);
  if(!target)return;pendingFocus.current=false;
  if(target.tagName==='H2')target.tabIndex=-1;target.focus({preventScroll:true});
  const bounds=target.getBoundingClientRect();if(bounds.top<110||bounds.bottom>window.innerHeight-100)target.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});
 },[stage,point?.id,view,episode.id,panel,lens]);
 function start(){pendingFocus.current=true;onStart();}
 function answerSubmit(event){if(onSubmit(event)){pendingFocus.current=true;audio.chime();}}
 function openChest(){pendingFocus.current=true;if(onChest())audio.chime('fragment');}
 function openPortal(){pendingFocus.current=true;if(onPortal())audio.chime('portal');}
 function closeLens(){setLens(false);switchView('adventure');}
 const activeRealm=INVISIBLE_REALMS.find(item=>item.id===episode.realm)?.name;
 const panelTitle={guardian:'Parler à '+episode.guardian,map:'La carte de l’aventure',settings:'Réglages de l’aventure',help:'Comment jouer ?'}[panel];

 return <section className="invisible-page invisible-campaign invisible-simple" data-testid="invisible-page" data-realm={episode.realm} aria-label="Le Monde Invisible">
  <header className="simple-world-header"><div><p className="invisible-eyebrow">LE MONDE INVISIBLE</p><h1>{view==='adventure'?episode.city:views.find(row=>row[0]===view)?.[1]}</h1></div><div className="simple-header-actions"><Button variant="ghost" onClick={()=>goTo('world3b')} aria-label="Retour au Monde 3B"><ArrowLeft size={18}/></Button><Button data-testid="invisible-open-settings" variant="ghost" onClick={()=>setPanel('settings')} aria-label="Réglages de l’aventure"><Settings2 size={18}/></Button><Button data-testid="invisible-open-help" variant="ghost" onClick={()=>setPanel('help')} aria-label="Comment jouer ?"><HelpCircle size={18}/></Button></div></header>
  <nav className="simple-world-nav" aria-label="Navigation du Monde Invisible"><Button className="simple-camera-tab" data-testid="open-invisible-lens" variant="ghost" disabled={!loaded} onClick={()=>setLens(true)}><Camera size={18} aria-hidden="true"/><span>Caméra</span></Button>{views.map(([id,label,Icon])=><Button key={id} data-testid={'invisible-nav-'+id} variant="ghost" aria-current={view===id?'page':undefined} onClick={()=>switchView(id)}><Icon size={17} aria-hidden="true"/><span>{label}</span></Button>)}</nav>
  {loadBlocked&&<div className="invisible-recovery" role="alert"><p>{saveMessage}</p><Button onClick={onRecover}>Réessayer le chargement</Button>{status?.outcome==='auth'&&<Button variant="ghost" onClick={()=>goTo('member')}>Ouvrir mon Passeport</Button>}</div>}
  <div ref={content} tabIndex={-1} className="simple-world-content" data-testid={'invisible-view-'+view}>
   {view==='adventure'&&<>
    <section className={'simple-adventure-step simple-stage-'+stage} data-testid="invisible-current-objective" data-stage={stage} aria-label="Étape actuelle de l’aventure">
     {stage==='start'?<>
      <div className="simple-adventure-intro"><img data-testid="invisible-adventure-art" src={episode.realm==='france'?'/invisible/leman-adventure-v3.jpg':'/invisible/eight-kingdoms-v3.jpg'} width={1672} height={941} alt="Illustration de fiction de l’aventure et de ses portes" fetchPriority="high"/><div className="simple-intro-shade" aria-hidden="true"/><div><p className="invisible-eyebrow">{activeRealm} · AVENTURE DE FICTION</p><h2>{episode.realm==='france'?'Le secret du Léman':episode.title}</h2><p>{episode.guardian} t’attend. Résous trois énigmes pour retrouver le fragment de {episode.fragment.value.toLowerCase()}.</p></div></div>
      <div className="simple-step-copy"><p className="simple-step-sequence">3 énigmes <ArrowUpRight size={13}/> 1 coffre <ArrowUpRight size={13}/> 1 portail</p><Button data-testid="invisible-start" data-primary-action onClick={start} disabled={!loaded}>Commencer l’aventure <ArrowUpRight size={18}/></Button><p className="invisible-small">Tout est jouable ici. Déplacement, caméra et GPS sont facultatifs.</p></div>
     </>:stage==='riddle'?<div className="simple-step-copy simple-question" data-testid="invisible-riddle-panel">
      <div className="simple-question-meta" aria-live="polite" aria-atomic="true"><span className="invisible-eyebrow">ÉNIGME {episode.points.indexOf(point)+1} / 3</span><span>{point.name}</span></div><h2 id="invisible-riddle-title">{point.name}</h2>
      <form className="invisible-riddle-form" onSubmit={answerSubmit}><p id="invisible-riddle-question" className="invisible-question">{point.riddle.question}</p><label htmlFor="invisible-answer">Ta réponse</label><input id="invisible-answer" data-testid="riddle-answer" aria-describedby="invisible-riddle-question" value={answer} onChange={event=>onAnswerChange(event.target.value)} placeholder="Écris ta réponse…" autoComplete="off" maxLength={100} required disabled={!loaded}/><div className="simple-answer-actions"><Button type="submit" data-testid="riddle-submit" data-primary-action disabled={!loaded||!answer.trim()}>Révéler la trace <ArrowUpRight size={17}/></Button><details key={point.id} data-testid="riddle-clue"><summary>Révéler un indice facultatif</summary><p>{point.riddle.clue}</p></details></div></form>
     </div>:stage==='chest'?<div className="simple-step-copy simple-reveal"><div className="invisible-chest-art" aria-hidden="true"><div><Gem size={38}/></div></div><p className="invisible-eyebrow">LES TROIS ÉNIGMES SONT RÉSOLUES</p><h2>Le coffre de {episode.city}</h2><p>Ta clé est complète. Le fragment t’attend dans ce coffre virtuel.</p><Button data-testid="chest-open" data-primary-action disabled={!loaded} onClick={openChest}>Ouvrir le coffre <KeyRound size={18}/></Button><small>Récompense unique · +{episode.rewards.xp} XP Monde · +{episode.rewards.shards} éclats</small></div>:stage==='portal'?<>
      <Suspense fallback={<p role="status">Le portail prend forme…</p>}><InvisiblePortal key={episode.id} opened={false} realm={episode.realm} value={episode.fragment.value}/></Suspense><div className="simple-step-copy"><p className="invisible-eyebrow">FRAGMENT RETROUVÉ</p><h2>{episode.fragment.name}</h2><p>Il est conservé dans ton carnet. Réveille le passage pour terminer cette aventure.</p><Button data-testid="portal-open" data-primary-action disabled={!loaded} onClick={openPortal}>Activer le portail <Sparkles size={18}/></Button></div>
     </>:stage==='next'?<div className="simple-step-copy simple-reveal"><span className="simple-success-symbol" aria-hidden="true"><Check size={32}/></span><p className="invisible-eyebrow">AVENTURE ACCOMPLIE</p><h2>Le passage de {episode.city} est ouvert.</h2><p>La prochaine aventure t’attend à {nextEpisode.city}. Tes découvertes restent dans ton carnet.</p><Button data-testid="invisible-objective-action" data-primary-action disabled={!loaded} onClick={()=>selectRealm(nextEpisode.id)}>Continuer vers {nextEpisode.city} <ArrowUpRight size={18}/></Button><Button data-testid="portal-enter" variant="ghost" onClick={()=>goTo('world3b')}>Entrer dans le Monde 3B</Button></div>:stage==='finale'?<div className="simple-step-copy simple-question"><p className="invisible-eyebrow">LES HUIT FRAGMENTS SONT RÉUNIS</p><h2>{INVISIBLE_CONVERGENCE.title}</h2><form className="invisible-riddle-form" onSubmit={event=>{event.preventDefault();if(onConverge(finalAnswer)){pendingFocus.current=true;audio.chime('portal');}}}><p className="invisible-question">{INVISIBLE_CONVERGENCE.question||INVISIBLE_CONVERGENCE.riddle?.question}</p><label htmlFor="invisible-final-answer">Le mot du lien</label><input id="invisible-final-answer" data-testid="convergence-answer" maxLength={100} value={finalAnswer} onChange={event=>setFinalAnswer(event.target.value)} required disabled={!loaded}/><div className="simple-answer-actions"><Button data-testid="convergence-submit" data-primary-action type="submit" disabled={!loaded||!finalAnswer.trim()}>Réunir les huit valeurs</Button><details><summary>Révéler un indice facultatif</summary><p>{INVISIBLE_CONVERGENCE.clue||INVISIBLE_CONVERGENCE.riddle?.clue}</p></details></div></form></div>:<div className="simple-step-copy simple-reveal"><span className="simple-success-symbol" aria-hidden="true"><Check size={32}/></span><h2>Les huit valeurs sont réunies.</h2><p>Ton voyage reste dans le carnet. Le Cercle t’attend pour les missions collectives.</p><Button data-testid="invisible-objective-action" data-primary-action disabled={!loaded} onClick={()=>switchView('missions')}>Découvrir les missions <Sparkles size={18}/></Button></div>}
     {error&&<p className="invisible-feedback is-error simple-feedback" role="alert">{error}</p>}
    </section>
    <div className="simple-context-actions"><Button data-testid="invisible-open-guardian" variant="ghost" onClick={()=>setPanel('guardian')}><MessageCircle size={17}/>Le Gardien</Button><Button data-testid="invisible-open-map" variant="ghost" onClick={()=>setPanel('map')}><MapPin size={17}/>La carte</Button></div>
    <p className="simple-progress-note"><Gem size={14} aria-hidden="true"/>{summary.completed}/8 fragments retrouvés · {state.mode==='walk'?'Balade facultative':'Jeu à distance'}</p>
   </>}
   {view==='realms'&&<section className="simple-realms" aria-labelledby="invisible-realms-title"><h2 id="invisible-realms-title">Choisis ta prochaine aventure</h2><p className="invisible-muted">Les huit royaumes sont ouverts. Ta progression reste dans chaque aventure.</p><div className="simple-realm-list">{INVISIBLE_EPISODES.map(item=>{const journey=invisibleEpisodeProgress(state,item.id);return <Button key={item.id} data-testid={'episode-'+item.realm} variant="ghost" aria-current={item.id===episode.id?'true':undefined} onClick={()=>selectRealm(item.id)} disabled={!loaded}><span className="simple-realm-mark" aria-hidden="true">{journey.portalOpened?<Check size={20}/>:item.icon}</span><span><strong>{item.city}</strong><small>{INVISIBLE_REALMS.find(realm=>realm.id===item.realm)?.name} · {journey.portalOpened?'Aventure accomplie':journey.started?journey.solved.length+'/3 énigmes résolues':'À découvrir'}</small></span><ArrowUpRight size={19} aria-hidden="true"/></Button>;})}</div></section>}
   {view==='journal'&&<section className="simple-journal" aria-labelledby="invisible-journal-title"><h2 id="invisible-journal-title">Ton carnet de voyage</h2><p className="invisible-muted">{summary.completed}/8 fragments retrouvés · {episode.city}</p><div className="simple-fragments">{INVISIBLE_EPISODES.map(item=><span key={item.id} className={summary.fragments.includes(item.id)?'is-found':''}><Gem size={15}/>{item.fragment.value}</span>)}</div>{!progress.started?<p>Ton histoire commence à la première rencontre.</p>:<ol><li><strong>L’appel de {episode.city}</strong><p>{episode.guardian} te confie la recherche du fragment de {episode.fragment.value.toLowerCase()}.</p></li>{episode.points.filter(item=>progress.solved.includes(item.id)).map(item=><li key={item.id}><strong>{item.name}</strong><p>{item.story}</p></li>)}{progress.chestOpened&&<li><strong>{episode.fragment.name}</strong><p>Le fragment est conservé dans ton carnet du Monde Invisible.</p></li>}{progress.portalOpened&&<li><strong>Un passage éveillé</strong><p>Le portail de {episode.city} est activé.</p></li>}</ol>}<Button variant="ghost" onClick={()=>switchView('adventure')}>Reprendre mon aventure <ArrowUpRight size={16}/></Button></section>}
   {view==='missions'&&<CooperationPanel uid={uid} save={save}/>}
  </div>
  <p className="simple-save-note"><span className={'invisible-save-dot'+(status?.outcome==='synced'?' is-ready':'')} aria-hidden="true"/>{saveLabel}</p>
  {panel&&<Modal open title={panelTitle} onClose={closePanel} className="invisible-simple-panel"><div className="simple-panel-header"><h2>{panelTitle}</h2><Button data-testid="invisible-panel-close" variant="ghost" onClick={closePanel} aria-label="Fermer ce panneau"><X size={20}/></Button></div><div data-testid={'invisible-panel-'+panel}>
   {panel==='guardian'&&<GuardianPanel save={save}/>}
   {panel==='map'&&<><p>Cette carte est une illustration du récit. Aucun lieu réel n’est requis pour jouer.</p><InvisibleMap episode={episode} points={episode.points} solved={progress.solved} selected={mapSelection} started={progress.started} onSelect={setMapSelection}/><p>{episode.points.find(item=>item.id===mapSelection)?.description}</p></>}
   {panel==='settings'&&<><div className="simple-settings-group"><h3>Ta manière de jouer</h3><div className="simple-setting-actions"><Button data-testid="mode-remote" variant={state.mode==='remote'?'champagne':'ghost'} disabled={!loaded} aria-pressed={state.mode==='remote'} onClick={()=>onMode('remote')}><Globe2 size={16}/>À distance</Button><Button data-testid="mode-walk" variant={state.mode==='walk'?'champagne':'ghost'} disabled={!loaded} aria-pressed={state.mode==='walk'} onClick={()=>onMode('walk')}><MapPin size={16}/>En balade</Button></div><p>Les énigmes et récompenses restent accessibles sans caméra, GPS ou déplacement.</p>{state.mode==='walk'&&<WalkCheck onRemote={()=>onMode('remote')}/>}</div><div className="simple-settings-group"><h3>Ambiance sonore</h3><Button variant="ghost" onClick={audio.toggle} aria-pressed={audio.enabled}>{audio.enabled?<VolumeX size={16}/>:<Volume2 size={16}/>} {audio.enabled?'Couper l’ambiance':'Activer l’ambiance'}</Button>{audio.message&&<p role="status">{audio.message}</p>}</div><div className="simple-settings-group"><h3>Souvenirs facultatifs</h3><label className="simple-memory-label"><input type="checkbox" data-testid="invisible-memory-consent" checked={state.memoryConsent} disabled={!loaded} onChange={event=>onMemory(event.target.checked)}/><span>Autoriser le souvenir de mes prochaines découvertes<small>Uniquement des résumés de fiction. Les messages, images et positions ne sont pas mémorisés.</small></span></label><Button data-testid="forget-memory" variant="ghost" disabled={!loaded||(!state.memoryConsent&&!state.memory.length)} onClick={onForget}><Trash2 size={16}/>Supprimer les souvenirs</Button></div><div className="simple-settings-group"><h3>Sauvegarde</h3><p>{saveMessage}</p><Button data-testid="invisible-sync" variant="ghost" onClick={onSync} disabled={!loaded||saving}><RefreshCw size={16}/>Synchroniser l’aventure</Button>{notice&&<p role="status">{notice}</p>}</div></>}
   {panel==='help'&&<><ol className="simple-help-steps"><li><strong>Résous trois énigmes.</strong><p>Lis la question, écris ta réponse puis valide. Un indice est disponible uniquement si tu choisis de l’ouvrir.</p></li><li><strong>Ouvre le coffre.</strong><p>La troisième réponse forme ta clé. Le bouton du coffre apparaît aussitôt.</p></li><li><strong>Réveille le portail.</strong><p>Retrouve ton fragment puis passe au royaume suivant. La finale s’ouvre après les huit fragments.</p></li></ol><p>La 3D et la caméra sont une exploration facultative. Inspecter un objet ne valide aucune énigme et ne donne aucune récompense.</p><div className="simple-safety"><ShieldCheck size={18}/><p>{episode.safety}</p></div><details><summary>Fiction et sauvegarde</summary><p>{episode.fiction}</p><p>{saveMessage}</p></details></>}
  </div></Modal>}
  {lens&&<Suspense fallback={<div className="invisible-lens-loading" role="status"><p>Le monde invisible prend forme…</p><Button variant="ghost" onClick={closeLens}>Annuler</Button></div>}><LensExperience key={uid+':'+episode.id} episode={episode} progress={progress} onInspect={()=>{}} onExit={closeLens}/></Suspense>}
 </section>;
}
