import React,{Suspense,useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,Camera,Check,Compass,Gem,Globe2,KeyRound,MapPin,RefreshCw,ShieldCheck,Sparkles,Trash2,Volume2,VolumeX} from 'lucide-react';
import {Button,Progress} from '../../design-system/index.jsx';
import {INVISIBLE_EPISODES,INVISIBLE_CONVERGENCE,INVISIBLE_REALMS,getInvisibleEpisode} from './catalog.js';
import {invisibleEpisodeProgress,invisibleCampaignSummary} from './progression.js';
import InvisibleMap from './InvisibleMap.jsx';
import WalkCheck from './WalkCheck.jsx';
import GuardianPanel from './GuardianPanel.jsx';
import CooperationPanel from './CooperationPanel.jsx';
import useInvisibleAudio from './useInvisibleAudio.js';
import './campaign.css';
const LensExperience=React.lazy(()=>import('./LensExperience.jsx'));
const InvisiblePortal=React.lazy(()=>import('./InvisiblePortal.jsx'));

export default function CampaignExperience({uid,save,loaded,loadBlocked,saving,status,saveMessage,error,notice,selected,answer,onAnswerChange,onSelectPoint,onSelectEpisode,onStart,onSubmit,onChest,onPortal,onMode,onMemory,onForget,onConverge,onSync,onRecover,goTo}){
 const state=save.invisible,episode=getInvisibleEpisode(state.activeEpisode),progress=invisibleEpisodeProgress(state,episode.id),summary=invisibleCampaignSummary(state);
 const point=episode.points.find(item=>item.id===selected)||episode.points[Math.min(progress.solved.length,episode.points.length-1)];
 const index=episode.points.indexOf(point),done=progress.solved.includes(point.id),allSolved=progress.solved.length===episode.points.length;
 const [lens,setLens]=useState(false),[finalAnswer,setFinalAnswer]=useState(''),[guided,setGuided]=useState(false),[inspection,setInspection]=useState('');
 const audio=useInvisibleAudio(episode.realm);
 useEffect(()=>{setFinalAnswer('');setGuided(false);setInspection('');setLens(false);},[episode.id,uid]);
 const saveLabel=loadBlocked?'Compte à récupérer':saving?'Synchronisation…':status?.outcome==='synced'?'Compte synchronisé':status?.outcome==='pending'?'Synchronisation en attente':loaded?'Aventure conservée sur cet appareil':'Chargement…';
 const complete=progress.solved.length+(progress.chestOpened?1:0)+(progress.portalOpened?1:0);
 function inspect(row){const target=episode.points.find(item=>item.id===row?.id);setInspection(target?target.riddle.clue:row?.kind==='chest'?'Le coffre s’ouvre après les trois énigmes de cette aventure.':row?.kind==='fragment'?episode.fragment.name+' se retrouve en résolvant les trois énigmes puis en ouvrant le coffre.':row?.kind==='guardian'?episode.guardian+' accompagne la recherche du fragment de '+episode.fragment.value+'.':'Ce portail relie cette aventure à ton Monde 3B.');if(target)onSelectPoint(target.id);}
 function answerSubmit(event){if(onSubmit(event))audio.chime();}
 return <section className="invisible-page invisible-campaign" data-testid="invisible-page" data-realm={episode.realm} aria-label="Le Monde Invisible">
  <div className="invisible-topbar"><Button variant="ghost" onClick={()=>goTo('world3b')}><ArrowLeft size={16} aria-hidden="true"/>Monde 3B</Button><span className="invisible-top-signature">3B / LE MONDE INVISIBLE</span><div className="invisible-save"><span className={'invisible-save-dot'+(status?.outcome==='synced'?' is-ready':'')} aria-hidden="true"/><span>{saveLabel}</span><Button variant="ghost" size="sm" onClick={onSync} disabled={!loaded||saving} aria-label="Synchroniser l’aventure"><RefreshCw size={14} aria-hidden="true"/></Button></div></div>
  <header className="invisible-hero"><div className="invisible-hero-copy"><p className="invisible-eyebrow"><span/>HUIT ROYAUMES · UN MÊME LIEN</p><h1>Regarde autrement.<br/><em>Le monde s’éveille.</em></h1><p>Des fragments, des Gardiens et des passages t’attendent. Choisis une aventure, révèle ses trois secrets et réunis les huit valeurs du 3B.</p><div className="invisible-hero-meta"><span><Gem size={16} aria-hidden="true"/>{summary.completed}/8 fragments retrouvés</span><span><Globe2 size={16} aria-hidden="true"/>24 énigmes · une grande finale</span></div><div className="invisible-hero-actions"><Button data-testid="open-invisible-lens" disabled={!loaded} onClick={()=>setLens(true)}><Camera size={18} aria-hidden="true"/>Ouvrir l’exploration visuelle</Button><Button variant="ghost" onClick={audio.toggle} aria-pressed={audio.enabled}>{audio.enabled?<VolumeX size={17} aria-hidden="true"/>:<Volume2 size={17} aria-hidden="true"/>}{audio.enabled?'Couper l’ambiance':'Activer l’ambiance sonore'}</Button></div><p className="invisible-small">Caméra facultative · objets 3D à inspecter · toute l’aventure accessible à distance</p></div><div className="invisible-hero-emblem invisible-campaign-emblem" aria-hidden="true"><div className="invisible-orbit orbit-one"/><div className="invisible-orbit orbit-two"/><div className="invisible-emblem-core"><Gem size={64} strokeWidth={.9}/></div><span>{episode.fragment.value.toUpperCase()}</span><small>{episode.city.toUpperCase()}</small><div className="invisible-emblem-stars">{INVISIBLE_EPISODES.map(item=><i key={item.id} className={summary.fragments.includes(item.id)?'is-lit':''}/>)}</div></div></header>
  {audio.message&&<p className="invisible-small" role="status">{audio.message}</p>}
  <section className="invisible-how" aria-label="Comment jouer"><div><span>01</span><strong>Choisis ton royaume</strong><p>Les huit aventures sont ouvertes. Tu peux changer quand tu veux.</p></div><div><span>02</span><strong>Trouve trois réponses</strong><p>Lis, observe ou inspecte les objets 3D. Un indice et une aide guidée restent disponibles.</p></div><div><span>03</span><strong>Réunis les fragments</strong><p>Ouvre les coffres, réveille les portails et participe aux énigmes collectives.</p></div></section>
  {loadBlocked&&<div className="invisible-recovery" role="alert"><p>{saveMessage}</p><p>Récupère ton compte pour poursuivre avec ta sauvegarde.</p><Button onClick={onRecover}>Réessayer le chargement</Button>{status?.outcome==='auth'&&<Button variant="ghost" onClick={()=>goTo('member')}>Ouvrir mon Passeport</Button>}</div>}
  <section className="invisible-realm-selection" aria-labelledby="invisible-realms-title"><div className="invisible-section-heading"><div><p className="invisible-eyebrow">ATLAS DES HUIT ROYAUMES</p><h2 id="invisible-realms-title">Ta prochaine porte</h2></div><span className="invisible-pill">{summary.completed}/8 fragments</span></div><div className="invisible-realm-cards">{INVISIBLE_EPISODES.map((item,i)=>{const journey=invisibleEpisodeProgress(state,item.id),active=item.id===episode.id;return <Button data-testid={'episode-'+item.realm} className={'invisible-realm-card'+(active?' is-selected':'')+(journey.chestOpened?' is-complete':'')} variant="ghost" key={item.id} disabled={!loaded} aria-pressed={active} onClick={()=>onSelectEpisode(item.id)}><span className="invisible-realm-card-number">0{i+1}</span><span className="invisible-realm-card-body"><strong>{item.city}</strong><span>{INVISIBLE_REALMS.find(realm=>realm.id===item.realm)?.name} · {item.fragment.value}</span><small>{item.title}</small><span className="invisible-realm-card-progress"><i style={{width:(journey.solved.length/3*100)+'%'}}/></span></span><span className="invisible-realm-card-status">{journey.chestOpened?<Check size={19} aria-hidden="true"/>:<Gem size={19} aria-hidden="true"/>}<small>{journey.chestOpened?'Fragment':'Explorer'}</small></span></Button>;})}</div></section>
  <section className="invisible-adventure-head" aria-labelledby="invisible-episode-title"><div><p className="invisible-eyebrow">{episode.city.toUpperCase()} / {episode.fragment.value.toUpperCase()}</p><h2 id="invisible-episode-title">{episode.title}</h2><p>{episode.description}</p></div><div className="invisible-progress-summary"><span>{complete}/5 découvertes</span><Progress value={complete/5*100} label="Progression de cette aventure"/><small>{progress.portalOpened?'Le passage est ouvert':progress.chestOpened?'Le fragment est retrouvé':allSolved?'Le coffre attend ta clé':'Trois traces à relier'}</small></div></section>
  <div className="invisible-mode-row" role="group" aria-label="Choisir la manière de jouer"><Button data-testid="mode-remote" variant={state.mode==='remote'?'champagne':'ghost'} aria-pressed={state.mode==='remote'} disabled={!loaded} onClick={()=>onMode('remote')}><Globe2 size={16} aria-hidden="true"/>À distance</Button><Button data-testid="mode-walk" variant={state.mode==='walk'?'champagne':'ghost'} aria-pressed={state.mode==='walk'} disabled={!loaded} onClick={()=>onMode('walk')}><MapPin size={16} aria-hidden="true"/>En balade</Button><span>{state.mode==='remote'?'Joue depuis ici : énigmes, objets 3D et récompenses sont accessibles.':'Arrête-toi pour explorer. Le GPS est un repère facultatif ; la carte reste artistique.'}</span></div>
  {state.mode==='walk'&&<WalkCheck onRemote={()=>onMode('remote')}/>}
  <div className="invisible-play-grid"><section className="invisible-atlas" aria-labelledby="invisible-atlas-title"><div className="invisible-panel-heading"><h3 id="invisible-atlas-title"><Compass size={17} aria-hidden="true"/>Atlas de {episode.city}</h3><span>LES TROIS TRACES</span></div><InvisibleMap episode={episode} points={episode.points} solved={progress.solved} selected={point.id} started={progress.started} onSelect={onSelectPoint}/><Button className="invisible-atlas-lens" variant="ghost" disabled={!loaded} onClick={()=>setLens(true)}><Camera size={16} aria-hidden="true"/>Inspecter les objets en 3D</Button>{inspection&&<p className="invisible-feedback" role="status">{inspection}</p>}</section>
   <section className="invisible-riddle" aria-labelledby="invisible-riddle-title" data-testid="invisible-riddle-panel">{!progress.started?<><span className="invisible-story-icon" aria-hidden="true"><KeyRound size={28}/></span><p className="invisible-eyebrow">UNE INVITATION DE {episode.guardian.toUpperCase()}</p><h3 id="invisible-riddle-title">Une nouvelle trace t’attend.</h3><blockquote>« {episode.introduction||'Les fragments se cachent dans ce que nous oublions de regarder. Relie trois traces : une porte se réveillera.'} »</blockquote><p>Trois énigmes, un coffre et un fragment de {episode.fragment.value.toLowerCase()}. Écris une réponse ou utilise l’aide guidée.</p><Button data-testid="invisible-start" onClick={onStart} disabled={!loaded}><Sparkles size={17} aria-hidden="true"/>Commencer l’aventure</Button></>:<><div className="invisible-riddle-top"><span className="invisible-eyebrow">TRACE {index+1}/3</span><span className="invisible-status-pill">{done?<><Check size={13} aria-hidden="true"/>Retrouvée</>:'À déchiffrer'}</span></div><h3 id="invisible-riddle-title">{point.name}</h3><p className="invisible-small">{point.description}</p>{done?<div className="invisible-story-reveal"><Gem size={23} aria-hidden="true"/><p>{point.story}</p>{!allSolved&&<Button variant="ghost" onClick={()=>onSelectPoint(episode.points[progress.solved.length].id)}>Poursuivre vers la trace suivante <ArrowUpRight size={16} aria-hidden="true"/></Button>}</div>:<form onSubmit={answerSubmit} className="invisible-riddle-form"><p className="invisible-question">{point.riddle.question}</p><label htmlFor="invisible-answer">Ta réponse</label><input id="invisible-answer" data-testid="riddle-answer" value={answer} onChange={e=>onAnswerChange(e.target.value)} placeholder="Un mot suffit…" autoComplete="off" maxLength={100} required disabled={!loaded}/><div className="invisible-riddle-actions"><Button type="submit" data-testid="riddle-submit" disabled={!loaded||!answer.trim()}>Révéler la trace <ArrowUpRight size={16} aria-hidden="true"/></Button><details><summary>Besoin d’un indice ?</summary><p>{point.riddle.clue}</p></details></div><Button variant="ghost" size="sm" type="button" aria-expanded={guided} onClick={()=>setGuided(!guided)}>{guided?'Masquer les propositions':'Je débute : proposer trois réponses'}</Button>{guided&&<div className="invisible-guided-options" role="group" aria-label="Propositions de réponse">{(point.riddle.options||[point.riddle.answers[0],'le temps','le vent']).map(option=><Button key={option} variant="ghost" type="button" onClick={()=>onAnswerChange(option)}>{option}</Button>)}<small>Choisis une proposition, puis appuie sur « Révéler la trace ».</small></div>}</form>}</>}{error&&<p className="invisible-feedback is-error" role="alert">{error}</p>}{notice&&<p className="invisible-feedback" role="status">{notice}</p>}</section></div>
  {allSolved&&<section className="invisible-reward" aria-labelledby="invisible-chest-title"><div className="invisible-chest-art" aria-hidden="true"><div className={progress.chestOpened?'is-opened':''}><Gem size={38} strokeWidth={1}/></div></div><div><p className="invisible-eyebrow">{progress.chestOpened?'CARNET / FRAGMENT RETROUVÉ':'LES TROIS TRACES SONT RÉUNIES'}</p><h2 id="invisible-chest-title">{progress.chestOpened?episode.fragment.name:'Le coffre de '+episode.city}</h2><p>{progress.chestOpened?episode.conclusion||'Cette valeur rejoint ton carnet. Un passage relie maintenant cette aventure au Monde 3B.':'La clé est complète. Ouvre ce coffre virtuel pour conserver ton fragment.'}</p><div className="invisible-reward-meta"><span>+{episode.rewards.xp} XP Monde</span><span>+{episode.rewards.shards} éclats</span><span>Récompense unique</span></div>{!progress.chestOpened&&<Button data-testid="chest-open" onClick={()=>{if(onChest())audio.chime('fragment');}}><KeyRound size={16} aria-hidden="true"/>Ouvrir le coffre</Button>}</div></section>}
  {progress.chestOpened&&<section className="invisible-portal-section" aria-labelledby="invisible-portal-title"><Suspense fallback={<div className="invisible-loading" role="status">Le portail prend forme…</div>}><InvisiblePortal key={episode.id} opened={progress.portalOpened} realm={episode.realm} value={episode.fragment.value}/></Suspense><div className="invisible-portal-copy"><p className="invisible-eyebrow">UNE PORTE VERS TON UNIVERS</p><h2 id="invisible-portal-title">Le passage de {episode.fragment.value.toLowerCase()}</h2><p>Ton fragment et tes gains voyagent avec la sauvegarde de ton Passeport. Continue dans le Monde 3B ou retrouve le prochain royaume ici.</p>{!progress.portalOpened?<Button data-testid="portal-open" onClick={()=>{if(onPortal())audio.chime('portal');}}>Activer le portail <ArrowUpRight size={17} aria-hidden="true"/></Button>:<Button data-testid="portal-enter" onClick={()=>goTo('world3b')}>Entrer dans le Monde 3B <ArrowUpRight size={17} aria-hidden="true"/></Button>}<Button variant="ghost" onClick={()=>setLens(true)}><Camera size={16} aria-hidden="true"/>Explorer les objets et le Gardien</Button><small>Vérifie la synchronisation avant de changer d’appareil.</small></div></section>}
  <div className="invisible-bottom-grid"><section className="invisible-journal" aria-labelledby="invisible-journal-title"><div className="invisible-panel-heading"><h3 id="invisible-journal-title"><BookOpen size={17} aria-hidden="true"/>Ton journal · {episode.city}</h3><span>{progress.solved.length}/3 TRACES</span></div>{!progress.started?<p>Ton histoire commence à la première rencontre.</p>:<ol><li><span className="invisible-journal-dot"/><div><strong>L’appel de {episode.city}</strong><p>{episode.guardian} te confie la recherche du fragment de {episode.fragment.value.toLowerCase()}.</p></div></li>{episode.points.filter(item=>progress.solved.includes(item.id)).map(item=><li key={item.id}><span className="invisible-journal-dot"/><div><strong>{item.name}</strong><p>{item.story}</p></div></li>)}{progress.chestOpened&&<li><span className="invisible-journal-dot"/><div><strong>{episode.fragment.name}</strong><p>Le fragment est conservé dans ton carnet du Monde Invisible.</p></div></li>}{progress.portalOpened&&<li><span className="invisible-journal-dot"/><div><strong>Un passage éveillé</strong><p>Le portail de {episode.city} est activé.</p></div></li>}</ol>}<div className="invisible-fragment-shelf" aria-label="Fragments de la campagne">{INVISIBLE_EPISODES.map(item=><span className={summary.fragments.includes(item.id)?'is-found':''} key={item.id}><Gem size={15} aria-hidden="true"/>{item.fragment.value}</span>)}</div></section><section className="invisible-guardian-zone" aria-label="Rencontre avec le Gardien"><GuardianPanel save={save}/><div className="invisible-memory"><label><input type="checkbox" data-testid="invisible-memory-consent" checked={state.memoryConsent} disabled={!loaded} onChange={e=>onMemory(e.target.checked)}/><span><strong>Autoriser le souvenir de mes prochaines découvertes</strong><small>Uniquement des résumés de fiction. Les messages, les images et la position ne sont pas mémorisés.</small></span></label>{state.memoryConsent&&<p className="invisible-small">{state.memory.length} souvenir{state.memory.length!==1?'s':''} conservé{state.memory.length!==1?'s':''}.</p>}<Button data-testid="forget-memory" variant="ghost" size="sm" disabled={!loaded||(!state.memoryConsent&&!state.memory.length)} onClick={onForget}><Trash2 size={14} aria-hidden="true"/>Supprimer les souvenirs</Button></div></section></div>
  <section className={'invisible-convergence'+(summary.convergenceReady?' is-ready':'')} aria-labelledby="invisible-convergence-title"><div className="invisible-section-heading"><div><p className="invisible-eyebrow">FINALE DE LA CAMPAGNE</p><h2 id="invisible-convergence-title">{INVISIBLE_CONVERGENCE.title}</h2></div><span className="invisible-pill">{summary.convergenceCompleted?'Lien réuni':summary.completed+'/8 fragments'}</span></div><p>{summary.convergenceCompleted?INVISIBLE_CONVERGENCE.story||'Les huit valeurs se rejoignent. La transmission continue, portée par chaque rencontre.':INVISIBLE_CONVERGENCE.description||'Les huit fragments révèlent la dernière énigme de ton voyage.'}</p>{summary.convergenceReady&&!summary.convergenceCompleted?<form onSubmit={e=>{e.preventDefault();if(onConverge(finalAnswer))audio.chime('portal');}}><p className="invisible-question">{INVISIBLE_CONVERGENCE.question||INVISIBLE_CONVERGENCE.riddle?.question}</p><label htmlFor="invisible-final-answer">Le mot du lien</label><input id="invisible-final-answer" data-testid="convergence-answer" maxLength={100} value={finalAnswer} onChange={e=>setFinalAnswer(e.target.value)} required/><Button data-testid="convergence-submit" type="submit" disabled={!finalAnswer.trim()}>Réunir les huit valeurs</Button><details><summary>Un indice pour la finale</summary><p>{INVISIBLE_CONVERGENCE.clue||INVISIBLE_CONVERGENCE.riddle?.clue}</p></details></form>:!summary.convergenceReady?<p className="invisible-muted">Retrouve les huit fragments pour ouvrir cette dernière énigme. Tes découvertes sont conservées lorsque tu changes de royaume.</p>:<p className="invisible-notice" role="status">La campagne est terminée. Les missions collectives et les saisons continuent avec les autres voyageurs.</p>}{error&&summary.convergenceReady&&<p className="invisible-feedback is-error" role="alert">{error}</p>}</section>
  <CooperationPanel uid={uid} save={save}/>
  <footer className="invisible-footer"><div><ShieldCheck size={19} aria-hidden="true"/><div><strong>Explore à ton rythme et en sécurité.</strong><p>{episode.safety}</p></div></div><details><summary>À propos de cette aventure et de la sauvegarde</summary><p>{episode.fiction}</p><p>{saveMessage}</p><p>Les cartes sont artistiques. Aucun objet du jeu ne justifie une entrée dans une propriété privée, une approche de l’eau ou un déplacement vers un lieu fermé.</p></details></footer>
  {lens&&<Suspense fallback={<div className="invisible-lens-loading" role="status"><p>Le monde invisible prend forme…</p><Button variant="ghost" onClick={()=>setLens(false)}>Annuler</Button></div>}><LensExperience key={uid+':'+episode.id} episode={episode} progress={progress} onInspect={inspect} onExit={()=>setLens(false)}/></Suspense>}
 </section>;
}
