import CompactCard from '../components/CompactCard.jsx';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Heart,MessageCircle,Shield,Users,ArrowUpRight,Plus} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {authClient} from '../loyalty/client.js';
import {ecosystem} from '../lib/ecosystem.js';
import DesignPreview from '../ai/DesignPreview.jsx';
import './community.css';
const categories={all:'Tout',discussion:'Échanges',creation:'Créations',challenge:'Défis',collaboration:'Collaborations'};
const RULES_VERSION='2026-09-v1';
const dates=s=>new Date(s).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});
function initialDraft(){try{const draft=JSON.parse(sessionStorage.getItem('3b-studio-share')||'null');return draft&&typeof draft==='object'?draft:null;}catch{return null;}}
export default function CommunityPage({goTo}){
 const account=useLoyalty(),uid=account.user?.id;
 const[view,setView]=useState(()=>{if(initialDraft())return 'feed';try{return sessionStorage.getItem('3b-community-intent')==='chat'?'chat':'home';}catch{return 'home';}}),[category,setCategory]=useState('all'),[sort,setSort]=useState('created_at'),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const[draft,setDraft]=useState(initialDraft),[compose,setCompose]=useState(()=>!!initialDraft()),[title,setTitle]=useState(''),[body,setBody]=useState(''),[postKind,setPostKind]=useState(()=>initialDraft()?'creation':'discussion');
 const[acceptRules,setAcceptRules]=useState(false);
 const[bio,setBio]=useState(''),[kind,setKind]=useState('member'),[report,setReport]=useState(null),[reason,setReason]=useState(''),[reports,setReports]=useState([]);
 const lock=useRef(false),generation=useRef(0),reportDialog=useRef(null);
 useEffect(()=>{if(report)reportDialog.current?.showModal();},[report]);
 const refresh=useCallback(async()=>{if(!uid)return;const n=++generation.current;try{const r=await ecosystem('snapshot',{category,sort});if(n===generation.current){setData(r);setError('');}}catch(e){if(n===generation.current)setError(e.message);}},[uid,category,sort]);
 useEffect(()=>{refresh();return()=>{generation.current++;};},[refresh]);
 useEffect(()=>{if(data?.mine){setBio(data.mine.bio);setKind(data.mine.kind);setAcceptRules(data.mine.rules_version===RULES_VERSION&&!!data.mine.rules_accepted_at);}},[data?.mine?.bio,data?.mine?.kind,data?.mine?.rules_version,data?.mine?.rules_accepted_at]);
 useEffect(()=>{if(!uid)return;let timer;const update=()=>{clearTimeout(timer);timer=setTimeout(refresh,600);};const c=authClient.channel('community-feed-'+uid).on('postgres_changes',{event:'*',schema:'public',table:'community_posts'},update).on('postgres_changes',{event:'*',schema:'public',table:'community_likes'},update).subscribe();return()=>{clearTimeout(timer);authClient.removeChannel(c);};},[uid,refresh]);
 async function act(action,values,message){if(lock.current)return false;lock.current=true;setBusy(true);setNotice('');try{await ecosystem(action,values);if(message)setNotice(message);await refresh();return true;}catch(e){setNotice(e.message);return false;}finally{lock.current=false;setBusy(false);}}
 const enrolled=!!(data?.mine?.listed&&data.mine.rules_version===RULES_VERSION&&data.mine.rules_accepted_at);
 function join(mode){try{sessionStorage.setItem('3b-auth-intent',mode);sessionStorage.setItem('3b-community-intent','chat');}catch{}goTo('member');}
 function choose(id){setNotice('');setView(id);}
 const visibleProfiles=(data?.profiles||[]).filter(p=>(view!=='creators'||p.kind==='creator')&&(p.name+' '+p.handle+' '+p.bio).toLowerCase().includes(search.toLowerCase()));
 const author=id=>data?.postAuthors?.find(p=>p.user_id===id)||data?.profiles?.find(p=>p.user_id===id);
 const openReports=async()=>{setView('moderation');try{setReports((await ecosystem('reports')).reports);}catch(e){setNotice(e.message);}};
 return <section className="editorial-page community-page"><div className="editorial-heading"><p className="eyebrow">LE COLLECTIF 3B</p><h1>{view==='chat'?'Le salon 3B.':view==='feed'?'Les idées du collectif.':view==='members'||view==='creators'?'Le réseau 3B.':view==='profile'?'Ta place dans le collectif.':'Ensemble, créons la suite.'}</h1><p>Échange, propose une idée et rencontre celles et ceux qui font vivre le 3B.</p></div>
 {!uid?<><div className="compact-list"><CompactCard title="Le salon en direct" description="Discute avec les membres du collectif." icon={<MessageCircle/>} action="Rejoindre" onClick={()=>join('register')}/><CompactCard title="Idées & créations" description="Propose, échange et soutiens les concepts qui te parlent." icon={<Heart/>} onClick={()=>join('register')}/><CompactCard title="Membres & créateurs" description="Trouve des inspirations et des collaborations." icon={<Users/>} onClick={()=>join('register')}/></div><div className="surface-panel community-entry"><Shield size={25}/><div><h2>Entre dans le collectif.</h2><p>1. Crée ton compte ou connecte-toi.<br/>2. Prépare ton profil et accepte les règles.<br/>3. Rejoins le salon et les échanges.</p><div className="member-actions"><button className="surface-button" onClick={()=>join('register')}>Créer mon compte</button><button className="quiet-button" onClick={()=>join('login')}>J’ai déjà un compte</button></div></div></div></>:<>
 {view!=='home'&&<div className="community-view-nav"><button className="quiet-button" onClick={()=>choose('home')}>← Communauté</button><button className="quiet-button" onClick={()=>choose('profile')}>Mon profil</button></div>}
 {view==='home'&&<><div className="compact-list"><CompactCard title="Le salon en direct" eyebrow="DISCUTER" description="Un lieu commun pour échanger maintenant." icon={<MessageCircle/>} onClick={()=>choose('chat')}/><CompactCard title="Idées & créations" eyebrow="IMAGINER ENSEMBLE" description="Créations, défis et collaborations du collectif." icon={<Heart/>} onClick={()=>choose('feed')}/><CompactCard title="Membres & créateurs" eyebrow="SE RENCONTRER" description="Découvre les profils et suis leurs projets." icon={<Users/>} onClick={()=>choose('members')}/></div><div className="community-view-nav"><button className="quiet-button" onClick={()=>choose('profile')}>Mon profil communautaire</button>{data?.moderator&&<button className="quiet-button" onClick={openReports}>Modération</button>}</div><div className="community-invitation"><p className="eyebrow">LA PROCHAINE IDÉE PEUT ÊTRE LA TIENNE</p><CompactCard title="Imaginer une pièce 3B" description="L’atelier t’aide à préparer un concept à proposer au collectif." action="Créer" icon={<Plus/>} onClick={()=>goTo('ia-textile')}/></div></>}
 {error&&<p className="surface-notice" role="alert">{error} <button className="quiet-button" onClick={refresh}>Réessayer</button></p>}{notice&&<p className="surface-notice" role="status">{notice}</p>}
 {!data&&!error&&<p role="status">Ouverture de la communauté…</p>}
 {data&&!enrolled&&view!=='profile'&&<div className="surface-panel"><h2>Une dernière étape avant de participer.</h2><p>Ta session est connectée. Prépare ton profil et accepte les règles pour entrer dans le salon, publier et voter. Ton nom et ta présentation seront visibles des membres.</p><button className="surface-button" onClick={()=>setView('profile')}>Vérifier mon accès au collectif</button></div>}
 {view==='profile'&&<div className="community-profile-layout"><form className="surface-panel surface-form" onSubmit={async e=>{e.preventDefault();if(await act('profile',{bio,kind,listed:true,acceptRules},'Ton accès au collectif est prêt.')){setView(draft?'feed':'chat');try{sessionStorage.removeItem('3b-community-intent');}catch{}}}}><p className="eyebrow">TA PRÉSENTATION AU COLLECTIF</p><h2>{account.profile?.name||'Ton profil 3B'}</h2><label>Je participe comme<select value={kind} onChange={e=>setKind(e.target.value)}><option value="member">Membre</option><option value="creator">Créateur / créatrice</option></select></label><label>Quelques mots sur toi<textarea value={bio} maxLength={500} rows={4} onChange={e=>setBio(e.target.value)} placeholder="Tes inspirations, tes projets, ce que tu aimerais partager…"/></label><p className="muted-copy">Ton nom, ton identifiant, cette présentation et ton rôle choisi sont visibles des membres. « Créateur » est une présentation personnelle, sans certification.</p><label className="community-consent"><input type="checkbox" required checked={acceptRules} onChange={e=>setAcceptRules(e.target.checked)}/><span>J’accepte les règles du collectif : respect, créations autorisées, aucun harcèlement ni spam. Les échanges sont visibles des membres.</span></label><p className="muted-copy">Vérification d’accès : compte connecté, profil activé et charte acceptée.</p><button className="surface-button" disabled={busy||!acceptRules}>{data?.mine?.listed?'Enregistrer mon profil':'Activer mon profil public'}</button>{data?.mine?.listed&&<button className="quiet-button" type="button" disabled={busy} onClick={()=>act('profile',{bio,kind,listed:false},'Ton profil, tes publications et tes messages sont masqués. Tu peux les réactiver ici.')}>Masquer mon profil et mes échanges</button>}</form><article className="surface-panel"><h2>Tu gardes la main.</h2><p>Tu peux retirer tes contenus, signaler un message et bloquer un membre. Le blocage masque vos profils et échanges l’un pour l’autre.</p><h3>Membres bloqués</h3>{data?.blocks?.length?data.blocks.map(b=><div className="blocked-row" key={b.target_id}><span>Membre {b.target_id.slice(0,8)}</span><button className="quiet-button" disabled={busy} onClick={()=>act('block',{id:b.target_id,active:false},'Blocage retiré.')}>Débloquer</button></div>):<p>Aucun membre bloqué.</p>}</article></div>}
 {view==='feed'&&data&&<>
 <div className="community-controls"><div className="surface-tabs" aria-label="Types de publications">{Object.entries(categories).map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div><label className="community-sort">Trier<select value={sort} onChange={e=>setSort(e.target.value)}><option value="created_at">Plus récentes</option><option value="votes">Plus de votes</option></select></label><button className="surface-button" disabled={!enrolled} onClick={()=>setCompose(!compose)}><Plus size={17}/>{compose?'Fermer':'Publier'}</button></div>
 {category==='creation'&&<p className="surface-notice">Les créations les plus aimées remontent dans le classement. Leur production reste soumise à l’étude du modèle, des droits, des matières et du coût par 3B. Aucun lancement n’est automatique.</p>}
 {compose&&<form className="surface-panel surface-form community-composer" onSubmit={async e=>{e.preventDefault();if(await act('post',{id:crypto.randomUUID(),title,body,category:postKind,design:draft?.design,assetPath:draft?.assetPath},'Ta publication est en ligne.')){setCompose(false);setTitle('');setBody('');setDraft(null);try{sessionStorage.removeItem('3b-studio-share');}catch{}}}}><h2>Partager avec le collectif</h2>{draft?.design&&<div className="shared-draft"><DesignPreview design={draft.design}/><p>Ton concept de l’atelier 3B sera joint à la publication.</p></div>}<div className="form-columns"><label>Titre<input required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Catégorie<select value={postKind} onChange={e=>setPostKind(e.target.value)}>{Object.entries(categories).filter(([id])=>id!=='all').map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div><label>Ton message<textarea required maxLength={3000} rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><p className="muted-copy">Visible des membres connectés. Partage uniquement du contenu que tu as le droit de publier.</p><button className="surface-button" disabled={busy||!enrolled}>{busy?'Publication…':'Publier dans la communauté'}</button></form>}
 <div className="community-feed">{data.posts.length?data.posts.map(p=>{const a=author(p.author_id),liked=data.likes.some(l=>l.post_id===p.id);return <article key={p.id} className="community-post"><header><span className="member-avatar">{a?.name?.slice(0,1)||'3B'}</span><div><strong>{a?.name||'Membre 3B'}</strong><small>@{a?.handle} · {dates(p.created_at)}</small></div><span className="status-pill">{categories[p.category]}</span></header>{p.imageUrl?<img className="community-design-image" src={p.imageUrl} alt={p.title}/>:p.design?<DesignPreview design={p.design}/>:null}<div className="community-post-copy"><h2>{p.title}</h2><p>{p.body}</p></div><footer><button className="quiet-button" disabled={busy||p.author_id===uid||!enrolled} aria-pressed={liked} aria-label={(liked?'Retirer mon vote pour ':'Voter pour ')+p.title} onClick={()=>act('like',{id:p.id,active:!liked})}><Heart size={16} fill={liked?'currentColor':'none'}/>{p.votes} votes</button>{p.author_id===uid?<button className="text-button" disabled={busy} onClick={()=>act('remove',{id:p.id,kind:'post'},'Publication retirée.')}>Retirer</button>:<><button className="text-button" onClick={()=>{setReason('');setReport({id:p.id,kind:'post'});}}>Signaler</button><button className="text-button" disabled={busy} onClick={()=>act('block',{id:p.author_id,active:true},'Membre bloqué.')}>Bloquer</button></>}</footer></article>;}):<div className="surface-panel community-empty"><MessageCircle size={34}/><h2>La prochaine idée peut être la tienne.</h2><p>Aucune publication dans cette catégorie pour le moment.</p><button className="quiet-button" onClick={()=>goTo('ia-textile')}>Créer un concept dans l’atelier</button></div>}</div><p className="muted-copy">Les 60 premières publications selon le tri choisi. Un vote par compte et par publication ; aucun vote sur sa propre création.</p></>}
 {['members','creators'].includes(view)&&data&&<><div className="surface-tabs" aria-label="Profils du réseau"><button aria-pressed={view==='members'} onClick={()=>setView('members')}>Tous les membres</button><button aria-pressed={view==='creators'} onClick={()=>setView('creators')}>Créateurs</button></div><label className="surface-form">Rechercher un membre<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, identifiant ou inspiration…"/></label><div className="community-members">{visibleProfiles.map(p=><article className="surface-panel" key={p.user_id}><span className="member-avatar">{p.name.slice(0,1)}</span><h2>{p.name}</h2><p className="member-handle">@{p.handle} · {p.kind==='creator'?'Créateur':'Membre'}</p><p>{p.bio||'Une nouvelle histoire dans le collectif 3B.'}</p>{p.user_id!==uid&&<div className="member-actions"><button className="quiet-button" disabled={busy||!enrolled} onClick={()=>act('follow',{id:p.user_id,active:!data.follows.some(f=>f.target_id===p.user_id)})}>{data.follows.some(f=>f.target_id===p.user_id)?'Ne plus suivre':'Suivre'}</button><button className="text-button" disabled={busy} onClick={()=>act('block',{id:p.user_id,active:true},'Membre bloqué.')}>Bloquer</button></div>}</article>)}</div>{!visibleProfiles.length&&<p className="surface-notice">Aucun profil ne correspond à cette recherche.</p>}</>}
 {view==='chat'&&enrolled&&<ChatRoom uid={uid} enabled={enrolled} onReport={target=>{setReason('');setReport(target);}}/>}
 {view==='moderation'&&<div className="community-feed">{reports.length?reports.map(r=><article className="surface-panel" key={r.id}><h2>Signalement · {r.kind==='chat'?'Message':'Publication'}</h2><p>{r.reason}</p><blockquote>{r.content?.body||'Contenu retiré'}</blockquote><button className="quiet-button" disabled={busy} onClick={async()=>{await act('moderate',{id:r.id,hide:true},'Contenu masqué.');openReports();}}>Masquer le contenu</button><button className="quiet-button" disabled={busy} onClick={async()=>{await act('moderate',{id:r.id,hide:false},'Signalement classé.');openReports();}}>Classer sans masquer</button></article>):<p>Aucun signalement ouvert.</p>}</div>}
 {report&&<dialog ref={reportDialog} className="report-panel" aria-labelledby="report-title" onCancel={()=>setReport(null)}><form className="surface-panel surface-form" onSubmit={async e=>{e.preventDefault();if(await act('report',{...report,reason},'Signalement transmis à la file de modération.'))setReport(null);}}><h2 id="report-title">Signaler ce contenu</h2><label>Motif<textarea autoFocus required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explique le problème…"/></label><div className="member-actions"><button className="surface-button" disabled={busy}>Transmettre le signalement</button><button type="button" className="quiet-button" onClick={()=>setReport(null)}>Annuler</button></div></form></dialog>}
 </>}
 <details className="guide-faq"><summary>Les règles du collectif</summary><p>Respecte les personnes, leurs convictions et leurs créations. Pas de harcèlement, de spam, de divulgation de données privées ni de contenus illégaux. Les salons sont collectifs et visibles des membres ; ils ne constituent pas une messagerie privée. Un signalement permet une revue par la modération, sans garantie de traitement immédiat.</p></details></section>;
}
function ChatRoom({uid,enabled,onReport}){
 const[room,setRoom]=useState('general'),[messages,setMessages]=useState([]),[profiles,setProfiles]=useState([]),[status,setStatus]=useState('Connexion…'),[error,setError]=useState(''),[input,setInput]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),scroller=useRef(null),nearBottom=useRef(true);
 useEffect(()=>{let live=true,pending=false;const controller=new AbortController();setMessages([]);setProfiles([]);nearBottom.current=true;setStatus('Connexion…');const load=async()=>{if(pending||document.hidden)return;pending=true;try{const r=await ecosystem('chat-list',{room},{signal:controller.signal});if(live){setMessages(r.messages);setProfiles(r.profiles);setError('');}}catch(e){if(live)setError(e.message);}finally{pending=false;}};load();const c=authClient.channel('chat-'+room+'-'+uid).on('postgres_changes',{event:'*',schema:'public',table:'community_chat',filter:'room=eq.'+room},load).subscribe(s=>{if(live)setStatus(s==='SUBSCRIBED'?'En direct':s==='CHANNEL_ERROR'||s==='TIMED_OUT'?'Reconnexion · actualisation toutes les 15 s':'Connexion…');});const interval=setInterval(load,15000);document.addEventListener('visibilitychange',load);return()=>{live=false;controller.abort();clearInterval(interval);document.removeEventListener('visibilitychange',load);authClient.removeChannel(c);};},[uid,room]);
 useEffect(()=>{const el=scroller.current;if(el&&nearBottom.current)el.scrollTop=el.scrollHeight;},[messages]);
 return <div className="chat-shell"><label className="chat-room-select">Salon<select value={room} disabled={busy} onChange={e=>setRoom(e.target.value)}><option value="general">Le salon 3B</option><option value="atelier">Créateurs & atelier</option><option value="sport">Sport & défis</option></select></label><section className="chat-room"><header><h2>{room==='general'?'Le salon 3B':room==='atelier'?'Créateurs & atelier':'Sport & défis'}</h2><span className="status-pill">{status}</span></header><div ref={scroller} onScroll={e=>{const el=e.currentTarget;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;}} className="chat-messages" role="log" aria-label="Messages du salon" aria-live="polite">{messages.length?messages.map(m=><article key={m.id} className={m.author_id===uid?'own':''}><div><strong>{profiles.find(p=>p.user_id===m.author_id)?.name||'Membre'}</strong><time>{dates(m.created_at)}</time></div><p>{m.body}</p>{m.author_id!==uid?<button className="text-button" onClick={()=>onReport({id:m.id,kind:'chat'})}>Signaler</button>:<button className="text-button" disabled={busy} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);try{await ecosystem('remove',{id:m.id,kind:'chat'});setMessages(items=>items.filter(item=>item.id!==m.id));}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}}>Retirer</button>}</article>):<p className="muted-copy">Le salon attend ses premiers échanges.</p>}</div>{error&&<p className="surface-notice" role="alert">{error}</p>}<form className="chat-composer" onSubmit={async e=>{e.preventDefault();if(lock.current||!input.trim())return;lock.current=true;setBusy(true);try{await ecosystem('chat-send',{id:crypto.randomUUID(),room,text:input});setInput('');nearBottom.current=true;const r=await ecosystem('chat-list',{room});setMessages(r.messages);setProfiles(r.profiles);}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}}><label className="sr-only" htmlFor="chat-input">Message au salon</label><textarea id="chat-input" rows={2} required maxLength={1500} value={input} disabled={!enabled} onChange={e=>setInput(e.target.value)} placeholder={enabled?'Ton message au collectif…':'Active ton profil pour écrire dans le salon.'}/><button className="surface-button" disabled={busy||!enabled||!input.trim()}>{busy?'Envoi…':'Envoyer'}</button></form></section></div>;
}

