import {useCallback,useEffect,useRef,useState} from 'react';
import {Heart,MessageCircle,Shield,Users,ArrowUpRight,Plus} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {authClient} from '../loyalty/client.js';
import {ecosystem} from '../lib/ecosystem.js';
import DesignPreview from '../ai/DesignPreview.jsx';
import './community.css';
const categories={all:'Tout',discussion:'Échanges',creation:'Créations',challenge:'Défis',collaboration:'Collaborations'};
const dates=s=>new Date(s).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});
function initialDraft(){try{const draft=JSON.parse(sessionStorage.getItem('3b-studio-share')||'null');return draft&&typeof draft==='object'?draft:null;}catch{return null;}}
export default function CommunityPage({goTo}){
 const account=useLoyalty(),uid=account.user?.id;
 const[view,setView]=useState('feed'),[category,setCategory]=useState('all'),[sort,setSort]=useState('created_at'),[data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const[draft,setDraft]=useState(initialDraft),[compose,setCompose]=useState(()=>!!initialDraft()),[title,setTitle]=useState(''),[body,setBody]=useState(''),[postKind,setPostKind]=useState(()=>initialDraft()?'creation':'discussion');
 const[bio,setBio]=useState(''),[kind,setKind]=useState('member'),[report,setReport]=useState(null),[reason,setReason]=useState(''),[reports,setReports]=useState([]);
 const lock=useRef(false),generation=useRef(0),reportDialog=useRef(null);
 useEffect(()=>{if(report)reportDialog.current?.showModal();},[report]);
 const refresh=useCallback(async()=>{if(!uid)return;const n=++generation.current;try{const r=await ecosystem('snapshot',{category,sort});if(n===generation.current){setData(r);setError('');}}catch(e){if(n===generation.current)setError(e.message);}},[uid,category,sort]);
 useEffect(()=>{refresh();return()=>{generation.current++;};},[refresh]);
 useEffect(()=>{if(data?.mine){setBio(data.mine.bio);setKind(data.mine.kind);}},[data?.mine?.bio,data?.mine?.kind]);
 useEffect(()=>{if(!uid)return;let timer;const update=()=>{clearTimeout(timer);timer=setTimeout(refresh,600);};const c=authClient.channel('community-feed-'+uid).on('postgres_changes',{event:'*',schema:'public',table:'community_posts'},update).on('postgres_changes',{event:'*',schema:'public',table:'community_likes'},update).subscribe();return()=>{clearTimeout(timer);authClient.removeChannel(c);};},[uid,refresh]);
 async function act(action,values,message){if(lock.current)return false;lock.current=true;setBusy(true);setNotice('');try{await ecosystem(action,values);if(message)setNotice(message);await refresh();return true;}catch(e){setNotice(e.message);return false;}finally{lock.current=false;setBusy(false);}}
 const visibleProfiles=(data?.profiles||[]).filter(p=>(view!=='creators'||p.kind==='creator')&&(p.name+' '+p.handle+' '+p.bio).toLowerCase().includes(search.toLowerCase()));
 const author=id=>data?.postAuthors?.find(p=>p.user_id===id)||data?.profiles?.find(p=>p.user_id===id);
 const openReports=async()=>{setView('moderation');try{setReports((await ecosystem('reports')).reports);}catch(e){setNotice(e.message);}};
 return <section className="editorial-page community-page"><div className="community-heading"><div className="editorial-heading"><p className="eyebrow">LE COLLECTIF 3B</p><h1>Des idées.<br/><em>Des liens. Une histoire.</em></h1><p>Membres, créateurs et passionnés. Un lieu pour se rencontrer et créer ensemble.</p></div><div className="community-emblem" aria-hidden="true"><Users size={68} strokeWidth={1}/><span>LE CERCLE<br/>EST OUVERT</span></div></div>
 {!uid?<div className="surface-panel community-entry"><Shield size={30}/><div><h2>Les échanges commencent avec ton compte.</h2><p>Les publications et les salons sont réservés aux membres connectés. Ton profil apparaît dans l’annuaire uniquement si tu l’actives.</p><button className="surface-button" onClick={()=>goTo('member')}>Me connecter à 3B <ArrowUpRight size={17}/></button></div></div>:<>
 <div className="surface-tabs" role="group" aria-label="Espaces de la communauté">{[['feed','Fil de la communauté'],['members','Membres'],['creators','Créateurs'],['chat','Tchat en direct'],['profile','Mon profil public']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}{data?.moderator&&<button onClick={openReports} aria-pressed={view==='moderation'}>Modération</button>}</div>
 {error&&<p className="surface-notice" role="alert">{error} <button className="quiet-button" onClick={refresh}>Réessayer</button></p>}{notice&&<p className="surface-notice" role="status">{notice}</p>}
 {!data&&!error&&<p role="status">Ouverture de la communauté…</p>}
 {data&&!data.mine?.listed&&view!=='profile'&&<div className="surface-panel"><h2>Choisis ta place dans le collectif.</h2><p>Active ton profil pour publier, discuter, suivre des créateurs et voter. Ton nom et ta présentation seront visibles des membres.</p><button className="surface-button" onClick={()=>setView('profile')}>Préparer mon profil public</button></div>}
 {view==='profile'&&<div className="community-profile-layout"><form className="surface-panel surface-form" onSubmit={async e=>{e.preventDefault();await act('profile',{bio,kind,listed:true},'Ton profil est visible des membres.');}}><p className="eyebrow">TA PRÉSENTATION AU COLLECTIF</p><h2>{account.profile?.name||'Ton profil 3B'}</h2><label>Je participe comme<select value={kind} onChange={e=>setKind(e.target.value)}><option value="member">Membre</option><option value="creator">Créateur / créatrice</option></select></label><label>Quelques mots sur toi<textarea value={bio} maxLength={500} rows={4} onChange={e=>setBio(e.target.value)} placeholder="Tes inspirations, tes projets, ce que tu aimerais partager…"/></label><p className="muted-copy">Ton nom, ton identifiant, cette présentation et ton rôle choisi sont visibles des membres. « Créateur » est une présentation personnelle, sans certification.</p><button className="surface-button" disabled={busy}>{data?.mine?.listed?'Enregistrer mon profil':'Activer mon profil public'}</button>{data?.mine?.listed&&<button className="quiet-button" type="button" disabled={busy} onClick={()=>act('profile',{bio,kind,listed:false},'Ton profil, tes publications et tes messages sont masqués. Tu peux les réactiver ici.')}>Masquer mon profil et mes échanges</button>}</form><article className="surface-panel"><h2>Tu gardes la main.</h2><p>Tu peux retirer tes contenus, signaler un message et bloquer un membre. Le blocage masque vos profils et échanges l’un pour l’autre.</p><h3>Membres bloqués</h3>{data?.blocks?.length?data.blocks.map(b=><div className="blocked-row" key={b.target_id}><span>Membre {b.target_id.slice(0,8)}</span><button className="quiet-button" disabled={busy} onClick={()=>act('block',{id:b.target_id,active:false},'Blocage retiré.')}>Débloquer</button></div>):<p>Aucun membre bloqué.</p>}</article></div>}
 {view==='feed'&&data&&<>
 <div className="community-controls"><div className="surface-tabs" aria-label="Types de publications">{Object.entries(categories).map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div><label className="community-sort">Trier<select value={sort} onChange={e=>setSort(e.target.value)}><option value="created_at">Plus récentes</option><option value="votes">Plus de votes</option></select></label><button className="surface-button" disabled={!data.mine?.listed} onClick={()=>setCompose(!compose)}><Plus size={17}/>{compose?'Fermer':'Publier'}</button></div>
 {category==='creation'&&<p className="surface-notice">Les créations les plus aimées remontent dans le classement. Leur production reste soumise à l’étude du modèle, des droits, des matières et du coût par 3B. Aucun lancement n’est automatique.</p>}
 {compose&&<form className="surface-panel surface-form community-composer" onSubmit={async e=>{e.preventDefault();if(await act('post',{id:crypto.randomUUID(),title,body,category:postKind,design:draft?.design,assetPath:draft?.assetPath},'Ta publication est en ligne.')){setCompose(false);setTitle('');setBody('');setDraft(null);try{sessionStorage.removeItem('3b-studio-share');}catch{}}}}><h2>Partager avec le collectif</h2>{draft?.design&&<div className="shared-draft"><DesignPreview design={draft.design}/><p>Ton concept de l’atelier 3B sera joint à la publication.</p></div>}<div className="form-columns"><label>Titre<input required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Catégorie<select value={postKind} onChange={e=>setPostKind(e.target.value)}>{Object.entries(categories).filter(([id])=>id!=='all').map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div><label>Ton message<textarea required maxLength={3000} rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><p className="muted-copy">Visible des membres connectés. Partage uniquement du contenu que tu as le droit de publier.</p><button className="surface-button" disabled={busy||!data.mine?.listed}>{busy?'Publication…':'Publier dans la communauté'}</button></form>}
 <div className="community-feed">{data.posts.length?data.posts.map(p=>{const a=author(p.author_id),liked=data.likes.some(l=>l.post_id===p.id);return <article key={p.id} className="community-post"><header><span className="member-avatar">{a?.name?.slice(0,1)||'3B'}</span><div><strong>{a?.name||'Membre 3B'}</strong><small>@{a?.handle} · {dates(p.created_at)}</small></div><span className="status-pill">{categories[p.category]}</span></header>{p.imageUrl?<img className="community-design-image" src={p.imageUrl} alt={p.title}/>:p.design?<DesignPreview design={p.design}/>:null}<div className="community-post-copy"><h2>{p.title}</h2><p>{p.body}</p></div><footer><button className="quiet-button" disabled={busy||p.author_id===uid||!data.mine?.listed} aria-pressed={liked} aria-label={(liked?'Retirer mon vote pour ':'Voter pour ')+p.title} onClick={()=>act('like',{id:p.id,active:!liked})}><Heart size={16} fill={liked?'currentColor':'none'}/>{p.votes} votes</button>{p.author_id===uid?<button className="text-button" disabled={busy} onClick={()=>act('remove',{id:p.id,kind:'post'},'Publication retirée.')}>Retirer</button>:<><button className="text-button" onClick={()=>{setReason('');setReport({id:p.id,kind:'post'});}}>Signaler</button><button className="text-button" disabled={busy} onClick={()=>act('block',{id:p.author_id,active:true},'Membre bloqué.')}>Bloquer</button></>}</footer></article>;}):<div className="surface-panel community-empty"><MessageCircle size={34}/><h2>La prochaine idée peut être la tienne.</h2><p>Aucune publication dans cette catégorie pour le moment.</p><button className="quiet-button" onClick={()=>goTo('ia-textile')}>Créer un concept dans l’atelier</button></div>}</div><p className="muted-copy">Les 60 premières publications selon le tri choisi. Un vote par compte et par publication ; aucun vote sur sa propre création.</p></>}
 {['members','creators'].includes(view)&&data&&<><label className="surface-form">Rechercher un membre<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom, identifiant ou inspiration…"/></label><div className="community-members">{visibleProfiles.map(p=><article className="surface-panel" key={p.user_id}><span className="member-avatar">{p.name.slice(0,1)}</span><h2>{p.name}</h2><p className="member-handle">@{p.handle} · {p.kind==='creator'?'Créateur':'Membre'}</p><p>{p.bio||'Une nouvelle histoire dans le collectif 3B.'}</p>{p.user_id!==uid&&<div className="member-actions"><button className="quiet-button" disabled={busy||!data.mine?.listed} onClick={()=>act('follow',{id:p.user_id,active:!data.follows.some(f=>f.target_id===p.user_id)})}>{data.follows.some(f=>f.target_id===p.user_id)?'Ne plus suivre':'Suivre'}</button><button className="text-button" disabled={busy} onClick={()=>act('block',{id:p.user_id,active:true},'Membre bloqué.')}>Bloquer</button></div>}</article>)}</div>{!visibleProfiles.length&&<p className="surface-notice">Aucun profil ne correspond à cette recherche.</p>}</>}
 {view==='chat'&&<ChatRoom uid={uid} enabled={data?.mine?.listed} onReport={target=>{setReason('');setReport(target);}}/>}
 {view==='moderation'&&<div className="community-feed">{reports.length?reports.map(r=><article className="surface-panel" key={r.id}><h2>Signalement · {r.kind==='chat'?'Message':'Publication'}</h2><p>{r.reason}</p><blockquote>{r.content?.body||'Contenu retiré'}</blockquote><button className="quiet-button" disabled={busy} onClick={async()=>{await act('moderate',{id:r.id,hide:true},'Contenu masqué.');openReports();}}>Masquer le contenu</button><button className="quiet-button" disabled={busy} onClick={async()=>{await act('moderate',{id:r.id,hide:false},'Signalement classé.');openReports();}}>Classer sans masquer</button></article>):<p>Aucun signalement ouvert.</p>}</div>}
 {report&&<dialog ref={reportDialog} className="report-panel" aria-labelledby="report-title" onCancel={()=>setReport(null)}><form className="surface-panel surface-form" onSubmit={async e=>{e.preventDefault();if(await act('report',{...report,reason},'Signalement transmis à la file de modération.'))setReport(null);}}><h2 id="report-title">Signaler ce contenu</h2><label>Motif<textarea autoFocus required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explique le problème…"/></label><div className="member-actions"><button className="surface-button" disabled={busy}>Transmettre le signalement</button><button type="button" className="quiet-button" onClick={()=>setReport(null)}>Annuler</button></div></form></dialog>}
 </>}
 <details className="guide-faq"><summary>Les règles du collectif</summary><p>Respecte les personnes, leurs convictions et leurs créations. Pas de harcèlement, de spam, de divulgation de données privées ni de contenus illégaux. Les salons sont collectifs et visibles des membres ; ils ne constituent pas une messagerie privée. Un signalement permet une revue par la modération, sans garantie de traitement immédiat.</p></details></section>;
}
function ChatRoom({uid,enabled,onReport}){
 const[room,setRoom]=useState('general'),[messages,setMessages]=useState([]),[profiles,setProfiles]=useState([]),[status,setStatus]=useState('Connexion…'),[error,setError]=useState(''),[input,setInput]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),tail=useRef(null);
 useEffect(()=>{let live=true,pending=false;const controller=new AbortController();setMessages([]);setProfiles([]);const load=async()=>{if(pending||document.hidden)return;pending=true;try{const r=await ecosystem('chat-list',{room},{signal:controller.signal});if(live){setMessages(r.messages);setProfiles(r.profiles);setError('');}}catch(e){if(live)setError(e.message);}finally{pending=false;}};load();const c=authClient.channel('chat-'+room+'-'+uid).on('postgres_changes',{event:'*',schema:'public',table:'community_chat',filter:'room=eq.'+room},load).subscribe(s=>{if(live)setStatus(s==='SUBSCRIBED'?'En direct':s==='CHANNEL_ERROR'||s==='TIMED_OUT'?'Reconnexion · actualisation toutes les 15 s':'Connexion…');});const interval=setInterval(load,15000);document.addEventListener('visibilitychange',load);return()=>{live=false;controller.abort();clearInterval(interval);document.removeEventListener('visibilitychange',load);authClient.removeChannel(c);};},[uid,room]);
 useEffect(()=>{tail.current?.scrollIntoView({block:'nearest',behavior:'instant'});},[messages.length]);
 return <div className="chat-shell"><aside><p className="eyebrow">LES SALONS</p>{[['general','Le salon 3B'],['atelier','Créateurs & atelier'],['sport','Sport & défis']].map(([id,label])=><button className="quiet-button" aria-pressed={room===id} key={id} disabled={busy} onClick={()=>setRoom(id)}># {label}</button>)}</aside><section className="chat-room"><header><h2>{room==='general'?'Le salon 3B':room==='atelier'?'Créateurs & atelier':'Sport & défis'}</h2><span className="status-pill">{status}</span></header><div className="chat-messages" role="log" aria-label="Messages du salon" aria-live="polite">{messages.length?messages.map(m=><article key={m.id} className={m.author_id===uid?'own':''}><div><strong>{profiles.find(p=>p.user_id===m.author_id)?.name||'Membre'}</strong><time>{dates(m.created_at)}</time></div><p>{m.body}</p>{m.author_id!==uid?<button className="text-button" onClick={()=>onReport({id:m.id,kind:'chat'})}>Signaler</button>:<button className="text-button" disabled={busy} onClick={async()=>{if(lock.current)return;lock.current=true;setBusy(true);try{await ecosystem('remove',{id:m.id,kind:'chat'});setMessages(items=>items.filter(item=>item.id!==m.id));}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}}>Retirer</button>}</article>):<p className="muted-copy">Le salon attend ses premiers échanges.</p>}<div ref={tail}/></div>{error&&<p className="surface-notice" role="alert">{error}</p>}<form className="chat-composer" onSubmit={async e=>{e.preventDefault();if(lock.current||!input.trim())return;lock.current=true;setBusy(true);try{await ecosystem('chat-send',{id:crypto.randomUUID(),room,text:input});setInput('');const r=await ecosystem('chat-list',{room});setMessages(r.messages);setProfiles(r.profiles);}catch(e){setError(e.message);}finally{lock.current=false;setBusy(false);}}}><label className="sr-only" htmlFor="chat-input">Message au salon</label><textarea id="chat-input" rows={2} required maxLength={1500} value={input} disabled={!enabled} onChange={e=>setInput(e.target.value)} placeholder={enabled?'Ton message au collectif…':'Active ton profil pour écrire dans le salon.'}/><button className="surface-button" disabled={busy||!enabled||!input.trim()}>{busy?'Envoi…':'Envoyer'}</button></form></section></div>;
}
