export const LEVELS = [
  { name: "Découverte", minPoints: 0, description: "Début du voyage 3B." },
  { name: "Membre", minPoints: 300, description: "Profil complété et premières missions." },
  { name: "Héritier", minPoints: 800, description: "Premier pays ou logo débloqué." },
  { name: "Gardien", minPoints: 1600, description: "Plusieurs pays et cartes débloqués." },
  { name: "Légende", minPoints: 3000, description: "Statut rare de l'univers 3B." },
];

export const COUNTRIES = [
  {
    id: "france",
    name: "France",
    emoji: "🇫🇷",
    status: "locked",
    theme: "Luxe, héritage, élégance, prestige.",
    colors: "Bleu, blanc, rouge, argent.",
    bonusName: "Élégance",
    bonusEffect: "Améliore le design du Passeport et donne +10% sur les missions style/création.",
    characterEffect: "Broche argent/or et aura blanche/or.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "maroc",
    name: "Maroc",
    emoji: "🇲🇦",
    status: "locked",
    theme: "Force, royauté, identité, racines.",
    colors: "Rouge, vert, or.",
    bonusName: "Force Royale",
    bonusEffect: "Protège la série de connexion 1 fois par mois.",
    characterEffect: "Aura dorée, détail rouge/vert, posture puissante.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "italie",
    name: "Italie",
    emoji: "🇮🇹",
    status: "hint_active",
    theme: "Art, style, mystère, indice.",
    colors: "Vert, blanc, rouge, or.",
    bonusName: "Style Secret",
    bonusEffect: "Donne 1 indice supplémentaire sur une mission secrète.",
    characterEffect: "Accessoire designer et animation mystère révélé.",
    secretHint: "Italie s’y comprennent",
    unlockDate: "8 juillet — 20h",
    fragments: 1,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "algerie",
    name: "Algérie",
    emoji: "🇩🇿",
    status: "locked",
    theme: "Racines, courage, fierté, communauté.",
    colors: "Vert, blanc, rouge, or.",
    bonusName: "Fierté",
    bonusEffect: "Donne +20% de points sur les missions communauté.",
    characterEffect: "Aura verte/blanche et animation de victoire.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "tunisie",
    name: "Tunisie",
    emoji: "🇹🇳",
    status: "locked",
    theme: "Lumière, Méditerranée, héritage, découverte.",
    colors: "Rouge, blanc, argent.",
    bonusName: "Lumière",
    bonusEffect: "Révèle plus vite les pays avec indice actif.",
    characterEffect: "Halo rouge/blanc et lumière autour des pas.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "espagne",
    name: "Espagne",
    emoji: "🇪🇸",
    status: "locked",
    theme: "Passion, mouvement, puissance, énergie.",
    colors: "Rouge, or, noir.",
    bonusName: "Passion",
    bonusEffect: "Donne +1 tentative supplémentaire dans les mini-jeux.",
    characterEffect: "Mouvement plus dynamique et effet rouge/or.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "turquie",
    name: "Turquie",
    emoji: "🇹🇷",
    status: "locked",
    theme: "Étoile, croissant, symbole, puissance.",
    colors: "Rouge, blanc, or.",
    bonusName: "Étoile",
    bonusEffect: "10% de chance de gagner une récompense bonus après une mission.",
    characterEffect: "Petite étoile lumineuse autour de l'explorateur.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
  {
    id: "estonie",
    name: "Estonie",
    emoji: "🇪🇪",
    status: "locked",
    theme: "Loup, force froide, stratégie, mémoire.",
    colors: "Bleu, noir, blanc, argent.",
    bonusName: "Loup Nordique",
    bonusEffect: "Élimine 1 mauvaise réponse dans certains quiz.",
    characterEffect: "Aura bleue froide et traces de pas lumineuses.",
    fragments: 0,
    fragmentsRequired: 5,
    rewardPoints: 250,
  },
];

export const STARTER_CARDS = [
  {
    id: "carte_decouverte_3b",
    name: "Carte Découverte 3B",
    type: "starter",
    rarity: "Commune",
    unlocked: true,
    description: "Première carte obtenue à la création du Passeport 3B.",
  },
  {
    id: "carte_membre_3b",
    name: "Carte Membre 3B",
    type: "level",
    rarity: "Premium",
    unlocked: false,
    description: "Obtenue au niveau Membre.",
  },
  {
    id: "carte_secret_3b",
    name: "Carte Secret 3B",
    type: "secret",
    rarity: "Épique",
    unlocked: false,
    description: "Obtenue avec un indice ou un code spécial.",
  },
  {
    id: "carte_legende_3b",
    name: "Carte Légende 3B",
    type: "level",
    rarity: "Légendaire",
    unlocked: false,
    description: "Réservée aux explorateurs les plus avancés.",
  },
];

export const MISSIONS = [
  {
    id: "mission_complete_profile",
    title: "Complète ton profil",
    type: "welcome",
    rewardPoints: 50,
    rewardFragmentCountry: null,
    status: "available",
    description: "Ajoute ton avatar, ton pays d'origine et ton identité 3B.",
  },
  {
    id: "mission_open_world_map",
    title: "Découvre la carte du monde",
    type: "welcome",
    rewardPoints: 25,
    rewardFragmentCountry: null,
    status: "available",
    description: "Ouvre la carte du monde du Passeport 3B.",
  },
  {
    id: "quiz_italie",
    title: "Quiz Italie",
    type: "quiz",
    country: "italie",
    rewardPoints: 100,
    rewardFragmentCountry: "italie",
    status: "available",
    description: "Réponds au quiz Italie pour gagner un fragment.",
  },
  {
    id: "secret_italie",
    title: "Indice Italie",
    type: "secret",
    country: "italie",
    rewardPoints: 100,
    rewardFragmentCountry: "italie",
    status: "available",
    description: "Découvre l'indice : Italie s’y comprennent.",
  },
];

export const INITIAL_USER = {
  id: "user_001",
  pseudo: "",
  avatar: "explorateur",
  countryOrigin: "",
  currentCountry: "",
  points: 0,
  level: "Découverte",
  passportActivated: false,
  unlockedCountries: [],
  cardsOwned: [],
  stampsOwned: [],
  activeBonuses: [],
  completedMissions: [],
};
