import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {ArrowUpRight,BookOpen,Check,Compass,Palette,Ship,Star,TrainFront,Wrench} from 'lucide-react';
import {createPremiumTransitVehicle} from '../premium-hub-visuals.js';
import {HUB_CITY_SERVICE_NAMES,HUB_SERVICE_VEHICLES,HUB_SERVICE_PALETTES,HUB_ATELIER_MATERIALS,HUB_ATELIER_PATTERNS,hubServiceArchive,hubServiceConnections,hubServiceMissionTarget,loadHubServicePreferences,saveHubServicePreferences,hubPaletteAvatarPatch,resolveHubCityService} from './hub-city-services.js';
import './HubCityServices.css';

const TRANSPORT_NAMES={train:'3B Express',boat:'Navette maritime',telepheric:'Téléphérique',zipline:'Tyrolienne'};
const STATUS_NAMES={available:'À découvrir',active:'En cours',completed:'Accomplie'};

function patternTexture(atelier){
 const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');
 if(!ctx)return null;
 ctx.fillStyle=atelier.base;ctx.fillRect(0,0,256,256);ctx.fillStyle=atelier.accent;ctx.strokeStyle=atelier.accent;
 if(atelier.pattern==='bandes'){for(let x=0;x<256;x+=64)ctx.fillRect(x,0,18,256);}
 else if(atelier.pattern==='damier'){for(let x=0;x<4;x++)for(let y=0;y<4;y++)if((x+y)%2===0)ctx.fillRect(x*64,y*64,64,64);}
 else if(atelier.pattern==='insigne'){ctx.font='bold 84px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('3B',128,126);ctx.lineWidth=3;ctx.strokeRect(28,28,200,200);}
 else if(atelier.pattern==='broderie'){ctx.lineWidth=2;for(let y=24;y<256;y+=48){ctx.beginPath();for(let x=0;x<=256;x+=16)x?ctx.lineTo(x,y+(x%32?7:-7)):ctx.moveTo(x,y-7);ctx.stroke();}}
 ctx.globalAlpha=.09;for(let i=0;i<256;i+=3){ctx.fillRect(i,0,1,256);ctx.fillRect(0,i,256,1);}
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture;
}

/** Renders the same transit meshes used in the world, without a second game loop. */
function ServiceStudio({vehicleId='navette',finish='heritage',atelier=null}){
 const host=useRef(null),canvas=useRef(null),[unavailable,setUnavailable]=useState(false);
 const vehicle=HUB_SERVICE_VEHICLES.find(row=>row.id===vehicleId)||HUB_SERVICE_VEHICLES[1],palette=HUB_SERVICE_PALETTES.find(row=>row.id===finish)||HUB_SERVICE_PALETTES[0];
 useEffect(()=>{
  const element=host.current,target=canvas.current;if(!element||!target)return;setUnavailable(false);
  let renderer;try{renderer=new THREE.WebGLRenderer({canvas:target,antialias:true,alpha:false,powerPreference:'low-power'});}catch{setUnavailable(true);return;}
  const world=new THREE.Scene();world.background=new THREE.Color('#0b1420');const camera=new THREE.PerspectiveCamera(34,1,.1,80),materials=new Set(),geometries=new Set(),textures=[];
  const material=(color,props={})=>{const value=new THREE.MeshStandardMaterial({color,...props});materials.add(value);return value;};
  const box=new THREE.BoxGeometry(1,1,1),cylinder=new THREE.CylinderGeometry(1,1,1,24);geometries.add(box);geometries.add(cylinder);
  world.add(new THREE.HemisphereLight('#d9edff','#132033',3.2));const key=new THREE.DirectionalLight('#fff1d6',5.5);key.position.set(5,9,7);world.add(key);const rim=new THREE.DirectionalLight('#74c9ff',3);rim.position.set(-6,4,-5);world.add(rim);
  const model=new THREE.Group();world.add(model);
  let radius;
  if(atelier){
   const recipe=HUB_ATELIER_MATERIALS.find(row=>row.id===atelier.material)||HUB_ATELIER_MATERIALS[0],texture=patternTexture(atelier);if(texture)textures.push(texture);
   const sample=new THREE.Mesh(box,material('#ffffff',{map:texture,roughness:recipe.roughness,metalness:recipe.metalness}));sample.scale.set(4.4,.26,4.4);sample.position.y=.5;model.add(sample);
   const trim=material(atelier.accent,{roughness:.28,metalness:.7});for(const side of [-1,1])for(const axis of ['x','z']){const rail=new THREE.Mesh(box,trim);rail.scale.set(axis==='x'?.055:4.6,.1,axis==='z'?.055:4.6);rail.position.set(axis==='x'?side*2.27:0,.57,axis==='z'?side*2.27:0);model.add(rail);}radius=10;
  }else{const actual=createPremiumTransitVehicle({...vehicle,color:palette.accent,height:0},{x:0,z:0},{root:model,geometry:{box,cylinder},material,groundY:()=>0});actual.position.y=1.05;radius=vehicle.transport==='train'?12.8:vehicle.transport==='boat'?9.4:6.8;}
  const floor=new THREE.Mesh(cylinder,material('#172533',{roughness:.45,metalness:.32}));floor.scale.set(atelier?3.1:vehicle.transport==='train'?5.5:3.7,.16,atelier?3.1:vehicle.transport==='train'?5.5:3.7);floor.position.y=-.15;world.add(floor);
  const ringGeometry=new THREE.TorusGeometry(atelier?3.2:vehicle.transport==='train'?5.6:3.8,.016,5,72);geometries.add(ringGeometry);const ring=new THREE.Mesh(ringGeometry,material(palette.accent,{emissive:palette.accent,emissiveIntensity:.55,roughness:.25}));ring.rotation.x=Math.PI/2;ring.position.y=-.05;world.add(ring);
  renderer.setPixelRatio(Math.min(1.5,globalThis.devicePixelRatio||1));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
  let yaw=.74,pitch=.42,drag=null,disposed=false;
  const render=()=>{if(disposed)return;camera.position.set(Math.sin(yaw)*Math.cos(pitch)*radius,Math.sin(pitch)*radius+1.2,Math.cos(yaw)*Math.cos(pitch)*radius);camera.lookAt(0,.8,0);renderer.render(world,camera);};
  const resize=()=>{const rect=element.getBoundingClientRect();renderer.setSize(Math.max(1,rect.width),Math.max(1,rect.height),false);camera.aspect=Math.max(1,rect.width)/Math.max(1,rect.height);camera.updateProjectionMatrix();render();};
  const down=event=>{drag={x:event.clientX,y:event.clientY};target.setPointerCapture?.(event.pointerId);};
  const move=event=>{if(!drag)return;yaw-=(event.clientX-drag.x)*.012;pitch=Math.max(.12,Math.min(.95,pitch+(event.clientY-drag.y)*.007));drag={x:event.clientX,y:event.clientY};render();};
  const up=()=>{drag=null;};
  const lost=event=>{event.preventDefault();setUnavailable(true);};
  target.addEventListener('pointerdown',down);target.addEventListener('pointermove',move);target.addEventListener('pointerup',up);target.addEventListener('pointercancel',up);target.addEventListener('webglcontextlost',lost);
  const observer=typeof ResizeObserver==='function'?new ResizeObserver(resize):null;observer?.observe(element);if(!observer)globalThis.addEventListener?.('resize',resize);resize();
  return()=>{disposed=true;observer?.disconnect();if(!observer)globalThis.removeEventListener?.('resize',resize);target.removeEventListener('pointerdown',down);target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',up);target.removeEventListener('pointercancel',up);target.removeEventListener('webglcontextlost',lost);world.traverse(object=>{if(object.geometry)geometries.add(object.geometry);for(const value of Array.isArray(object.material)?object.material:object.material?[object.material]:[]){materials.add(value);for(const property of Object.values(value))if(property?.isTexture&&!textures.includes(property))textures.push(property);}});geometries.forEach(value=>value.dispose());materials.forEach(value=>value.dispose());textures.forEach(value=>value.dispose());renderer.dispose();};
 },[vehicleId,finish,atelier?.material,atelier?.base,atelier?.accent,atelier?.pattern]);
 return <div className="hub-service-studio" ref={host}><canvas ref={canvas} aria-label={atelier?'Échantillon de matière en trois dimensions':'Modèle du '+vehicle.name+' utilisé dans la cité'}/>{unavailable&&<div className="hub-service-studio-fallback"><Compass size={32}/><strong>{atelier?'Échantillon de matière':vehicle.name}</strong><span>L’aperçu 3D est indisponible. Les réglages et itinéraires restent accessibles.</span></div>}<span className="hub-service-studio-label">{atelier?'ÉCHANTILLON DE MATIÈRE':'MODÈLE DE LA CITÉ'} · glisse pour tourner</span></div>;
}

function Connections({items,district='docks',transport=null,onNavigate}){
 const routes=hubServiceConnections(items,{district,transport});
 return <section className="hub-service-section"><h4><Compass size={17}/> Embarquements disponibles</h4><p>Rejoins la station à pied pour monter à bord.</p><div className="hub-service-route-list">{routes.length?routes.map(({station,next,stops})=><article key={station.id}><div><small>{TRANSPORT_NAMES[station.transport]||station.transport} · {stops.length} arrêts</small><strong>{station.name}</strong><span>{next?'Prochain arrêt : '+next.name:'Destination indiquée sur place'}</span>{(station.correspondence||next?.correspondence)&&<small>Correspondance à pied entre les Docks et la Place de l’Héritage.</small>}</div><button type="button" onClick={()=>onNavigate?.(station)}>Rejoindre <ArrowUpRight size={16}/></button></article>):<p>Aucun embarquement disponible à proximité de ce bâtiment.</p>}</div></section>;
}

function ArchiveServices({save,items,preferences,update,onNavigate,onPanel}){
 const records=hubServiceArchive(save),[selected,setSelected]=useState('arrival'),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
 const visible=records.filter(row=>(filter!=='favorites'||preferences.favorites.includes(row.id))&&(!search.trim()||(row.title+' '+row.topic+' '+row.text).toLocaleLowerCase('fr').includes(search.trim().toLocaleLowerCase('fr'))));
 const record=visible.find(row=>row.id===selected)||visible[0];
 function favorite(id){update({...preferences,favorites:preferences.favorites.includes(id)?preferences.favorites.filter(value=>value!==id):[...preferences.favorites,id]});}
 return <><div className="hub-service-search"><label>Rechercher une chronique<input type="search" value={search} maxLength={80} onChange={event=>setSearch(event.target.value)} placeholder="Cercle, ouvriers, transports…"/></label><div className="hub-service-chips" aria-label="Catalogue"><button type="button" aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>Tout le catalogue</button><button type="button" aria-pressed={filter==='favorites'} onClick={()=>setFilter('favorites')}><Star size={14}/> Mes favoris</button></div></div><div className="hub-service-archive"><nav aria-label="Chroniques de la cité">{visible.map(row=><button type="button" key={row.id} aria-pressed={record?.id===row.id} onClick={()=>setSelected(row.id)}><small>{row.topic}</small><strong>{row.title}</strong><span>{row.missions.filter(m=>m.claimed).length}/{row.missions.length} missions accomplies</span></button>)}{!visible.length&&<p>Aucune chronique dans cette sélection.</p>}</nav>{record&&<article className="hub-service-reading"><span className="world-kicker">CHRONIQUE · {record.topic}</span><h3>{record.title}</h3><p>{record.text}</p><div className="hub-service-chips"><button type="button" aria-pressed={preferences.favorites.includes(record.id)} onClick={()=>favorite(record.id)}><Star size={15}/>{preferences.favorites.includes(record.id)?'Retirer des favoris':'Garder cette chronique'}</button>{items.find(item=>item.buildingId===record.placeId)&&<button type="button" onClick={()=>{const target=items.find(item=>item.buildingId===record.placeId);onNavigate?.({...target,...target.entrance});}}>Repérer le lieu <ArrowUpRight size={15}/></button>}</div><h4>Les traces de ton voyage</h4><div className="hub-service-missions">{record.missions.map(mission=>{const target=hubServiceMissionTarget(items,mission.id);return <article key={mission.id}><strong>{mission.title}</strong><small>{mission.claimed?'Accomplie et récompense reçue':mission.locked?'Prérequis à accomplir':STATUS_NAMES[mission.status]||'À découvrir'} · {mission.completedObjectives}/{mission.totalObjectives}</small><p>{mission.claimed?'La trace de cette mission est conservée.':mission.objectives[mission.completedObjectives]||'Retourne auprès du donneur de mission.'}</p>{mission.locked&&<p>Prérequis : {mission.missingPrerequisites.join(', ')}.</p>}{target&&!mission.claimed&&<button type="button" onClick={()=>onNavigate?.(target)}>Rejoindre le repère</button>}</article>;})}</div></article>}</div><div className="hub-service-footer"><button type="button" onClick={()=>onPanel?.('collection')}><BookOpen size={17}/> Voir mes compagnons</button><button type="button" onClick={()=>onPanel?.('journal')}>Ouvrir mon journal</button></div></>;
}

function GarageServices({preferences,update,items,onNavigate}){
 const draft=preferences.vehicle,vehicle=HUB_SERVICE_VEHICLES.find(row=>row.id===draft.id)||HUB_SERVICE_VEHICLES[1];
 const set=patch=>update({...preferences,vehicle:{...draft,...patch}});
 return <><div className="hub-service-workbench"><section><ServiceStudio vehicleId={draft.id} finish={draft.finish}/><p className="hub-service-caption">{vehicle.role} Modèle utilisé par les transports de la cité.</p></section><section className="hub-service-controls"><label>Véhicule à examiner<select value={draft.id} onChange={event=>set({id:event.target.value,checks:[]})}>{HUB_SERVICE_VEHICLES.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><fieldset><legend>Finition de la maquette</legend><div className="hub-service-swatches">{HUB_SERVICE_PALETTES.map(row=><button type="button" key={row.id} aria-label={row.name} aria-pressed={draft.finish===row.id} style={{'--swatch':row.base,'--accent':row.accent}} onClick={()=>set({finish:row.id})}><i/><span>{row.name}</span></button>)}</div></fieldset><label>Dossier de préparation<select value={draft.purpose} onChange={event=>set({purpose:event.target.value})}><option value="inspection">Inspection</option><option value="liaison">Liaison entre quartiers</option><option value="secours">Préparation de secours</option></select></label><fieldset className="hub-service-checks"><legend>Mon contrôle visuel · {draft.checks.length}/4</legend>{vehicle.checks.map((label,index)=><label key={label}><input type="checkbox" checked={draft.checks.includes(index)} onChange={()=>set({checks:draft.checks.includes(index)?draft.checks.filter(value=>value!==index):[...draft.checks,index]})}/><span>{label}</span></label>)}</fieldset><p className="hub-service-note">Ce dossier conserve tes choix et observations. La finition de la maquette ne modifie pas la flotte en circulation.</p></section></div><Connections items={items} district="docks" transport={vehicle.transport} onNavigate={onNavigate}/></>;
}

function AtelierServices({preferences,update,onApplyPalette,onPanel}){
 const draft=preferences.atelier,[message,setMessage]=useState('');const set=patch=>{setMessage('');update({...preferences,atelier:{...draft,...patch}});};
 return <><div className="hub-service-workbench"><section><ServiceStudio atelier={draft}/><p className="hub-service-caption">{HUB_ATELIER_MATERIALS.find(row=>row.id===draft.material)?.detail}</p></section><section className="hub-service-controls"><label>Matière de l’échantillon<select value={draft.material} onChange={event=>set({material:event.target.value})}>{HUB_ATELIER_MATERIALS.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><fieldset><legend>Palettes de la cité</legend><div className="hub-service-swatches">{HUB_SERVICE_PALETTES.map(row=><button type="button" key={row.id} aria-label={row.name} style={{'--swatch':row.base,'--accent':row.accent}} onClick={()=>set({base:row.base,accent:row.accent})}><i/><span>{row.name}</span></button>)}</div></fieldset><div className="hub-service-colors"><label>Couleur principale<input type="color" value={draft.base} onChange={event=>set({base:event.target.value})}/></label><label>Couleur des détails<input type="color" value={draft.accent} onChange={event=>set({accent:event.target.value})}/></label></div><label>Motif<select value={draft.pattern} onChange={event=>set({pattern:event.target.value})}>{HUB_ATELIER_PATTERNS.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button type="button" className="world-primary" disabled={!onApplyPalette} onClick={()=>{const applied=onApplyPalette?.(hubPaletteAvatarPatch(draft));setMessage(applied===false?'La palette n’a pas pu être appliquée. Tes choix sont conservés.':'Palette et motif appliqués à ta tenue.');}}><Check size={17}/> Appliquer à ma tenue</button><p className="hub-service-note">La matière concerne l’échantillon. La tenue reçoit les deux couleurs et le motif.</p>{message&&<p role="status" className="hub-service-feedback">{message}</p>}</section></div><div className="hub-service-footer"><button type="button" onClick={()=>onPanel?.('avatar')}><Palette size={17}/> Personnalisation complète</button></div></>;
}

function UrbanismServices({item,save,items,onNavigate,onOpenCity,onPanel}){
 const visited=new Set(save.hub?.stats?.buildingVisits||[]),buildings=items.filter(row=>row.type==='hubBuilding'),[filter,setFilter]=useState('all');
 return <><div className="hub-service-urbanism"><div><span className="world-kicker">CONSTRUIRE · VISITER · RETROUVER</span><h3>Ta ville, ton prochain horizon.</h3><p>Le Bureau d’Urbanisme donne accès à Créer ma Ville 3B. Retrouve tes sauvegardes ou fonde une nouvelle ville. Dans une partie, le menu Ma ville puis Visiter donne accès aux villes publiques.</p><button type="button" className="world-primary" disabled={!onOpenCity} onClick={()=>onOpenCity?.()}><ArrowUpRight size={18}/> Ouvrir Créer ma Ville</button><small>Ton Passeport est utilisé pour retrouver tes constructions. La progression de ta Ville reste indépendante du Monde 3B.</small></div><div className="hub-service-survey"><Compass size={34}/><strong>{visited.size}<span>/{buildings.length}</span></strong><p>lieux du hub visités</p><button type="button" onClick={()=>onPanel?.('atlas')}>Ouvrir la carte de la cité</button></div></div><section className="hub-service-section"><h4>Le carnet des bâtiments</h4><div className="hub-service-chips"><button type="button" aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>Tous les lieux</button><button type="button" aria-pressed={filter==='unvisited'} onClick={()=>setFilter('unvisited')}>À découvrir</button></div><div className="hub-service-building-list">{buildings.filter(row=>filter!=='unvisited'||!visited.has(row.buildingId)).map(row=><button type="button" key={row.id} onClick={()=>onNavigate?.({...row,...row.entrance})}><strong>{row.name}</strong><small>{visited.has(row.buildingId)?'Visité':'À découvrir'}{row.buildingId===item.buildingId?' · tu es ici':''}</small><ArrowUpRight size={16}/></button>)}</div></section></>;
}

export function HubCityServices({item,save={},items=[],accountId=null,onNavigate,onPanel,onOpenCity,onApplyPalette}){
 const service=resolveHubCityService(item),[preferences,setPreferences]=useState(()=>loadHubServicePreferences(accountId)),[storageMessage,setStorageMessage]=useState('');
 useEffect(()=>{setPreferences(loadHubServicePreferences(accountId));setStorageMessage('');},[accountId]);
 const update=next=>{const result=saveHubServicePreferences(next,accountId);setPreferences(result.value);setStorageMessage(result.ok?'Tes choix sont enregistrés sur cet appareil.':'Tes choix restent disponibles pendant cette visite ; l’enregistrement local est indisponible.');};
 if(!service)return null;
 const icons={garage:Wrench,dock:Ship,rail:TrainFront,atelier:Palette,archives:BookOpen,urbanism:Compass},Icon=icons[service];
 return <div className="hub-city-services" data-service={service}><header className="hub-service-heading"><Icon size={22}/><div><span className="world-kicker">{item.name}</span><h3>{HUB_CITY_SERVICE_NAMES[service]}</h3></div></header>
 {service==='garage'&&<GarageServices preferences={preferences} update={update} items={items} onNavigate={onNavigate}/>}
 {service==='atelier'&&<AtelierServices preferences={preferences} update={update} onApplyPalette={onApplyPalette} onPanel={onPanel}/>}
 {service==='archives'&&<ArchiveServices save={save} items={items} preferences={preferences} update={update} onNavigate={onNavigate} onPanel={onPanel}/>}
 {service==='urbanism'&&<UrbanismServices item={item} save={save} items={items} onNavigate={onNavigate} onOpenCity={onOpenCity} onPanel={onPanel}/>}
 {(service==='dock'||service==='rail')&&<><div className="hub-service-workbench"><section><ServiceStudio vehicleId={service==='rail'?'express':'navette'}/></section><section className="hub-service-controls"><span className="world-kicker">{service==='rail'?'RÉSEAU FERROVIAIRE':'RÉSEAU MARITIME'}</span><h3>{service==='rail'?'Les quartiers, reliés.':'Les quais des Horizons.'}</h3><p>{service==='rail'?'Le 3B Express dessert les stations physiques de la cité. Repère ton prochain arrêt, puis rejoins le quai.':'Le chantier naval prépare les navettes qui desservent les embarcadères du hub. Choisis une liaison, puis rejoins son quai pour embarquer.'}</p><button type="button" onClick={()=>onPanel?.('atlas')}>Voir les lignes sur la carte</button><button type="button" onClick={()=>onPanel?.('journal')}>Missions et journal de bord</button></section></div><Connections items={items} district={item.district||'docks'} transport={service==='rail'?'train':'boat'} onNavigate={onNavigate}/>{service==='dock'&&<Connections items={items} district={item.district||'docks'} transport="telepheric" onNavigate={onNavigate}/>}</>}
 {storageMessage&&<p className="hub-service-storage" role="status">{storageMessage}</p>}</div>;
}
