import React from 'react';
import {Button} from '../../design-system/index.jsx';
import {hubDistrictStory,platformWorldState} from './platform-life.js';
import {hubPlaceLabel,hubItemLabel,hubMissionLabel,hubObjectiveLabel} from './presentation.js';
export function HubDistrictPanel({place,save,items,onNavigate,onMission,onService}){
 const story=hubDistrictStory(place.district),world=platformWorldState(save),missions=items.filter(i=>i.type==='hubMission'&&(story.missions.includes(i.missionId)||i.district===place.district));
 const state=save.hub?.missions||{},status=id=>state[id]?.claimed?'Accomplie':state[id]?.status==='completed'?'Récompense prête':state[id]?.status==='active'?'En cours':'À découvrir';
 return <div className="hub-district-panel"><span className="world-kicker">{place.kind==='value'?'LES HUIT VALEURS':'LA CITÉ VIVANTE'}</span><h3>{hubPlaceLabel(place.name)}</h3><p>{hubPlaceLabel(place.kind==='district'?story.story:place.detail)}</p>
 <div className="hub-civic-status"><span>{world.missionsFinished} missions accomplies</span><span>{world.networkRestored?'Réseau Matrix réparé':'Relais Matrix instables'}</span><span>{world.gardenRestored?'Conservatoire restauré':'Conservatoire à restaurer'}</span><span>{world.communityUnited?'Rencontre des habitants organisée':'Les habitants cherchent à se réunir'}</span></div>
 {missions.length>0&&<><h4>Histoires et activités du quartier</h4><div className="hub-locations">{missions.map(m=><article key={m.id}><strong>{m.name}</strong><small>{status(m.missionId)}{m.locked?' · à débloquer':''}</small><p>{m.locked?'Termine « '+(m.missingPrerequisites||[]).map(hubMissionLabel).join(' », « ')+' » et récupère les récompenses.':state[m.missionId]?.status==='completed'?(state[m.missionId]?.claimed?'Cette histoire fait désormais partie de la Cité.':'Retourne voir l’habitant pour récupérer ta récompense.'):hubObjectiveLabel(m.objectives?.[state[m.missionId]?.completedObjectives||0]||'Retourne voir le donneur de mission.')}</p><Button aria-label={'Placer un repère pour '+m.name} onClick={()=>onNavigate(m)}>Placer un repère</Button>{(state[m.missionId]?.status||'available')==='available'&&!m.locked&&<Button onClick={()=>onMission(m)}>Lire la proposition</Button>}</article>)}</div></>}
 <h4>Repères du quartier</h4><p>Place un repère puis suis les chemins de la Cité. Les départs en transport se font à la station.</p><div className="hub-locations">{items.filter(i=>i.type==='hubBuilding'&&story.services.includes(i.buildingId)).map(i=><Button key={i.id} onClick={()=>onService(i)}>{hubItemLabel(i)}<small>Placer un repère vers l’entrée</small></Button>)}{items.filter(i=>i.type==='hubTransport'&&i.district===place.district&&i.boardable!==false).map(i=><Button key={i.id} onClick={()=>onNavigate(i)}>{hubItemLabel(i)}<small>Placer un repère vers la station</small></Button>)}</div>
 <h4>Rencontrer les habitants</h4><div className="hub-locations">{items.filter(i=>i.type==='hubNpc'&&i.district===place.district).map(i=><Button key={i.id} onClick={()=>onNavigate(i)}>{hubItemLabel(i)}<small>{i.role} · placer un repère</small></Button>)}</div>
 </div>;
}
