import {Button} from '../../design-system/index.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {HUB_SERVICE_PATTERNS,HUB_SERVICE_STYLES,HUB_SERVICE_VEHICLES,HUB_REFUGE_CARE,HUB_SERVICE_LIMITS,normalizeHubServices,normalizeHubDesign,hubDesignSvg} from './services-state.js';
import './hub-services.css';

const TITLES={garage:'Garage 3B',textile:'Atelier textile 3B',memorial:'Carnet du Mémorial',refuge:'Refuge des Jardins',gallery:'Ma galerie personnelle'};
const kindFor=service=>service==='garage'?'vehicle':service==='gallery'?'postcard':'textile';
const defaultDesign=service=>normalizeHubDesign({kind:kindFor(service),title:service==='garage'?'Ma livrée 3B':service==='gallery'?'Ma Cité des Héritages':'Ma tenue 3B'});
function downloadFile(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportDesign(design){downloadFile(hubDesignSvg(design),`${design.id||'creation-3b'}.svg`,'image/svg+xml;charset=utf-8');}
function Preview({design}){const uri=useMemo(()=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(hubDesignSvg(design))}`,[design]);return <img className="hub-service-preview" src={uri} alt={`Aperçu de ${design.title}`} width="640" height="540"/>;}

export default function HubServicePanel({service='gallery',save,act,onClose,onWardrobe}){
 const services=normalizeHubServices(save?.hub?.services),[draft,setDraft]=useState(()=>defaultDesign(service)),[message,setMessage]=useState(''),[tributeName,setTributeName]=useState(''),[tributeMessage,setTributeMessage]=useState(''),[confirmDelete,setConfirmDelete]=useState(null),[query,setQuery]=useState('');
 useEffect(()=>{setDraft(defaultDesign(service));setMessage('');setConfirmDelete(null);setQuery('');},[service]);
 const set=(key,value)=>setDraft(current=>({...current,[key]:value}));
 const perform=(action,success)=>{try{const result=act?.({type:'hubService',...action});if(result){setMessage(success);return result;}setMessage('L’enregistrement n’a pas abouti. Réessaie.');return null;}catch(error){setMessage(error.message);return null;}};
 const saveDesign=event=>{event.preventDefault();const result=perform({operation:'saveDesign',design:draft},'Création enregistrée dans ta galerie.');if(result){const next=normalizeHubServices(result.hub?.services);setDraft(next.designs.find(row=>row.id===draft.id)||next.designs.at(-1)||draft);}};
 const remove=(id,tribute=false)=>{if(perform({operation:tribute?'deleteTribute':'deleteDesign',id},tribute?'Hommage retiré du carnet.':'Création supprimée.')){setConfirmDelete(null);if(draft.id===id)setDraft(defaultDesign(service));}};
 const applyTextile=()=>{if(!save?.adventure?.avatar?.created){setMessage('Crée d’abord ton personnage pour lui appliquer cette tenue.');onWardrobe?.();return;}try{const result=act?.({type:'hubTextileWear',design:draft});setMessage(result?'Couleurs, motif et coupe appliqués à ton personnage.':'La tenue n’a pas pu être appliquée.');}catch(error){setMessage(error.message);}};
 const designs=services.designs.filter(row=>(service==='gallery'||row.kind===kindFor(service))&&(`${row.title} ${row.caption}`).toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')));
 const discovered=[...new Set(save?.hub?.stats?.secretProgress?.secret_workers_names||[])].filter(step=>Number.isInteger(step)&&step>=0&&step<8);
 const care=services.care.wolf_signal,rescued=save?.hub?.missions?.lost_wolf_signal?.status==='completed';
 return <article className="hub-service-panel" aria-label={TITLES[service]||TITLES.gallery}>
  <header><span className="world-kicker">Cité des Huit Héritages</span><h3>{TITLES[service]||TITLES.gallery}</h3><p>Ton carnet et tes créations sont conservés dans ta sauvegarde du Monde.</p></header>
  {['garage','textile','gallery'].includes(service)&&<>
   <p className="hub-service-note">{service==='garage'?'Compose et conserve la livrée de ta maquette de véhicule. L’aperçu et l’export sont disponibles ici ; cette maquette ne se conduit pas dans la Cité.':service==='textile'?'Choisis une coupe, deux couleurs et un motif. Applique la tenue à ton personnage ou exporte ta création vectorielle. Les motifs sont composés avec tes réglages.':'Rassemble tes créations, choisis celle à mettre en avant et dessine une carte souvenir de ta Cité. Les images exportées sont tes compositions d’atelier.'}</p>
   <div className="hub-service-workspace"><Preview design={draft}/><form onSubmit={saveDesign} className="hub-service-form">
    <label>Nom de la création<input required maxLength={48} value={draft.title} onChange={event=>set('title',event.target.value)}/></label>
    <label>Légende<textarea rows={2} maxLength={180} value={draft.caption} onChange={event=>set('caption',event.target.value)}/></label>
    {draft.kind==='vehicle'&&<label>Maquette<select value={draft.vehicle} onChange={event=>set('vehicle',event.target.value)}>{Object.entries(HUB_SERVICE_VEHICLES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}
    {draft.kind==='textile'&&<label>Coupe<select value={draft.style} onChange={event=>set('style',event.target.value)}>{Object.entries(HUB_SERVICE_STYLES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}
    <div className="hub-service-colors"><label>Couleur principale<input type="color" value={draft.baseColor} onChange={event=>set('baseColor',event.target.value)}/></label><label>Couleur du motif<input type="color" value={draft.accentColor} onChange={event=>set('accentColor',event.target.value)}/></label></div>
    <label>Motif<select value={draft.pattern} onChange={event=>set('pattern',event.target.value)}>{Object.entries(HUB_SERVICE_PATTERNS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
    <div className="hub-service-actions"><Button variant="ghost" type="submit" className="world-primary">{draft.id?'Enregistrer les modifications':'Enregistrer dans ma galerie'}</Button><Button variant="ghost" type="button" onClick={()=>exportDesign(draft)}>Exporter le SVG</Button>{draft.kind==='textile'&&<Button variant="ghost" type="button" onClick={applyTextile}>Porter cette tenue</Button>}<Button variant="ghost" type="button" onClick={()=>{setDraft(defaultDesign(service));setMessage('Nouvelle création.');}}>Nouvelle création</Button></div>
   </form></div>
   <section><div className="hub-service-section-title"><h4>{service==='gallery'?'Mes créations':'Créations enregistrées'}</h4><span>{services.designs.length}/{HUB_SERVICE_LIMITS.designs}</span></div><label className="hub-service-search">Rechercher<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Nom ou légende"/></label>
    {!designs.length&&<p>Aucune création {query?'ne correspond à ta recherche.':'enregistrée ici. Compose la première dans l’atelier.'}</p>}
    <div className="hub-service-gallery">{designs.map(design=><article key={design.id} className={services.featured===design.id?'is-featured':''}><Preview design={design}/><h5>{design.title}{services.featured===design.id&&<span> · À l’honneur</span>}</h5>{design.caption&&<p>{design.caption}</p>}<div className="hub-service-actions"><Button variant="ghost" type="button" onClick={()=>{setDraft(design);setMessage('Création chargée dans l’atelier.');}}>Modifier</Button><Button variant="ghost" type="button" onClick={()=>exportDesign(design)}>Exporter</Button><Button variant="ghost" type="button" disabled={services.featured===design.id} onClick={()=>perform({operation:'setFeatured',id:design.id},'Création mise à l’honneur.')}>Mettre à l’honneur</Button><Button variant="ghost" type="button" onClick={()=>setConfirmDelete(design.id)}>Supprimer</Button></div>{confirmDelete===design.id&&<div className="hub-service-confirm"><p>Supprimer « {design.title} » de ta galerie ?</p><Button variant="ghost" type="button" onClick={()=>remove(design.id)}>Confirmer la suppression</Button><Button variant="ghost" type="button" onClick={()=>setConfirmDelete(null)}>Garder</Button></div>}</article>)}</div>
    {services.designs.length>0&&<Button variant="ghost" type="button" onClick={()=>downloadFile(JSON.stringify({version:1,designs:services.designs,featured:services.featured},null,2),'galerie-personnelle-3b.json','application/json')}>Exporter le catalogue de ma galerie</Button>}
   </section>
  </>}
  {service==='memorial'&&<>
   <section><h4>Les huit inscriptions du Mémorial · {discovered.length}/8</h4><p>Retrouve les inscriptions dans les Jardins pour compléter ce relevé. Ton carnet d’hommages personnel reste distinct de ces découvertes.</p><ol className="hub-service-inscriptions">{Array.from({length:8},(_,i)=><li key={i} className={discovered.includes(i)?'is-found':''}>Inscription {i+1}<span>{discovered.includes(i)?'Retrouvée':'À retrouver dans les Jardins'}</span></li>)}</ol></section>
   <form className="hub-service-form" onSubmit={event=>{event.preventDefault();if(perform({operation:'saveTribute',name:tributeName,message:tributeMessage},'Hommage conservé dans ton carnet personnel.')){setTributeName('');setTributeMessage('');}}}><h4>Conserver un nom dans mon carnet</h4><label>Nom de la personne<input required maxLength={48} value={tributeName} onChange={event=>setTributeName(event.target.value)}/></label><label>Quelques mots de transmission<textarea maxLength={180} rows={3} value={tributeMessage} onChange={event=>setTributeMessage(event.target.value)}/></label><Button variant="ghost" type="submit" disabled={services.tributes.length>=HUB_SERVICE_LIMITS.tributes}>Inscrire cet hommage personnel</Button></form>
   <div className="hub-service-tributes">{services.tributes.map(tribute=><article key={tribute.id}><h5>{tribute.name}</h5><p>{tribute.message||'Un nom transmis, une mémoire conservée.'}</p><Button variant="ghost" type="button" onClick={()=>setConfirmDelete(tribute.id)}>Retirer du carnet</Button>{confirmDelete===tribute.id&&<div className="hub-service-confirm"><p>Retirer cet hommage ?</p><Button variant="ghost" type="button" onClick={()=>remove(tribute.id,true)}>Confirmer</Button><Button variant="ghost" type="button" onClick={()=>setConfirmDelete(null)}>Garder</Button></div>}</article>)}</div>
   {services.tributes.length>0&&<Button variant="ghost" type="button" onClick={()=>downloadFile(services.tributes.map(tribute=>`${tribute.name}\n${tribute.message}`).join('\n\n'),'carnet-memorial-3b.txt','text/plain;charset=utf-8')}>Exporter mon carnet</Button>}
  </>}
  {service==='refuge'&&<section className="hub-service-refuge"><span className="hub-service-animal" aria-hidden="true">◈</span><h4>L’espace du loup-signal</h4><p>{rescued?'Tu as protégé le loup-signal. Evelin t’invite à préparer un accueil respectueux et à garder tes distances.':'Evelin prépare un espace calme pour le loup-signal. Tu peux aménager cet accueil pendant que tu suis sa piste dans les Jardins.'}</p><p><strong>{care.length}/3 gestes d’accueil réalisés</strong></p><progress max="3" value={care.length} aria-label="Préparation de l’accueil du loup-signal"/><div className="hub-service-care">{Object.entries(HUB_REFUGE_CARE).map(([id,label])=><Button variant="ghost" type="button" key={id} disabled={care.includes(id)||(id==='observe'&&!rescued)} onClick={()=>perform({operation:'careAnimal',animal:'wolf_signal',task:id},`${label} : geste enregistré dans le carnet du refuge.`)}><span>{care.includes(id)?'✓':'○'}</span>{label}<small>{care.includes(id)?'Réalisé':id==='water'?'Remplir le point d’eau du refuge':id==='shelter'?'Préparer une zone abritée et dégagée':rescued?'Consigner une observation sans approcher':'Après la mission Le Signal du Loup'}</small></Button>)}</div>{care.length===3&&<p className="hub-service-note">L’accueil est prêt. Laisse au loup-signal une sortie et de l’espace : ta protection ne demande pas de le capturer.</p>}</section>}
  <p role="status" aria-live="polite" className="hub-service-status">{message}</p>
  <Button variant="ghost" type="button" className="hub-building-return" onClick={onClose}>Revenir dans la Cité</Button>
 </article>;
}
