/** Public places and story are anchored in the hub; rewards remain server-owned. */
import {HUB_SCALE,PLATFORM_DISTRICTS,platformPortal} from './platform-layout.js';
import {COUNTRIES} from '../catalog.js';
import {GUARDIAN_VALUES} from '../guardian-values.js';
import {REFERENCE_GATE_TITLES} from './gate-identity.js';
export const HUB_DISTRICT_STORIES=Object.freeze({
 heritage_square:{name:'Place de l’Héritage',story:'La Place de l’Héritage est le point d’arrivée de la cité. Maël t’apprend à lire ses chemins, rencontrer les habitants et rejoindre les huit portes. Les ouvriers ont laissé des repères jusqu’à la Place du Sol : une ville partagée commence par une place où chacun peut trouver sa route.',missions:['first_steps','voices_square'],services:['heritage_welcome','mission_hotel']},
 broken_circle_tower:{name:'Tour du Cercle Brisé',story:'La Tour du Cercle Brisé rassemble huit portes et un même héritage. Le Monstre de l’Oubli a séparé les Gardiens ; Noah cherche les fréquences qui rendent leur mémoire aux habitants. Depuis le Pont des Civilisations et le belvédère, observe les quartiers qui se répondent au-dessus de l’eau.',missions:['eight_signals'],services:['tower_circle']},
 archives:{name:'Les Archives de la Mémoire',story:'Connaître pour construire : Inès conserve les souvenirs que l’Oubli tente d’effacer. Le Mont des Savoirs garde la chronique des bâtisseurs ; le Lac des Reflets permet de comparer leurs récits. Une voix enregistrée à l’envers relie ces archives à une mémoire engloutie.',missions:['first_echo','broken_record','three_reflections'],services:['memory_archives','living_cards_gallery']},
 arena:{name:'Arène 3B',story:'Défis et entraînement : Hugo prépare les voyageurs aux parcours de mobilité et Sofia enseigne la maîtrise sous pression. La cité demeure une zone sûre. Observe les signaux depuis les Falaises d’Orient avant de choisir ton prochain entraînement.',missions:['rooftops_circle','passion_trial'],services:['arena_3b','mobility_center']},
 commerce:{name:'Quartier Commerce',story:'Créer, échanger, s’entreprendre : les artisans rapprochent les matières, les idées et les personnes. Aux Souks du Monde, une table raconte comment un même motif peut unir huit cultures. Les créateurs cherchent celui que l’Oubli n’arrive pas à reproduire.',missions:['golden_pattern','living_fabric'],services:['house_3b','garage_3b']},
 community:{name:'Quartier Communauté',story:'Rencontrer, échanger, grandir : une cité tient par les personnes qui s’entraident. Les désaccords se résolvent en écoutant plusieurs voix et en vérifiant leurs preuves. Les terrasses de la Place du Sol accueillent les récits et les rencontres, sans qu’un habitant perde son identité.',missions:['voices_square'],services:['community_house']},
 innovation:{name:'Quartier Innovation & IA',story:'Créer demain : les ateliers transforment la mémoire en matière. Le Lac des Reflets conserve l’écho des premières inventions ; le réseau bleu relie ces expériences aux huit portes. Répare ses relais et ses transports pour que le savoir circule à nouveau.',missions:['blue_blackout','silent_cable','living_fabric'],services:['ai_textile_lab','mode3_studio']},
 docks:{name:'Docks & Transports',story:'Connecter le monde : dans la Baie des Horizons, chaque départ doit avoir un retour. Un bateau sans pavillon porte une trace du Cercle et le Conducteur garde le secret du huitième wagon. Aux Rives du Soleil et face à la Mer Infinie, les navigateurs comparent les courants avant d’embarquer.',missions:['boat_without_flag','wagon_eight','storm_rescue','memory_under_water'],services:['central_marina','shipyard_3b','train_station']},
 gardens:{name:'Jardins de l’Unité',story:'Nature, équilibre, demain : huit graines gardent les liens de la cité. Écoute la Vallée des Cascades, compare les plantes des Jardins de la Dolce Vita et protège l’animal-signal. Les Terrasses de l’Onis conservent la mémoire de celles et ceux qui ont bâti ces îlots.',missions:['eight_seeds','garden_listens','lost_wolf_signal'],services:['workers_memorial','wildlife_refuge']},
 city3b_portal:{name:'Portail Ville 3B',story:'Visiter, voyager, repartir : le Bureau d’Urbanisme et la Galerie des Villes relient la vie de la cité à l’envie de bâtir. Lis la maquette et les plans avant de créer ta propre ville. Créer ma Ville conserve sa progression indépendante ; les habitants du hub gardent leur histoire commune.',missions:[],services:['city_planning_office','city_gallery']},
});
export const HUB_VALUES=Object.freeze(COUNTRIES.map(c=>GUARDIAN_VALUES[c.id].value));
/** The hub's inscriptions follow the reference; realm Guardian values keep their saved canon. */
export const HUB_REFERENCE_VALUES=Object.freeze(COUNTRIES.map(c=>REFERENCE_GATE_TITLES[c.id]));
export function hubDistrictStory(id){return HUB_DISTRICT_STORIES[id]||HUB_DISTRICT_STORIES.heritage_square;}
export function platformWorldState(save){
 const done=id=>save.hub?.missions?.[id]?.claimed===true;
 return {networkRestored:done('blue_blackout'),gardenRestored:done('eight_seeds'),communityUnited:done('voices_square'),workshopRestored:done('living_fabric'),memoryAwakened:done('first_echo'),missionsFinished:Object.values(save.hub?.missions||{}).filter(m=>m.claimed).length};
}
export function hubPublicPlaces(){
 const districts=Object.entries(HUB_DISTRICT_STORIES).map(([district,story])=>({id:'hub:place:'+district,type:'hubPublicPlace',kind:'district',district,name:'Borne · '+story.name,detail:story.story,actions:['use','inspect'],...PLATFORM_DISTRICTS[district],range:4.5}));
 // The core itself is a fountain. Put its public console on the approach promenade.
 districts.find(p=>p.district==='broken_circle_tower').z=28*HUB_SCALE;
 const sites={heritage_square:[0,50],archives:[-96,-52],arena:[95,-50],commerce:[125,0],community:[-95,20],innovation:[0,-125],docks:[0,116],city3b_portal:[80,104],gardens:[-92,64]};
 for(const p of districts)if(sites[p.district]){p.x=sites[p.district][0]*HUB_SCALE;p.z=sites[p.district][1]*HUB_SCALE;}
 const gates=HUB_VALUES.map((value,index)=>{const p=platformPortal(index),len=Math.hypot(p.x,p.z),r=len-18*HUB_SCALE,country=COUNTRIES[index],referenceValue=HUB_REFERENCE_VALUES[index];return {id:'hub:value:'+index,type:'hubPublicPlace',kind:'value',district:'broken_circle_tower',name:country.name+' · Porte de '+referenceValue,detail:'La porte de '+country.name+' porte '+referenceValue+'. Cette qualité inspire la vie de la cité : explorer, apprendre, créer et partager. Au-delà du hub, son Gardien poursuit l’histoire de '+value+'. Écoute les habitants et rapporte les fragments au Cercle pour reconstruire ces liens.',actions:['use','inspect'],value,referenceValue,country:country.id,index,x:p.x/len*r+Math.cos(index*Math.PI/4)*8*HUB_SCALE,z:p.z/len*r+Math.sin(index*Math.PI/4)*8*HUB_SCALE,range:4.5};});
 return [...districts,...gates];
}
