import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {newManifest,newScene,validateManifest,choiceLock,safeMedia,mediaPath,collectMedia,validatePoll,formatTime,demoManifest,MAX_MEDIA_BYTES} from '../src/destin/model.js';
const valid=()=>{const m=newManifest();m.nodes.forEach(n=>{n.src='https://media.example.org/'+n.id+'.mp4';});return m;};
const mutate=fn=>{const m=valid();fn(m);return validateManifest(m);};

test('destin: complete three-scene film validates',()=>assert.deepEqual(validateManifest(valid()),[]));
test('destin: empty template cannot accidentally publish',()=>assert.equal(validateManifest(newManifest()).length,3));
test('destin: each draft is an independent object',()=>{const a=newManifest(),b=newManifest();a.nodes[0].choices[0].label='changed';assert.notEqual(a.nodes[0].choices[0].label,b.nodes[0].choices[0].label);});
test('destin: unknown schema and invalid metadata fail',()=>assert.ok(mutate(m=>{m.schema=9;m.title='';m.synopsis='x'.repeat(1201);}).length>=3));
test('destin: missing target is detected',()=>assert.ok(mutate(m=>m.nodes[0].choices[0].target='missing').length));
test('destin: unknown entry is detected',()=>assert.ok(mutate(m=>m.entry='missing').length));
test('destin: duplicate scene identifiers are rejected',()=>assert.ok(mutate(m=>m.nodes[2].id=m.nodes[1].id).length));
test('destin: duplicate choices are rejected',()=>assert.ok(mutate(m=>m.nodes[0].choices[1].id='a').length));
test('destin: duplicate endings are rejected',()=>assert.ok(mutate(m=>m.nodes[2].ending.id=m.nodes[1].ending.id).length));
test('destin: circular narratives cannot publish',()=>assert.ok(mutate(m=>m.nodes[0].choices[0].target='intro').some(e=>e.includes('boucle'))));
test('destin: isolated scenes cannot publish',()=>assert.ok(mutate(m=>m.nodes.push({...newScene('isolated'),src:'https://media.example.org/isolated.mp4',ending:{id:'isolated',title:'Isolated',fragment:'',rarity:'standard',reward:false}})).some(e=>e.includes('isolées'))));
test('destin: a free choice prevents level soft-locks',()=>assert.ok(mutate(m=>m.nodes[0].choices.forEach(c=>c.minLevel=2)).some(e=>e.includes('accessible à tous'))));
test('destin: gated timeout defaults are rejected',()=>assert.ok(mutate(m=>m.nodes[0].choices[0].minLevel=2).some(e=>e.includes('automatique'))));
test('destin: no timer is a valid accessibility setting',()=>assert.deepEqual(mutate(m=>{m.nodes[0].timeout=0;m.nodes[0].defaultChoice='';}),[]));
test('destin: timers below five seconds are rejected',()=>assert.ok(mutate(m=>m.nodes[0].timeout=1).length));
test('destin: fifth answer is rejected',()=>assert.ok(mutate(m=>{m.nodes[0].choices=[1,2,3,4,5].map(i=>({id:'c'+i,label:'Choice '+i,target:'fin-a',minLevel:1,requiresEnding:''}));}).length));
test('destin: nonfinite and reversed timestamps are rejected',()=>{for(const value of [NaN,Infinity,-1])assert.ok(mutate(m=>m.nodes[0].start=value).length);assert.ok(mutate(m=>m.nodes[0].end=0).length);});
test('destin: ending scenes cannot also have choices',()=>assert.ok(mutate(m=>m.nodes[1].choices=[...m.nodes[0].choices]).length));
test('destin: missing ending requirements are rejected',()=>assert.ok(mutate(m=>m.nodes[0].choices[1].requiresEnding='missing').length));
test('destin: lock reasons come from authoritative level and unlock list',()=>{const c={minLevel:4,requiresEnding:'secret'};assert.match(choiceLock(c,{level:2}),/Niveau 4/);assert.ok(choiceLock(c,{level:4,unlocked:[]}));assert.equal(choiceLock(c,{level:4,unlocked:['secret']}),'');});
test('destin: HTTPS media and owned storage references are accepted',()=>{assert.ok(safeMedia('https://media.example.org/a.mp4'));const s='storage:11111111-1111-4111-8111-111111111111/22222222-2222-4222-8222-222222222222.mp4';assert.ok(safeMedia(s));assert.ok(mediaPath(s));});
test('destin: script, local file, data, insecure and credential URLs are rejected',()=>{for(const url of ['javascript:alert(1)','file:///tmp/a.mp4','data:video/mp4,evil','http://media.example.org/a.mp4','https://user:password@example.org/a.mp4','storage:../../secret',''])assert.equal(safeMedia(url),false,url);});
test('destin: media collection is deduplicated',()=>{const m=valid();m.nodes[1].src=m.nodes[0].src;assert.equal(collectMedia(m).length,2);});
test('destin: storage uses the actual 50 MiB bucket limit',()=>assert.equal(MAX_MEDIA_BYTES,52428800));
test('destin: demo never validates for publication',()=>{assert.deepEqual(validateManifest(demoManifest(),{preview:true}),[]);assert.ok(validateManifest(demoManifest()).length);assert.ok(demoManifest().nodes.every(n=>!n.ending?.reward));});
test('destin: poll options must be complete and unique',()=>{const p={question:'Quel chemin ?',options:[{id:'a',label:'Gauche'},{id:'b',label:'Droite'}],closesAt:'2026-10-06T15:00:00Z'};assert.equal(validatePoll(p),'');assert.ok(validatePoll({...p,options:[p.options[0],p.options[0]]}));assert.ok(validatePoll({...p,closesAt:'bad'}));});
test('destin: readable elapsed timestamps',()=>{assert.equal(formatTime(61.9),'1:01');assert.equal(formatTime(-5),'0:00');assert.equal(formatTime(NaN),'0:00');});
test('destin: application route and directory are integrated',()=>{const app=fs.readFileSync('src/App.jsx','utf8'),nav=fs.readFileSync('src/components/AppNavigation.jsx','utf8'),routes=fs.readFileSync('src/lib/navigation.js','utf8');assert.ok(app.includes('const DestinPage = lazy('));assert.ok(app.includes('id: "destin"'));assert.ok(app.includes('page === "destin"'));assert.ok(nav.includes('["world3b", "destin", "secret"]'));assert.ok(routes.includes('destin: "destin"'));});
test('destin: studio authorization is verified on the server, never user metadata',()=>{const entry=fs.readFileSync('supabase/functions/destin-api/index.ts','utf8'),handler=fs.readFileSync('supabase/functions/destin-api/handler.ts','utf8');assert.ok(entry.includes('db.auth.getUser('));assert.ok(handler.includes('owner_user_id===userId'));assert.ok(handler.includes("p_user:userId"));assert.ok(!handler.includes('user_metadata'));assert.ok(handler.includes('validateManifest(payload.manifest)'));assert.ok(handler.includes('createSignedUploadUrl'));});
test('destin: browser never contains an administrative key',()=>{for(const name of fs.readdirSync('src/destin')){if(!/\.(jsx|js)$/.test(name))continue;assert.ok(!fs.readFileSync('src/destin/'+name,'utf8').includes('SUPABASE_SERVICE_ROLE_KEY'),name);}});


test('destin: Mémoire and Avenir grants are permanent, idempotent and server guarded',()=>{
 const migration=fs.readFileSync('supabase/migrations/20261005170000_destin_le_combat_commence_rewards_v1.sql','utf8');
 assert.ok(migration.includes("'DESTIN_MEMORY_KEY'"));
 assert.ok(migration.includes("'DESTIN_FUTURE_COMPASS'"));
 assert.ok(migration.includes("'DESTIN_MEMORY_PAVILION'"));
 assert.ok(migration.includes("'DESTIN_FUTURE_WORKSHOP'"));
 assert.ok(migration.includes('primary key(user_id,story_id)'));
 assert.ok(migration.includes("p_ending not in ('combat-memoire','combat-avenir')"));
 assert.ok(migration.includes("public.market_mint_item("));
 assert.ok(migration.includes('destin_city_reward_guard'));
 assert.ok(migration.includes("p.building_code=new.building_code"));
});
test('destin: cross-app rewards stay hidden from accounts that did not earn their path',()=>{
 const city=fs.readFileSync('supabase/functions/city-3b/index.ts','utf8');
 assert.ok(city.includes('destin_required_item'));
 assert.ok(city.includes('ownedItemCodes.has(building.metadata.destin_required_item)'));
 const passport=fs.readFileSync('src/passport/PassportExperience.jsx','utf8');
 assert.ok(passport.includes("ending_id === 'combat-memoire'"));
 assert.ok(passport.includes("ending_id === 'combat-avenir'"));
 const world=fs.readFileSync('src/world/WorldPage.jsx','utf8');
 assert.ok(world.includes("'memory_archives'"));
 assert.ok(world.includes("'central_marina'"));
 assert.ok(world.includes("item?.buildingId===destinLegacy.worldPlace"));
});
test('destin: final screen exposes the earned object, Passport title, World capability and City building',()=>{
 const player=fs.readFileSync('src/destin/DestinPlayer.jsx','utf8');
 assert.ok(player.includes('snapshot.endingReward?.reward?.pathReward'));
 assert.ok(player.includes('Clé des Origines'));
 assert.ok(player.includes('Boussole de l’Aube'));
 assert.ok(player.includes('Pavillon de la Mémoire'));
 assert.ok(player.includes('Atelier de l’Avenir'));
});
