import test from 'node:test';
import assert from 'node:assert/strict';
import {Tower} from '../src/games/tower.js';
import {doorDifficulty,doorPerks,doorUnlocked,readDoorCampaign,freshDoorCampaign} from '../src/games/door-campaign.js';
import {freshProgress,validateProgress,recordGame} from '../src/games/save.js';
const enter=(g,type)=>g.door(g.doors.findIndex(d=>d.type===type));
function solveRunes(g){
 // Reconstruct the chain using only the visible clues and the labelled options.
 const names=Object.fromEntries(g.puzzle.options.map(r=>[r.name,r.id]));
 const links=g.puzzle.clues.map(s=>s.slice(0,-1).split(' précède immédiatement '));let current=links.find(([a])=>!links.some(([,b])=>b===a))[0];
 for(let i=0;i<g.puzzle.options.length;i++){g.chooseRune(names[current]);current=links.find(([a])=>a===current)?.[1];}g.checkRunes();
}
function solveLock(g){let steps=0;while(g.room==='mechanism'&&g.status==='playing'&&steps++<6000){g.update(1/120);if(g.lock.hold===0&&Math.abs(g.lock.position-g.lock.target)<g.difficulty.lockWidth*.4)g.stopMechanism();}assert.equal(g.room,'resolved');}
function solveFight(g){let turns=0;while(g.room==='combat'&&g.status==='playing'&&turns++<120){const e=g.enemy,power=16+g.perks.attack+g.bonusAttack+(g.counter?8:0);if(e.intent!=='guard'&&e.hp<=power&&g.focus>=1)g.attack();else if(e.intent==='strike'||g.focus<2)g.guard();else g.breakGuard();g.update(.6);}assert.ok(turns<120,'combat terminates');assert.equal(g.status==='ended'?g.won:g.room==='resolved',true,`duel won at level ${g.stageNumber}`);}
function solveRoom(g,type){enter(g,type);if(type==='runes')solveRunes(g);else if(type==='mechanism')solveLock(g);else solveFight(g);}
let campaign=freshDoorCampaign();
for(let level=1;level<=100;level++)test(`door: level ${level} is winnable through all three trials and its final guardian`,()=>{
 const g=new Tower(undefined,campaign,level);assert.equal(g.stageNumber,level);const p=doorPerks(campaign);assert.equal(g.player.maxHp,p.hp);
 for(let room=0;room<g.difficulty.rooms;room++){assert.equal(new Set(g.doors.map(d=>d.type)).size,3);solveRoom(g,['combat','runes','mechanism'][room%3]);g.chooseReward(g.player.hp<g.player.maxHp-10?'vitality':g.focus<g.perks.focus?'focus':'power');g.next();}
 assert.equal(g.room,'gate');g.openGate();if(g.difficulty.boss)solveFight(g);else g.update(1.1);
 assert.equal(g.won,true);assert.equal(g.stars,3);assert.equal(g.campaign.completed.length,level);assert.equal(doorUnlocked(g.campaign),Math.min(100,level+1));assert.equal(g.snapshot().run,null);assert.deepEqual(readDoorCampaign(g.snapshot()),g.snapshot());campaign=g.snapshot();
});
test('door: difficulty advances and all four permanent talents unlock once',()=>{const a=doorDifficulty(1),b=doorDifficulty(100);for(const key of ['rooms','enemyHp','damage','runes','lockRounds','lockSpeed','errorDamage'])assert.ok(b[key]>a[key],key);assert.ok(b.lockWidth<a.lockWidth);assert.deepEqual(doorPerks(campaign),{hp:110,attack:2,focus:6,elixirs:2});const g=new Tower(undefined,campaign,1);for(let i=0;i<3;i++){solveRoom(g,'runes');g.chooseReward('power');g.next();}g.openGate();g.update(1.1);assert.equal(g.firstClear,false);assert.equal(g.campaign.completed.length,100);assert.equal(g.campaign.best[1].stars,3);});
test('door: inspection is safe, double entry and premature gate cannot award a victory',()=>{const g=new Tower(1);g.selectDoor(0);assert.equal(g.room,'doors');assert.equal(g.player.hp,100);g.openGate();g.win();assert.equal(g.status,'playing');enter(g,'runes');const p=g.puzzle;g.door(0);assert.equal(g.puzzle,p);solveRunes(g);const score=g.score;g.clearRoom();g.checkRunes();g.next();assert.equal(g.room,'resolved');assert.equal(g.passed,1);assert.equal(g.score,score);g.chooseReward('power');g.chooseReward('power');assert.equal(g.bonusAttack,2);g.next();assert.equal(g.room,'doors');});
test('door: combat waits for player input, guard restores focus and lethal attacks never retaliate',()=>{const g=new Tower();enter(g,'combat');g.update(100);assert.equal(g.player.hp,100);assert.equal(g.enemy.hp,g.enemy.maxHp);g.focus=1;g.guard();g.guard();assert.equal(g.focus,3);g.update(.6);assert.equal(g.player.hp,98);assert.equal(g.counter,true);g.enemy.intent='strike';g.enemy.hp=10;const hp=g.player.hp;g.attack();g.update(.6);assert.equal(g.player.hp,hp);assert.equal(g.room,'resolved');});
test('door: guard and charged attacks require different counters; concentration cannot go negative',()=>{const g=new Tower();enter(g,'combat');g.enemy.hp=g.enemy.maxHp=200;g.enemy.intent='guard';g.attack();assert.equal(g.enemy.hp,196);assert.equal(g.mistakes,1);g.update(.6);g.enemy.intent='heavy';const hp=g.player.hp;g.breakGuard();g.update(.6);assert.equal(g.player.hp,hp);g.enemy.intent='guard';const enemyHp=g.enemy.hp;g.breakGuard();assert.equal(enemyHp-g.enemy.hp,26);g.update(.6);g.focus=0;g.attack();g.breakGuard();assert.equal(g.focus,0);assert.equal(g.busy,0);g.guard();assert.equal(g.focus,2);});
test('door: incorrect runes cost life, incomplete answers and repeated symbols do not',()=>{const g=new Tower();enter(g,'runes');g.checkRunes();assert.equal(g.player.hp,100);const p=g.puzzle;g.chooseRune(p.order[0]);g.chooseRune(p.order[0]);assert.equal(p.chosen.length,1);g.undoRune();for(const id of [...p.order].reverse())g.chooseRune(id);g.checkRunes();assert.equal(g.player.hp,94);assert.equal(g.mistakes,1);assert.deepEqual(p.chosen,[]);solveRunes(g);assert.equal(g.room,'resolved');});
test('door: mechanism counts each stop once and punishes missed windows',()=>{const g=new Tower();enter(g,'mechanism');g.stopMechanism();assert.equal(g.player.hp,94);assert.equal(g.mistakes,1);g.stopMechanism();assert.equal(g.player.hp,94);g.update(.5);solveLock(g);assert.equal(g.passed,1);});
test('door: death freezes all actions and time, clears the run and does not unlock levels',()=>{const g=new Tower();enter(g,'runes');g.player.hp=1;for(const id of [...g.puzzle.order].reverse())g.chooseRune(id);g.checkRunes();const t=g.time;g.update(100);g.heal();g.chooseReward('vitality');g.win();assert.equal(g.time,t);assert.equal(g.player.hp,0);assert.equal(g.won,false);assert.equal(doorUnlocked(g.campaign),1);assert.equal(g.snapshot().run,null);});
test('door: checkpoints restore the last threshold, including a single chosen boon',()=>{const g=new Tower();solveRoom(g,'runes');g.chooseReward('power');g.update(2);const restored=new Tower(undefined,g.snapshot());assert.equal(restored.room,'resolved');assert.equal(restored.rewardChosen,true);restored.chooseReward('power');assert.equal(restored.bonusAttack,2);restored.next();const before=restored.snapshot();enter(restored,'combat');restored.attack();restored.update(.6);const after=new Tower(undefined,restored.snapshot());assert.equal(after.room,'doors');assert.equal(after.player.hp,before.run.hp);assert.equal(after.focus,before.run.focus);assert.equal(after.passed,1);assert.ok(after.time>before.run.time);});
test('door: elixirs are limited and checkpointed; restart resets resources without erasing records',()=>{const g=new Tower();g.player.hp=40;g.heal();assert.equal(g.player.hp,75);g.heal();assert.equal(g.player.hp,75);assert.equal(g.usedElixirs,1);assert.equal(new Tower(undefined,g.snapshot()).elixirs,0);const reset=new Tower(undefined,g.snapshot(),1,{restart:true});assert.equal(reset.elixirs,1);assert.equal(reset.player.hp,100);});
test('door: legacy saves remain valid, malformed and non-sequential campaigns are rejected',()=>{const old={version:1,records:{tower:{best:800,plays:2,wins:1,floor:15}},maze:null,refuge:null,cities:null};assert.equal(validateProgress(old).tower,null);const fresh=freshProgress();fresh.tower=campaign;assert.deepEqual(validateProgress(fresh),fresh);assert.throws(()=>readDoorCampaign({...campaign,completed:[1,3]}));assert.throws(()=>readDoorCampaign({...campaign,best:{}}));const g=new Tower(),run=g.snapshot();assert.throws(()=>readDoorCampaign({...run,run:{...run.run,focus:99}}));assert.throws(()=>readDoorCampaign({...run,run:{...run.run,room:'combat'}}));const records=recordGame(fresh,'tower',new Tower(undefined,campaign,100));assert.equal(validateProgress(records).records.tower.floor,100);assert.equal(new Tower(undefined,null,100).stageNumber,1);});
