import test from 'node:test';import assert from 'node:assert/strict';
import {FINAL_GOLD_MASTER_SLOTS,FINAL_POLICE_SLOTS,FINAL_ENVIRONMENT_SLOTS,finalAssetProductionReport,nextFinalAssetTask} from '../src/games/underground/finalAssetProductionV3.js';
import {PREMIUM_ENVIRONMENT_PACKS,environmentProductionReport} from '../src/games/underground/environmentAssetManifestV3.js';
import {AUDIO_SLOTS,CINEMATIC_SLOTS,COUNTRY_AUDIO_CINEMATIC_PACKS,GLOBAL_CINEMATICS,VEHICLE_AUDIO_FAMILIES,mediaProductionReport} from '../src/games/underground/audioCinematicManifestV3.js';
import {CAPTURE_SCENARIOS,captureEvidenceTemplate,validateCaptureEvidence,captureSuiteReport} from '../src/games/underground/gameplayCaptureValidationV3.js';
import {assetReady,raceAssetGate} from '../src/games/underground/assetIntegrationDirectorV3.js';
import {finalProductionDashboard} from '../src/games/underground/finalProductionDashboardV3.js';

test('final production reserves exactly 160 player Gold Masters, 40 enforcement assets and 8 premium environments',()=>{assert.equal(FINAL_GOLD_MASTER_SLOTS.length,160);assert.equal(FINAL_POLICE_SLOTS.length,40);assert.equal(FINAL_ENVIRONMENT_SLOTS.length,8);assert.equal(PREMIUM_ENVIRONMENT_PACKS.every(x=>x.cityKits.length===20),true);});
test('empty production remains honestly at zero and starts with France',()=>{const r=finalAssetProductionReport({});assert.deepEqual(r.goldMasters,{done:0,total:160});assert.deepEqual(r.police,{done:0,total:40});assert.deepEqual(r.environments,{done:0,total:8});assert.equal(r.complete,false);assert.equal(nextFinalAssetTask({}).countryId,'france');});
test('media manifest reserves country audio, vehicle audio and cinematics without pretending files exist',()=>{assert.equal(COUNTRY_AUDIO_CINEMATIC_PACKS.length,8);assert.equal(AUDIO_SLOTS.length,8);assert.equal(CINEMATIC_SLOTS.length,4);assert.equal(VEHICLE_AUDIO_FAMILIES.length,6);assert.equal(GLOBAL_CINEMATICS.length,4);const r=mediaProductionReport({});assert.equal(r.audio.total,88);assert.equal(r.audio.done,0);assert.equal(r.cinematics.total,36);assert.equal(r.cinematics.done,0);});
test('environment packs require all modules, 20 city kits, real capture and 60fps',()=>{const r=environmentProductionReport({});assert.equal(r.total,8);assert.equal(r.complete,0);assert.equal(r.ready,false);});
test('race integration rejects concept or partial assets',()=>{assert.equal(assetReady({realAsset:true,validated:true,qaPass:true}),true);assert.equal(assetReady({realAsset:false,validated:true,qaPass:true}),false);const g=raceAssetGate({playerVehicle:{realAsset:true,validated:true,qaPass:true},opponents:[{realAsset:false}],environment:{realAsset:true,validated:true,qaPass:true}});assert.equal(g.ready,false);assert.ok(g.blockers.includes('opponent-0'));});
test('capture validation accepts only real-build evidence with enough frames and 60fps',()=>{const e=captureEvidenceTemplate('race-dry-day');assert.equal(validateCaptureEvidence(e).ok,false);e.video='/captures/race-dry-day.webm';e.screenshots=['a.png','b.png','c.png'];e.averageFps=60;e.frames=5400;e.approved=true;assert.equal(validateCaptureEvidence(e).ok,true);assert.equal(captureSuiteReport({}).complete,false);assert.equal(CAPTURE_SCENARIOS.length,6);});
test('unified dashboard cannot report release ready without real assets and captures',()=>{const d=finalProductionDashboard({health:{visual:100,vehicles:100,gameplay:100,world:100,police:100,performance:100,quality:100,averageFps:120},e2ePass:true,criticalBugs:0});assert.equal(d.ready,false);assert.equal(d.assets.goldMasters.done,0);assert.ok(d.release.blockers.some(x=>x.startsWith('gold-masters:')));});
