import test from 'node:test';
import assert from 'node:assert/strict';
import {HIDDEN_WORLD_RELEASE,RETIRED_CHALLENGE_ACTIONS,assertHiddenWorldAction,validateHiddenMission,hiddenMissionAvailability} from '../src/world/invisible/platform.js';
import {readInvisibleView,invisibleViewHref} from '../src/world/invisible/navigation.js';
const draft={id:'future-drawing',title:'Une future trace',status:'draft',realm:'france',kind:'drawing',place:{label:'Lieu à confirmer',instructions:'Consignes à valider',latitude:46,longitude:6,radiusMeters:25},targetAssetId:'asset-reference',recognizerId:'server-recognizer'};
test('No live or demonstration challenge and retired actions cannot be launched',()=>{assert.equal(HIDDEN_WORLD_RELEASE.phase,'preparation');assert.deepEqual(HIDDEN_WORLD_RELEASE.missions,[]);for(const type of RETIRED_CHALLENGE_ACTIONS)assert.throws(()=>assertHiddenWorldAction({type}),/retirées/);assert.doesNotThrow(()=>assertHiddenWorldAction({type:'invisibleForget'}));});
test('Publishing requires a precise valid location, reference, recognizer and server validation',()=>{assert.equal(validateHiddenMission(draft).ok,true);assert.equal(hiddenMissionAvailability(draft).state,'draft');assert.equal(validateHiddenMission({...draft,status:'published'}).ok,false);assert.equal(validateHiddenMission({...draft,status:'published',publicationId:'release-1',serverValidated:true}).ok,true);for(const latitude of [NaN,Infinity,91,'46'])assert.equal(validateHiddenMission({...draft,place:{...draft.place,latitude}}).ok,false);assert.equal(validateHiddenMission({...draft,targetAssetId:''}).ok,false);assert.equal(validateHiddenMission({...draft,recognizerId:''}).ok,false);assert.equal(validateHiddenMission({...draft,place:{...draft.place,radiusMeters:0}}).ok,false);assert.equal(hiddenMissionAvailability(null).state,'empty');});
test('Riddles require a question and a server validation reference, no embedded solution',()=>{const mission={...draft,kind:'riddle',question:'Question future',validationKey:'server-rule-1'};assert.equal(validateHiddenMission(mission).ok,true);assert.equal(validateHiddenMission({...mission,validationKey:''}).ok,false);assert.equal(validateHiddenMission({...mission,question:''}).ok,false);});
test('Scanner navigation survives reloads and browser history without losing unrelated parameters',()=>{const location=new URL('https://3b.example/?campaign=later#monde-invisible');const next=new URL(invisibleViewHref('scanner',location),location);assert.equal(readInvisibleView(next),'scanner');assert.equal(next.searchParams.get('campaign'),'later');assert.equal(readInvisibleView(new URL(invisibleViewHref('adventure',next),next)),'adventure');});
