import test from 'node:test';
import assert from 'node:assert/strict';
import {Matrix4} from 'three';
import {placementFromHit,manualPlacement,multiplyRigid,relativeRigid} from '../src/world/invisible/spatial-placement.js';
import {createSpatialSession} from '../src/world/invisible/spatial-session.js';
const pose=(x=0,y=0,z=0)=>new Matrix4().makeTranslation(x,y,z).toArray();
const wall=()=>new Matrix4().makeRotationX(Math.PI/2).setPosition(0,0,-.55).toArray();
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve;const promise=new Promise(yes=>resolve=yes);return {promise,resolve};};
class Session extends EventTarget{ends=0;cancels=0;domOverlayState={type:'screen'};reference=new EventTarget();async requestReferenceSpace(){return this.reference;}async requestHitTestSource(){return {cancel:()=>this.cancels++};}async end(){this.ends++;this.dispatchEvent(new Event('end'));}}
function fixture(extra={}){
 const session=new Session(),poses=[],states=[],candidates=[];let options;
 const controller=createSpatialSession({xr:{requestSession:async(mode,value)=>{options=value;return session;}},overlayRoot:{},attachSession:()=>session.reference,onState:value=>states.push(value),onPose:value=>poses.push(value),onCandidate:value=>candidates.push(value),makeTransform:(position,orientation)=>({position,orientation}),...extra});
 return {session,controller,poses,states,candidates,get options(){return options;}};
}
function frame(session,{viewer=pose(),hits=[],anchorPose=pose(0,0,-.55),createAnchor=()=>Promise.reject(Error('unexpected'))}={}){return {session,getViewerPose:()=>viewer?{transform:{matrix:viewer}}:null,getHitTestResults:()=>hits,getPose:()=>anchorPose?{transform:{matrix:anchorPose}}:null,createAnchor};}
function near(actual,expected){actual.forEach((value,index)=>assert.ok(Math.abs(value-expected[index])<1e-6,index+': '+value+' != '+expected[index]));}
test('wall placement at 55 cm is upright, centered and offsets the tracked plane toward the viewer',()=>{const result=placementFromHit(wall(),pose());assert.equal(result.kind,'wall');assert.ok(result.matrix[14]>-.55);assert.equal(result.matrix[5],1);near(multiplyRigid(wall(),result.offset),result.matrix);});
test('distances, sloped surfaces, ceilings and invalid transforms cannot receive an automatic portal',()=>{for(const z of [-.2,-1,-2])assert.equal(placementFromHit(new Matrix4().makeRotationX(Math.PI/2).setPosition(0,0,z).toArray(),pose()),null);assert.equal(placementFromHit(new Matrix4().makeRotationX(Math.PI).setPosition(0,0,-.55).toArray(),pose()),null);assert.equal(placementFromHit(new Matrix4().makeRotationX(Math.PI/4).setPosition(0,0,-.55).toArray(),pose()),null);const bad=wall();bad[0]=NaN;assert.equal(placementFromHit(bad,pose()),null);});
test('manual spatial placement follows viewer direction only at creation and supports a viewer translated in the room',()=>{const viewer=new Matrix4().makeRotationY(Math.PI/2).setPosition(2,1.7,3).toArray(),result=manualPlacement(viewer);assert.equal(result.kind,'manual');assert.ok(Math.abs(result.position.x-1.45)<1e-6);assert.equal(result.position.y,1.7);assert.equal(result.position.z,3);assert.equal(manualPlacement(new Matrix4().makeRotationX(Math.PI/2).toArray()),null);});
test('anchor-local offsets survive an updated world reference with rotation and translation',()=>{const a=new Matrix4().makeRotationY(.8).setPosition(1,2,3).toArray(),b=new Matrix4().makeRotationY(-.3).setPosition(2,3,4).toArray();near(multiplyRigid(a,relativeRigid(a,b)),b);});
test('a real anchor is required, follows its tracked pose, and never repositions to a moving viewer',async()=>{
 const f=fixture();await f.controller.start();assert.deepEqual(f.options.requiredFeatures,['local','hit-test','anchors','dom-overlay']);
 let creates=0,deletes=0;const anchor={anchorSpace:{},delete:()=>deletes++},hit={getPose:()=>({transform:{matrix:wall()}}),createAnchor:()=>{creates++;return Promise.resolve(anchor);}};
 f.controller.frame(frame(f.session,{hits:[hit]}));assert.equal(f.states.at(-1).phase,'surface');assert.equal(f.poses.at(-1),undefined);
 f.controller.requestPlacement();f.controller.frame(frame(f.session,{hits:[hit]}));await tick();assert.equal(creates,1);
 f.controller.frame(frame(f.session,{viewer:pose(.3,0,0),anchorPose:wall()}));const first=f.poses.at(-1).slice();
 f.controller.frame(frame(f.session,{viewer:pose(.7,0,0),anchorPose:wall()}));near(f.poses.at(-1),first);
 const moved=wall();moved[12]=.1;f.controller.frame(frame(f.session,{anchorPose:moved}));assert.ok(Math.abs(f.poses.at(-1)[12]-.1)<1e-6);
 f.controller.frame(frame(f.session,{anchorPose:null}));assert.equal(f.poses.at(-1),null);assert.equal(f.states.at(-1).phase,'tracking-lost');
 await f.controller.stop();assert.equal(deletes,1);assert.equal(f.session.cancels,1);assert.equal(f.session.ends,1);
});
test('blank wall fallback creates a native anchor at 55 cm inside the active frame, never a camera overlay',async()=>{const f=fixture();await f.controller.start();let transform;f.controller.requestPlacement();f.controller.frame(frame(f.session,{createAnchor:(value,space)=>{transform=value;assert.equal(space,f.session.reference);return Promise.resolve({anchorSpace:{},delete(){}});}}));await tick();assert.equal(transform.position.z,-.55);f.controller.frame(frame(f.session));assert.equal(f.states.at(-1).phase,'placed');assert.match(f.states.at(-1).message,/mur n’a pas été mesuré/);await f.controller.stop();});
test('loss of viewer tracking cannot place a stale surface or manual anchor',async()=>{const f=fixture();await f.controller.start();f.controller.requestPlacement();f.controller.frame(frame(f.session,{viewer:null,createAnchor:()=>assert.fail('no tracking')}));assert.equal(f.states.at(-1).canPlace,false);assert.equal(f.candidates.at(-1),null);await f.controller.stop();});
test('late anchors are deleted after close or reposition and cannot revive an object',async()=>{for(const action of ['stop','rePlace']){const f=fixture(),pending=deferred();await f.controller.start();let deletes=0;f.controller.requestPlacement();f.controller.frame(frame(f.session,{createAnchor:()=>pending.promise}));await f.controller[action]();pending.resolve({anchorSpace:{},delete:()=>deletes++});await tick();assert.equal(deletes,1);assert.equal(f.poses.at(-1),null);await f.controller.stop();}});
test('late permission and source results release native resources after closure',async()=>{const p=deferred(),f=fixture({xr:{requestSession:()=>p.promise}});const started=f.controller.start();await f.controller.stop();p.resolve(f.session);assert.equal(await started,false);assert.equal(f.session.ends,1);const q=deferred(),g=fixture();g.session.requestHitTestSource=()=>q.promise;const next=g.controller.start();await tick();await g.controller.stop();let cancel=0;q.resolve({cancel:()=>cancel++});assert.equal(await next,false);assert.equal(cancel,1);});
test('refused permissions and absent controls end the session without a misleading fallback',async()=>{const f=fixture({xr:{requestSession:async()=>{throw new DOMException('denied','NotAllowedError');}}});assert.equal(await f.controller.start(),false);assert.equal(f.controller.phase,'error');const g=fixture();g.session.domOverlayState=null;assert.equal(await g.controller.start(),false);assert.equal(g.session.ends,1);});
test('reference reset and native hiding remove anchors and close tracking resources',async()=>{const f=fixture();await f.controller.start();f.controller.frame(frame(f.session));f.session.reference.dispatchEvent(new Event('reset'));assert.equal(f.poses.at(-1),null);f.session.visibilityState='hidden';f.session.dispatchEvent(new Event('visibilitychange'));await tick();assert.equal(f.controller.active,false);assert.equal(f.session.cancels,1);});
