import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createHubPlatform} from '../src/world/hub/platform-scene.js';
import {referenceLandmarkPlans} from '../src/world/hub/reference-landmarks.js';
import {HUB_SCALE} from '../src/world/hub/platform-layout.js';
import {blankSave} from '../src/world/rules.js';

test('real landmark signs face their interaction and never obscure it with mirrored back faces',async()=>{
 const previousDocument=globalThis.document,load=THREE.TextureLoader.prototype.load;
 // Rasterization and external textures are irrelevant to face culling. Keep the
 // real sign geometry, transforms, material and text generated by the Hub.
 globalThis.document={createElement(tag){
  assert.equal(tag,'canvas');
  const canvas={},context={fillText(text){canvas.signText=text;}};
  for(const method of ['fillRect','strokeRect','clearRect','beginPath','closePath','moveTo','lineTo','arc','fill','stroke'])context[method]=()=>{};
  canvas.getContext=()=>context;return canvas;
 }};
 THREE.TextureLoader.prototype.load=function(_url,onLoad){const texture=new THREE.Texture();queueMicrotask(()=>onLoad?.(texture));return texture;};
 let hub;
 try{
  hub=createHubPlatform(blankSave());await hub.ready;hub.root.updateMatrixWorld(true);
  const signs=new Map(),flags=[];
  hub.root.traverse(mesh=>{
   const canvas=mesh.material?.map?.image;
   if(canvas?.signText)signs.set(canvas.signText,mesh);
   else if(canvas?.width===360&&canvas?.height===240)flags.push(mesh);
  });
  const ray=new THREE.Raycaster();
  for(const plan of referenceLandmarkPlans()){
   const label=signs.get(plan.site.name.toUpperCase());assert.ok(label,plan.site.name+' has its real text mesh');
   assert.equal(label.material.side,THREE.FrontSide);
   const centre=label.getWorldPosition(new THREE.Vector3()),normal=new THREE.Vector3(0,0,1).transformDirection(label.matrixWorld);
   const anchor=plan.anchors.find(item=>item.id.endsWith(':display'));
   const approach=new THREE.Vector3(anchor.x*HUB_SCALE,centre.y,anchor.z*HUB_SCALE);
   assert.ok(approach.clone().sub(centre).dot(normal)>0,plan.site.name+' faces its reading or examination approach');
   ray.set(approach,centre.clone().sub(approach).normalize());
   assert.ok(ray.intersectObject(label).length>0,plan.site.name+' remains readable from the front');
   ray.set(centre.clone().addScaledVector(normal,-15),normal);
   assert.equal(ray.intersectObject(label).length,0,plan.site.name+' leaves the rear camera view clear');
  }
  assert.equal(flags.length,8,'all eight country flags remain present');
  assert.ok(flags.every(flag=>flag.material.side===THREE.DoubleSide),'cloth flags still render from both sides');
 }finally{
  hub?.dispose();THREE.TextureLoader.prototype.load=load;
  if(previousDocument===undefined)delete globalThis.document;else globalThis.document=previousDocument;
 }
});
