import test from 'node:test';
import assert from 'node:assert/strict';
import { NEXUS_WORLDS, resolveNexusWorld, nexusGatePosition, nexusPixelRatio, rememberNexusCountry } from '../src/components/nexus-worlds.js';
import { queueNexusVisit, consumeNexusVisit, NEXUS_REQUEST_KEY } from '../src/components/nexus-handoff.js';
function memory(){const data=new Map();return{setItem:(k,v)=>data.set(k,v),getItem:k=>data.get(k)||null,removeItem:k=>data.delete(k)};}
test('exactly eight unique countries and established guardians',()=>{assert.equal(NEXUS_WORLDS.length,8);assert.equal(new Set(NEXUS_WORLDS.map(w=>w.id)).size,8);assert.equal(resolveNexusWorld('FR').guardian,'Céliane');assert.equal(resolveNexusWorld('TN').guardian,'Soraya');assert.equal(resolveNexusWorld('EE').value,'Sagesse');});
for(const world of NEXUS_WORLDS)test(`one-shot destination ${world.code}`,()=>{const storage=memory();assert.equal(queueNexusVisit(storage,world.code,1000),true);assert.deepEqual(consumeNexusVisit(storage,1100),{type:'visit',region:world.id});assert.equal(consumeNexusVisit(storage,1200),null);});
test('ORIGINE cannot create a world travel command',()=>{const storage=memory();for(const value of ['ORIGIN','ORIGINE','__proto__',null,{}]){assert.equal(queueNexusVisit(storage,value,1000),false);assert.equal(resolveNexusWorld(value),null);}});
test('expired, future and malformed requests are ignored and removed',()=>{const storage=memory();for(const value of ['{',JSON.stringify({code:'FR',at:999999}),JSON.stringify({code:'FR',at:1}),JSON.stringify({code:'FR',at:'100'})]){storage.setItem(NEXUS_REQUEST_KEY,value);assert.equal(consumeNexusVisit(storage,150000),null);assert.equal(storage.getItem(NEXUS_REQUEST_KEY),null);}});
test('blocked browser storage never breaks navigation',()=>{const blocked={setItem(){throw Error('blocked');},getItem(){throw Error('blocked');},removeItem(){throw Error('blocked');}};assert.equal(queueNexusVisit(blocked,'FR'),false);assert.equal(consumeNexusVisit(blocked),null);assert.equal(rememberNexusCountry(blocked,'FR'),false);});
test('remembering a country does not write a reward or save key',()=>{const writes=[];assert.equal(rememberNexusCountry({setItem:(k,v)=>writes.push([k,v])},'DZ'),true);assert.deepEqual(writes,[['3b:nexus-country','DZ']]);});
test('render budget is bounded on high-density mobile screens',()=>{assert.equal(nexusPixelRatio(390,4),1.35);assert.equal(nexusPixelRatio(1440,4),1.75);assert.equal(nexusPixelRatio(390,4,'light'),1);assert.equal(nexusPixelRatio(390,NaN),1);});
test('gate positions form a finite distinct arc',()=>{const points=NEXUS_WORLDS.map((_,i)=>nexusGatePosition(i));assert.ok(points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.z)));assert.equal(new Set(points.map(p=>`${p.x},${p.z}`)).size,8);assert.ok(Math.abs(points[0].x+points[7].x)<1e-6);});
