import test from 'node:test';
import assert from 'node:assert/strict';
import {NEXUS_DOORS,doorByCode,nexusProgress,readSelectedDoor,canTravelFromNexus} from '../src/components/nexus-data.js';
import {NEXUS_DOORS as GAME_DOORS,nexusProgress as gameProgress,planNexusActions,enterNexusWorld} from '../src/passport/nexus-flow.js';
const complete=()=>({region:'hub',seals:NEXUS_DOORS.map(d=>d.id),adventure:{chapters:Object.fromEntries(NEXUS_DOORS.map(d=>[d.id,{restored:3}]))}});
test('eight distinct countries and architectural silhouettes',()=>{for(const field of ['id','code','guardian','shape'])assert.equal(new Set(NEXUS_DOORS.map(x=>x[field])).size,8);assert.equal(NEXUS_DOORS.length,8);});
test('art direction preserves canonical country/value mapping',()=>{assert.deepEqual(NEXUS_DOORS.map(d=>[d.code,d.id,d.country,d.value]),GAME_DOORS.map(d=>[d.code,d.region,d.country,d.value]));});
test('unknown or corrupt progress never unlocks ORIGINE',()=>{for(const s of [undefined,null,{}, {seals:'france'},{seals:Array(9).fill('france')},{seals:['fake']},{xp:999999,visited:NEXUS_DOORS.map(d=>d.id)}])assert.equal(nexusProgress(s).originUnlocked,false);});
test('eight seals without rebuilt countries do not unlock ORIGINE',()=>assert.equal(nexusProgress({seals:NEXUS_DOORS.map(d=>d.id)}).originUnlocked,false));
test('seven seals do not unlock ORIGINE',()=>{const s=complete();s.seals.pop();assert.equal(nexusProgress(s).originUnlocked,false);});
test('seven rebuilt countries do not unlock ORIGINE',()=>{const s=complete();s.adventure.chapters.france.restored=2;assert.equal(nexusProgress(s).originUnlocked,false);});
test('eight seals and eight reconstructions unlock the existing finale',()=>{const s=complete();assert.equal(nexusProgress(s).originUnlocked,true);assert.deepEqual(planNexusActions(s,'ORIGINE'),[{type:'final'}]);});
test('a completed finale cannot be newly started by the visual wrapper',()=>{const s=complete();s.adventure.finished=true;assert.equal(nexusProgress(s).originUnlocked,false);});
test('presentation wrapper delegates the gate to canonical gameplay',()=>{for(const s of [null,complete(),{seals:['france']}])assert.equal(nexusProgress(s).originUnlocked,gameProgress(s).originReady);});
test('progress read is immutable and filters duplicates',()=>{const s=Object.freeze({seals:Object.freeze(['france','fake','france'])});assert.deepEqual(nexusProgress(s).keys,['FR']);});
test('invalid or blocked storage has a safe fallback',()=>{assert.equal(readSelectedDoor({getItem(){throw Error('blocked');}}),'FR');assert.equal(readSelectedDoor({getItem:()=>'<script>'}),'FR');assert.equal(readSelectedDoor({getItem:()=> 'EE'}),'EE');assert.equal(doorByCode('unknown'),null);});
test('in-progress encounter is not bypassed via a country',()=>{const s={region:'france',adventure:{encounter:{result:null}}};assert.equal(canTravelFromNexus(s),false);assert.throws(()=>planNexusActions(s,'IT'),/rencontre/);assert.deepEqual(planNexusActions(s,undefined),[]);});
test('existing unresolved finale is resumed without creating another fight',()=>{assert.deepEqual(planNexusActions({adventure:{encounter:{final:true,result:null}}},'ORIGINE'),[]);});
test('country change uses the existing hub visit command',()=>{assert.deepEqual(planNexusActions({region:'france'},'EE'),[{type:'visit',region:'hub'},{type:'visit',region:'estonie'}]);});
test('same-country selection records no duplicate visit',()=>assert.deepEqual(planNexusActions({region:'france'},'FR'),[]));
test('closed or changed account does not record a late command',async()=>{let active=true,writes=0;const api={loadWorld:async()=>{active=false;return{data:{region:'hub'}};},recordWorldAction:()=>writes++};assert.equal(await enterNexusWorld(api,'account-a','FR',()=>active),null);assert.equal(writes,0);});
test('the full route is validated before the first record',async()=>{let writes=0;const api={loadWorld:async()=>({data:{region:'france'}}),applyWorldAction:(s,a)=>{if(a.region==='italie')throw Error('refused');return{...s,region:a.region};},recordWorldAction:()=>writes++};await assert.rejects(()=>enterNexusWorld(api,null,'IT'),/refused/);assert.equal(writes,0);});
test('render preference does not grant seals or rewards',()=>{const s=complete();const copy=JSON.stringify(s);for(const d of NEXUS_DOORS)doorByCode(d.code);nexusProgress(s);assert.equal(JSON.stringify(s),copy);});
