import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { normalizeMemberHandle, normalizeProjectPayload, reviewPreview, validateProjectPayload } from "../src/nosbloc/staging-contract.js";
const read = rel => readFileSync(new URL(rel, import.meta.url), "utf8");
const client=read("../src/nosbloc/staging-client.js"),panel=read("../src/nosbloc/NosblocServerPanel.jsx"),edge=read("../supabase/functions/nosbloc-staging/index.ts"),sql=read("../supabase/staging/20260926030000_nosbloc_server_staging_v1.sql"),manifest=JSON.parse(read("../supabase/functions/DEPLOYED_FUNCTIONS_SNAPSHOT.json"));

test("staging client is fail-closed and sends the real Passport session JWT",()=>{assert.match(client,/VITE_NOSBLOC_STAGING_SYNC/);assert.match(client,/NOSBLOC_STAGING_DISABLED/);assert.match(client,/Authorization: `Bearer \$\{session\.access_token\}`/);assert.doesNotMatch(client,/SERVICE_ROLE/);});
test("project contract normalizes payloads and requires exact 100 percent",()=>{const p=normalizeProjectPayload({id:"p-123",title:"Ville Test",type:"world",template:"Ville",description:"Une description suffisamment longue pour valider le contrat de synchronisation staging.",safety:{moderation:true},rights:{contentOwned:true,thirdPartyLicensed:true,audienceReviewed:true},splits:[{id:"owner",name:"Zakaria",role:"Direction",shareBps:10000,status:"owner"}]});assert.equal(validateProjectPayload(p).valid,true);assert.equal(reviewPreview(p).agreementsAccepted,true);assert.equal(normalizeMemberHandle("Zakaria_3B"),"zakaria_3b");});
test("review preview blocks unaccepted collaborators",()=>{const p={id:"p-456",title:"Projet équipe",type:"game",template:"Course",description:"Une expérience mobile complète avec contrôles, équipe et modération avant diffusion.",safety:{moderation:true},rights:{contentOwned:true,thirdPartyLicensed:true,audienceReviewed:true},splits:[{id:"o",name:"O",role:"Direction",shareBps:5000,status:"owner"},{id:"m",name:"M",role:"3D",shareBps:5000,status:"invited"}]};assert.equal(reviewPreview(p).ready,false);p.splits[1].status="accepted";assert.equal(reviewPreview(p).ready,true);});
test("Edge function has a kill switch, authenticated sessions and no payment or Discover action",()=>{assert.match(edge,/NOSBLOC_STAGING_ENABLED/);assert.match(edge,/loyalty_session_valid/);assert.match(edge,/project_sync/);assert.match(edge,/invite_decide/);assert.match(edge,/review_submit/);assert.match(edge,/moderation_decide/);assert.doesNotMatch(edge,/"publish"|"payout"|"payment"|"discover"/);});
test("staging schema links projects to member_profiles and keeps all public features locked",()=>{assert.match(sql,/references public\.member_profiles/);assert.match(sql,/discover_enabled boolean not null default false/);assert.match(sql,/payments_enabled boolean not null default false/);assert.match(sql,/payouts_enabled boolean not null default false/);assert.match(sql,/visibility text not null default 'private' check\(visibility='private'\)/);assert.match(sql,/enable row level security/g);assert.match(sql,/revoke all .* public,anon,authenticated/);});
test("versions and audit records are immutable and invitations are accepted only by their real account",()=>{assert.match(sql,/nosbloc_stg_versions_immutable/);assert.match(sql,/nosbloc_stg_audit_immutable/);assert.match(sql,/invited_user_id=p_user/);assert.match(sql,/membership_status=v_status/);assert.match(sql,/sum\(share_bps\)/);assert.match(sql,/membership_status not in\('owner','accepted'\)/);});
test("human moderation cannot unlock publication, Discover or money",()=>{assert.match(sql,/public_badge_key='director_founder'/);assert.match(sql,/moderation_queue/);assert.match(sql,/status=p_decision,visibility='private',publication_locked=true,discover_locked=true,monetization_locked=true/);});
test("server package stays source-only until an isolated environment exists",()=>{assert.equal(existsSync(new URL("../supabase/staging/20260926030000_nosbloc_server_staging_v1.sql",import.meta.url)),true);assert.equal(existsSync(new URL("../supabase/migrations/20260926030000_nosbloc_server_staging_v1.sql",import.meta.url)),false);assert.equal(manifest.functions.some(row=>row.slug==="nosbloc-staging"),false);assert.match(panel,/ENVIRONNEMENT DE TEST/);assert.match(panel,/Discover fermé/);assert.match(panel,/Paiements fermés/);});
