import test from 'node:test';
import assert from 'node:assert/strict';
import {COUNTRIES,ALL_EVENTS,eventsFor,isCountryUnlocked} from '../src/games/underground/data.js';
import {createCareerState,completeEvent,bossUnlocked,registerRivalDefeat,completeBossStage,validateCareerState} from '../src/games/underground/career.js';
import {DEFAULT_VEHICLE,performanceIndex,applyUpgrade} from '../src/games/underground/carModel.js';
import {createRaceSession,stepRace,raceResult} from '../src/games/underground/raceEngine.js';

test('Underground contains 8 countries and 192 career events',()=>{assert.equal(COUNTRIES.length,8);assert.equal(ALL_EVENTS.length,192);for(const c of COUNTRIES)assert.equal(eventsFor(c.id).length,24);});
test('country gates follow fragments',()=>{const s=createCareerState();assert.equal(isCountryUnlocked('france',s),true);assert.equal(isCountryUnlocked('algeria',s),false);s.territories.france.guardianDefeated=true;s.fragments.push('france');assert.equal(isCountryUnlocked('algeria',s),true);assert.equal(isCountryUnlocked('spain',s),true);});
test('vehicle upgrades increase performance index',()=>{const base=performanceIndex(DEFAULT_VEHICLE);let v=DEFAULT_VEHICLE;for(let i=0;i<5;i++)v=applyUpgrade(v,'engine');assert.ok(performanceIndex(v)>base);});
test('event completion rewards without mutating source state',()=>{const s=createCareerState(),e=eventsFor('france')[0];const r=completeEvent(s,e.id,{finished:true,position:1,time:100,targetTime:115,score:15000,collisions:0,offroadSeconds:0,bestSpeedKph:210,driftScore:0});assert.ok(r.reward.influence>0);assert.ok(r.state.territories.france.influence>0);assert.equal(s.territories.france.influence,0);});
test('guardian unlock and four stages award a fragment',()=>{let s=createCareerState();s.territories.france.influence=10000;for(const e of eventsFor('france').filter(e=>e.major).slice(0,3))s.territories.france.events[e.id]={wins:1,bestStars:3,bestTime:100,bestScore:15000};for(const e of eventsFor('france').filter(e=>!e.major).slice(0,3))s.territories.france.events[e.id]={wins:1,bestStars:3,bestTime:100,bestScore:15000};s=registerRivalDefeat(s,'france','france-lieutenant','lieutenant');assert.equal(bossUnlocked(s,'france'),true);for(let i=0;i<4;i++)s=completeBossStage(s,'france',i,true).state;assert.equal(s.territories.france.guardianDefeated,true);assert.deepEqual(s.fragments,['france']);});
test('race engine produces a valid result',()=>{const event=eventsFor('france')[0],s=createRaceSession({event,vehicle:DEFAULT_VEHICLE,difficulty:'easy'});let guard=0;while(s.status!=='finished'&&guard++<20000)stepRace(s,{throttle:1,brake:0,steer:0,nitrous:true},.02);const r=raceResult(s);assert.ok(r.time>0);assert.ok(r.position>=1);});
test('career validation restores safe structure',()=>{const s=createCareerState();s.coins=Infinity;s.fragments=['france','bad'];const clean=validateCareerState(s);assert.ok(Number.isFinite(clean.coins));assert.deepEqual(clean.fragments,['france']);});
