import test from 'node:test';
import assert from 'node:assert/strict';
import {CUSTOMIZATION_CATEGORIES,CUSTOMIZATION_OPTIONS,CUSTOMIZATION_SLOTS,DEFAULT_CUSTOMIZATION,addVinylLayer,customizationStats,normalizeCustomization} from '../src/games/underground/customization.js';
import {DEFAULT_VEHICLE,UPGRADE_KEYS,applyUpgrade,performanceIndex} from '../src/games/underground/carModel.js';
import {activeVehicle,buyVisualPart,createCareerState,setVehicleNeon,setVehiclePlate,setVisualColor} from '../src/games/underground/career.js';

test('ultra customization catalogue covers every requested family',()=>{const categories=new Set(CUSTOMIZATION_CATEGORIES.map(x=>x.id));for(const id of ['body','wheels','lighting','paint','livery','interior','audio','engineBay','identity'])assert.ok(categories.has(id));assert.ok(CUSTOMIZATION_SLOTS.some(x=>x.id==='seats'));assert.ok(CUSTOMIZATION_SLOTS.some(x=>x.id==='headUnit'));assert.ok(CUSTOMIZATION_SLOTS.some(x=>x.id==='headlights'));assert.ok(CUSTOMIZATION_SLOTS.some(x=>x.id==='underglowHardware'));assert.ok(CUSTOMIZATION_OPTIONS.length>=250);});
test('customization remains independent of final vehicle mesh',()=>{const c=normalizeCustomization(DEFAULT_CUSTOMIZATION);assert.equal(DEFAULT_VEHICLE.modelAsset,null);assert.ok(customizationStats(c).slots>=45);});
test('livery editor supports up to 128 independent layers',()=>{let c=normalizeCustomization(DEFAULT_CUSTOMIZATION);for(let i=0;i<140;i++)c=addVinylLayer(c,{kind:'shape',shape:'stripe',x:(i%10)/10});assert.equal(c.vinylLayers.length,128);});
test('visual parts can be bought and equipped without affecting modelAsset',()=>{let state=createCareerState();const option=CUSTOMIZATION_OPTIONS.find(x=>x.slot==='seats'&&x.price>0);const before=state.coins;const result=buyVisualPart(state,option.id);assert.equal(result.error,null);state=result.state;const v=activeVehicle(state);assert.equal(v.modelAsset,null);assert.equal(v.customization.selections.seats,option.id);assert.equal(state.coins,before-option.price);});
test('paint, neon and plate are persistent data',()=>{let state=createCareerState();state=setVisualColor(state,'primary','#123456');state=setVehicleNeon(state,'enabled',true);state=setVehicleNeon(state,'color','#2f75ff');state=setVehiclePlate(state,{text:'3B 888',style:'gold'});const c=activeVehicle(state).customization;assert.equal(c.colors.primary,'#123456');assert.equal(c.neon.enabled,true);assert.equal(c.plate.text,'3B 888');assert.equal(c.plate.style,'gold');});
test('performance tuning has been expanded beyond the original eight systems',()=>{assert.ok(UPGRADE_KEYS.length>=18);const base=performanceIndex(DEFAULT_VEHICLE);let v=DEFAULT_VEHICLE;for(const key of ['engine','intake','ecu','fuel','exhaust','turbo','intercooler'])v=applyUpgrade(v,key);assert.ok(performanceIndex(v)>base);});
