import test from 'node:test';import assert from 'node:assert/strict';
import {createCombat,command,stepCombat} from '../src/world/origins/combat.js';
import {defenseOutcome} from '../src/world/origins/weapon-styles.js';
const flags={echo:true,echo2:true},p={x:0,z:23};
function ready(weapon){const c=createCombat();c.loadout={weapon};c.enemy.x=0;c.enemy.z=25;c.enemy.state='recover';c.enemy.timer=10;return c;}
test('scissors detach with a real cost, forbid guarding and recall before another attack',()=>{const c=ready('scissors');assert.equal(command(c,'circle',p),true);assert.equal(c.energy,40);assert.equal(c.detached,4);assert.equal(command(c,'guard',p),false);command(c,'light',p);assert.equal(c.attack.definition.range,6);for(let i=0;i<12;i++)stepCombat(c,.05,p,0,flags,'sanctuary');assert.ok(c.enemy.hp<130);assert.ok(command(c,'circle',p));assert.equal(c.detached,0);assert.equal(command(c,'light',p),false);for(let i=0;i<7;i++)stepCombat(c,.05,p,0,flags,'sanctuary');assert.ok(command(c,'guard',p));});
test('lance needs a narrow aiming line and loses damage at point blank distance',()=>{const c=ready('paris');c.enemy.x=2;c.enemy.z=24;command(c,'light',p);for(let i=0;i<12;i++)stepCombat(c,.05,p,0,flags,'sanctuary');assert.equal(c.enemy.hp,130);const near=ready('paris');near.enemy.z=23.5;command(near,'light',p);for(let i=0;i<12;i++)stepCombat(near,.05,p,0,flags,'sanctuary');assert.ok(near.enemy.hp>122&&near.enemy.hp<130);});
test('shield blocks only the front and fails if endurance cannot absorb impact',()=>{const c=ready('zellige');assert.ok(command(c,'guard',p));c.guardAge=.5;assert.equal(defenseOutcome(c,Math.PI,p,c.enemy).blocked,false);assert.equal(defenseOutcome(c,0,p,c.enemy,true).blocked,false);const r=defenseOutcome(c,0,p,c.enemy);assert.equal(r.reduction,.8);assert.equal(c.stamina,70);assert.equal(c.guard,0);command(c,'guard',p);c.stamina=10;assert.equal(defenseOutcome(c,0,p,c.enemy).broken,true);});
test('guard has a limited lifetime and dodge cancels it',()=>{const c=ready('zellige');command(c,'guard',p);for(let i=0;i<42;i++)stepCombat(c,.05,p,0,{},'sanctuary');assert.equal(c.guard,0);command(c,'guard',p);command(c,'dodge',p);assert.equal(c.guard,0);});
