import test from 'node:test';
import assert from 'node:assert/strict';
import {blankSave,normalizeSave,teamStats} from '../src/world/rules.js';
import {applyWorldAction} from '../src/world/engine.js';
import {CHARACTERS,CARDS} from '../src/world/catalog.js';
import {livingPlaceCollisions} from '../src/world/places.js';
import {toLandscape} from '../src/world/terrain.js';
const act=(s,type,other={})=>applyWorldAction(s,{type,...other});
function restored(choice){let s=act(blankSave(),'visit',{region:'maroc'});s=act(s,'help');for(const power of ['ally','ambiance','terrain'])s=act(s,'power',{power});for(const index of [0,1,1,2,2,2])s=act(s,'puzzleStep',{index});s=act(s,'solve');for(const id of [0,1,2])s=act(s,'beacon',{id:'maroc:'+id});return act(s,'restore',{choice});}
test('companions preserve all source beings and saved ownership without representing objects as people',()=>{assert.equal(CHARACTERS.length,172);assert.equal(CARDS.length,368);let s=blankSave();assert.throws(()=>act(s,'companion',{id:'C002'}));assert.throws(()=>act(s,'companion',{id:'C357'}));s=act(s,'visit',{region:'maroc'});s=act(s,'help');const id=s.team[0],before={...s.collection};s=act(s,'companion',{id});assert.equal(normalizeSave(s).adventure.companion,id);assert.deepEqual(s.collection,before);assert.equal(s.adventure.avatar.name,'Voyageur');assert.equal(normalizeSave({...s,adventure:{...s.adventure,companion:'C999'}}).adventure.companion,null);});
test('restoration offers a real, bounded preparation consumed once at the next encounter',()=>{for(const choice of ['garden','workshop']){let s=restored(choice);const stats=teamStats(s),xp=s.xp,shards=s.shards;s=act(act(s,'prepare'),'prepare');assert.equal(s.xp,xp);assert.equal(s.shards,shards);s=act(s,'encounter',{id:'maroc:guardian'});const e=s.adventure.encounter;assert.equal(e.maxHP,stats.health+(choice==='garden'?16:0));assert.equal(e.stats.attack,stats.attack+(choice==='workshop'?4:0));assert.equal(s.adventure.preparation,null);assert.throws(()=>act(s,'prepare'));s=act(s,'leave');s=act(s,'encounter',{id:'maroc:guardian'});assert.equal(s.adventure.encounter.stats.attack,stats.attack);assert.equal(s.adventure.encounter.maxHP,stats.health);}});
test('unrestored and forged sanctuaries cannot grant preparation',()=>{assert.throws(()=>act(blankSave(),'prepare'));const s=act(blankSave(),'visit',{region:'maroc'});assert.throws(()=>act(s,'prepare'));assert.equal(normalizeSave({...s,adventure:{...s.adventure,preparation:'maroc'}}).adventure.preparation,null);});
test('the riad has clear approaches on its four sides and a solid fountain',()=>{const center=toLandscape('maroc',-18,17),obstacles=livingPlaceCollisions('maroc'),a=.72;for(const side of [-1,1])for(const axis of ['x','z']){const local={x:axis==='x'?side*7.4:0,z:axis==='z'?side*7.4:0},p={x:center.x+local.x*Math.cos(a)-local.z*Math.sin(a),z:center.z+local.x*Math.sin(a)+local.z*Math.cos(a)};assert.ok(obstacles.every(o=>Math.hypot(p.x-o.x,p.z-o.z)>o.r+.7));}assert.ok(obstacles.some(o=>o.r===1.65&&Math.hypot(o.x-center.x,o.z-center.z)<.01));});
