import {COUNTRIES,eventsFor} from './data.js';
import {goldMastersForCountry} from './productionCatalog.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const CAREER_COUNTRY_ORDER=Object.freeze(['france','algeria','morocco','tunisia','spain','italy','turkey','estonia']);
export function createCareerState(){return {xp:0,level:1,coins:5000,fragments:[],countries:Object.fromEntries(CAREER_COUNTRY_ORDER.map(id=>[id,{influence:0,completedEvents:[],cityBosses:[],guardianDefeated:false,legendaryUnlocked:false}])),finalNexusCompleted:false};}
export function levelFromXp(xp=0){return clamp(1+Math.floor(Math.sqrt(Math.max(0,xp)/220)),1,100);}
export function completeCareerEvent(state,event,{mastery=false}={}){if(!event||!state.countries[event.countryId])return state;const c=state.countries[event.countryId],already=c.completedEvents.includes(event.id);if(already)return state;const influence=(event.reward?.influence||0)+(mastery?80:0),xp=(event.reward?.xp||0)+(mastery?60:0),coins=(event.reward?.coins||0)+(mastery?350:0);const nextXp=state.xp+xp;return {...state,xp:nextXp,level:levelFromXp(nextXp),coins:state.coins+coins,countries:{...state.countries,[event.countryId]:{...c,influence:Math.min(10000,c.influence+influence),completedEvents:[...c.completedEvents,event.id]}}};}
export function cityBossesForCountry(countryId){return goldMastersForCountry(countryId).map((v,i)=>({id:`${countryId}-city-boss-${i+1}`,countryId,city:v.city,name:`Rival ${v.city}`,vehicleId:v.id,requiredEvents:Math.min(24,4+i),reward:{coins:2500+i*350,xp:350+i*25,vehicleId:v.id}}));}
export function defeatCityBoss(state,boss){const c=state.countries[boss.countryId];if(!c||c.cityBosses.includes(boss.id))return state;return {...state,coins:state.coins+boss.reward.coins,xp:state.xp+boss.reward.xp,countries:{...state.countries,[boss.countryId]:{...c,cityBosses:[...c.cityBosses,boss.id]}}};}
export function guardianEligible(state,countryId){const c=state.countries[countryId];return Boolean(c&&c.influence>=8000&&c.cityBosses.length>=12&&c.completedEvents.length>=18);}
export function defeatGuardian(state,countryId){if(!guardianEligible(state,countryId))return state;const c=state.countries[countryId],fragment=`fragment-${countryId}`,fragments=state.fragments.includes(fragment)?state.fragments:[...state.fragments,fragment];return {...state,fragments,coins:state.coins+12000,xp:state.xp+1500,countries:{...state.countries,[countryId]:{...c,guardianDefeated:true,legendaryUnlocked:true}}};}
export function countryUnlocked(state,countryId){const index=CAREER_COUNTRY_ORDER.indexOf(countryId);if(index<0)return false;if(index===0)return true;return CAREER_COUNTRY_ORDER.slice(0,index).every(id=>state.countries[id].guardianDefeated);}
export function careerReport(state){const countries=CAREER_COUNTRY_ORDER.map(id=>{const c=state.countries[id];return {id,unlocked:countryUnlocked(state,id),events:c.completedEvents.length,totalEvents:eventsFor(id).length,cityBosses:c.cityBosses.length,influence:c.influence,guardian:c.guardianDefeated,legendary:c.legendaryUnlocked};});return {level:state.level,xp:state.xp,coins:state.coins,fragments:state.fragments.length,countries,finalNexusUnlocked:state.fragments.length===8,complete:state.finalNexusCompleted};}
