import * as THREE from 'three';
import {QUALITY_PROFILES,zoneAt} from './visualConfig.js';

const TAU=Math.PI*2;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
function basis(curve,u){const p=curve.getPointAt(((u%1)+1)%1),t=curve.getTangentAt(((u%1)+1)%1).normalize(),side=new THREE.Vector3(-t.z,0,t.x).normalize();return {p,t,side,yaw:Math.atan2(t.x,t.z)};}
function instanced(geometry,material,matrices,{shadows=true}={}){const mesh=new THREE.InstancedMesh(geometry,material,Math.max(1,matrices.length));mesh.count=matrices.length;matrices.forEach((m,i)=>mesh.setMatrixAt(i,m));mesh.instanceMatrix.needsUpdate=true;mesh.castShadow=shadows;mesh.receiveShadow=shadows;return mesh;}
function matrixAt(curve,u,{offset=0,y=0,scale=[1,1,1],yawOffset=0,tiltX=0,roll=0}={}){const {p,side,yaw}=basis(curve,u),o=new THREE.Object3D();o.position.copy(p).addScaledVector(side,offset);o.position.y+=y;o.rotation.set(tiltX,yaw+yawOffset,roll);o.scale.set(...scale);o.updateMatrix();return o.matrix.clone();}
function addGroupDisposeTag(group){group.userData.cinematicDetail=true;return group;}

export class CinematicDetailPass{
  constructor(scene,curve,event,{quality='high',palette}={}){
    this.scene=scene;this.curve=curve;this.event=event;this.countryId=event.countryId||'france';this.palette=palette||{warm:0xffb66e,gold:0xd7b76b,matrix:0x356dff};this.quality=QUALITY_PROFILES[quality]||QUALITY_PROFILES.high;this.profile=quality;this.rnd=rng(hash(`${event.id}:cinematic-v5`));this.elapsed=0;this.root=addGroupDisposeTag(new THREE.Group());this.root.name='U3B_CinematicDetailPass';scene.add(this.root);
    this.buildMaterials();this.buildStars();this.buildWetRoadDetails();this.buildReflectorsAndLightPools();this.buildGuardrails();
    if(this.countryId==='france'){this.buildTunnelSkin();this.buildQuayHeroDetails();this.buildMatrixHeroDetails();this.buildAlpineRoadside();this.buildSanctuaryDetails();this.buildLightShafts();}
  }
  buildMaterials(){const p=this.palette;
    this.materials={
      puddle:new THREE.MeshPhysicalMaterial({color:0x07101a,metalness:.18,roughness:.075,clearcoat:1,clearcoatRoughness:.035,transparent:true,opacity:.42,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}),
      patch:new THREE.MeshStandardMaterial({color:0x090c10,roughness:.88,metalness:.04,transparent:true,opacity:.78,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}),
      reflector:new THREE.MeshStandardMaterial({color:0xe8f1ff,roughness:.25,emissive:0xe8f1ff,emissiveIntensity:2.1}),
      warm:new THREE.MeshBasicMaterial({color:p.warm,transparent:true,opacity:.17,depthWrite:false,blending:THREE.AdditiveBlending}),
      cool:new THREE.MeshBasicMaterial({color:p.matrix,transparent:true,opacity:.14,depthWrite:false,blending:THREE.AdditiveBlending}),
      rail:new THREE.MeshStandardMaterial({color:0x222932,metalness:.78,roughness:.32}),
      stone:new THREE.MeshStandardMaterial({color:0x45413d,roughness:.72,metalness:.04}),
      tunnel:new THREE.MeshStandardMaterial({color:0x0a0c10,roughness:.56,metalness:.28}),
      tunnelPanel:new THREE.MeshStandardMaterial({color:0x15191f,roughness:.38,metalness:.58}),
      blue:new THREE.MeshStandardMaterial({color:p.matrix,emissive:p.matrix,emissiveIntensity:3.7,metalness:.2,roughness:.25}),
      gold:new THREE.MeshStandardMaterial({color:p.gold,emissive:p.gold,emissiveIntensity:2.4,metalness:.72,roughness:.22}),
      tree:new THREE.MeshStandardMaterial({color:0x07110e,roughness:.96,metalness:0}),
      rock:new THREE.MeshStandardMaterial({color:0x12171c,roughness:.94,metalness:.02}),
      shaftWarm:new THREE.MeshBasicMaterial({color:p.warm,transparent:true,opacity:.045,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}),
      shaftBlue:new THREE.MeshBasicMaterial({color:p.matrix,transparent:true,opacity:.04,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending})
    };
  }
  buildStars(){const count={low:90,medium:150,high:230,ultra:340}[this.profile]||220,arr=new Float32Array(count*3);for(let i=0;i<count;i++){const a=this.rnd()*TAU,r=300+this.rnd()*300,y=90+this.rnd()*230;arr.set([Math.cos(a)*r,y,Math.sin(a)*r],i*3);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(arr,3));this.stars=new THREE.Points(g,new THREE.PointsMaterial({color:0xbfd6ff,size:this.profile==='ultra'?.75:.55,transparent:true,opacity:.55,depthWrite:false,blending:THREE.AdditiveBlending}));this.root.add(this.stars);}
  buildWetRoadDetails(){const puddles={low:28,medium:48,high:82,ultra:118}[this.profile]||72,repairs={low:22,medium:35,high:58,ultra:84}[this.profile]||50;const pg=new THREE.CircleGeometry(1,20),pM=[],dummy=new THREE.Object3D();for(let i=0;i<puddles;i++){const u=this.rnd(),z=zoneAt(u,this.countryId);if(z.id==='tunnel'&&this.rnd()<.7)continue;const {p,side,yaw}=basis(this.curve,u),edge=this.rnd()<.72,offset=(this.rnd()<.5?-1:1)*(edge?(3.2+this.rnd()*2.6):(this.rnd()*2.5));dummy.position.copy(p).addScaledVector(side,offset);dummy.position.y+=.072;dummy.rotation.set(-Math.PI/2,0,-yaw);dummy.scale.set(.7+this.rnd()*2.6,.22+this.rnd()*1.1,1);dummy.updateMatrix();pM.push(dummy.matrix.clone());}this.puddleMesh=instanced(pg,this.materials.puddle,pM,{shadows:false});this.root.add(this.puddleMesh);
    const rg=new THREE.PlaneGeometry(1,1),rM=[];for(let i=0;i<repairs;i++){const u=this.rnd(),{p,side,yaw}=basis(this.curve,u),offset=(this.rnd()-.5)*8.6;dummy.position.copy(p).addScaledVector(side,offset);dummy.position.y+=.068;dummy.rotation.set(-Math.PI/2,0,-yaw);dummy.scale.set(.35+this.rnd()*1.7,.2+this.rnd()*.8,1);dummy.updateMatrix();rM.push(dummy.matrix.clone());}this.root.add(instanced(rg,this.materials.patch,rM,{shadows:false}));
  }
  buildReflectorsAndLightPools(){const length=Math.max(1,this.curve.getLength()),studCount=Math.floor(length/14),studs=[],pools=[],studGeo=new THREE.BoxGeometry(.10,.035,.16),poolGeo=new THREE.CircleGeometry(1,18),dummy=new THREE.Object3D();for(let i=0;i<studCount;i++){const u=i/studCount,{p,side,yaw}=basis(this.curve,u),z=zoneAt(u,this.countryId);for(const s of [-1,1]){dummy.position.copy(p).addScaledVector(side,s*5.95);dummy.position.y+=.085;dummy.rotation.y=yaw;dummy.scale.set(1,1,1);dummy.updateMatrix();studs.push(dummy.matrix.clone());}if(i%2===0){dummy.position.copy(p);dummy.position.y+=.062;dummy.rotation.set(-Math.PI/2,0,-yaw);dummy.scale.set(z.id==='tunnel'?4.7:3.4,z.id==='tunnel'?2.7:1.8,1);dummy.updateMatrix();pools.push({matrix:dummy.matrix.clone(),cool:z.cool>z.warm});}}
    this.root.add(instanced(studGeo,this.materials.reflector,studs,{shadows:false}));const warm=pools.filter(x=>!x.cool).map(x=>x.matrix),cool=pools.filter(x=>x.cool).map(x=>x.matrix);this.warmPools=instanced(poolGeo,this.materials.warm,warm,{shadows:false});this.coolPools=instanced(poolGeo,this.materials.cool,cool,{shadows:false});this.root.add(this.warmPools,this.coolPools);
  }
  buildGuardrails(){const railGeo=new THREE.BoxGeometry(.13,.34,5.8),postGeo=new THREE.BoxGeometry(.16,.72,.16),rails=[],posts=[];const segments=[[.29,.43],[.43,.56],[.69,.86]];for(const [a,b] of segments){const n=Math.ceil((b-a)*64);for(let i=0;i<=n;i++){const u=a+(b-a)*i/n;for(const side of [-1,1]){rails.push(matrixAt(this.curve,u,{offset:side*7.15,y:.56,scale:[1,1,1]}));if(i%2===0)posts.push(matrixAt(this.curve,u,{offset:side*7.15,y:.29,scale:[1,1,1]}));}}}this.root.add(instanced(railGeo,this.materials.rail,rails),instanced(postGeo,this.materials.rail,posts));}
  buildTunnelSkin(){const shellGeo=new THREE.BoxGeometry(1,1,1),walls=[],ceiling=[],panels=[],warm=[],cool=[],n=this.profile==='low'?20:30;for(let i=0;i<n;i++){const u=.43+(i/(n-1))*.13;walls.push(matrixAt(this.curve,u,{offset:-7.7,y:3.15,scale:[.42,6.3,5.4]}),matrixAt(this.curve,u,{offset:7.7,y:3.15,scale:[.42,6.3,5.4]}));ceiling.push(matrixAt(this.curve,u,{y:6.38,scale:[15.8,.32,5.4]}));if(i%2===0){panels.push(matrixAt(this.curve,u,{offset:-7.2,y:2.0,scale:[.08,1.2,2.0]}),matrixAt(this.curve,u,{offset:7.2,y:2.0,scale:[.08,1.2,2.0]}));const target=i<n*.52?warm:cool;target.push(matrixAt(this.curve,u,{y:6.10,scale:[5.4,.055,1.25]}));}}
    this.root.add(instanced(shellGeo,this.materials.tunnel,walls),instanced(shellGeo,this.materials.tunnel,ceiling),instanced(shellGeo,this.materials.tunnelPanel,panels),instanced(shellGeo,this.materials.gold,warm,{shadows:false}),instanced(shellGeo,this.materials.blue,cool,{shadows:false}));
  }
  buildQuayHeroDetails(){const bridgeUs=[.175,.225,.275];for(const u of bridgeUs){const {p,yaw}=basis(this.curve,u),g=new THREE.Group();for(const x of [-11,0,11]){const arc=new THREE.Mesh(new THREE.TorusGeometry(5.3,.34,10,40,Math.PI),this.materials.stone);arc.position.set(x,.6,0);arc.rotation.z=Math.PI;g.add(arc);const gold=new THREE.Mesh(new THREE.TorusGeometry(5.3,.055,6,40,Math.PI),this.materials.gold);gold.position.set(x,.62,.38);gold.rotation.z=Math.PI;g.add(gold);}g.position.copy(p);g.rotation.y=yaw+Math.PI/2;g.position.y+=.4;this.root.add(g);}const reflections=[];for(let i=0;i<36;i++){const u=.15+i/35*.16,{p,side}=basis(this.curve,u),o=new THREE.Object3D();o.position.copy(p).addScaledVector(side,42+(i%3)*7);o.position.y=-.82;o.scale.set(.18,1.4+this.rnd()*2.2,.02);o.rotation.x=-Math.PI/2;o.updateMatrix();reflections.push(o.matrix.clone());}const reflMat=new THREE.MeshBasicMaterial({color:this.palette.warm,transparent:true,opacity:.15,depthWrite:false,blending:THREE.AdditiveBlending});this.root.add(instanced(new THREE.PlaneGeometry(1,1),reflMat,reflections,{shadows:false}));}
  buildMatrixHeroDetails(){const towers=[],strips=[],geo=new THREE.BoxGeometry(1,1,1);for(let i=0;i<18;i++){const u=.565+this.rnd()*.12,side=this.rnd()<.5?-1:1,h=38+this.rnd()*72,offset=side*(24+this.rnd()*56);towers.push(matrixAt(this.curve,u,{offset,y:h*.5-1,scale:[5+this.rnd()*8,h,5+this.rnd()*8],yawOffset:(this.rnd()-.5)*.2}));for(let k=0;k<2;k++)strips.push(matrixAt(this.curve,u,{offset:offset+side*(2+k*1.1),y:8+this.rnd()*(h-12),scale:[.08,6+this.rnd()*14,.08]}));}this.root.add(instanced(geo,new THREE.MeshPhysicalMaterial({color:0x0c1621,metalness:.56,roughness:.2,clearcoat:.8,clearcoatRoughness:.12}),towers),instanced(geo,this.materials.blue,strips,{shadows:false}));}
  buildAlpineRoadside(){const trees=[],rocks=[],treeGeo=new THREE.ConeGeometry(.65,4.2,7),rockGeo=new THREE.DodecahedronGeometry(1,0),count={low:70,medium:120,high:190,ultra:280}[this.profile]||170;for(let i=0;i<count;i++){const u=.69+this.rnd()*.17,side=this.rnd()<.5?-1:1,offset=side*(10+this.rnd()*45),h=.7+this.rnd()*1.2;trees.push(matrixAt(this.curve,u,{offset,y:1.8*h,scale:[h,1.2*h,h],yawOffset:this.rnd()*TAU}));if(i%5===0)rocks.push(matrixAt(this.curve,u,{offset:offset+side*(2+this.rnd()*7),y:.35,scale:[1+this.rnd()*2,.7+this.rnd()*2,1+this.rnd()*2],yawOffset:this.rnd()*TAU}));}const tm=instanced(treeGeo,this.materials.tree,trees,{shadows:this.profile!=='low'}),rm=instanced(rockGeo,this.materials.rock,rocks,{shadows:this.profile==='ultra'});this.root.add(tm,rm);}
  buildSanctuaryDetails(){const {p,side}=basis(this.curve,.925),center=p.clone().addScaledVector(side,58);const colMat=this.materials.stone,gold=this.materials.gold;for(let i=0;i<12;i++){const a=i/12*TAU,r=24+((i%2)*4),g=new THREE.Group(),column=new THREE.Mesh(new THREE.CylinderGeometry(.65,.9,9.5,12),colMat);column.position.y=4.5;g.add(column);const crown=new THREE.Mesh(new THREE.SphereGeometry(.28,10,8),gold);crown.position.y=9.5;g.add(crown);g.position.set(center.x+Math.cos(a)*r,-.2,center.z+Math.sin(a)*r);this.root.add(g);}for(const r of [13,20,30]){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.055,6,96),gold);ring.rotation.x=Math.PI/2;ring.position.copy(center);ring.position.y=-.25;this.root.add(ring);}if(this.profile!=='low')for(let i=0;i<4;i++){const a=i/4*TAU,l=new THREE.PointLight(this.palette.gold,6.5,32,2);l.position.set(center.x+Math.cos(a)*18,4.5,center.z+Math.sin(a)*18);this.root.add(l);}}
  buildLightShafts(){const cone=new THREE.ConeGeometry(4.4,28,16,1,true),shafts=[];const make=(u,offset,mat)=>{const {p,side}=basis(this.curve,u),m=new THREE.Mesh(cone,mat);m.position.copy(p).addScaledVector(side,offset);m.position.y=13.5;m.rotation.z=Math.PI;m.rotation.x=(this.rnd()-.5)*.06;m.userData.baseOpacity=mat.opacity;this.root.add(m);shafts.push(m);};make(.555,-5,this.materials.shaftWarm);make(.555,5,this.materials.shaftBlue);make(.93,-18,this.materials.shaftWarm);make(.93,18,this.materials.shaftBlue);this.shafts=shafts;}
  update({progress=0,speedKph=0,wetness=.5,dt=.016}={}){this.elapsed+=dt;const z=zoneAt(progress,this.countryId),speed=clamp(speedKph/300);if(this.puddleMesh)this.materials.puddle.opacity=.18+.42*wetness;if(this.warmPools)this.materials.warm.opacity=.09+.12*wetness+.03*Math.sin(this.elapsed*.9);if(this.coolPools)this.materials.cool.opacity=.08+.11*wetness+.025*Math.sin(this.elapsed*1.1+.8);if(this.stars)this.stars.material.opacity=.38+.17*(1-speed);if(this.shafts)for(const [i,s] of this.shafts.entries())s.material.opacity=(i%2?.032:.038)*(1+.18*Math.sin(this.elapsed*1.5+i));return {zone:z,detailGrade:this.profile,wetDetail:wetness};}
}
