import {GOLD_MASTER_VEHICLES} from './productionCatalog.js';
import {goldMasterMaterialRecipe} from './goldMasterMaterialSystem.js';
import {variantsForGoldMaster} from './goldMasterVariantSystem.js';
import {homologationSpec} from './goldMasterHomologation.js';
import {expectedGoldMasterBundle} from './goldMasterAssetContract.js';
import {GOLD_MASTER_TUNING_GROUPS} from './goldMasterTuningSlots.js';
const ARCH=['sculptural-wedge','open-wheel-bridge','mineral-monocoque','architectural-fastback','aero-capsule','longtail-canopy','split-body-runner','raised-arch-tourer','low-deck-speedster','faceted-grand-tourer'];
const PROP=['dual-motor-awd','rear-biased-awd','tri-motor-vector','electric-rwd','hybrid-awd'];
export function completeVehicleDesignSpec(vehicle,index=0){const material=goldMasterMaterialRecipe(vehicle.id);return {vehicleId:vehicle.id,name:vehicle.displayName,countryId:vehicle.countryId,country:vehicle.countryName,city:vehicle.city,architecture:ARCH[index%ARCH.length],silhouette:vehicle.silhouette,dimensions:{lengthM:Number((4.15+(index%6)*.19).toFixed(2)),widthM:Number((1.86+(index%4)*.08).toFixed(2)),heightM:Number((1.08+(index%5)*.09).toFixed(2)),wheelbaseM:Number((2.58+(index%5)*.11).toFixed(2))},propulsion:PROP[index%PROP.length],materials:material,lighting:{front:'3B matrix signature unique to city family',rear:'floating broken-circle light architecture',underglow:'tunable'},cockpit:{seats:2,configurable:true,hud:'3B panoramic HUD',audioModular:true,materialsTunable:true},body:{modularPanels:true,separableWheels:true,activeAero:true,cityIdentityRequired:true,noManufacturerReskin:true},tuning:{groups:GOLD_MASTER_TUNING_GROUPS,focus:vehicle.tuningFocus},variants:variantsForGoldMaster(vehicle.id),homologation:homologationSpec(vehicle.id),assets:expectedGoldMasterBundle(vehicle.id),artRules:['recognisable from silhouette alone','country identity without flag decal','city identity through form and material','Earth materials used structurally and luxuriously','functional rolling vehicle, not conventional manufacturer copy','premium futuristic 3B design']};}
export const COMPLETE_GOLD_MASTER_DESIGNS=Object.freeze(GOLD_MASTER_VEHICLES.map(completeVehicleDesignSpec));
export const DESIGNS_BY_COUNTRY=Object.freeze(Object.groupBy?Object.groupBy(COMPLETE_GOLD_MASTER_DESIGNS,x=>x.countryId):COMPLETE_GOLD_MASTER_DESIGNS.reduce((a,x)=>((a[x.countryId]??=[]).push(x),a),{}));
export function vehicleDesignReport(){return {total:COMPLETE_GOLD_MASTER_DESIGNS.length,countries:Object.fromEntries(Object.entries(DESIGNS_BY_COUNTRY).map(([k,v])=>[k,v.length])),modular:COMPLETE_GOLD_MASTER_DESIGNS.every(x=>x.body.modularPanels&&x.cockpit.configurable),productionSpecified:COMPLETE_GOLD_MASTER_DESIGNS.every(x=>x.assets?.model&&x.materials?.layers?.length>=4)};}
