import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {PLATFORM_ENVELOPE} from './vehiclePlatform.js';
import {createParisienneMontaraCandidate,isParisienneMontaraCandidate} from './ParisienneMontaraCandidate.js';

const loader=new GLTFLoader();loader.setMeshoptDecoder(MeshoptDecoder);const draco=new DRACOLoader();draco.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');loader.setDRACOLoader(draco);
const assetCache=new Map();const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function cloneScene(root){const clone=root.clone(true);clone.traverse(o=>{if(!o.isMesh)return;o.geometry=o.geometry?.clone?.()||o.geometry;if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material],copied=mats.map(m=>m.clone());o.material=Array.isArray(o.material)?copied:copied[0];}o.castShadow=true;o.receiveShadow=true;});return clone;}
function normalizeScene(root,envelope=PLATFORM_ENVELOPE){root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root),size=new THREE.Vector3();box.getSize(size);const targetLength=envelope.lengthM||4.35,longest=Math.max(size.x,size.z,.001),scale=clamp(targetLength/longest,.08,20);root.scale.multiplyScalar(scale);root.updateMatrixWorld(true);const normalizedBox=new THREE.Box3().setFromObject(root),center=new THREE.Vector3();normalizedBox.getCenter(center);root.position.x-=center.x;root.position.z-=center.z;root.position.y-=normalizedBox.min.y;root.updateMatrixWorld(true);return {box:new THREE.Box3().setFromObject(root),scale};}
function wheelRole(name=''){const n=name.toLowerCase();if(/wheel_fl|front[_ -]?left|avant[_ -]?gauche/.test(n))return'fl';if(/wheel_fr|front[_ -]?right|avant[_ -]?droite/.test(n))return'fr';if(/wheel_rl|rear[_ -]?left|arriere[_ -]?gauche/.test(n))return'rl';if(/wheel_rr|rear[_ -]?right|arriere[_ -]?droite/.test(n))return'rr';return null;}
function discoverWheels(root){const all=[],byRole={};root.traverse(o=>{const n=(o.name||'').toLowerCase();if(!/wheel|rim|tire|tyre|roue/.test(n))return;all.push(o);const role=wheelRole(n);if(role&&!byRole[role])byRole[role]=o;});return {all,byRole};}
function productionStats(root){let meshes=0,triangles=0,physicalMaterials=0;root.traverse(o=>{if(!o.isMesh)return;meshes++;triangles+=(o.geometry?.index?.count||o.geometry?.attributes?.position?.count||0)/3;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)if(m?.isMeshStandardMaterial||m?.isMeshPhysicalMaterial)physicalMaterials++;});return {meshes,triangles:Math.round(triangles),physicalMaterials};}
function tagProductionModel(root,vehicle,meta){const wheels=discoverWheels(root),stats=productionStats(root);root.name=`U3B_Final_${vehicle?.id||'vehicle'}`;Object.assign(root.userData,{productionVehicle:true,vehicleId:vehicle?.id||null,modelAsset:vehicle?.modelAsset||null,productionMeta:{...meta,...stats,wheelRoles:Object.keys(wheels.byRole)},wheelNodes:wheels.all,wheelRoles:wheels.byRole});root.userData.disposeProductionAsset=()=>root.traverse(o=>{o.geometry?.dispose?.();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{for(const key of ['map','normalMap','roughnessMap','metalnessMap','aoMap','emissiveMap','alphaMap'])m[key]?.dispose?.();m.dispose?.();});});return root;}
async function fetchTemplate(url){if(assetCache.has(url))return assetCache.get(url);const promise=loader.loadAsync(url).then(gltf=>({scene:gltf.scene,animations:gltf.animations||[],asset:gltf.asset||{}})).catch(error=>{assetCache.delete(url);throw error;});assetCache.set(url,promise);return promise;}
export function hasProductionVehicleAsset(vehicle){return isParisienneMontaraCandidate(vehicle)||(typeof vehicle?.modelAsset==='string'&&(/\.(?:glb|gltf)(?:$|\?)/i.test(vehicle.modelAsset)||/^https?:\/\//i.test(vehicle.modelAsset)));}
export async function loadProductionVehicle(vehicle,{envelope=PLATFORM_ENVELOPE}={}){if(!hasProductionVehicleAsset(vehicle))return null;if(isParisienneMontaraCandidate(vehicle)){const root=createParisienneMontaraCandidate(),fit=normalizeScene(root,envelope);return tagProductionModel(root,vehicle,{source:'procedural-candidate:parisienne-montara',fitScale:fit.scale,animations:0,candidate:true,generatedAt:Date.now()});}const template=await fetchTemplate(vehicle.modelAsset),root=cloneScene(template.scene),fit=normalizeScene(root,envelope);return tagProductionModel(root,vehicle,{source:vehicle.modelAsset,fitScale:fit.scale,animations:template.animations.length,candidate:false,generatedAt:Date.now()});}
export function productionVehicleRuntimeReport(root){if(!root?.userData?.productionVehicle)return {ok:false,errors:['not-production']};const m=root.userData.productionMeta||{},errors=[];if((m.meshes||0)<1)errors.push('mesh-missing');if((m.triangles||0)<5000)errors.push('geometry-too-simple');if((m.physicalMaterials||0)<1)errors.push('pbr-material-missing');for(const r of ['fl','fr','rl','rr'])if(!root.userData.wheelRoles?.[r])errors.push(`wheel-${r}`);return {ok:errors.length===0,errors,meta:m};}
export function updateProductionVehicleRuntime(root,{speedKph=0,time=0,steer=0}={}){if(!root?.userData?.productionVehicle)return;const spin=time*Math.max(.4,speedKph*.12),roles=root.userData.wheelRoles||{};for(const [role,node] of Object.entries(roles)){node.rotation.x=spin;if(role==='fl'||role==='fr')node.rotation.y=steer*.32;}}
export function clearProductionVehicleCache(){assetCache.clear();}
