import {AI_ARCHETYPES,opponentsFor} from './data.js';
import {createVehicleState,estimateTopSpeedKph,stepVehicle} from './carModel.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),fract=v=>v-Math.floor(v);
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
export function surfaceGrip(weather){return ({sec:1,pluie:.82,brume:.9,vent:.95,chaleur:.94,sable:.72,'nuit claire':1,'pluie rare':.84,neige:.68,glace:.48}[weather]??.92);}
export function trackCurvature(event,normalized){const seed=hash(event.routeId||event.id),x=normalized*Math.PI*2,a=.16+.18*fract(seed*.000001),b=.07+.13*fract(seed*.0000037),c=.04+.1*fract(seed*.0000071);return clamp(Math.abs(Math.sin(x*(2+seed%3)+seed%11)*a+Math.sin(x*5.3+1.7)*b+Math.sin(x*9.1+.4)*c),0,.72);}
export function targetSpeedFor(event,vehicle,normalized,grip=1){const top=estimateTopSpeedKph(vehicle)/3.6,curve=trackCurvature(event,normalized);return Math.max(16,top*(1-curve*.67)*Math.sqrt(grip));}
function defaultOpponentCount(event){if(event.discipline==='duel'||event.discipline==='chrono'||event.discipline==='redline')return event.discipline==='duel'?1:0;if(event.discipline==='convoy')return 5;return 7;}
function difficultyFactor(d){return ({easy:.91,normal:.96,hard:1.005,legend:1.035}[d]||.96);}
function makeAI(event,index,difficulty,random,boss){const pool=opponentsFor(event.countryId),pick=boss&&index===0?pool.at(-1):pool[index%Math.max(1,pool.length-2)]||{id:`ai-${index}`,name:`Rival ${index+1}`,type:'calculator',skill:.9},arch=AI_ARCHETYPES[pick.type]||AI_ARCHETYPES.calculator,skill=clamp((pick.skill||.9)*difficultyFactor(difficulty)+(random()-.5)*.025,.72,1.04);return {id:pick.id,name:pick.name,type:pick.type,skill,arch,distanceM:-index*4.2,speedMps:0,lane:(index%3-1)*.45,errorTimer:.5+random()*2,errorAmount:0,finished:false,finishTime:null};}
export function createRaceSession({event,vehicle,difficulty='normal',boss=false,bossStage=0}){if(!event)throw Error('event required');const random=rng(hash(event.id+':'+difficulty+':'+bossStage)),totalDistanceM=Math.max(250,event.distanceKm*1000),opponentCount=boss?1:defaultOpponentCount(event),gripBase=surfaceGrip(event.weather),top=estimateTopSpeedKph(vehicle)/3.6,expectedAvg=Math.max(18,top*(event.discipline==='redline'?.78:event.discipline==='flow'?.48:.61)*gripBase),targetTime=totalDistanceM/expectedAvg;return {event,vehicle,difficulty,boss,bossStage,totalDistanceM,targetTime,status:'countdown',countdown:3,time:0,player:{distanceM:0,state:createVehicleState(),lane:0,finished:false,finishTime:null,collisions:0,offroadSeconds:0,driftScore:0,bestSpeedKph:0,combo:0,comboTimer:0},ai:Array.from({length:opponentCount},(_,i)=>makeAI(event,i,difficulty,random,boss)),random,gripBase,trafficSeed:hash(event.id+'traffic'),feedback:null,finishedOrder:[]};}
function dynamicGrip(session,progress){if(session.event.countryId==='estonia'&&(session.boss||session.event.discipline==='nexus')){const phase=progress<.33?1:progress<.67?.76:.52;return session.gripBase*phase;}return session.gripBase;}
function roadLaneLimit(session){return session.event.discipline==='redline'?.78:1;}
function updateAI(session,ai,dt){if(ai.finished)return;const p=clamp(ai.distanceM/session.totalDistanceM,0,1),grip=dynamicGrip(session,p),curve=trackCurvature(session.event,p),top=Math.max(42,estimateTopSpeedKph(session.vehicle)/3.6*(.92+ai.skill*.08));ai.errorTimer-=dt;if(ai.errorTimer<=0){ai.errorTimer=.8+session.random()*3.7;ai.errorAmount=session.random()<ai.arch.error?(.08+session.random()*.18):0;}const corner=1-curve*(.58+(1-ai.arch.grip)*.8),desired=top*corner*Math.sqrt(grip)*ai.skill*(1-ai.errorAmount),accel=6.2*(.8+ai.arch.pace*.3),brake=10.5;ai.speedMps+=clamp(desired-ai.speedMps,-brake*dt,accel*dt);ai.speedMps=Math.max(0,ai.speedMps);ai.distanceM+=ai.speedMps*dt;ai.lane=clamp(ai.lane+Math.sin(session.time*.32+(hash(ai.id)%17))*dt*.035,-.78,.78);if(ai.distanceM>=session.totalDistanceM){ai.finished=true;ai.finishTime=session.time;session.finishedOrder.push(ai.id);}}
function trafficCollisionChance(session,dt){const level=session.event.traffic==='high'?.7:session.event.traffic==='medium'?.35:.08,p=clamp(session.player.distanceM/session.totalDistanceM,0,1),wave=fract(Math.sin((p*180+session.trafficSeed)%997)*43758.5453);return wave<level*dt*.055;}
export function stepRace(session,input,dt){dt=clamp(dt,0,1/20);if(session.status==='finished')return session;if(session.status==='countdown'){session.countdown-=dt;if(session.countdown<=0){session.countdown=0;session.status='racing';}return session;}if(session.status!=='racing')return session;session.time+=dt;const player=session.player,p=clamp(player.distanceM/session.totalDistanceM,0,1),grip=dynamicGrip(session,p),curve=trackCurvature(session.event,p),laneLimit=roadLaneLimit(session),steer=input.steer||0;player.state=stepVehicle(session.vehicle,player.state,input,dt,{grip,slope:Math.sin(p*Math.PI*10)*.01});const cornerTarget=targetSpeedFor(session.event,session.vehicle,p,grip);if(player.state.speedMps>cornerTarget*1.12&&Math.abs(steer)<curve*.35){player.state.speedMps*=Math.max(.955,1-dt*curve*.5);player.state.lateral+=Math.sign(Math.sin(p*31+2))*curve*dt*.2;}player.lane=clamp(player.state.lateral,-1.35,1.35);if(Math.abs(player.lane)>laneLimit){player.offroadSeconds+=dt;player.state.speedMps*=Math.max(.975,1-dt*.45);}const speedKph=player.state.speedMps*3.6;player.bestSpeedKph=Math.max(player.bestSpeedKph,speedKph);const slip=Math.abs(steer)*curve*speedKph;if(speedKph>45&&slip>10){player.comboTimer=.7;player.combo+=slip*dt*.45;player.driftScore+=slip*dt*(1+player.combo*.001);}else{player.comboTimer-=dt;if(player.comboTimer<=0)player.combo=0;}if(trafficCollisionChance(session,dt)&&Math.abs(player.lane)<.42&&speedKph>70){player.collisions++;player.state.speedMps*=.72;session.feedback='collision';}for(const ai of session.ai)if(!ai.finished&&Math.abs(ai.distanceM-player.distanceM)<2.8&&Math.abs(ai.lane-player.lane)<.28&&speedKph>25){player.collisions++;player.state.speedMps*=.91;ai.speedMps*=.92;ai.lane+=player.lane<=ai.lane?.12:-.12;session.feedback='contact';}player.distanceM+=player.state.speedMps*dt;session.ai.forEach(ai=>updateAI(session,ai,dt));if(player.distanceM>=session.totalDistanceM&&!player.finished){player.finished=true;player.finishTime=session.time;session.finishedOrder.push('player');}if(player.finished){const unresolved=session.ai.some(ai=>!ai.finished&&ai.distanceM>session.totalDistanceM-120);if(!unresolved||session.time-player.finishTime>6)session.status='finished';}else if(session.ai.every(ai=>ai.finished)&&session.ai.length)session.status='finished';return session;}
export function racePosition(session){const ranking=[{id:'player',distance:session.player.finished?session.totalDistanceM+100000-session.player.finishTime:session.player.distanceM},...session.ai.map(ai=>({id:ai.id,distance:ai.finished?session.totalDistanceM+100000-ai.finishTime:ai.distanceM}))].sort((a,b)=>b.distance-a.distance);return ranking.findIndex(x=>x.id==='player')+1;}
export function raceResult(session){const position=racePosition(session),player=session.player,score=Math.round((player.finished?12000:0)+Math.max(0,10000-position*900)+player.driftScore*.35-Math.min(6000,player.collisions*800+player.offroadSeconds*160));return {finished:player.finished,position,time:player.finishTime||session.time,targetTime:session.targetTime,score,collisions:player.collisions,offroadSeconds:player.offroadSeconds,driftScore:Math.round(player.driftScore),bestSpeedKph:Math.round(player.bestSpeedKph),driftTarget:Math.round(session.event.distanceKm*900),masteryScoreTarget:11000};}
export function raceHud(session){const p=clamp(session.player.distanceM/session.totalDistanceM,0,1),position=racePosition(session);return {progress:p,position,total:session.ai.length+1,speedKph:Math.round(session.player.state.speedMps*3.6),gear:session.player.state.gear,rpm:Math.round(session.player.state.rpm),nitrous:session.player.state.nitrous,time:session.time,grip:dynamicGrip(session,p),curvature:trackCurvature(session.event,p)};}
