import * as THREE from 'three';

function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function rng(seed){let s=seed>>>0;return()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
function makeCloudTexture(seed=1,size=128){const rnd=rng(seed),data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){let v=0,amp=1,total=0;for(let o=0;o<5;o++){const scale=2**o,nx=Math.floor(x/Math.max(1,size/(scale*3))),ny=Math.floor(y/Math.max(1,size/(scale*3)));const n=Math.sin((nx*12.9898+ny*78.233+seed*31.17))*43758.5453;const f=n-Math.floor(n);v+=f*amp;total+=amp;amp*=.55;}v/=total;const dx=(x-size/2)/(size/2),dy=(y-size/2)/(size/2),edge=Math.max(0,1-Math.pow(Math.sqrt(dx*dx+dy*dy),1.7));const a=Math.max(0,Math.min(1,(v-.40)*2.2))*edge;const i=(y*size+x)*4,c=Math.round(150+70*v);data[i]=c;data[i+1]=c+4;data[i+2]=Math.min(255,c+14);data[i+3]=Math.round(170*a);}const tex=new THREE.DataTexture(data,size,size,THREE.RGBAFormat);tex.needsUpdate=true;tex.minFilter=THREE.LinearFilter;tex.magFilter=THREE.LinearFilter;tex.wrapS=tex.wrapT=THREE.ClampToEdgeWrapping;return tex;}

export class SkyAtmosphereV6{
  constructor(scene,event,{palette,quality='high'}={}){this.scene=scene;this.event=event;this.palette=palette;this.quality=quality;this.rnd=rng(hash(`${event.id}:sky-v6`));this.root=new THREE.Group();this.root.name='U3B_SkyAtmosphereV6';scene.add(this.root);this.build();}
  build(){const count=this.quality==='ultra'?18:this.quality==='high'?13:this.quality==='medium'?9:5;this.cloudTextures=[];for(let i=0;i<3;i++)this.cloudTextures.push(makeCloudTexture(hash(`${this.event.id}:cloud:${i}`),128));for(let i=0;i<count;i++){const tex=this.cloudTextures[i%this.cloudTextures.length],mat=new THREE.MeshBasicMaterial({map:tex,color:i%3===0?0x6b7484:0x3b4351,transparent:true,opacity:.20+this.rnd()*.16,depthWrite:false,side:THREE.DoubleSide,blending:THREE.NormalBlending});const p=new THREE.Mesh(new THREE.PlaneGeometry(120+this.rnd()*120,55+this.rnd()*75),mat);const a=this.rnd()*Math.PI*2,r=100+this.rnd()*250;p.position.set(Math.cos(a)*r,75+this.rnd()*65,Math.sin(a)*r);p.rotation.set(-Math.PI/2+(this.rnd()-.5)*.18,a+(this.rnd()-.5)*.4,0);this.root.add(p);}const moonMat=new THREE.MeshBasicMaterial({color:0xeaf1ff});const moon=new THREE.Mesh(new THREE.SphereGeometry(4.1,24,16),moonMat);moon.position.set(-150,118,-230);this.root.add(moon);const haloMat=new THREE.MeshBasicMaterial({color:0x9eb9e8,transparent:true,opacity:.10,depthWrite:false,blending:THREE.AdditiveBlending});const halo=new THREE.Mesh(new THREE.CircleGeometry(13,48),haloMat);halo.position.copy(moon.position);halo.lookAt(new THREE.Vector3(0,55,0));this.root.add(halo);this.moon=moon;this.halo=halo;}
  update({dt=.016,speedKph=0}={}){this.root.rotation.y+=dt*(.0008+Math.min(1,speedKph/300)*.0005);if(this.halo)this.halo.material.opacity=.085+.025*Math.sin(performance.now()*.00035);return {skyV6:true};}
  dispose(){for(const t of this.cloudTextures)t.dispose?.();}
}
