import {useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useAlbertSpaces} from './AlbertSpacesContext.jsx';
import {newSpace,newPanel,newId,PANEL_TYPES,safeLink} from './albert-spaces-model.js';
import './albert-spaces.css';
export default function AlbertSpaces({privacyMode,reduced=false}){
 const{state,edit,forget,back,forward,canUndo,canRedo,owner,status,syncing,sync}=useAlbertSpaces();
 const[detached,setDetached]=useState(null),[drag,setDrag]=useState(null),[name,setName]=useState(''),[kind,setKind]=useState('notes'),[focus,setFocus]=useState(null),grid=useRef(null),resize=useRef(null),dialog=useRef(null),returnFocus=useRef(null);
 const space=state.spaces.find(s=>s.id===state.active)||state.spaces[0];
 const previousRects=useRef(new Map());
 useLayoutEffect(()=>{
  const next=new Map(),reduce=reduced||window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  for(const el of grid.current?.children||[]){
   const key=el.dataset.panelId;if(!key)continue;const rect=el.getBoundingClientRect(),old=previousRects.current.get(key);next.set(key,rect);
   if(!reduce&&!resize.current&&old&&(old.x!==rect.x||old.y!==rect.y))el.animate([{transform:`translate(${old.x-rect.x}px,${old.y-rect.y}px)`},{transform:'none'}],{duration:320,easing:'cubic-bezier(.2,.8,.2,1)'});
  }
  previousRects.current=next;
 },[space.panels,focus,detached,privacyMode,reduced]);
 const update=(fn,label,checkpoint=true)=>edit(s=>({...s,spaces:s.spaces.map(x=>x.id===space.id?fn(x):x)}),label,checkpoint);
 const panelEdit=(id,patch,checkpoint=true)=>update(s=>({...s,panels:s.panels.map(p=>p.id===id?{...p,...patch}:p)}),'Panneau modifié',checkpoint);
 function detach(id,event){returnFocus.current=event.currentTarget;setDetached(id);setTimeout(()=>dialog.current?.showModal(),0);}
 function close(){dialog.current?.close();setDetached(null);returnFocus.current?.focus();}
 function resizeStart(e,p){if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);resize.current={x:e.clientX,y:e.clientY,width:p.width,height:p.height,unit:(grid.current?.clientWidth||900)/12,id:p.id};edit(s=>s,'Redimensionnement');}
 function resizeMove(e){const r=resize.current;if(!r)return;panelEdit(r.id,{width:Math.min(12,Math.max(3,Math.round(r.width+(e.clientX-r.x)/r.unit))),height:Math.max(200,Math.min(800,r.height+e.clientY-r.y))},false);}
 function body(p){
  if(p.kind==='notes')return <textarea aria-label={'Contenu de '+p.title} value={p.text} maxLength={10000} onFocus={()=>edit(s=>s,'Édition de note')} onChange={e=>panelEdit(p.id,{text:e.target.value},false)} placeholder="Écrivez votre idée…"/>;
  if(p.kind==='tasks'||p.kind==='planning'){
   const tasks=p.kind==='planning'?[...space.tasks].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')):space.tasks;
   return <><p className="as-help">Tâches et planning partagent les mêmes échéances.</p>{tasks.map(t=><div className="as-task" key={t.id}><input type="checkbox" aria-label={'Terminer '+t.text} checked={t.done} onChange={e=>update(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,done:e.target.checked}:x)}),'Priorité actualisée')}/><span>{t.text}</span><input type="date" aria-label={'Échéance de '+t.text} value={t.due} onChange={e=>update(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,due:e.target.value}:x)}),'Échéance déplacée')}/><button aria-label={'Retirer '+t.text} onClick={()=>update(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id)}),'Tâche retirée')}>×</button></div>)}<form onSubmit={e=>{e.preventDefault();const text=new FormData(e.currentTarget).get('task')?.trim();if(!text||space.tasks.length>=100)return;update(s=>({...s,tasks:[...s.tasks,{id:newId(),text,done:false,due:''}]}),'Tâche ajoutée');e.currentTarget.reset();}}><input name="task" aria-label="Nouvelle tâche" maxLength={300} placeholder="Nouvelle priorité" required/><button>Ajouter</button></form></>;
  }
  if(p.kind==='budget')return <><strong className="as-total">{p.rows.reduce((sum,r)=>sum+r.amount,0).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</strong><p className="as-help">Budget saisi manuellement · aucune donnée bancaire.</p>{p.rows.map(r=><div className="as-row" key={r.id}><span>{r.label}</span><strong>{r.amount.toLocaleString('fr-FR')} €</strong><button aria-label={'Retirer '+r.label} onClick={()=>panelEdit(p.id,{rows:p.rows.filter(x=>x.id!==r.id)})}>×</button></div>)}<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),label=data.get('label').trim(),amount=Number(data.get('amount'));if(!label||!Number.isFinite(amount)||p.rows.length>=100)return;panelEdit(p.id,{rows:[...p.rows,{id:newId(),label,amount,url:''}]});e.currentTarget.reset();}}><input name="label" aria-label="Ligne budgétaire" maxLength={200} placeholder="Dépense / recette" required/><input name="amount" aria-label="Montant en euros" type="number" min="-1000000000" max="1000000000" step=".01" required/><button>+</button></form></>;
  return <><p className="as-help">Références par lien · aucun fichier envoyé automatiquement.</p>{p.rows.map(r=><div className="as-row" key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.label}</a><button aria-label={'Retirer '+r.label} onClick={()=>panelEdit(p.id,{rows:p.rows.filter(x=>x.id!==r.id)})}>×</button></div>)}<form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),url=safeLink(data.get('url')),label=data.get('label').trim();if(!url||!label||p.rows.length>=100)return;panelEdit(p.id,{rows:[...p.rows,{id:newId(),label,url,amount:0}]});e.currentTarget.reset();}}><input name="label" aria-label="Nom du document" maxLength={200} placeholder="Nom" required/><input name="url" aria-label="Lien du document" type="url" placeholder="https://…" required/><button>+</button></form></>;
 }
 function card(p,inDialog=false){return <article key={p.id} data-panel-id={p.id} className={'as-panel'+(inDialog?' detached':'')} style={{gridColumn:'span '+p.width,height:inDialog?'70vh':p.height,animation:reduced?'none':undefined}} onDragOver={e=>{if(drag)e.preventDefault();}} onDrop={e=>{e.preventDefault();if(!drag||drag===p.id)return;update(s=>{const list=[...s.panels],from=list.findIndex(x=>x.id===drag),to=list.findIndex(x=>x.id===p.id);if(from<0||to<0)return s;list.splice(to,0,list.splice(from,1)[0]);return {...s,panels:list};},'Panneau déplacé');setDrag(null);}}>
  <header><span className="as-handle" draggable={!inDialog} onDragStart={e=>{setDrag(p.id);e.dataTransfer.setData('text/plain',p.id);}} onDragEnd={()=>setDrag(null)}>⠿</span><input aria-label="Titre du panneau" value={p.title} maxLength={80} onFocus={()=>edit(s=>s,'Renommer un panneau')} onChange={e=>panelEdit(p.id,{title:e.target.value},false)}/><details><summary aria-label={'Options de '+p.title}>···</summary><nav><button onClick={()=>panelEdit(p.id,{width:p.width===12?6:12})}>Largeur {p.width===12?'½':'entière'}</button><button onClick={()=>update(s=>({...s,panels:[s.panels.find(x=>x.id===p.id),...s.panels.filter(x=>x.id!==p.id)]}),'Panneau placé en premier')}>Placer en premier</button><button disabled={space.panels.length>=16} onClick={()=>update(s=>({...s,panels:[...s.panels,{...structuredClone(p),id:newId(),title:p.title+' · copie'}]}),'Panneau dupliqué')}>Dupliquer</button><button onClick={()=>setFocus(f=>f===p.id?null:p.id)}>Isoler / restaurer</button>{!inDialog&&<button onClick={e=>detach(p.id,e)}>Détacher</button>}<button onClick={()=>{update(s=>({...s,panels:s.panels.filter(x=>x.id!==p.id)}),'Panneau retiré');if(inDialog)close();}}>Retirer</button><label>Largeur<input aria-label={'Largeur de '+p.title} type="range" min="3" max="12" value={p.width} onChange={e=>panelEdit(p.id,{width:Number(e.target.value)})}/></label></nav></details></header>
  <div className="as-content">{body(p)}</div>{!inDialog&&<button className="as-resize" aria-label={'Redimensionner '+p.title} onPointerDown={e=>resizeStart(e,p)} onPointerMove={resizeMove} onPointerUp={()=>resize.current=null} onPointerCancel={()=>resize.current=null} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();panelEdit(p.id,{width:Math.min(12,Math.max(3,p.width+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0))),height:Math.max(200,Math.min(800,p.height+(e.key==='ArrowDown'?20:e.key==='ArrowUp'?-20:0)))});}}}>◢</button>}
 </article>;}
 if(!owner)return null;
 if(privacyMode)return <section className="as-shell"><p>Espaces et mémoire masqués en mode privé.</p></section>;
 const floating=space.panels.find(p=>p.id===detached);
 return <section className="as-shell" aria-label="Espaces composables"><div className="as-heading"><div><p>COMPOSEZ VOTRE UNIVERS</p><h2>Un espace pour chaque intention.</h2></div><div><button disabled={!canUndo} onClick={back}>↶ Annuler</button><button disabled={!canRedo} onClick={forward}>↷ Rétablir</button></div></div>
 <div className="as-tabs" role="tablist" aria-label="Espaces">{state.spaces.map(s=><button key={s.id} role="tab" aria-selected={s.id===space.id} onClick={()=>{edit(v=>({...v,active:s.id}),'Espace ouvert');setFocus(null);setDetached(null);}}>{s.name}</button>)}</div>
 <details className="as-settings"><summary>Gérer « {space.name} »</summary><label>Nom de l’espace <input aria-label="Renommer l’espace" value={space.name} maxLength={80} onFocus={()=>edit(s=>s,'Renommer un espace')} onChange={e=>update(s=>({...s,name:e.target.value}),'Nom actualisé',false)}/></label><button disabled={state.spaces.length===1} onClick={()=>{if(confirm('Retirer cet espace et ses panneaux ? Vous pourrez annuler.')){edit(s=>{const remaining=s.spaces.filter(x=>x.id!==space.id);return {...s,spaces:remaining,active:remaining[0].id};},'Espace retiré');setFocus(null);setDetached(null);}}}>Retirer cet espace</button></details>
 <details className="as-settings"><summary>Composer et synchroniser</summary><div className="as-controls"><form onSubmit={e=>{e.preventDefault();if(!name.trim()||state.spaces.length>=8)return;const s=newSpace(name);edit(v=>({...v,active:s.id,spaces:[...v.spaces,s]}),'Espace créé');setName('');}}><input aria-label="Nom du nouvel espace" value={name} onChange={e=>setName(e.target.value)} maxLength={80} placeholder="Nouvel espace" required/><button disabled={state.spaces.length>=8}>Créer</button></form><select aria-label="Type de panneau" value={kind} onChange={e=>setKind(e.target.value)}>{PANEL_TYPES.map(k=><option key={k}>{k}</option>)}</select><button disabled={space.panels.length>=16} onClick={()=>update(s=>({...s,panels:[...s.panels,newPanel(kind)]}),'Panneau ajouté')}>Ajouter le panneau</button><button disabled={syncing} onClick={()=>sync('push')}>Sauvegarder en ligne</button><button disabled={syncing} onClick={()=>{if(confirm('Charger la version en ligne ? Votre version actuelle reste accessible via Annuler.'))sync('pull');}}>Charger en ligne</button></div><p className="as-help" role="status">{status} · 8 espaces maximum, 16 panneaux par espace.</p></details>
 {focus&&<button onClick={()=>setFocus(null)}>Afficher tous les panneaux</button>}
 <div className="as-grid" ref={grid}>{space.panels.filter(p=>p.id!==detached&&(!focus||focus===p.id)).map(p=>card(p))}{!space.panels.length&&<p>Aucun panneau. Demandez « ajoute un budget » à Albert.</p>}</div>
 <details className="as-memory"><summary>Mémoire et journal</summary><p className="as-help">Les 12 derniers messages peuvent être transmis à l’IA avec l’espace courant. La synchronisation est manuelle : après effacement local, sauvegardez en ligne pour effacer aussi la copie serveur. Les copies sur vos autres appareils ne sont pas effacées automatiquement.</p><button onClick={forget}>Effacer la conversation locale</button>{state.messages.map((m,i)=><p key={i}><strong>{m.role==='user'?'Vous':'Albert'} : </strong>{m.text}</p>)}<ol>{state.journal.slice(-12).reverse().map((j,i)=><li key={i}>{j.text} · {new Date(j.at).toLocaleTimeString('fr-FR')}</li>)}</ol></details>
 {createPortal(<dialog className="as-dialog" ref={dialog} onCancel={e=>{e.preventDefault();close();}}><button onClick={close}>Rattacher au cockpit ×</button>{floating&&card(floating,true)}</dialog>,document.body)}
 </section>;
}
