const BASE=Deno.env.get("SUPABASE_URL")!;
const PUBLIC=Deno.env.get("SUPABASE_ANON_KEY")!;
const PROJECT_REF="zykdfgahzqqanlyxjtbe";
const ORIGIN=`https://${PROJECT_REF}.supabase.co`;
const API=`${ORIGIN}/functions/v1/nosbloc-staging`;
const ACTIONS=new Set(["snapshot","project_sync","invite_create","invite_decide","version_checkpoint","review_submit","moderation_decide"]);
const headers={
  "Content-Security-Policy":`default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src ${ORIGIN}; img-src data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`,
  "Referrer-Policy":"no-referrer","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY",
  "X-Robots-Tag":"noindex,nofollow,noarchive","Permissions-Policy":"camera=(), microphone=(), geolocation=(), payment=()","Cache-Control":"no-store"
};
const countries=["France","Algérie","Espagne","Maroc","Italie","Tunisie","Turquie","Estonie"];
const html=`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Nosbloc 3B · Staging privé</title><style>
:root{color-scheme:dark;--bg:#05080d;--panel:#0b121c;--line:#263545;--gold:#d9b86f;--blue:#63d9ff;--muted:#9fb0c0;--ok:#74e6af;--bad:#ff9a9a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#102c40 0,transparent 36%),var(--bg);color:#f7f4eb;font:15px/1.5 Inter,system-ui,sans-serif}main{width:min(1120px,100%);margin:auto;padding:16px}.hero,.panel{border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,rgba(14,24,36,.98),rgba(5,9,14,.98));box-shadow:0 22px 70px #0008}.hero{padding:clamp(24px,5vw,48px);margin-bottom:16px}.eyebrow{color:var(--blue);font-size:12px;font-weight:900;letter-spacing:.15em}.hero h1{font-size:clamp(34px,7vw,70px);line-height:1;margin:.25em 0}.hero em{color:var(--gold);font-style:normal}.badges,.actions,.tabs{display:flex;flex-wrap:wrap;gap:8px}.badge{border:1px solid #ffffff18;border-radius:999px;padding:7px 11px;color:#d6e3ee;font-size:12px}.badge.ok{color:var(--ok);border-color:#74e6af55}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel{padding:20px}.wide{grid-column:1/-1}h2,h3{margin:.2em 0 .7em}label{display:grid;gap:6px;margin:10px 0;color:#d8e4ee;font-weight:700;font-size:13px}input,textarea,select,button{font:inherit}input,textarea,select{width:100%;border:1px solid #ffffff20;border-radius:11px;background:#07101a;color:#fff;padding:11px 12px}textarea{min-height:115px;resize:vertical}button{border:1px solid #d9b86f66;border-radius:11px;background:#d9b86f18;color:#fff;padding:10px 13px;cursor:pointer;font-weight:800}button:hover{border-color:var(--gold)}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:linear-gradient(135deg,#d9b86f44,#63d9ff20)}.danger{border-color:#ff8d8d55;background:#ff8d8d12}.tabs button[aria-pressed=true]{border-color:var(--blue);color:var(--blue)}.notice,.error{margin:12px 0;padding:11px;border-radius:10px}.notice{border:1px solid #74e6af55;background:#74e6af12;color:#b5f5d5}.error{border:1px solid #ff8d8d55;background:#ff8d8d12;color:#ffc3c3}.row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:center;padding:10px 0;border-top:1px solid #ffffff12}.row span{display:grid}.row small,.muted{color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;background:#02060a;padding:12px;border-radius:12px;color:#b8d7e8}.hidden{display:none!important}.identity{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.status-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--ok);box-shadow:0 0 18px var(--ok);margin-right:7px}.invite-note{padding:10px 12px;border-left:2px solid var(--gold);background:#d9b86f0e;color:#dacda9}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.row{grid-template-columns:1fr auto auto}main{padding:12px}.panel{padding:16px}}
</style></head><body><main>
<section class="hero"><p class="eyebrow">NOSBLOC DU 3B · ENVIRONNEMENT ISOLÉ</p><h1>Staging <em>privé.</em></h1><p>Teste les Passeports, projets, invitations, versions et décisions humaines sans toucher à la production.</p><div class="badges"><span class="badge ok">Projet Supabase séparé</span><span class="badge">Inscription sur invitation</span><span class="badge">Discover fermé</span><span class="badge">Paiements fermés</span><span class="badge">Publication verrouillée</span></div></section>
<div id="message"></div>
<section id="authPanel" class="panel"><div class="tabs"><button id="loginTab" aria-pressed="true">Connexion</button><button id="signupTab" aria-pressed="false">Créer un Passeport test</button></div><form id="authForm"><label>Adresse e-mail<input id="email" type="email" required autocomplete="email"></label><label>Mot de passe<input id="password" type="password" required minlength="10" autocomplete="current-password"></label><div id="signupFields" class="hidden"><p class="invite-note">Un code ne fonctionne qu’une fois et disparaît des données du compte après validation.</p><label>Code d’accès à usage unique<input id="inviteCode" minlength="16" maxlength="80" autocomplete="one-time-code" placeholder="NB3B-..."></label><label>Identifiant 3B test<input id="handle" minlength="3" maxlength="24" placeholder="zakaria-test"></label><label>Nom affiché<input id="displayName" minlength="2" maxlength="80" placeholder="Zakaria"></label><label>Pays<select id="country">${countries.map(x=>`<option>${x}</option>`).join("")}</select></label></div><button class="primary" id="authSubmit">Se connecter</button></form></section>
<section id="workspace" class="hidden"><div class="identity panel"><span><i class="status-dot"></i><strong id="identity"></strong></span><button id="logout" class="danger">Déconnexion</button></div><div class="grid"><section class="panel"><h2>Projet de test</h2><label>Titre<input id="title" value="Ville 3B Staging"></label><label>Description<textarea id="description">Une ville communautaire privée destinée à tester la synchronisation, les versions et la modération Nosbloc sans publication publique.</textarea></label><label>Collaborateur staging (optionnel)<input id="collabHandle" placeholder="identifiant-3b-test"></label><label>Part collaborateur (%)<input id="collabShare" type="number" min="0" max="90" value="40"></label><div class="actions"><button id="sync" class="primary">Synchroniser</button><button id="invite">Inviter</button><button id="checkpoint">Point serveur</button><button id="review">Envoyer en modération</button></div><p class="muted" id="projectState">Projet non lié.</p></section><section class="panel"><h2>Invitations reçues</h2><div id="invitations"><p class="muted">Actualise pour consulter les invitations.</p></div></section><section class="panel wide"><div class="actions"><button id="refresh" class="primary">Actualiser le serveur</button></div><h2>File de modération</h2><div id="moderation"><p class="muted">Visible uniquement par le compte modérateur staging.</p></div></section><section class="panel wide"><h2>Réponse serveur</h2><pre id="log">Aucune opération.</pre></section></div></section>
<script>
const BASE=${JSON.stringify(ORIGIN)},KEY=${JSON.stringify(PUBLIC)},PROXY=location.pathname,STORE='nosbloc_staging_console_session_v1',PROJECT_STORE='nosbloc_staging_console_project_v1';let mode='login',session=null,user=null,snapshot=null,serverProjectId=localStorage.getItem(PROJECT_STORE)||'';const $=id=>document.getElementById(id),uuid=()=>crypto.randomUUID();
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function show(t,b=false){$('message').innerHTML=t?'<div class="'+(b?'error':'notice')+'">'+esc(t)+'</div>':''}
function setMode(next){mode=next;$('loginTab').setAttribute('aria-pressed',next==='login');$('signupTab').setAttribute('aria-pressed',next==='signup');$('signupFields').classList.toggle('hidden',next!=='signup');$('authSubmit').textContent=next==='signup'?'Créer le Passeport test':'Se connecter';$('password').autocomplete=next==='signup'?'new-password':'current-password'}
async function auth(path,body,token){const r=await fetch(BASE+'/auth/v1/'+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok){if(path==='signup')throw Error('Code invalide, expiré ou déjà utilisé, ou compte non créé.');throw Error(d.msg||d.error_description||d.message||'Authentification impossible.')}return d}
function save(v){session=v||null;if(v)localStorage.setItem(STORE,JSON.stringify(v));else localStorage.removeItem(STORE)}async function restore(){try{session=JSON.parse(localStorage.getItem(STORE)||'null')}catch{session=null}if(!session?.access_token)return false;const r=await fetch(BASE+'/auth/v1/user',{headers:{apikey:KEY,Authorization:'Bearer '+session.access_token}}).catch(()=>null);if(r?.ok){user=await r.json();return true}if(session.refresh_token)try{const d=await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token});save(d);user=d.user;return true}catch{}save(null);return false}
async function proxy(action,body={},retry=true){if(!session?.access_token)throw Error('Connecte un Passeport staging.');const r=await fetch(PROXY,{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({action,...body})}),d=await r.json().catch(()=>({}));if(r.status===401&&retry&&session.refresh_token){const fresh=await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token});save(fresh);user=fresh.user;return proxy(action,body,false)}if(!r.ok)throw Error(d.error||'Opération staging refusée.');$('log').textContent=JSON.stringify(d,null,2);return d}
function profileName(){return user?.user_metadata?.handle||user?.email||'membre-staging'}function payload(){const share=Math.max(0,Math.min(90,Number($('collabShare').value)||0)),collab=$('collabHandle').value.trim().toLowerCase(),owner=10000-Math.round(share*100),splits=[{id:'owner',memberKey:'owner',name:profileName(),role:'Direction',shareBps:collab?owner:10000,status:'owner',localStatus:'owner'}];if(collab)splits.push({id:'member-1',memberKey:'member-1',name:collab,role:'Création',shareBps:Math.round(share*100),status:'draft',localStatus:'draft'});let id=localStorage.getItem('nosbloc_staging_client_id');if(!id){id='console-'+uuid();localStorage.setItem('nosbloc_staging_client_id',id)}return{id,title:$('title').value.trim(),type:'world',template:'Ville 3B staging',description:$('description').value.trim(),audience:'Test privé',platforms:{mobile:true,web:true,pc:false},safety:{moderation:true,cosmeticFirst:true,ageGate:'Tout public'},rights:{contentOwned:true,thirdPartyLicensed:true,audienceReviewed:true},splits,plan:[{id:'vision',title:'Vision',done:true},{id:'mobile',title:'Mobile',done:true},{id:'security',title:'Sécurité',done:true},{id:'review',title:'Révision',done:true}],licensedAssets:[]}}
function render(){const ok=!!session?.access_token;$('authPanel').classList.toggle('hidden',ok);$('workspace').classList.toggle('hidden',!ok);if(ok){$('identity').textContent=profileName()+' · '+(user?.user_metadata?.country||'France');$('projectState').textContent=serverProjectId?'Projet lié : '+serverProjectId:'Projet non lié.'}}
function renderSnapshot(data){snapshot=data;const inv=data?.incomingInvitations||[];$('invitations').innerHTML=inv.length?inv.map(x=>'<div class="row"><span><strong>'+esc(x.project_title)+'</strong><small>'+esc(x.role_name)+' · '+(Number(x.share_bps)/100)+' %</small></span><button data-i="'+x.invitation_id+'" data-a="1">Accepter</button><button class="danger" data-i="'+x.invitation_id+'" data-a="0">Refuser</button></div>').join(''):'<p class="muted">Aucune invitation en attente.</p>';document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>run(async()=>{await proxy('invite_decide',{invitationId:b.dataset.i,accept:b.dataset.a==='1',idempotency:uuid()});await refresh()}));const q=data?.moderationQueue||[];$('moderation').innerHTML=data?.isModerator?(q.length?q.map(x=>'<div class="row"><span><strong>'+esc(x.project_title)+'</strong><small>Version '+x.version_no+' · '+esc(x.owner_handle)+'</small></span><button data-c="'+x.case_id+'" data-d="approved">Approuver</button><button class="danger" data-c="'+x.case_id+'" data-d="rejected">Refuser</button></div>').join(''):'<p class="muted">Aucun dossier en attente.</p>'):'<p class="muted">Ce compte n’est pas modérateur staging.</p>';document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>run(async()=>{const reason=prompt('Motif de la décision')||'';await proxy('moderation_decide',{caseId:b.dataset.c,decision:b.dataset.d,reason,idempotency:uuid()});await refresh()}))}
async function run(fn){show('Opération en cours…');try{await fn();show('Opération terminée.')}catch(e){show(e.message,true)}}async function refresh(){renderSnapshot(await proxy('snapshot'))}
$('loginTab').onclick=()=>setMode('login');$('signupTab').onclick=()=>setMode('signup');$('authForm').onsubmit=e=>{e.preventDefault();run(async()=>{const email=$('email').value.trim(),password=$('password').value;if(mode==='signup'){const handle=$('handle').value.trim().toLowerCase(),code=$('inviteCode').value.trim();if(!/^[a-z0-9][a-z0-9._-]{2,23}$/.test(handle))throw Error('Identifiant invalide.');if(code.length<16)throw Error('Code d’accès requis.');const d=await auth('signup',{email,password,data:{handle,display_name:$('displayName').value.trim()||handle,country:$('country').value,nosbloc_invite_code:code}});$('inviteCode').value='';if(!d.access_token){show('Compte créé. Confirme l’e-mail puis connecte-toi.');return}save(d);user=d.user}else{const d=await auth('token?grant_type=password',{email,password});save(d);user=d.user}render();await refresh()})};
$('logout').onclick=()=>run(async()=>{if(session?.access_token)await auth('logout',null,session.access_token).catch(()=>{});save(null);user=null;snapshot=null;render();show('Passeport staging déconnecté.')});$('refresh').onclick=()=>run(refresh);$('sync').onclick=()=>run(async()=>{const d=await proxy('project_sync',{project:payload(),idempotency:uuid()});serverProjectId=d.projectId;localStorage.setItem(PROJECT_STORE,serverProjectId);render();await refresh()});$('invite').onclick=()=>run(async()=>{if(!serverProjectId)throw Error('Synchronise le projet.');const handle=$('collabHandle').value.trim().toLowerCase();if(!handle)throw Error('Renseigne le collaborateur.');await proxy('invite_create',{projectId:serverProjectId,memberKey:'member-1',handle,role:'Création',shareBps:Math.round((Number($('collabShare').value)||0)*100),idempotency:uuid()});await refresh()});$('checkpoint').onclick=()=>run(async()=>{if(!serverProjectId)throw Error('Synchronise le projet.');await proxy('version_checkpoint',{projectId:serverProjectId,project:payload(),note:'Point console',idempotency:uuid()});await refresh()});$('review').onclick=()=>run(async()=>{if(!serverProjectId)throw Error('Synchronise le projet.');await proxy('project_sync',{project:payload(),idempotency:uuid()});await proxy('review_submit',{projectId:serverProjectId,project:payload(),note:'Version en modération',idempotency:uuid()});await refresh()});(async()=>{setMode('login');if(await restore()){render();await run(refresh)}else render()})();
</script></main></body></html>`;
Deno.serve(async req=>{const origin=req.headers.get("origin")||"";if(req.method==="GET")return new Response(html,{status:200,headers:{...headers,"Content-Type":"text/html; charset=utf-8"}});if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{...headers,"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}});if(req.method!=="POST")return Response.json({error:"Méthode non autorisée."},{status:405,headers});if(origin&&origin!==ORIGIN)return Response.json({error:"Origine non autorisée."},{status:403,headers});const authorization=req.headers.get("authorization")||"";if(!authorization.startsWith("Bearer "))return Response.json({error:"Passeport staging requis."},{status:401,headers});const text=await req.text();if(text.length>524288)return Response.json({error:"Demande trop volumineuse."},{status:413,headers});let body;try{body=JSON.parse(text)}catch{return Response.json({error:"Demande invalide."},{status:400,headers})}if(!ACTIONS.has(String(body?.action||"")))return Response.json({error:"Action inconnue."},{status:400,headers});const upstream=await fetch(API,{method:"POST",headers:{apikey:PUBLIC,Authorization:authorization,"Content-Type":"application/json"},body:text,signal:AbortSignal.timeout(20000)}),result=await upstream.text();return new Response(result,{status:upstream.status,headers:{...headers,"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":ORIGIN,"Vary":"Origin"}})});
