const BASE=Deno.env.get("SUPABASE_URL")!;
const PUBLIC=Deno.env.get("SUPABASE_ANON_KEY")!;
const PROJECT_REF="zykdfgahzqqanlyxjtbe";
const ORIGIN=`https://${PROJECT_REF}.supabase.co`;
const API=`${ORIGIN}/functions/v1/nosbloc-staging`;
const ACTIONS=new Set(["snapshot","project_sync","invite_create","invite_decide","version_checkpoint","review_submit","moderation_decide"]);
const security={
 "Content-Security-Policy":`default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src ${ORIGIN}; img-src data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'`,
 "Referrer-Policy":"no-referrer",
 "X-Content-Type-Options":"nosniff",
 "X-Frame-Options":"DENY",
 "X-Robots-Tag":"noindex,nofollow,noarchive",
 "Permissions-Policy":"camera=(), microphone=(), geolocation=(), payment=()",
 "Cache-Control":"no-store",
};
const html=`<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Nosbloc 3B · Staging privé</title>
<style>
:root{color-scheme:dark;--bg:#05080d;--panel:#0b121c;--line:#263545;--gold:#d9b86f;--blue:#63d9ff;--muted:#9fb0c0;--ok:#74e6af;--bad:#ff9a9a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 75% 0,#102c40 0,transparent 35%),var(--bg);color:#f7f4eb;font:15px/1.5 Inter,system-ui,sans-serif}main{width:min(1120px,100%);margin:auto;padding:20px}.hero,.panel{border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,rgba(14,24,36,.98),rgba(5,9,14,.98));box-shadow:0 22px 70px #0008}.hero{padding:clamp(22px,5vw,46px);margin-bottom:16px}.eyebrow{color:var(--blue);font-size:12px;font-weight:900;letter-spacing:.15em}.hero h1{font-size:clamp(32px,7vw,68px);line-height:1;margin:.3em 0}.hero em{color:var(--gold);font-style:normal}.badges{display:flex;flex-wrap:wrap;gap:8px}.badge{border:1px solid #ffffff18;border-radius:999px;padding:7px 11px;color:#d6e3ee;font-size:12px}.badge.ok{color:var(--ok);border-color:#74e6af55}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel{padding:20px}.wide{grid-column:1/-1}h2,h3{margin:.2em 0 .7em}label{display:grid;gap:6px;margin:10px 0;color:#d8e4ee;font-weight:700;font-size:13px}input,textarea,select,button{font:inherit}input,textarea,select{width:100%;border:1px solid #ffffff20;border-radius:11px;background:#07101a;color:#fff;padding:11px 12px}textarea{min-height:110px;resize:vertical}button{border:1px solid #d9b86f66;border-radius:11px;background:#d9b86f18;color:#fff;padding:10px 13px;cursor:pointer;font-weight:800}button:hover{border-color:var(--gold)}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:linear-gradient(135deg,#d9b86f44,#63d9ff20)}.danger{border-color:#ff8d8d55;background:#ff8d8d12}.tabs,.actions{display:flex;flex-wrap:wrap;gap:8px}.tabs button[aria-pressed=true]{border-color:var(--blue);color:var(--blue)}.notice,.error{margin:12px 0;padding:11px;border-radius:10px}.notice{border:1px solid #74e6af55;background:#74e6af12;color:#b5f5d5}.error{border:1px solid #ff8d8d55;background:#ff8d8d12;color:#ffc3c3}.row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:center;padding:10px 0;border-top:1px solid #ffffff12}.row span{display:grid}.row small,.muted{color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;background:#02060a;padding:12px;border-radius:12px;color:#b8d7e8}.hidden{display:none!important}.identity{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 0 16px}.status-dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--ok);box-shadow:0 0 18px var(--ok);margin-right:7px}@media(max-width:760px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.row{grid-template-columns:1fr auto auto}main{padding:12px}.panel{padding:16px}}
</style></head><body><main>
<section class="hero"><p class="eyebrow">NOSBLOC DU 3B · ENVIRONNEMENT ISOLÉ</p><h1>Staging <em>privé.</em></h1><p>Teste les Passeports, projets, invitations, versions et décisions humaines sans toucher à la production.</p><div class="badges"><span class="badge ok">Projet Supabase séparé</span><span class="badge">Discover fermé</span><span class="badge">Paiements fermés</span><span class="badge">Publication verrouillée</span></div></section>
<div id="message"></div>
<section id="authPanel" class="panel"><div class="tabs"><button id="loginTab" aria-pressed="true">Connexion</button><button id="signupTab" aria-pressed="false">Créer un Passeport test</button></div><form id="authForm"><label>Adresse e-mail<input id="email" type="email" required autocomplete="email"></label><label>Mot de passe<input id="password" type="password" required minlength="10" autocomplete="current-password"></label><div id="signupFields" class="hidden"><label>Identifiant 3B test<input id="handle" minlength="3" maxlength="24" placeholder="zakaria-test"></label><label>Nom affiché<input id="displayName" minlength="2" maxlength="80" placeholder="Zakaria"></label><label>Pays<select id="country">${["France","Algérie","Espagne","Maroc","Italie","Tunisie","Turquie","Estonie"].map(x=>`<option>${x}</option>`).join("")}</select></label></div><button class="primary" id="authSubmit">Se connecter</button></form></section>
<section id="workspace" class="hidden"><div class="identity panel"><span><i class="status-dot"></i><strong id="identity"></strong></span><button id="logout" class="danger">Déconnexion</button></div><div class="grid">
<section class="panel"><h2>Projet de test</h2><label>Titre<input id="title" value="Ville 3B Staging"></label><label>Description<textarea id="description">Une ville communautaire privée destinée à tester la synchronisation, les versions et la modération Nosbloc sans publication publique.</textarea></label><label>Collaborateur staging (optionnel)<input id="collabHandle" placeholder="identifiant-3b-test"></label><label>Part collaborateur (%)<input id="collabShare" type="number" min="0" max="90" value="40"></label><div class="actions"><button id="sync" class="primary">Synchroniser</button><button id="invite">Inviter</button><button id="checkpoint">Point serveur</button><button id="review">Envoyer en modération</button></div><p class="muted" id="projectState">Projet non lié.</p></section>
<section class="panel"><h2>Invitations reçues</h2><div id="invitations"><p class="muted">Actualise pour consulter les invitations.</p></div></section>
<section class="panel wide"><div class="actions"><button id="refresh" class="primary">Actualiser le serveur</button></div><h2>File de modération</h2><div id="moderation"><p class="muted">Visible uniquement par le compte modérateur staging.</p></div></section>
<section class="panel wide"><h2>Réponse serveur</h2><pre id="log">Aucune opération.</pre></section>
</div></section>
<script>
const BASE=${JSON.stringify(ORIGIN)},KEY=${JSON.stringify(PUBLIC)},PROXY=location.pathname,STORE='nosbloc_staging_console_session_v1',PROJECT_STORE='nosbloc_staging_console_project_v1';
let mode='login',session=null,user=null,snapshot=null,serverProjectId=localStorage.getItem(PROJECT_STORE)||'';
const $=id=>document.getElementById(id),uuid=()=>crypto.randomUUID();
function show(text,bad=false){$('message').innerHTML=text?'<div class="'+(bad?'error':'notice')+'">'+escapeHtml(text)+'</div>':'';}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function setMode(next){mode=next;$('loginTab').setAttribute('aria-pressed',next==='login');$('signupTab').setAttribute('aria-pressed',next==='signup');$('signupFields').classList.toggle('hidden',next!=='signup');$('authSubmit').textContent=next==='signup'?'Créer le Passeport test':'Se connecter';$('password').autocomplete=next==='signup'?'new-password':'current-password';}
async function authRequest(path,body,token){const r=await fetch(BASE+'/auth/v1/'+path,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.msg||d.error_description||d.message||'Authentification impossible.');return d;}
function saveSession(value){session=value||null;if(value)localStorage.setItem(STORE,JSON.stringify(value));else localStorage.removeItem(STORE);}
async function restoreSession(){try{session=JSON.parse(localStorage.getItem(STORE)||'null')}catch{session=null}if(!session?.access_token)return false;try{const r=await fetch(BASE+'/auth/v1/user',{headers:{apikey:KEY,Authorization:'Bearer '+session.access_token}});if(r.ok){user=await r.json();return true}}catch{}if(session.refresh_token)try{const d=await authRequest('token?grant_type=refresh_token',{refresh_token:session.refresh_token});saveSession(d);user=d.user;return true}catch{}saveSession(null);return false;}
async function proxy(action,body={},retry=true){if(!session?.access_token)throw Error('Connecte un Passeport staging.');const r=await fetch(PROXY,{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({action,...body})});const d=await r.json().catch(()=>({}));if(r.status===401&&retry&&session.refresh_token){const fresh=await authRequest('token?grant_type=refresh_token',{refresh_token:session.refresh_token});saveSession(fresh);user=fresh.user;return proxy(action,body,false)}if(!r.ok)throw Error(d.error||'Opération staging refusée.');$('log').textContent=JSON.stringify(d,null,2);return d;}
function profileName(){return user?.user_metadata?.handle||user?.email||'membre-staging'}
function projectPayload(){const share=Math.max(0,Math.min(90,Number($('collabShare').value)||0)),collab=$('collabHandle').value.trim().toLowerCase(),owner=10000-Math.round(share*100);const splits=[{id:'owner',memberKey:'owner',name:profileName(),role:'Direction',shareBps:collab?owner:10000,status:'owner',localStatus:'owner'}];if(collab)splits.push({id:'member-1',memberKey:'member-1',name:collab,role:'Création',shareBps:Math.round(share*100),status:'draft',localStatus:'draft'});return{id:localStorage.getItem('nosbloc_staging_client_id')||(()=>{const id='console-'+uuid();localStorage.setItem('nosbloc_staging_client_id',id);return id})(),title:$('title').value.trim(),type:'world',template:'Ville 3B staging',description:$('description').value.trim(),audience:'Test privé',platforms:{mobile:true,web:true,pc:false},safety:{moderation:true,cosmeticFirst:true,ageGate:'Tout public'},rights:{contentOwned:true,thirdPartyLicensed:true,audienceReviewed:true},splits,plan:[{id:'vision',title:'Vision validée',done:true},{id:'mobile',title:'Mobile validé',done:true},{id:'security',title:'Sécurité validée',done:true},{id:'review',title:'Révision préparée',done:true}],licensedAssets:[]};}
function render(){const logged=!!session?.access_token;$('authPanel').classList.toggle('hidden',logged);$('workspace').classList.toggle('hidden',!logged);if(logged){$('identity').textContent=profileName()+' · '+(user?.user_metadata?.country||'France');$('projectState').textContent=serverProjectId?'Projet lié : '+serverProjectId:'Projet non lié.'}}
function renderSnapshot(data){snapshot=data;const invites=data?.incomingInvitations||[];$('invitations').innerHTML=invites.length?invites.map(x=>'<div class="row"><span><strong>'+escapeHtml(x.project_title)+'</strong><small>'+escapeHtml(x.role_name)+' · '+(Number(x.share_bps)/100)+' %</small></span><button data-invite="'+x.invitation_id+'" data-accept="1">Accepter</button><button class="danger" data-invite="'+x.invitation_id+'" data-accept="0">Refuser</button></div>').join(''):'<p class="muted">Aucune invitation en attente.</p>';document.querySelectorAll('[data-invite]').forEach(b=>b.onclick=async()=>run(async()=>{await proxy('invite_decide',{invitationId:b.dataset.invite,accept:b.dataset.accept==='1',idempotency:uuid()});await refresh()}));const queue=data?.moderationQueue||[];$('moderation').innerHTML=data?.isModerator?(queue.length?queue.map(x=>'<div class="row"><span><strong>'+escapeHtml(x.project_title)+'</strong><small>Version '+x.version_no+' · '+escapeHtml(x.owner_handle)+'</small></span><button data-case="'+x.case_id+'" data-decision="approved">Approuver en privé</button><button class="danger" data-case="'+x.case_id+'" data-decision="rejected">Refuser</button></div>').join(''):'<p class="muted">Aucun dossier en attente.</p>'):'<p class="muted">Ce compte n’est pas modérateur staging.</p>';document.querySelectorAll('[data-case]').forEach(b=>b.onclick=async()=>run(async()=>{const reason=prompt('Motif de la décision')||'';await proxy('moderation_decide',{caseId:b.dataset.case,decision:b.dataset.decision,reason,idempotency:uuid()});await refresh()}));}
async function run(fn){show('Opération en cours…');try{await fn();show('Opération terminée.')}catch(e){show(e.message,true)}}
async function refresh(){const data=await proxy('snapshot');renderSnapshot(data);}
$('loginTab').onclick=()=>setMode('login');$('signupTab').onclick=()=>setMode('signup');
$('authForm').onsubmit=async e=>{e.preventDefault();await run(async()=>{const email=$('email').value.trim(),password=$('password').value;if(mode==='signup'){const handle=$('handle').value.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9._-]{2,23}$/.test(handle))throw Error('Identifiant invalide.');const d=await authRequest('signup',{email,password,data:{handle,display_name:$('displayName').value.trim()||handle,country:$('country').value}});if(!d.access_token){show('Compte créé. Confirme l’e-mail puis connecte-toi.',false);return}saveSession(d);user=d.user}else{const d=await authRequest('token?grant_type=password',{email,password});saveSession(d);user=d.user}render();await refresh()})};
$('logout').onclick=()=>run(async()=>{if(session?.access_token)await authRequest('logout',null,session.access_token).catch(()=>{});saveSession(null);user=null;snapshot=null;render();show('Passeport staging déconnecté.')});
$('refresh').onclick=()=>run(refresh);
$('sync').onclick=()=>run(async()=>{const d=await proxy('project_sync',{project:projectPayload(),idempotency:uuid()});serverProjectId=d.projectId;localStorage.setItem(PROJECT_STORE,serverProjectId);render();await refresh()});
$('invite').onclick=()=>run(async()=>{if(!serverProjectId)throw Error('Synchronise le projet avant l’invitation.');const handle=$('collabHandle').value.trim().toLowerCase();if(!handle)throw Error('Renseigne le collaborateur.');await proxy('invite_create',{projectId:serverProjectId,memberKey:'member-1',handle,role:'Création',shareBps:Math.round((Number($('collabShare').value)||0)*100),idempotency:uuid()});await refresh()});
$('checkpoint').onclick=()=>run(async()=>{if(!serverProjectId)throw Error('Synchronise le projet.');await proxy('version_checkpoint',{projectId:serverProjectId,project:projectPayload(),note:'Point de reprise console',idempotency:uuid()});await refresh()});
$('review').onclick=()=>run(async()=>{if(!serverProjectId)throw Error('Synchronise le projet.');await proxy('project_sync',{project:projectPayload(),idempotency:uuid()});await proxy('review_submit',{projectId:serverProjectId,project:projectPayload(),note:'Version envoyée à la modération humaine',idempotency:uuid()});await refresh()});
(async()=>{setMode('login');if(await restoreSession()){render();await run(refresh)}else render()})();
</script></main></body></html>`;

Deno.serve(async req=>{
 const origin=req.headers.get("origin")||"";
 if(req.method==="GET")return new Response(html,{status:200,headers:{...security,"Content-Type":"text/html; charset=utf-8"}});
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{...security,"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}});
 if(req.method!=="POST")return Response.json({error:"Méthode non autorisée."},{status:405,headers:security});
 if(origin&&origin!==ORIGIN)return Response.json({error:"Origine non autorisée."},{status:403,headers:security});
 const authorization=req.headers.get("authorization")||"";
 if(!authorization.startsWith("Bearer "))return Response.json({error:"Passeport staging requis."},{status:401,headers:security});
 const text=await req.text();
 if(text.length>524288)return Response.json({error:"Demande trop volumineuse."},{status:413,headers:security});
 let body;try{body=JSON.parse(text)}catch{return Response.json({error:"Demande invalide."},{status:400,headers:security})}
 if(!ACTIONS.has(String(body?.action||"")))return Response.json({error:"Action inconnue."},{status:400,headers:security});
 const upstream=await fetch(API,{method:"POST",headers:{apikey:PUBLIC,Authorization:authorization,"Content-Type":"application/json"},body:text,signal:AbortSignal.timeout(20000)}),result=await upstream.text();
 return new Response(result,{status:upstream.status,headers:{...security,"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":ORIGIN,"Vary":"Origin"}});
});
