import React from 'react';
import {COUNTRIES,cardById,countryById} from './catalog.js';
import {CHAPTERS,chapterState,chapterCards,chapterObjective,nexusLevel,COSMETICS,cosmeticUnlocked,puzzleSolved,waterFlow} from './chapters.js';
import {INTENTS,pactCue,pactChoices} from './engine.js';

export function StoryPanel({save,act,onNavigate,onClose}){
 const id=save.region,c=CHAPTERS[id],s=chapterState(save,id),cards=chapterCards(id),objective=chapterObjective(save,id);
 if(!c)return null;
 const board=s.board||[];
 return <div className="adventure-story" style={{'--chapter-color':countryById[id].color}}>
  <div className="adventure-banner"><span>{countryById[id].symbol}</span><div><small>CHAPITRE · {countryById[id].name.toUpperCase()}</small><h3>{c.title}</h3><p>{c.resident}</p></div><b>{s.restored}/3<small>RECONSTRUIT</small></b></div>
  <p className="adventure-dialogue">« {s.restored===3?c.ending:c.need} »</p>
  {!s.helped?<><p>Un premier geste suffit à faire revenir les liens. En aidant cet habitant, tu reçois un Allié et les cartes Terrain et Ambiance de ce chapitre.</p><button className="world-primary" onClick={()=>act({type:'help'})}>{c.help} · +80 XP</button></>:s.powers.length<3?<>
   <h3>Réveiller le lieu</h3><p>Ton Allié reconnaît la trace. L’Ambiance en révèle le sens. Le Terrain fait renaître la lumière du lieu. Ces cartes restent dans ta collection.</p>
   <div className="adventure-powers">{['ally','ambiance','terrain'].map((power,i)=><button key={power} disabled={i!==s.powers.length} className={i<s.powers.length?'is-complete':''} onClick={()=>act({type:'power',power})}><span>{['◈','☾','▱'][i]}</span><small>{['1 · RÉVÉLER','2 · COMPRENDRE','3 · MATÉRIALISER'][i]}</small><strong>{cardById[cards[power]]?.name}</strong><em>{i<s.powers.length?'Lien activé':i===s.powers.length?'Utiliser cette carte':'Attend la carte précédente'}</em></button>)}</div>
  </>:!s.solved?<>
   <div className="adventure-puzzle-heading"><div><small>MONUMENT INTERACTIF</small><h3>{c.puzzle}</h3></div><button className="world-link" onClick={()=>act({type:'puzzleReset'})}>Recommencer</button></div><p>{c.instruction}</p>
   <div className={'adventure-puzzle adventure-puzzle-'+c.kind}>
    {c.kind==='sequence'&&<><div className="adventure-sequence" aria-label="Ta séquence">{Array.from({length:4},(_,i)=><span key={i}>{c.symbols[board[i]]||'·'}</span>)}</div><div className="adventure-symbols">{c.symbols.map((symbol,i)=><button aria-label={['Étincelle','Graine','Maison','Soleil'][i]} key={symbol} onClick={()=>act({type:'puzzleStep',index:i})}>{symbol}<small>{['Étincelle','Graine','Maison','Soleil'][i]}</small></button>)}</div></>}
    {c.kind==='path'&&<div className="adventure-path">{Array.from({length:9},(_,i)=><button key={i} aria-label={'Dalle '+(i+1)} disabled={c.blocked.includes(i)} className={board.includes(i)?'is-complete':''} onClick={()=>act({type:'puzzleStep',index:i})}>{c.blocked.includes(i)?'╳':i===0?'Départ':i===8?'Jardin':board.includes(i)?'✦':'◇'}{board.includes(i)&&<small>{board.indexOf(i)+1}</small>}</button>)}</div>}
    {c.kind==='lights'&&<div className="adventure-lights">{board.map((n,i)=><button key={i} aria-label={'Rune '+(i+1)+(n?' allumée':' éteinte')} className={n?'is-lit':''} onClick={()=>act({type:'puzzleStep',index:i})}>✧<small>{i+1}</small></button>)}</div>}
    {c.kind==='pipes'&&<><div className="adventure-water-labels"><span>Source →</span><span>→ Jardin</span></div><div className="adventure-water">{board.map((n,i)=><button key={i} aria-label={'Canal '+(i+1)+' · orientation '+n} className={waterFlow(board).visited.includes(i)?'is-flowing':''} onClick={()=>act({type:'puzzleStep',index:i})}><svg viewBox="0 0 100 100" aria-hidden="true" style={{transform:`rotate(${n*90}deg)`}}><path d="M50 0V35Q50 50 65 50H100" fill="none" stroke="currentColor" strokeWidth="14"/></svg><small>{i+1}</small></button>)}</div></>}
    {['rotate','tide','balance','gears'].includes(c.kind)&&<div className="adventure-dials">{board.map((n,i)=><button key={i} aria-label={c.puzzle+' · élément '+(i+1)+' · valeur '+n} onClick={()=>act({type:'puzzleStep',index:i})}><span className={c.kind==='gears'?'adventure-gear':''} style={c.kind==='rotate'||c.kind==='gears'?{transform:`rotate(${n*90}deg)`}:undefined}>{c.kind==='rotate'?'↑':c.kind==='gears'?'⚙':n}</span><b>{c.kind==='gears'?n:c.kind==='rotate'?['Nord','Est','Sud','Ouest'][n]:c.kind==='tide'?'Niveau de l’eau':'Poids'}</b><small>{c.kind==='gears'?'Cible '+c.answer[i]:'Toucher pour régler'}</small></button>)}</div>}
   </div>
   <details className="adventure-hint"><summary>Lire l’indice du monument</summary><p>{c.hint}</p></details>
   <button className="world-primary" disabled={!puzzleSolved(id,board)} onClick={()=>act({type:'solve'})}>Éveiller le monument · +120 XP</button>
  </>:s.restored===1?<>
   <h3>{c.restores[0]} reprend vie</h3><p>Retrouve les trois souvenirs pour reconstruire le quartier suivant. Choisis ensuite un jardin ou un atelier : ce choix sera visible dans le décor.</p>
   <div className="adventure-restoration">{[0,1,2].map(i=><span key={i} className={save.beacons.includes(id+':'+i)?'is-complete':''}>{save.beacons.includes(id+':'+i)?'◆':'◇'} Souvenir {i+1}</span>)}</div>
   {[0,1,2].every(i=>save.beacons.includes(id+':'+i))?<div className="adventure-choice"><button onClick={()=>act({type:'restore',choice:'garden'})}><span>❧</span><strong>Un jardin partagé</strong><small>Fleurs, arbres et bancs · mêmes récompenses</small></button><button onClick={()=>act({type:'restore',choice:'workshop'})}><span>⚒</span><strong>Un atelier ouvert</strong><small>Établis, étals et lanternes · mêmes récompenses</small></button></div>:<button className="world-primary" onClick={()=>onNavigate(objective.target)}>Rejoindre le prochain souvenir</button>}
  </>:s.restored===2?<>
   <h3>{c.restores[1]} est reconstruit</h3><p>{c.guardian}</p>{save.seals.includes(id)?<button className="world-primary" onClick={()=>act({type:'restore'})}>Inaugurer {c.restores[2]} · +200 XP</button>:<button className="world-primary" onClick={()=>onNavigate(id+':guardian')}>Rejoindre le gardien</button>}
  </>:<><div className="adventure-complete">✦<h3>Le pays rejoint l’Union</h3><p>Une nouvelle présence t’attend au Nexus. La tenue {countryById[id].name} est disponible dans le Vestiaire.</p></div><button className="world-primary" onClick={onClose}>Continuer à explorer</button></>}
 </div>;
}

export function AdventureJournal({save,onNavigate,onStyle}){
 return <><div className="adventure-banner"><span>◈</span><div><small>TON BUT</small><h3>Rendre leur monde aux habitants</h3><p>Huit pays → huit quartiers vivants → le dernier combat contre l’Oubli.</p></div><b>{nexusLevel(save)}/8<small>PAYS VIVANTS</small></b></div>
  <p>Une expédition vise une découverte, un choix et une transformation visible. Tu peux t’arrêter après n’importe quelle étape : la progression est conservée.</p>
  <div className="adventure-chapters">{COUNTRIES.map(c=>{const s=chapterState(save,c.id),o=chapterObjective(save,c.id);return <article key={c.id} style={{'--chapter-color':c.color}}><span>{c.symbol}</span><div><small>{c.name.toUpperCase()} · {s.restored}/3 LIEUX</small><h3>{CHAPTERS[c.id].title}</h3><p>{o.title}</p><progress max={3} value={s.restored}/><small>{s.challenge?'◆ Défi expert accompli':o.reward}</small></div><button onClick={()=>onNavigate(save.region===c.id?o.target:save.region==='hub'?c.id:'hub')}>{save.region===c.id?'Suivre':'Rejoindre'}</button></article>;})}</div>
  <div className="adventure-economy"><article><strong>XP monde</strong><p>Quêtes, pactes et gardiens font progresser ton personnage. Les premiers niveaux sont rapides, les suivants demandent plus d’exploration.</p></article><article><strong>Éclats</strong><p>Assemble des équipements et propose des offrandes. Les cartes nécessaires à chaque chapitre sont données par son habitant.</p></article><article><strong>Fidélité du compte</strong><p>Les minutes de jeu actif et les achats de vêtements validés suivent le programme de ton compte. Les éclats du monde ne se convertissent pas en argent ni en points d’achat.</p></article></div>
  <h3>Le style de ton Nexus</h3><div className="world-actions"><button aria-pressed={save.adventure.nexusStyle==='garden'} onClick={()=>onStyle('garden')}>Jardins et fleurs</button><button aria-pressed={save.adventure.nexusStyle==='workshop'} onClick={()=>onStyle('workshop')}>Ateliers et lanternes</button></div>
 </>;
}
export function Wardrobe({save,act}){return <><p>Chaque pays reconstruit offre une couleur de tenue à ton personnage. Le dernier combat débloque la lumière de l’Union. Ces choix sont cosmétiques.</p><div className="adventure-wardrobe">{COSMETICS.map(c=><button key={c.id} disabled={!cosmeticUnlocked(save,c)} aria-pressed={save.adventure.cosmetic===c.id} onClick={()=>act({type:'cosmetic',id:c.id})}><span style={{background:c.color}}>3B</span><strong>{c.name}</strong><small>{save.adventure.cosmetic===c.id?'Tenue portée':cosmeticUnlocked(save,c)?'Porter cette tenue':c.need==='final'?'Achever la finale':'Reconstruire '+countryById[c.need]?.name}</small></button>)}</div></>;}

export function AdventureEncounter({save,act,onClose,Art}){
 const e=save.adventure.encounter;if(!e)return <p>La rencontre est terminée.</p>;const card=cardById[e.card],done=['victory','recruited','missed','defeat'].includes(e.result);
 return <div className="world-encounter"><div className="world-encounter-art"><Art card={card}/><div><span className="world-kicker">{e.final?'FINALE · L’OUBLI':e.boss?'GARDIEN · PHASE '+e.phase+'/3':'ÉCHO VIVANT · '+(e.approach==='help'?'CONFIANCE':e.approach==='offer'?'OFFRANDE':'RENCONTRE')}</span><h3>{e.final?'L’Oubli aux huit visages':card.name}</h3><p>{e.expert?'Défi expert':'Aventure'} · {e.final?'Les huit pays sont à tes côtés':card.countryName}</p></div></div>
  {done?<div className="world-result"><span className="adventure-result-symbol">{['victory','recruited'].includes(e.result)?'✦':'◇'}</span><h3>{e.result==='victory'?(e.final?'L’Union est retrouvée !':'Le sceau est libéré !'):e.result==='recruited'?'Un nouveau lien !':e.result==='defeat'?'Une autre approche est possible':'L’écho s’éloigne'}</h3><p>{e.final&&e.result==='victory'?'Les huit pays se souviennent les uns des autres. Le Nexus accueille leurs habitants. La tenue Union, 1 000 XP et 300 éclats sont à toi.':e.result==='victory'?'La carte unique rejoint ta collection. Retourne au monument pour inaugurer le pays.':e.result==='recruited'?'Cette carte rejoint ta collection. Tu peux l’équiper comme Allié.':e.log}</p><button className="world-primary" onClick={onClose}>Revenir au monde</button></div>:e.pact?<div className="adventure-pact"><h3>Répondre à ses besoins</h3><p>Observe trois réactions et choisis le geste juste. Trois erreurs dissipent le lien.</p><div className="adventure-sequence">{[0,1,2].map(i=><span key={i} className={i<e.pactStep?'is-complete':''}>{i<e.pactStep?'◆':'◇'}</span>)}</div><p className="adventure-cue">{pactCue(e)}</p><div className="world-actions">{pactChoices.map((choice,index)=><button key={choice} onClick={()=>act({type:'pactChoice',index})}>{choice}</button>)}</div><p role="status">{e.log} · {e.mistakes}/3 erreurs</p></div>:<div className="world-battle">
   <div className="world-health"><label>Ton équipe <b>{e.hp}/{e.maxHP}</b></label><progress max={e.maxHP} value={e.hp}/><label>{e.boss?'Gardien':'Agitation de l’écho'} <b>{e.enemy}/{e.enemyMax}</b></label><progress className="enemy" max={e.enemyMax} value={e.enemy}/></div>
   <p className="world-intent">{e.result==='calm'?'L’écho est prêt à créer un lien.':INTENTS[e.intent]}</p><p role="status">{e.log}</p>
   {!e.result&&<><div className="world-actions world-battle-actions">{[['strike','Frapper','+1 concentration'],['guard','Garder','Protège et soigne'],['power','Pouvoir',e.focus+' / 2 concentration']].map(([action,label,small])=><button key={action} disabled={action==='power'&&e.focus<2} className={action==='power'?'world-primary':''} onClick={()=>act({type:'battle',action})}>{label}<small>{small}</small></button>)}</div><div className="world-actions">{e.traps>0&&<button onClick={()=>act({type:'battle',action:'trap'})}>Piège · {e.traps} restants</button>}{e.support&&<button onClick={()=>act({type:'battle',action:'support'})}>Soutien · +32 vitalité</button>}</div>
    {!e.boss&&e.turn===0&&<details className="adventure-hint"><summary>Créer un lien autrement</summary><p>Tu peux aussi rassurer l’écho ou lui offrir de la lumière. Il faudra ensuite comprendre ses réactions.</p><div className="world-actions"><button disabled={!chapterState(save,e.region).helped} onClick={()=>act({type:'approach',kind:'help'})}>Montrer un refuge</button><button disabled={save.shards<12} onClick={()=>act({type:'approach',kind:'offer'})}>Offrir 12 éclats</button></div></details>}
   </>}
   {e.result==='calm'&&<button className="world-primary" onClick={()=>act({type:'pactStart'})}>Tisser un lien</button>}
  </div>}
 </div>;
}
