const NOTES={hub:174.61,france:196,italie:220,estonie:164.81,turquie:146.83,algerie:174.61,tunisie:196,maroc:146.83,espagne:164.81};
export function createWorldAudio(){
 let ctx,master,pad=[],enabled=false,hidden=false,noiseBuffer,ambience=[],birdTimer,currentRegion='hub',inside=false;
 function init(){if(ctx)return;const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;ctx=new Audio();master=ctx.createGain();master.gain.value=.23;master.connect(ctx.destination);for(const ratio of [1,1.5,2]){const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=174.61*ratio;g.gain.value=.025;o.connect(g).connect(master);o.start();pad.push({o,ratio});}}
 function region(id){currentRegion=id;if(!ctx)return;for(const {o,ratio} of pad)o.frequency.setTargetAtTime((NOTES[id]||174.61)*ratio,ctx.currentTime,.8);}
 function tone(frequency,duration,gain,type='sine'){if(!ctx||!enabled||hidden)return;ctx.resume().catch(()=>{});const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime;o.type=type;o.frequency.setValueAtTime(frequency,t);o.frequency.exponentialRampToValueAtTime(frequency*.65,t+duration);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(master);o.start(t);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
 function noise(duration,gain,frequency){if(!ctx||!enabled||hidden)return;if(!noiseBuffer){noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;}const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),volume=ctx.createGain();source.buffer=noiseBuffer;filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.6;volume.gain.setValueAtTime(gain,ctx.currentTime);volume.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);source.connect(filter).connect(volume).connect(master);source.start();source.stop(ctx.currentTime+duration);source.onended=()=>{source.disconnect();filter.disconnect();volume.disconnect();};}
 function startAmbience(){if(!ctx||birdTimer)return;birdTimer=setInterval(()=>{if(enabled&&!hidden&&!inside&&currentRegion==='france'){tone(1600+Math.random()*700,.18,.018);setTimeout(()=>tone(2200,.12,.014),180);}},6400);}
 return{enable(value,id){enabled=value;try{if(value){init();region(id);startAmbience();ctx?.resume().catch(()=>{});}else ctx?.suspend().catch(()=>{});}catch{}},region,
 ambience(id,interior){currentRegion=id;inside=!!interior;},
 step(id){noise(.065,inside?.075:.045,inside?550:1600);tone(inside?105:id==='estonie'?180:135,.065,.035,'triangle');},
 event(type,action){if(type==='battle'){const defence=['guard','dodge'].includes(action);noise(defence?.23:.13,defence?.1:.19,action==='dodge'?2300:action==='power'?1000:650);tone(action==='power'?330:defence?210:95,action==='power'?.42:.14,.13,defence?'sine':'triangle');}else if(type==='gather'){noise(.12,.07,1200);tone(380,.14,.07,'triangle');}else if(type==='build'||type==='restore'){tone(330,.6,.1);setTimeout(()=>tone(495,.6,.08),140);setTimeout(()=>tone(660,.7,.06),280);}else tone(type==='power'?440:660,.45,.1);},
 visibility(value){hidden=value;if(!ctx)return;if(value)ctx.suspend().catch(()=>{});else if(enabled)ctx.resume().catch(()=>{});},close(){clearInterval(birdTimer);enabled=false;pad.forEach(p=>p.o.stop());ambience.forEach(p=>p.stop());ctx?.close();}};
}
