import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AvatarCinematic} from './AvatarCinematic.jsx';
import {ArenaStage} from '../arena/ArenaStage.jsx';
import {LOOKS,TRAVEL_GEAR} from './wardrobe.js';
import {COUNTRIES} from './catalog.js';
import {normalizeAvatar,SKINS,OUTFITS,AVATAR_PATHS} from './avatar-rules.js';
import Armory from './origins/Armory.jsx';
import {clearAvatarDraft,readAvatarDraft,writeAvatarDraft} from './avatar-draft-store.js';
import '../arena/arena.css';
import './origins/creator.css';
import './hub/platform.css';
const TABS=[['identity','Identité','01'],['face','Visage','02'],['style','Style','03'],['equipment','Équipement','04'],['path','Voie','05'],['armory','Arme','06']];
export function AvatarPanel({save,act,onDone,uid=null}){
 const saved=useMemo(()=>normalizeAvatar(save.adventure.avatar),[save.adventure.avatar]),recovered=useMemo(()=>readAvatarDraft(uid,saved),[uid,saved]);
 const committed=useRef(false),[draft,setDraft]=useState(()=>recovered.avatar),[section,setSection]=useState('identity'),[message,setMessage]=useState(()=>recovered.recovered?'Tes derniers réglages ont été retrouvés.':''),[reveal,setReveal]=useState(null),[initiallyCreated]=useState(()=>!!save.adventure.avatar.created);
 useEffect(()=>{if(!uid||committed.current)return;if(JSON.stringify(draft)===JSON.stringify(saved)){clearAvatarDraft(uid);return;}const timer=setTimeout(()=>{if(!committed.current)writeAvatarDraft(uid,draft);},320);return()=>clearTimeout(timer);},[uid,draft,saved]);
 const set=(key,value)=>setDraft(d=>({...d,[key]:value})),merge=values=>setDraft(d=>({...d,...values}));
 const complete=result=>{const avatar=normalizeAvatar(result.adventure?.avatar||{...draft,created:true});committed.current=true;clearAvatarDraft(uid);if(initiallyCreated)onDone?.({firstCreation:false,avatar});else setReveal(avatar);};
 if(reveal)return <AvatarCinematic avatar={reveal} onDone={()=>onDone?.({firstCreation:true,openingPlayed:true,avatar:reveal})}/>;
 const select=(key,label,options)=><label>{label}<select value={draft[key]} onChange={e=>set(key,typeof options[0][0]==='number'?Number(e.target.value):e.target.value)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;
 const colors=(values,key)=><div className="avatar-swatches">{values.map((color,i)=><button type="button" key={color} style={{background:color}} aria-label={'Couleur '+(i+1)} aria-pressed={draft[key]===i} onClick={()=>key==='color'?merge({color:i,fabricColor:null}):set(key,i)}/>)}</div>;
 return <div className="avatar-editor hub-creator"><section className="avatar-preview"><div className="hub-creator-brand"><small>LE MONDE DU 3B</small><h3>{draft.name||'Kaïs'}</h3><span>Ton identité. Ton style. Ton héritage.</span></div><ArenaStage avatar={draft} focus={section==='face'?'face':'body'}/><small className="hub-creator-drag">Glisse pour tourner le personnage</small><div className="hub-creator-summary"><span>{draft.body==='femme'?'Voyageuse':'Voyageur'}</span><span>{AVATAR_PATHS[draft.path]?.name}</span><span>{TRAVEL_GEAR[draft.travelGear]?.name}</span></div></section>
 <div className="avatar-workbench"><nav className="hub-creator-tabs" aria-label="Personnalisation">{TABS.map(([id,label,n])=><button type="button" key={id} aria-pressed={section===id} onClick={()=>setSection(id)}><small>{n}</small>{label}</button>)}</nav><form className="avatar-fields" onSubmit={e=>{e.preventDefault();const result=act({type:'avatar',avatar:draft});if(result)complete(result);else setMessage('La sauvegarde a échoué. Tes réglages restent disponibles ici.');}}><header className="hub-creator-heading"><small>PERSONNALISATION</small><h3>{TABS.find(t=>t[0]===section)?.[1]}</h3></header>
 {section==='identity'&&<><label>Nom du personnage<input maxLength={20} required value={draft.name} onChange={e=>set('name',e.target.value)}/></label><fieldset><legend>Silhouette</legend><div className="world-actions">{['homme','femme'].map(body=><button type="button" key={body} aria-pressed={draft.body===body} onClick={()=>set('body',body)}>{body==='homme'?'Homme':'Femme'}</button>)}</div></fieldset>{select('shape','Morphologie',[['equilibre','Équilibrée'],['elance','Élancée'],['solide','Solide']])}<label>Origines personnelles<input maxLength={50} value={draft.nationality} placeholder="Tes origines, librement" onChange={e=>set('nationality',e.target.value)}/></label>{select('origin','Pays de cœur',[['3b','L’Union des huit portes'],...COUNTRIES.map(c=>[c.id,c.name])])}<p>Ton apparence et tes origines restent libres. Elles ne déterminent pas ta puissance.</p></>}
 {section==='face'&&<><fieldset><legend>Teint</legend>{colors(SKINS,'skin')}</fieldset>{select('hair','Coiffure',['Rasé','Coupe courte','Chignons','Raie souple','Cheveux longs','Court texturé','Crâne rasé'].map((name,i)=>[i,name]))}<label>Couleur des cheveux<input type="color" value={draft.hairColor} onChange={e=>set('hairColor',e.target.value)}/></label>{[['face','Largeur du visage'],['jaw','Mâchoire'],['nose','Nez']].map(([key,label])=><label className="avatar-range" key={key}>{label}<input type="range" min="-1" max="1" step=".1" value={draft[key]} onChange={e=>set(key,Number(e.target.value))}/></label>)}</>}
 {section==='style'&&<><fieldset className="avatar-looks"><legend>Looks complets</legend><div>{LOOKS.map(look=><button type="button" key={look.id} onClick={()=>{const {id,name,...changes}=look;merge(changes);}}><i style={{background:look.fabricColor,borderColor:look.accentColor}}/><span>{look.name}</span></button>)}</div></fieldset>{select('style','Coupe',[['voyageur','Voyageur'],['sentinelle','Sentinelle'],['mystique','Résonance']])}<fieldset><legend>Palette</legend>{colors(OUTFITS,'color')}</fieldset><div className="avatar-colors">{[['fabricColor','Tissu'],['accentColor','Détails'],['trouserColor','Pantalon'],['bootColor','Chaussures']].map(([key,label])=><label key={key}>{label}<input type="color" value={draft[key]||OUTFITS[draft.color]} onChange={e=>set(key,e.target.value)}/></label>)}</div>{select('pattern','Motif',[['uni','Uni'],['bandes','Rayures'],['damier','Damier'],['insigne','Signature 3B'],['broderie','Broderie']])}</>}
 {section==='equipment'&&<>{select('headwear','Couvre-chef',[['none','Aucun'],['beret','Béret'],['brim','Chapeau de voyage'],['hood','Capuche']])}{select('outer','Accessoire',[['none','Aucun'],['cape','Cape'],['scarf','Écharpe'],['apron','Tablier']])}{select('boots','Chaussures',[[0,'Voyage'],[1,'Exploration'],[2,'Garde']])}<label className="avatar-check"><input type="checkbox" checked={draft.bag} onChange={e=>set('bag',e.target.checked)}/>Sac de voyage</label>{select('travelGear','Équipement de voyage',Object.entries(TRAVEL_GEAR).map(([id,g])=>[id,g.name]))}<p>{TRAVEL_GEAR[draft.travelGear]?.description}</p></>}
 {section==='path'&&<><div className="hub-paths">{Object.entries(AVATAR_PATHS).map(([id,p])=><button type="button" key={id} aria-pressed={draft.path===id} onClick={()=>set('path',id)}><strong>{p.name}</strong><span>{p.description}</span></button>)}</div><p>La voie influence l’aventure. L’arène utilise des statistiques équilibrées pour les duels.</p></>}
 {section==='armory'&&<Armory draft={draft} change={merge} xp={save.xp}/>}
 <footer className="avatar-savebar"><button className="world-primary" type="submit">{initiallyCreated?'Enregistrer mon personnage':'Confirmer et entrer dans l’histoire'}</button><p role="status">{message}</p></footer></form></div></div>;
}
