import React,{memo,useMemo,useState} from 'react';
import {createTerrainField} from './terrain.js';
import {blankSave} from './rules.js';
import {REGIONS,compassHeading} from './settlements.js';

const MapGround=memo(function MapGround({field}){return <><circle r="134" fill="#253f37" stroke="#b4c5a330"/>{field.fields.map((f,i)=><rect key={'f'+i} x={f.x-f.w/2} y={f.z-f.h/2} width={f.w} height={f.h} fill="#728056" stroke="#a9ab711f" transform={`rotate(${-f.rotation*180/Math.PI} ${f.x} ${f.z})`}/>)}<circle cx={field.lake.x} cy={field.lake.z} r={field.lake.r} fill="#407c89" stroke="#769d9a" strokeWidth="1.5"/>{field.roads.map((r,i)=><polyline key={i} points={r.points.map(p=>p.x+','+p.z).join(' ')} fill="none" stroke={r.kind==='street'?'#ab9e82':'#768567'} strokeWidth={r.width} strokeLinejoin="round" strokeLinecap="round"/>)}{field.squares.map((p,i)=><circle key={'s'+i} cx={p.x} cy={p.z} r={p.r} fill="#ab9e82"/>)}{field.buildings.map((b,i)=><rect key={'b'+i} x={b.x-b.width/2} y={b.z-b.depth/2} width={b.width} height={b.depth} rx=".4" transform={`rotate(${-b.rotation*180/Math.PI} ${b.x} ${b.z})`} fill="#ddd0ad" stroke="#554d3f" strokeWidth=".5"/>)}</>;});
const icon=i=>i.type==='camp'?'⌂':i.type==='resource'?'✦':i.type==='patrol'?'⚔':i.type==='portal'?'◇':i.type==='sanctuary'?'❧':i.type==='atelier'?'✂':i.type==='guardian'?'♜':i.type==='survey'?'⌾':i.type==='beacon'?'✧':i.type==='story'?'!':'·';
export function Compass({yaw=0,waypoint,position}){const heading=compassHeading(yaw),bearing=waypoint?((Math.atan2(waypoint.x-position.x,position.z-waypoint.z)*180/Math.PI-heading+540)%360)-180:null;return <div className="world-compass" aria-label={'Boussole, '+Math.round(heading)+' degrés'}><div className="compass-track">{Array.from({length:24},(_,i)=>{const angle=i*15,diff=((angle-heading+540)%360)-180;return Math.abs(diff)<76?<span key={i} className={i%6===0?'cardinal':''} style={{left:`calc(50% + ${diff*1.5}px)`}}>{i%6===0?['N','E','S','O'][i/6]:i%3===0?'·':'│'}</span>:null;})}{bearing!==null&&Math.abs(bearing)<76&&<b style={{left:`calc(50% + ${bearing*1.5}px)`}}>◆</b>}</div><i/><small>{Math.round(heading).toString().padStart(3,'0')}°</small></div>;}
export function MiniMap({region,items,position,camera,waypoint,onOpen}){const [hidden,setHidden]=useState(false),[wide,setWide]=useState(region==='hub'),field=useMemo(()=>createTerrainField(region,blankSave()),[region]);const size=wide?(region==='hub'?134:78):46;return <aside className={'world-minimap'+(hidden?' collapsed':'')} aria-label="Mini-carte du monde"><div className="minimap-heading"><span>N ↑</span><button onClick={()=>setHidden(h=>!h)} aria-label={hidden?'Afficher la mini-carte':'Masquer la mini-carte'}>{hidden?'Carte':'−'}</button></div>{!hidden&&<><button className="minimap-open" onClick={onOpen} aria-label="Ouvrir la grande carte"><svg viewBox={`${-size} ${-size} ${size*2} ${size*2}`} aria-hidden="true"><g transform={`translate(${-position.x} ${-position.z})`}><MapGround field={field}/>{items.filter(i=>i.type!=='echo'&&i.type!=='final').map(i=><g key={i.id} transform={`translate(${i.x} ${i.z}) scale(${Math.max(1,size/65)})`}><circle r="3.3" fill="#132526" stroke={i.done?'#90aa94':i.color} strokeWidth=".65"/><text textAnchor="middle" y="1.7" fontSize="5" fill={i.done?'#90aa94':'#fff2ca'}>{icon(i)}</text></g>)}{waypoint&&<><line x1={position.x} y1={position.z} x2={waypoint.x} y2={waypoint.z} stroke="#f5d293" strokeWidth=".65" strokeDasharray="1.7 2"/><circle cx={waypoint.x} cy={waypoint.z} r="4.3" fill="none" stroke="#f5d293"/></>}</g><g transform={`rotate(${compassHeading(camera?.yaw)}) scale(${size/46})`}><path d="M 0 0 L -15 -24 Q 0 -31 15 -24 Z" fill="#e9d8a620"/><path d="M 0 -4.2 L 2.9 3 L 0 1.8 L -2.9 3 Z" fill="#fff1c7" stroke="#192e2b" strokeWidth=".7"/></g></svg></button><div className="minimap-footer"><span>{waypoint?Math.round(Math.hypot(waypoint.x-position.x,waypoint.z-position.z))+' m':'Explorer librement'}</span><button onClick={()=>setWide(v=>!v)} aria-label={wide?'Rapprocher la mini-carte':'Élargir la mini-carte'}>{wide?'+':'−'}</button></div></>}</aside>;}
export function DetailedMap({region='hub',items,position,onSelect}){const field=useMemo(()=>createTerrainField(region,blankSave()),[region]);return <div className="play-map cartography-map"><svg viewBox="-140 -140 280 280" role="group" aria-label="Rues, bâtiments et lieux du pays"><MapGround field={field}/>{items.map(item=><g key={item.id} role="button" tabIndex={0} aria-label={'Placer un repère : '+item.name} onClick={()=>onSelect(item)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(item);}}}><circle cx={item.x} cy={item.z} r="6" fill="#102625" stroke={item.done?'#72997d':item.color} strokeWidth="1"/><text x={item.x} y={item.z+2} textAnchor="middle" fill="#f2e5c8" fontSize="6">{icon(item)}</text><title>{item.name}</title></g>)}<circle cx={position.x} cy={position.z} r="3" fill="#fff1c7" stroke="#132e27"/><text x="0" y="-132" fill="#eddfb5" fontSize="6" textAnchor="middle">N ↑</text></svg><p>◇ Porte · ❧ Préparation · ✂ Atelier · ⌾ Découverte · ✧ Souvenir · ♜ Gardien</p><small>{REGIONS[region]?.city} · Choisis un lieu pour poser un repère.</small></div>;}
