import React,{memo,useId,useMemo,useRef,useState} from 'react';
import {Button} from '../design-system/index.jsx';
import {worldCartographyArt as mapArt} from '../design-system/tokens.js';
import {createTerrainField} from './terrain.js';
import {blankSave} from './rules.js';
import {REGIONS,compassHeading} from './settlements.js';
import {COMPASS_DIRECTIONS,compassDirection} from './heading.js';
import {createHubCartography,mapFootprint,mapStructureOutline,hubMapScale,hubMapRoute,hubMapDestinations,hubMiniMapMarkers,hubAtlasMapMarkers,hubMapCategory,hubMapElevation,HUB_TRANSPORT_MAP_STYLES} from './hub/cartography-model.js';
import {hubPlaceLabel,hubItemLabel,hubElevationLabel,hubDistanceLabel,hubSearchMatches} from './hub/presentation.js';
import './cartography.css';
import {realmDimensions,realmRoads,realmSites,realmBuildings} from './realm-layout.js';

const MapGround=memo(function MapGround({field}){return <><circle r={field.radius} fill="#253f37" stroke="#b4c5a330"/>{field.fields.map((f,i)=><rect key={'f'+i} x={f.x-f.w/2} y={f.z-f.h/2} width={f.w} height={f.h} fill="#728056" stroke="#a9ab711f" transform={`rotate(${-f.rotation*180/Math.PI} ${f.x} ${f.z})`}/>)}<circle cx={field.lake.x} cy={field.lake.z} r={field.lake.r} fill="#407c89" stroke="#769d9a" strokeWidth="1.5"/>{field.roads.map((r,i)=><polyline key={i} points={r.points.map(p=>p.x+','+p.z).join(' ')} fill="none" stroke={r.kind==='street'?'#ab9e82':'#768567'} strokeWidth={r.width} strokeLinejoin="round" strokeLinecap="round"/>)}{field.squares.map((p,i)=><circle key={'s'+i} cx={p.x} cy={p.z} r={p.r} fill="#ab9e82"/>)}{[...field.buildings,...field.civic,...field.paris].map((b,i)=><rect key={'b'+i} x={b.x-b.width/2} y={b.z-b.depth/2} width={b.width} height={b.depth} rx=".4" transform={`rotate(${-b.rotation*180/Math.PI} ${b.x} ${b.z})`} fill="#ddd0ad" stroke="#554d3f" strokeWidth=".5"/>)}</>;});
const icon=i=>i.type==='campaignObjective'?'!':i.type==='realmTravel'?'↔':i.type==='realmSite'?'◆':i.type==='hubLift'?'⇅':i.type==='hubLifeObject'?(i.kind==='read'?'▤':i.kind==='seat'?'▰':'⌕'):i.type==='hubPublicPlace'?'◈':i.type==='hubCreature'?'♧':i.type==='hubHeritageFacility'?'▣':i.type==='hubHeritagePlatform'?'◈':i.type==='hubSkybridge'?'═':i.type==='hubMilestone'?'✦':i.type==='hubDistrictLandmark'?'▲':i.type==='hubCivicPlaza'?'○':i.type==='hubWaterFeature'?'≈':i.type==='hubBuilding'?'▥':i.type==='hubTransport'?'↔':i.type==='hubMission'?'!':i.type==='hubNpc'?'●':i.type==='hubDistrict'?'◆':i.type==='hubGuardian'?'♜':i.type==='hubEvent'?'✦':i.type==='hubSecret'||i.type==='hubSecretStep'?'?':i.type==='landmark'?'▥':i.type==='vista'?'⌂':i.type==='camp'?'⌂':i.type==='resource'?'✦':i.type==='patrol'?'⚔':i.type==='portal'?'◇':i.type==='sanctuary'?'❧':i.type==='atelier'?'✂':i.type==='guardian'?'♜':i.type==='survey'?'⌾':i.type==='beacon'?'✧':i.type==='story'?'!':'·';
const mapVisible=i=>!['echo','final','hubRoad','hubStructure','hubTraffic','hubTransitLink','hubStreetFurniture','hubDistrictTerrace','hubVerticalConnector'].includes(i.type);
export function Compass({heading=180,waypoint,position}){
 const direction=compassDirection(heading),degrees=Math.round(heading)%360;
 const bearing=waypoint?((Math.atan2(waypoint.x-position.x,position.z-waypoint.z)*180/Math.PI-heading+540)%360)-180:null;
 return <div className="world-compass" aria-label={'Cap de déplacement : '+direction+', '+degrees+' degrés'}>
  <div className="compass-track">{Array.from({length:24},(_,i)=>{
   const angle=i*15,diff=((angle-heading+540)%360)-180;
   return Math.abs(diff)<76?<span key={i} className={i%6===0?'cardinal':i%3===0?'ordinal':''} style={{left:'calc(50% + '+diff*1.5+'px)'}}>{i%3===0?COMPASS_DIRECTIONS[i/3]:'│'}</span>:null;
  })}{bearing!==null&&Math.abs(bearing)<76&&<b style={{left:'calc(50% + '+bearing*1.5+'px)'}}>◆</b>}</div>
  <i/><small><strong>{direction}</strong> · {degrees.toString().padStart(3,'0')}°</small>
 </div>;
}
function CountryMiniMap({region,items,position,heading=180,camera,waypoint,onOpen}){const [hidden,setHidden]=useState(false),[wide,setWide]=useState(region==='hub'),field=useMemo(()=>createTerrainField(region,blankSave()),[region]);const size=wide?(region==='hub'?134:78):46;return <aside className={'world-minimap'+(hidden?' collapsed':'')} aria-label="Mini-carte du monde"><div className="minimap-heading"><span>N ↑</span><button onClick={()=>setHidden(h=>!h)} aria-label={hidden?'Afficher la mini-carte':'Masquer la mini-carte'}>{hidden?'Carte':'−'}</button></div>{!hidden&&<><button className="minimap-open" onClick={onOpen} aria-label="Ouvrir la grande carte"><svg viewBox={`${-size} ${-size} ${size*2} ${size*2}`} aria-hidden="true"><g transform={`translate(${-position.x} ${-position.z})`}><RealmMapGround region={region} field={field}/>{items.filter(mapVisible).map(i=><g key={i.id} transform={`translate(${i.x} ${i.z}) scale(${Math.max(1,size/65)})`}><circle r="3.3" fill="#132526" stroke={i.done?'#90aa94':i.color} strokeWidth=".65"/><text textAnchor="middle" y="1.7" fontSize="5" fill={i.done?'#90aa94':'#fff2ca'}>{icon(i)}</text></g>)}{waypoint&&<><line x1={position.x} y1={position.z} x2={waypoint.x} y2={waypoint.z} stroke="#f5d293" strokeWidth=".65" strokeDasharray="1.7 2"/><circle cx={waypoint.x} cy={waypoint.z} r="4.3" fill="none" stroke="#f5d293"/></>}</g><g transform={`rotate(${compassHeading(camera?.yaw)}) scale(${size/46})`}><path d="M 0 0 L -15 -24 Q 0 -31 15 -24 Z" fill="#e9d8a620"/></g><g className="minimap-player" transform={`rotate(${heading}) scale(${size/46})`}><path d="M 0 -4.2 L 2.9 3 L 0 1.8 L -2.9 3 Z" fill="#fff1c7" stroke="#192e2b" strokeWidth=".7"/></g></svg></button><div className="minimap-footer"><span>{waypoint?Math.round(Math.hypot(waypoint.x-position.x,waypoint.z-position.z))+' m':'Explorer librement'}</span><button onClick={()=>setWide(v=>!v)} aria-label={wide?'Rapprocher la mini-carte':'Élargir la mini-carte'}>{wide?'+':'−'}</button></div></>}</aside>;}
const RealmMapGround=memo(function RealmMapGround({region,field}){
 const layout=useMemo(()=>({roads:realmRoads(region),sites:realmSites(region),buildings:realmBuildings(region)}),[region]);
 return <><MapGround field={field}/>{layout.roads.map(road=><polyline key={road.id} points={road.points.map(p=>p.x+','+p.z).join(' ')} fill="none" stroke="#b9aa7b" strokeWidth={road.width} strokeLinecap="round"/>)}{layout.sites.map(site=><circle key={site.id} cx={site.x} cy={site.z} r={site.r} fill="#87915c55" stroke="#d5c79933"/>)}{layout.buildings.map(building=><rect key={building.id} x={building.x-building.width/2} y={building.z-building.depth/2} width={building.width} height={building.depth} fill="#d5c29d" transform={'rotate('+(-building.rotation*180/Math.PI)+' '+building.x+' '+building.z+')'}/>)}</>;
});
function CountryDetailedMap({region='france',items,position,onSelect,route,waypoint,heading=180}){
 const field=useMemo(()=>createTerrainField(region,blankSave()),[region]),dimensions=realmDimensions(region),id=useId().replace(/:/g,''),drag=useRef(null);
 const [zoom,setZoom]=useState(0),[center,setCenter]=useState({x:0,z:0}),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const halfSpan=(dimensions?.radius||field.radius)*1.03/Math.pow(1.75,zoom),scale=Math.max(.7,halfSpan/250);
 const visible=items.filter(mapVisible).filter(item=>filter==='all'||filter==='missions'&&item.type==='campaignObjective'||filter==='relays'&&item.type==='realmTravel'||filter==='places'&&['realmSite','landmark','camp','story','atelier','sanctuary'].includes(item.type)).filter(item=>item.name?.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')));
 const destinations=[...visible].sort((a,b)=>Math.hypot(a.x-position.x,a.z-position.z)-Math.hypot(b.x-position.x,b.z-position.z));
 const startDrag=e=>{if(e.target.closest('[role="button"]'))return;drag.current={x:e.clientX,y:e.clientY,center};e.currentTarget.setPointerCapture?.(e.pointerId);};
 const moveDrag=e=>{if(!drag.current)return;const d=drag.current,rect=e.currentTarget.getBoundingClientRect(),unit=halfSpan*2/Math.min(rect.width,rect.height);setCenter({x:d.center.x-(e.clientX-d.x)*unit,z:d.center.z-(e.clientY-d.y)*unit});};
 const zoomBy=d=>setZoom(z=>Math.max(0,Math.min(6,z+d))),local=()=>{setCenter({...position});setZoom(5);},reset=()=>{setCenter({x:0,z:0});setZoom(0);};
 const keys=e=>{const direction={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(direction){e.preventDefault();setCenter(p=>({x:p.x+direction[0]*halfSpan*.2,z:p.z+direction[1]*halfSpan*.2}));}else if(e.key==='+'||e.key==='='){e.preventDefault();zoomBy(1);}else if(e.key==='-'){e.preventDefault();zoomBy(-1);}else if(e.key==='Home'){e.preventDefault();reset();}};
 return <section className="play-map cartography-map hub-cartography realm-cartography" aria-label="Atlas du royaume">
  <header className="hub-map-toolbar"><div><small>{REGIONS[region]?.city} · {Math.round(dimensions?.area/1000000)} km²</small><h3>Le royaume et ses provinces</h3></div><div className="hub-map-zoom"><Button variant="ghost" onClick={()=>zoomBy(-1)} disabled={!zoom} aria-label="Élargir la carte">−</Button><Button variant="ghost" onClick={()=>zoomBy(1)} disabled={zoom===6} aria-label="Rapprocher la carte">+</Button><Button variant="ghost" onClick={local}>Autour de moi</Button><Button variant="ghost" onClick={reset}>Tout le royaume</Button></div></header>
  <div className="hub-map-layout"><div className="hub-map-viewport"><svg viewBox={[-halfSpan,-halfSpan,halfSpan*2,halfSpan*2].join(' ')} role="group" tabIndex={0} aria-label="Carte du royaume : flèches pour déplacer la vue, plus et moins pour zoomer" onKeyDown={keys} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
   <g transform={'translate('+(-center.x)+' '+(-center.z)+')'}><RealmMapGround region={region} field={field}/>{visible.map(item=><g key={item.id} transform={'translate('+item.x+' '+item.z+') scale('+scale+')'} role="button" tabIndex={0} aria-label={'Placer un repère : '+item.name} onClick={()=>onSelect(item)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(item);}}}><circle r="6" fill="#102625" stroke={item.done?'#72997d':item.color||'#d6c18e'} strokeWidth="1"/><text y="2" textAnchor="middle" fill="#f2e5c8" fontSize="7">{icon(item)}</text><title>{item.name}</title></g>)}<MapRoute position={position} route={route} waypoint={waypoint} scale={scale}/><PlayerMarker position={position} heading={heading} scale={scale}/></g><MapScale halfSpan={halfSpan}/>
  </svg><p>↔ Relais · ! Étape du récit · ◆ Province et village · ♜ Gardien</p><small>Glisse pour explorer la carte. Les repères suivent les lieux jouables ; le guidage reste activable depuis le monde.</small></div>
  <aside className="hub-map-destinations"><label htmlFor={id+'search'}>Trouver un lieu</label><input id={id+'search'} type="search" placeholder="Province, village, mission…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="hub-map-filters">{[['all','Tous'],['missions','Récit'],['relays','Relais'],['places','Lieux']].map(([key,label])=><Button variant="ghost" key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</Button>)}</div><p className="hub-map-count">{destinations.length} repères</p><div className="hub-map-destination-list">{destinations.map(item=><Button variant="ghost" key={item.id} onClick={()=>onSelect(item)}><i>{icon(item)}</i><span><strong>{item.name}</strong><small>{item.type==='realmTravel'?'Relais des voyageurs':item.type==='campaignObjective'?'Récit en cours':'Lieu du royaume'}</small></span><em>{hubDistanceLabel(item,position)}</em></Button>)}{!destinations.length&&<p>Aucun lieu ne correspond à cette recherche.</p>}</div></aside></div>
 </section>;
}

const points=polygon=>polygon.map(p=>`${p.x},${p.z}`).join(' ');
const countryMapCode={france:'FR',italie:'IT',estonie:'EE',turquie:'TR',algerie:'DZ',tunisie:'TN',maroc:'MA',espagne:'ES'};
const mapSymbol=item=>item.type==='portal'?(countryMapCode[item.id]||'◇'):icon(item);
const markerName=hubItemLabel;
const districtShort={heritage_square:'PLACE DE L’HÉRITAGE',broken_circle_tower:'TOUR DU CERCLE BRISÉ',archives:'LES ARCHIVES DE LA MÉMOIRE',arena:'ARÈNE 3B',commerce:'QUARTIER COMMERCE',community:'QUARTIER COMMUNAUTÉ',innovation:'QUARTIER INNOVATION & IA',docks:'DOCKS & TRANSPORTS',city3b_portal:'PORTAIL VILLE 3B',gardens:'JARDINS DE L’UNITÉ'};
function wrappedLabel(value,max=17){const lines=[];for(const word of value.split(' ')){const last=lines.at(-1);if(last&&last.length+word.length+1<=max)lines[lines.length-1]+=' '+word;else lines.push(word);}return lines;}
function MapLabel({x,z,name,scale=1,className='hub-map-district-label'}){return <text x={x} y={z} textAnchor="middle" fontSize={5.8*scale} className={className}>{wrappedLabel(name).map((line,i)=><tspan key={i} x={x} dy={i?6.8*scale:0}>{line}</tspan>)}</text>;}
const HubMapGround=memo(function HubMapGround({model,id,close=false,level}){
 const poolColor='#42a8bd';
 return <g className="hub-map-ground">
  <defs><radialGradient id={id+'water'}><stop stopColor="#123d52"/><stop offset="1" stopColor="#061b2d"/></radialGradient><pattern id={id+'paving'} width="5.1" height="5.1" patternUnits="userSpaceOnUse"><path d="M 0 0 H 5.1 M 0 0 V 5.1" stroke="#263c465e" strokeWidth=".14"/></pattern><linearGradient id={id+'ramp'}><stop stopColor="#697e7b"/><stop offset="1" stopColor="#ecce8c"/></linearGradient></defs>
  <rect x={-model.extent*3} y={-model.extent*3} width={model.extent*6} height={model.extent*6} fill={`url(#${id}water)`}/>
  {model.features.map((feature,i)=>{const water=['lake','sea','bay','water'].includes(feature.kind),fill=water?mapArt.water:feature.kind==='reef'?mapArt.reef:mapArt.relief;return <g key={feature.id||i} data-landscape-id={feature.id}>{feature.outline?.length?<polygon points={points(feature.outline)} fill={fill} stroke={water?mapArt.waterEdge:mapArt.reliefEdge} strokeWidth=".55"/>:feature.r?<circle cx={feature.x} cy={feature.z} r={feature.r} fill={fill} stroke={mapArt.featureEdge} strokeWidth=".55"/>:Number.isFinite(feature.width)&&Number.isFinite(feature.depth)?<polygon points={points(mapStructureOutline(feature))} fill={fill} stroke={mapArt.featureEdge} strokeWidth=".45"/>:null}<title>{hubPlaceLabel(feature.name)||'Paysage de la cité'}</title></g>;})}
  {model.islands.map(island=><polygon key={island.id+'cliff'} points={points(island.outline)} transform="translate(0 2.5)" fill="#03111b" stroke="#06394a" strokeWidth="3.5"/>)}
  {model.islands.map(island=><polygon key={island.id} data-island-id={island.id} data-elevation={island.elevation} points={points(island.outline)} fill={island.elevation?mapArt.raisedPlatform:island.color} stroke={island.elevation?mapArt.raisedPlatformEdge:mapArt.platformEdge} strokeWidth={island.elevation?'.85':'.45'}><title>{island.elevation?`Plateforme · ${hubElevationLabel(island.elevation)}`:'Plateforme de la cité'}</title></polygon>)}
  {model.promenades.map(p=><circle key={p.id} r={(p.inner+p.outer)/2} fill="none" stroke="#a7a58f" strokeWidth={p.outer-p.inner}/>)}
  {[...model.bridges,...model.connectors].map(b=><polygon key={b.id} points={points(mapFootprint(b))} fill="#a3a993" stroke="#d8bf88" strokeWidth=".55"/>)}
  {model.connectors.filter(span=>span.startHeight!==span.endHeight).map(span=><g key={span.id+'slope'} data-ramp-id={span.id}><polygon points={points(mapFootprint(span))} fill={`url(#${id}ramp)`} stroke={mapArt.rampEdge} strokeWidth=".8"/><title>{`Rampe accessible · ${hubElevationLabel(span.startHeight,{signed:false})} à ${hubElevationLabel(span.endHeight,{signed:false})}`}</title></g>)}
  {model.avenues.map(b=><polygon key={b.id} points={points(mapFootprint(b))} fill="#748c89" stroke="#d3bc855c" strokeWidth=".32"/>)}
  {model.promenades.map(p=><g key={p.id+'edges'}><circle r={p.inner} fill="none" stroke="#dfc28b" strokeWidth=".32"/><circle r={p.outer} fill="none" stroke="#dfc28b" strokeWidth=".32"/></g>)}
  {close&&model.islands.map(island=><polygon key={island.id+'paving'} points={points(island.outline)} fill={`url(#${id}paving)`}/>)}
  {model.terraces.map(t=><g key={t.id}><polygon points={points(mapFootprint(t))} fill={`url(#${id}ramp)`} stroke="#f2d69e" strokeWidth=".8"/><path d={`M ${t.x-Math.cos(-t.rotation)*4} ${t.z-Math.sin(-t.rotation)*4} l ${Math.cos(-t.rotation)*8} ${Math.sin(-t.rotation)*8}`} stroke="#fff1c7" strokeWidth=".5"/><title>{`Belvédère · ${hubElevationLabel(t.rise)}`}</title></g>)}{/* gold-master-allow: unchanged atlas illustration; docs/hub-master-presentation.md#cartographic-materials */}
  {model.obstacles.filter(o=>o.enabled!==false&&o.r>5).map((o,i)=><circle key={'basin'+i} cx={o.x} cy={o.z} r={o.r} fill={poolColor} stroke="#bfdddf" strokeWidth=".65"/>)}
  {model.structures.map((s,i)=>s.r?<circle key={'structure'+i} cx={s.x} cy={s.z} r={s.r} fill={s.color||'#455c67'} stroke="#e2bd83" strokeWidth=".5"/>:<polygon key={'structure'+i} points={points(mapStructureOutline(s))} fill={s.color||(s.kind==='vessel'?'#acb7ad':'#405563')} stroke="#d1bb8c" strokeWidth=".5"><title>{s.name||'Architecture'}</title></polygon>)}
  {model.fabric.map((b,i)=><polygon key={'fabric'+i} points={points(mapFootprint({...b,rotation:b.rotation||0}))} fill="#334d5b" stroke="#d0b889" strokeWidth=".4"><title>{b.name||'Bâtiment du quartier'}</title></polygon>)}
  {model.vegetation.map((p,i)=><circle key={'tree'+i} cx={p.x} cy={p.z} r={p.r||Math.max(1.5,(p.scale||1)*3.7)} fill="#335f4c" stroke="#79a785" strokeWidth=".28"/>)}
  {model.buildings.map(b=><g key={b.id} data-building-id={b.buildingId}><polygon points={points(mapFootprint(b))} fill="#1f3545" stroke="#edd4a1" strokeWidth=".6"/><rect x={b.x-b.width/2+.8} y={b.z-b.depth/2+.8} width={b.width-1.6} height={b.depth-1.6} fill="#7d8d85" stroke="#a8b3a0" strokeWidth=".25"/>{b.walls.map((w,i)=><polygon key={i} points={points(mapFootprint(w))} fill="#183245"/>)}<path d={`M ${b.entrance.x-2.3} ${b.z+b.depth/2} H ${b.entrance.x+2.3}`} stroke="#73e6e2" strokeWidth="1.2"/><title>{b.name+' · entrée'}</title></g>)}
  {close&&model.obstacles.filter(o=>o.enabled!==false&&(!o.r||o.r<=5)).map((o,i)=>o.r?<circle key={'solid'+i} cx={o.x} cy={o.z} r={o.r} fill="#365665" opacity=".7"/>:<polygon key={'solid'+i} points={points(mapFootprint(o))} fill="#365665" opacity=".65"/>)}
  {level&&<g data-floor-id={level.id}><polygon points={points(mapFootprint(level))} fill="#8ba69a" stroke="#9ff6ea" strokeWidth=".8"/>{model.obstacles.filter(o=>o.enabled!==false&&o.id?.startsWith('tower-display')).map(o=><polygon key={o.id} points={points(mapFootprint(o))} fill="#345864" stroke="#d5bd8a" strokeWidth=".3"/>)}<title>{`${level.name} · ${hubElevationLabel(level.y)}`}</title></g>}{/* gold-master-allow: unchanged atlas illustration; docs/hub-master-presentation.md#cartographic-materials */}
 </g>;
});
function HubTransportNetworks({model,scale=1,visible=true}){
 if(!visible)return null;
 return <g className="hub-map-networks" pointerEvents="none">{model.transportRoutes.map(route=>{const style=HUB_TRANSPORT_MAP_STYLES[route.transport],line=route.closed&&route.points.length? [...route.points,route.points[0]]:route.points;return <g key={route.id||route.transport+':'+route.line} data-transport-route={route.id||route.line} data-transport-type={route.transport}><polyline points={points(line)} fill="none" stroke={mapArt.networkUnderlay} strokeWidth={(style.width+1.2)*scale} strokeLinecap="round" strokeLinejoin="round" opacity=".75"/><polyline points={points(line)} fill="none" stroke={style.color} strokeWidth={style.width*scale} strokeDasharray={style.dash?.split(' ').map(Number).map(value=>value*scale).join(' ')} strokeLinecap="round" strokeLinejoin="round" opacity=".9"/><title>{style.name+' · '+(route.line||route.id)}</title></g>;})}</g>;
}
function HubMapLegend({networks,onNetworks,model}){return <div className="hub-map-legend" aria-label="Légende de la carte"><div className="hub-map-legend-ground"><span><i className="deck"/>Esplanade</span><span><i className="bridge"/>Chemin / pont</span><span><i className="building"/>Bâtiment et entrée</span><span><i className="garden"/>Jardin</span><span><i className="water"/>Eau / cascades</span><span><i className="terrace"/>Belvédère +6 m</span><span><i className="landmark"/>Lieu de l’affiche</span></div>{model.transportRoutes.length>0&&<div className="hub-map-legend-networks"><Button variant="ghost" onClick={onNetworks} aria-pressed={networks}>{networks?'Masquer':'Afficher'} les réseaux</Button>{Object.entries(HUB_TRANSPORT_MAP_STYLES).filter(([transport])=>model.transportRoutes.some(route=>route.transport===transport)).map(([transport,style])=><span key={transport}><i className={'network '+transport} style={{'--network-color':style.color}}/>{style.name}</span>)}</div>}</div>;}
function PlayerMarker({position,heading=0,scale=1}){return <g transform={`translate(${position.x} ${position.z})`} className="hub-map-player"><circle r={6*scale} fill="#092438" stroke="#d9fffb" strokeWidth={scale*.7}/><g transform={`rotate(${heading}) scale(${scale})`}><path d="M 0 -5 L 3.5 3.2 L 0 1.6 L -3.5 3.2 Z" fill="#efffff"/></g><title>Ta position</title></g>;}
function MapRoute({position,route,waypoint,scale=1}){
 const path=hubMapRoute(position,route);
 /* gold-master-allow: unchanged atlas illustration; docs/hub-master-presentation.md#cartographic-materials */ return <g className="hub-map-route">{path.length>1&&<><polyline points={points(path)} fill="none" stroke="#14293c" strokeWidth={3*scale} strokeLinejoin="round"/><polyline points={points(path)} fill="none" stroke="#f9da99" strokeWidth={1.3*scale} strokeLinejoin="round" strokeDasharray={`${3*scale} ${2*scale}`}/></>}{waypoint&&<g transform={`translate(${waypoint.x} ${waypoint.z})`}><circle r={6.5*scale} fill="none" stroke="#f9da99" strokeWidth={scale}/><path d={`M ${-2.8*scale} ${-2.8*scale} l ${5.6*scale} 0 l ${-2.8*scale} ${5.6*scale} Z`} fill="#f9da99"/><title>{markerName(waypoint)}</title></g>}</g>;
}
function MapMarker({item,scale=1,onSelect,label=false}){
 const action=e=>{e.stopPropagation();onSelect?.(item);};
 return <g transform={`translate(${item.x} ${item.z})`} className={'hub-map-marker '+hubMapCategory(item)} data-destination-id={item.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?'Placer un repère : '+markerName(item):undefined} onClick={onSelect?action:undefined} onKeyDown={onSelect?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action(e);}}:undefined}>
  {onSelect&&<circle r={18*scale} fill="transparent"/>}<circle r={5.4*scale} fill={item.kind==='landmark'?mapArt.landmarkMarker:mapArt.marker} stroke={item.done?mapArt.markerDone:item.color||mapArt.markerEdge} strokeWidth={.85*scale}/><text textAnchor="middle" y={2*scale} fontSize={7*scale} fill={mapArt.markerText}>{item.kind==='landmark'?'◆':mapSymbol(item)}</text>{label&&<text x={8*scale} y={2*scale} fontSize={5.7*scale} className="hub-map-place-label">{markerName(item)}</text>}<title>{markerName(item)}</title>
 </g>;
}
function MapScale({halfSpan,id}){const {distance,label}=hubMapScale(halfSpan*2),x=-halfSpan+halfSpan*.12,y=halfSpan-halfSpan*.12;return <g className="hub-map-scale" pointerEvents="none"><path d={`M ${x} ${y-halfSpan*.02} V ${y} H ${x+distance} V ${y-halfSpan*.02}`} fill="none" stroke="#eff5e6" strokeWidth={halfSpan*.007}/><text x={x} y={y-halfSpan*.045} fill="#eff5e6" fontSize={halfSpan*.065}>{label}</text><text x={halfSpan-halfSpan*.15} y={-halfSpan+halfSpan*.17} textAnchor="middle" fill="#eff5e6" fontSize={halfSpan*.09}>N</text><path d={`M ${halfSpan-halfSpan*.15} ${-halfSpan+halfSpan*.22} v ${-halfSpan*.065}`} stroke="#f6d49c" strokeWidth={halfSpan*.01}/></g>;}
function HubMiniMap({items,position,heading=180,camera,waypoint,onOpen,cartography,route,level}){
 const [hidden,setHidden]=useState(false),[zoom,setZoom]=useState(1),id=useId().replace(/:/g,''),model=useMemo(()=>createHubCartography([],cartography),[cartography]);
 const halfSpan=[65,130,model.extent][zoom],full=zoom===2,center=full?{x:0,z:0}:position,scale=halfSpan/80,markers=hubMiniMapMarkers(items,center,halfSpan,waypoint),elevation=level?.y??hubMapElevation(position);
 return <aside className={'world-minimap hub-minimap'+(hidden?' collapsed':'')} aria-label="Mini-carte de la Cité des Huit Héritages">
  <div className="minimap-heading"><span>CITÉ 3B</span><Button variant="ghost" onClick={()=>setHidden(v=>!v)} aria-label={hidden?'Afficher la mini-carte':'Masquer la mini-carte'} aria-expanded={!hidden}>{hidden?'Carte':'−'}</Button></div>
  {!hidden&&<><Button variant="ghost" className="minimap-open" onClick={onOpen} aria-label="Ouvrir et explorer la grande carte de la cité"><svg viewBox={`${-halfSpan} ${-halfSpan} ${halfSpan*2} ${halfSpan*2}`} aria-hidden="true"><g transform={`translate(${-center.x} ${-center.z})`}><HubMapGround model={model} id={id} close={zoom===0} level={level}/>{!level&&<HubTransportNetworks model={model} scale={scale*.6}/>} {markers.map(item=><MapMarker key={item.id} item={item} scale={scale}/>)}<MapRoute position={position} route={route} waypoint={waypoint} scale={scale}/><g transform={`translate(${position.x} ${position.z}) rotate(${compassHeading(camera?.yaw)}) scale(${scale})`}><path d="M 0 0 L -15 -24 Q 0 -31 15 -24 Z" fill={mapArt.cameraCone}/></g><PlayerMarker position={position} heading={heading} scale={scale}/></g><MapScale halfSpan={halfSpan}/></svg></Button>
  <div className="minimap-footer"><Button variant="ghost" disabled={zoom===0} onClick={()=>setZoom(v=>Math.max(0,v-1))} aria-label="Rapprocher la mini-carte">+</Button><span>{elevation>0?hubElevationLabel(elevation):full?'Toute la cité':zoom===0?'À proximité':'Quartier'}</span><Button variant="ghost" disabled={zoom===2} onClick={()=>setZoom(v=>Math.min(2,v+1))} aria-label="Élargir la mini-carte">−</Button></div></>}
 </aside>;
}
function HubDetailedMap({items,position,onSelect,cartography,route,waypoint,heading=0,level}){
 const model=useMemo(()=>createHubCartography([],cartography),[cartography]),id=useId().replace(/:/g,''),[zoom,setZoom]=useState(0),[center,setCenter]=useState({x:0,z:0}),[category,setCategory]=useState('all'),[query,setQuery]=useState(''),[networks,setNetworks]=useState(true),drag=useRef(null),fingers=useRef(new Map()),pinch=useRef(null);
 const halfSpan=model.extent/Math.pow(1.7,zoom),scale=halfSpan/250,destinations=useMemo(()=>hubMapDestinations(items,{category}).filter(item=>hubSearchMatches(item,query)),[items,category,query]);
 const atlasMarkers=hubAtlasMapMarkers(destinations,halfSpan);
 const sorted=[...destinations].sort((a,b)=>Math.hypot(a.x-position.x,a.z-position.z)-Math.hypot(b.x-position.x,b.z-position.z));
 const startDrag=e=>{
  if(e.target.closest('[role="button"]'))return;
  fingers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});
  e.currentTarget.setPointerCapture?.(e.pointerId);
  if(fingers.current.size===2){
   const [a,b]=[...fingers.current.values()];
   pinch.current={distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),zoom};
   drag.current=null;
  }else if(fingers.current.size===1)drag.current={x:e.clientX,y:e.clientY,center};
 };
 const moveDrag=e=>{
  if(!fingers.current.has(e.pointerId))return;
  fingers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});
  if(fingers.current.size>=2&&pinch.current){
   const [a,b]=[...fingers.current.values()];
   const distance=Math.max(1,Math.hypot(a.x-b.x,a.y-b.y));
   setZoom(Math.max(0,Math.min(4,pinch.current.zoom+Math.log(distance/pinch.current.distance)/Math.log(1.7))));
   return;
  }
  const d=drag.current;if(!d)return;
  const rect=e.currentTarget.getBoundingClientRect(),unit=halfSpan*2/Math.min(rect.width,rect.height);
  setCenter({x:d.center.x-(e.clientX-d.x)*unit,z:d.center.z-(e.clientY-d.y)*unit});
 };
 const stopDrag=e=>{fingers.current.delete(e.pointerId);if(fingers.current.size<2)pinch.current=null;drag.current=null;};
 const changeZoom=delta=>setZoom(z=>Math.max(0,Math.min(4,z+delta)));
 const reset=()=>{setZoom(0);setCenter({x:0,z:0});};
 const moveKeyboard=e=>{const shifts={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},d=shifts[e.key];if(d){e.preventDefault();setCenter(p=>({x:p.x+d[0]*halfSpan*.2,z:p.z+d[1]*halfSpan*.2}));}else if(e.key==='+'||e.key==='='){e.preventDefault();changeZoom(1);}else if(e.key==='-'){e.preventDefault();changeZoom(-1);}else if(e.key==='Home'){e.preventDefault();reset();}};
 return <section className="play-map cartography-map hub-cartography" aria-label="Atlas de la cité">
  <header className="hub-map-toolbar"><div><small>LA CITÉ DES HUIT HÉRITAGES</small><h3>Repérer un lieu dans la Cité</h3></div><div className="hub-map-zoom"><Button variant="ghost" onClick={()=>changeZoom(-1)} disabled={zoom===0} aria-label="Élargir la carte">−</Button><Button variant="ghost" onClick={()=>changeZoom(1)} disabled={zoom===4} aria-label="Rapprocher la carte">+</Button><Button variant="ghost" onClick={()=>{setCenter({...position});setZoom(z=>Math.max(z,2));}} aria-label="Centrer sur mon personnage">◎</Button><Button variant="ghost" onClick={reset}>Vue d’ensemble</Button><label className="hub-map-zoom-slider">Zoom <input aria-label="Zoom de l’Atlas" type="range" min="0" max="4" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div></header>
  <div className="hub-map-layout"><div className="hub-map-viewport">{level&&<p className="hub-map-level">{level.name} · {hubElevationLabel(level.y)}</p>}<svg viewBox={`${-halfSpan} ${-halfSpan} ${halfSpan*2} ${halfSpan*2}`} role="group" tabIndex={0} aria-label="Carte de la cité : flèches pour déplacer la vue, plus et moins pour zoomer, Début pour la vue d’ensemble" onKeyDown={moveKeyboard} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={stopDrag} onPointerCancel={stopDrag}>
   <g transform={`translate(${-center.x} ${-center.z})`}><HubMapGround model={model} id={id} close={zoom>=2} level={level}/>{!level&&<HubTransportNetworks model={model} scale={scale} visible={networks}/>} {model.districts.map(d=><MapLabel key={d.id} x={d.x} z={d.z+19} name={districtShort[d.id]} scale={Math.max(.8,scale)}/>)}{!level&&zoom<3&&model.landmarks.map(site=><MapLabel key={site.id} x={site.x} z={site.z+12*scale} name={hubPlaceLabel(site.name)+(site.elevation?' · '+hubElevationLabel(site.elevation):'')} scale={scale} className="hub-map-landmark-label"/>)}{atlasMarkers.map(item=><MapMarker key={item.id} item={item} onSelect={onSelect} scale={scale} label={zoom>=3}/>)}<MapRoute position={position} route={route} waypoint={waypoint} scale={scale}/><PlayerMarker position={position} heading={heading} scale={scale}/></g><MapScale halfSpan={halfSpan}/>
  </svg><HubMapLegend model={model} networks={networks} onNetworks={()=>setNetworks(value=>!value)}/><small>Un doigt pour déplacer · pince à deux doigts ou utilise le curseur Zoom. Glisse en dehors de la carte pour défiler le menu. Choisir un lieu place un repère ; active ensuite le guidage depuis le monde. Les distances sont à vol d’oiseau ; le trajet suit les chemins à pied.</small></div>
  <aside className="hub-map-destinations"><label htmlFor={id+'search'}>Trouver un lieu</label><input id={id+'search'} type="search" placeholder="Archives, lac, souks, train…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="hub-map-filters" aria-label="Types de destinations">{[['all','Tous'],['places','Lieux'],['services','Services'],['travel','Transports'],['story','Missions'],['life','Habitants']].map(([key,label])=><Button variant="ghost" key={key} aria-pressed={category===key} onClick={()=>setCategory(key)}>{label}</Button>)}</div><p className="hub-map-count" role="status">{destinations.length} {destinations.length===1?'repère':'repères'}{waypoint?' · Repère : '+markerName(waypoint):''}</p>{waypoint&&<Button variant="ghost" aria-label={'Localiser sur la carte : '+markerName(waypoint)} onClick={()=>{setCenter({x:waypoint.x,z:waypoint.z});setZoom(z=>Math.max(z,2));}}>Localiser mon repère</Button>}<div className="hub-map-destination-list">{sorted.map(item=><Button variant="ghost" key={item.id} data-destination-id={item.id} aria-label={'Placer un repère : '+markerName(item)+' · '+hubDistanceLabel(item,position)+' à vol d’oiseau'} onClick={()=>onSelect(item)}><i style={{'--map-accent':item.color||mapArt.destinationAccent}}>{item.kind==='landmark'?'◆':icon(item)}</i><span><strong>{markerName(item)}</strong><small>{item.activity||districtShort[item.district]|| (item.type==='portal'?'PORTE DES HÉRITAGES':'CITÉ 3B')}</small></span><em title="Distance à vol d’oiseau">{hubDistanceLabel(item,position)}</em></Button>)}{!sorted.length&&<div><p>Aucun repère ne correspond à cette recherche et à ce filtre.</p><Button variant="ghost" onClick={()=>{setQuery('');setCategory('all');}}>Afficher tous les repères</Button></div>}</div></aside></div>
 </section>;
}
export function MiniMap(props){return props.region==='hub'?<HubMiniMap {...props}/>:<CountryMiniMap {...props}/>;}
export function DetailedMap(props){return (props.region||'hub')==='hub'?<HubDetailedMap {...props}/>:<CountryDetailedMap {...props}/>;}
