import {CARDS,COUNTRIES,cardById,cardSlot} from './catalog.js';

// Chapter mechanics are shared by the browser and the authenticated game engine.
export const CHAPTERS={
 france:{title:'Les noms effacés',resident:'Léa, relieuse de souvenirs',need:'Les enseignes ont perdu leurs noms. Aide-moi à retrouver l’ordre de notre histoire.',help:'Rassembler les pages tombées',kind:'sequence',symbols:['✦','❧','⌂','☀'],answer:[0,1,2,3],hint:'Une étincelle réveille une graine. La graine abrite une maison. La maison accueille le soleil.',puzzle:'Le livre de la place',instruction:'Touche les quatre symboles dans l’ordre du récit.',restores:['La rue des ateliers','Le jardin des noms','La bibliothèque vivante'],ending:'Les habitants racontent à nouveau leur histoire. Léa ouvre une bibliothèque au Nexus.',pattern:['frappe','rempart','rituel','percée'],guardian:'Son rempart réduit les frappes. Garde ta concentration pour le rituel.'},
 italie:{title:'Les jardins suspendus',resident:'Elio, jardinier des terrasses',need:'Les terrasses ne communiquent plus. Les graines attendent de retrouver leur chemin.',help:'Porter les semences au jardin',kind:'path',answer:[0,3,4,7,8],hint:'Pars en haut à gauche. Évite les dalles fissurées, puis rejoins le jardin en bas à droite.',blocked:[1,2,5,6],puzzle:'Le passage des terrasses',instruction:'Trace un chemin de cases voisines, sans diagonale. Retouche la dernière case pour revenir.',restores:['Le pont des semences','Les terrasses fertiles','La serre des vérités'],ending:'Les ponts se couvrent de plantes. Elio rapporte ses premières pousses au Nexus.',pattern:['rempart','frappe','rituel','soin'],guardian:'Le loup se régénère après le rituel. Prépare ton pouvoir avant ce soin.'},
 estonie:{title:'La piste des aurores',resident:'Mira, veilleuse des pins',need:'La forêt a oublié ses sentiers. Seule la lumière des aurores peut les dessiner.',help:'Rallumer la lanterne de Mira',kind:'lights',initial:[1,0,0,0,1],answer:[1,1,1,1,1],hint:'Chaque rune inverse sa lumière et celle de ses voisines. Une seule rune suffit ici : celle du milieu.',puzzle:'Les cinq lumières',instruction:'Allume les cinq runes. Toucher une rune inverse aussi les deux voisines.',restores:['La clairière des lanternes','Le sentier boréal','Le refuge des pins'],ending:'Une aurore relie les clairières. Mira installe ses lanternes au Nexus.',pattern:['gel','rituel','frappe','percée'],guardian:'Le gel ralentit la concentration. Une garde l’annule avant la riposte suivante.'},
 turquie:{title:'Le ciel partagé',resident:'Deniz, cartographe du ciel',need:'Nos trois astrolabes regardent des ciels différents. Aidons-les à retrouver une même constellation.',help:'Récupérer les lentilles de Deniz',kind:'rotate',initial:[2,3,0],answer:[0,1,2],hint:'Le premier astrolabe regarde le nord, le deuxième l’est, le troisième le sud.',puzzle:'Les astrolabes de l’Union',instruction:'Tourne chaque astrolabe d’un quart de tour. Aligne-les sur la carte du ciel.',restores:['La galerie des étoiles','Le pont des deux rives','L’observatoire de l’Union'],ending:'Les trois astrolabes pointent vers la même étoile. Deniz ouvre une carte du ciel au Nexus.',pattern:['frappe','éclipse','rituel','double'],guardian:'L’éclipse cache sa force : garde, puis profite du rituel. Sa double frappe arrive ensuite.'},
 algerie:{title:'L’eau se souvient',resident:'Amel, gardienne de l’oasis',need:'L’eau s’arrête avant les jardins. Réoriente les canaux, la mémoire suivra leur courant.',help:'Dégager la source ensablée',kind:'pipes',initial:[0,0,0,0],answer:[2,1,0,3],hint:'L’eau entre à gauche en haut. Fais-la descendre, traverser le bassin du bas, puis remonter vers la sortie à droite.',puzzle:'Les canaux de la mémoire',instruction:'Tourne les quatre coudes pour relier la source au jardin. L’eau bleue indique le chemin déjà connecté.',restores:['Le canal des sources','Le jardin de l’oasis','La maison de la mémoire'],ending:'L’eau atteint les palmiers. Amel fait naître une petite oasis au Nexus.',pattern:['sable','frappe','rituel','soin'],guardian:'Le sable renforce la prochaine frappe. Une garde protège ton équipe ; le rituel ouvre une brèche.'},
 tunisie:{title:'Ce que la mer rend',resident:'Nour, passeuse des rivages',need:'La mer cache les marches de Carthage. Trouve un rythme qui laisse passer tout le monde.',help:'Ramener une voile échouée',kind:'tide',initial:[0,0,0],answer:[2,1,3],hint:'La première écluse doit être deux crans plus haute que le départ. La suivante descend d’un cran. La dernière remonte de deux.',puzzle:'Les écluses du rivage',instruction:'Règle les trois hauteurs de 0 à 3. Le passage s’ouvre quand elles suivent le relief.',restores:['L’escalier des marées','Le port des retrouvailles','La cour de Carthage'],ending:'Les marches émergent. Nour ramène au Nexus une voile que tous peuvent signer.',pattern:['vague','rituel','rempart','percée'],guardian:'La vague est puissante mais la garde la dissipe. Attaque lorsque le croissant entre en rituel.'},
 maroc:{title:'Le souffle des cimes',resident:'Yanis, artisan des vents',need:'Le vent emporte les messages entre les villages. Rééquilibre les trois cloches de l’Atlas.',help:'Attacher les rubans voyageurs',kind:'balance',initial:[0,0,0],answer:[1,2,3],hint:'Six poids au total. La deuxième cloche en porte un de plus que la première ; la troisième un de plus que la deuxième.',puzzle:'Les cloches de l’Atlas',instruction:'Répartis les poids entre les trois cloches. Le vent doit produire trois notes ascendantes.',restores:['La route des rubans','Le jardin des artisans','La halle des cimes'],ending:'Les cloches portent les messages de vallée en vallée. Yanis rejoint les artisans du Nexus.',pattern:['rempart','double','rituel','frappe'],guardian:'Le lion prépare deux frappes. La garde ou un piège les absorbe, puis son rituel le découvre.'},
 espagne:{title:'La dernière rotation',resident:'Inès, mécanicienne des falaises',need:'Les moulins tournent chacun à leur rythme. Accorde leurs engrenages pour rallumer le phare.',help:'Retrouver une dent d’engrenage',kind:'gears',initial:[0,0,0],answer:[1,2,3],hint:'Une rotation fait avancer la roue touchée et sa voisine de droite. Solution possible : gauche une fois, milieu une fois, droite deux fois.',puzzle:'Les engrenages du phare',instruction:'Chaque roue entraîne aussi sa voisine de droite. Place les aiguilles sur 1, 2 et 3.',restores:['L’allée des moulins','L’atelier des falaises','Le phare du crépuscule'],ending:'Le phare éclaire les huit horizons. Inès construit un moulin miniature au Nexus.',pattern:['percée','rempart','rituel','double'],guardian:'La charge traverse la garde en partie. Un piège l’arrête ; économise le pouvoir pour le rituel.'},
};
export const chapterCards=region=>({
 ally:CARDS.find(c=>c.country===region&&c.category==='Personnage classique'&&c.number%20===2)?.id,
 terrain:CARDS.find(c=>c.country===region&&cardSlot(c)==='terrain')?.id,
 ambiance:CARDS.find(c=>c.country===region&&cardSlot(c)==='ambiance')?.id,
});
export function chapterState(save,region){return save.adventure?.chapters?.[region]||{helped:false,powers:[],solved:false,restored:0,challenge:false,choice:null};}
export const restoredCountries=save=>COUNTRIES.filter(c=>chapterState(save,c.id).restored===3);
export const nexusLevel=save=>restoredCountries(save).length;
export function chapterObjective(save,region=save.region){
 if(region==='hub'){const n=nexusLevel(save);return n===8?{title:save.adventure?.finished?'L’Union est vivante':'Affronter l’Oubli',detail:save.adventure?.finished?'Explore les défis des gardiens et complète ton Codex.':'Les huit pays sont reconstruits. Le dernier passage est ouvert.',target:'final',reward:'Épilogue · tenue Union'}:{title:`${n} / 8 pays reconstruits`,detail:'Traverse une porte, aide un habitant et rends vie à son pays.',target:COUNTRIES.find(c=>chapterState(save,c.id).restored<3)?.id,reward:'Un nouveau quartier au Nexus'};}
 const c=CHAPTERS[region],s=chapterState(save,region);
 if(!s.helped)return{title:'Rencontrer '+c.resident.split(',')[0],detail:c.need,target:region+':story',reward:'Un Allié + Terrain + Ambiance · 80 XP'};
 if(s.powers.length<3)return{title:'Faire résonner tes cartes',detail:'Au monument : Allié → Ambiance → Terrain. Les cartes du chapitre sont prêtées pour ces actions.',target:region+':story',reward:'Un passage visible · 60 XP'};
 if(!s.solved)return{title:c.puzzle,detail:c.instruction,target:region+':story',reward:c.restores[0]+' · 120 XP'};
 const missing=[0,1,2].find(i=>!save.beacons.includes(region+':'+i));
 if(missing!==undefined)return{title:'Retrouver les souvenirs',detail:'Les fragments alimentent la reconstruction du quartier.',target:region+':'+missing,reward:'45 XP · 15 éclats · équipement'};
 if(s.restored<2)return{title:'Reconstruire '+c.restores[1],detail:'Les trois souvenirs ont retrouvé leur place. Choisis le futur du quartier.',target:region+':story',reward:'140 XP · 40 éclats'};
 if(!save.seals.includes(region))return{title:'Libérer le gardien',detail:c.guardian,target:region+':guardian',reward:'Sceau · carte unique · 250 XP'};
 if(s.restored<3)return{title:'Inaugurer '+c.restores[2],detail:'Le gardien reconnaît tes liens. Le pays peut maintenant rejoindre le Nexus.',target:region+':story',reward:'200 XP · 70 éclats · tenue régionale'};
 return{title:'Un pays retrouvé',detail:c.ending,target:region+':guardian',reward:s.challenge?'Défi maîtrisé · collection libre':'Défi expert optionnel · 180 XP'};
}
export function puzzleStart(region){const c=CHAPTERS[region];return [...(c.initial||[])];}
export function puzzleStep(region,board,index){
 const c=CHAPTERS[region];if(!c||!Number.isInteger(index)||index<0||index>8)return board;
 const b=[...board];
 if(c.kind==='sequence'){if(index>3)return b;return b.length>=4?[index]:[...b,index];}
 if(c.kind==='path'){if(c.blocked.includes(index))return b;if(b.at(-1)===index)return b.slice(0,-1);if(!b.length)return index===0?[0]:[];const last=b.at(-1);return !b.includes(index)&&Math.abs(last%3-index%3)+Math.abs(Math.floor(last/3)-Math.floor(index/3))===1?[...b,index]:b;}
 if(index>=b.length)return b;
 if(c.kind==='lights'){for(const i of [index-1,index,index+1])if(i>=0&&i<b.length)b[i]=1-b[i];}
 else {b[index]=(b[index]+1)%4;if(c.kind==='gears'&&index<2)b[index+1]=(b[index+1]+1)%4;}
 return b;
}
export function waterFlow(board){
 const visited=[];let cell=0,input=3;
 for(let i=0;i<4;i++){
  const turn=board[cell],ports=[turn,(turn+1)%4];if(!ports.includes(input)||visited.includes(cell))return{visited,complete:false};visited.push(cell);
  const output=ports.find(p=>p!==input);if(cell===1&&output===1)return{visited,complete:visited.length===4};
  const x=cell%2+[0,1,0,-1][output],y=Math.floor(cell/2)+[-1,0,1,0][output];if(x<0||x>1||y<0||y>1)return{visited,complete:false};cell=y*2+x;input=(output+2)%4;
 }return{visited,complete:false};
}
export const puzzleSolved=(region,board)=>region==='algerie'?waterFlow(board).complete:!!CHAPTERS[region]&&JSON.stringify(board)===JSON.stringify(CHAPTERS[region].answer);
export function explorationTrait(card){
 if(card.character)return card.trait+' Exploration : révèle les traces du monument avec un Allié du pays.';
 return card.trait+({terrain:' Exploration : matérialise le passage après lecture de l’indice.',ambiance:' Exploration : révèle le sens des traces découvertes.',fragment:' Reconstruction : les souvenirs retrouvés alimentent les quartiers.',pierre:' Reconstruction : ancre la lumière dans les monuments.'}[cardSlot(card)]||'');
}
export const COSMETICS=[{id:'voyageur',name:'Voyageur · or',color:'#e4c778',need:0},{id:'france',name:'Mémoire · azur',color:'#7bbdff',need:'france'},{id:'italie',name:'Jardins · émeraude',color:'#95e4b6',need:'italie'},{id:'estonie',name:'Aurore · argent',color:'#b6ecff',need:'estonie'},{id:'turquie',name:'Union · améthyste',color:'#e9a4e8',need:'turquie'},{id:'algerie',name:'Oasis · jade',color:'#b8dda2',need:'algerie'},{id:'tunisie',name:'Rivage · corail',color:'#ffb3a4',need:'tunisie'},{id:'maroc',name:'Atlas · cuivre',color:'#f7c77e',need:'maroc'},{id:'espagne',name:'Crépuscule · rubis',color:'#ff9e86',need:'espagne'},{id:'union',name:'Union · lumière',color:'#fff4cf',need:'final'}];
export const cosmeticUnlocked=(save,c)=>c.need===0||(c.need==='final'?save.adventure?.finished:chapterState(save,c.need).restored===3);
