const DATA={
 france:{vehicles:['Coupé Tricolore','Navette Hexagone','Moto Verrière','Rail Justice','Drone Atelier'],companions:['Faucon Justice','Chien des Verrières','Lynx Mémoire','Corbeau Relieur','Gardien Bleu'],weapons:['Lame Lumière','Bâton Justice','Arc Verrière','Bouclier Mémoire','Lance Hexagone'],skins:['Relieur Matrix','Ouvrier Héritage','Verrière Nocturne','Justice Or','Métro Bleu'],decor:['Horloge lumière','Banc verrière','Plaque mémoire','Réverbère Matrix','Fontaine atelier']},
 algerie:{vehicles:['Roadster Sahara','Navette Casbah','Moto Plateaux','Rail Oasis','Drone Source'],companions:['Fennec Loyauté','Aigle des Plateaux','Chacal Oasis','Cheval Sahara','Gardien Vert'],weapons:['Lame des Sources','Bâton Loyauté','Arc Casbah','Bouclier Oasis','Lance Sahara'],skins:['Casbah Matrix','Oasis Blanche','Plateaux Cuivre','Loyauté Verte','Sahara Nuit'],decor:['Fontaine source','Lanterne cuivre','Arc blanc','Palmier lumière','Mosaïque oasis']},
 maroc:{vehicles:['Coupé Atlas','Navette Médina','Moto Zellige','Rail Riad','Drone Souk'],companions:['Lion Noblesse','Faucon Atlas','Cheval Riad','Lynx Zellige','Gardien Or'],weapons:['Lame Atlas','Bâton Noblesse','Arc Zellige','Bouclier Riad','Lance Lion'],skins:['Riad Matrix','Atlas Or','Souk Nocturne','Noblesse Ocre','Zellige Bleu'],decor:['Fontaine zellige','Lanterne dorée','Porte riad','Ruban Atlas','Jardin orange']},
 tunisie:{vehicles:['Coupé Carthage','Navette du Golfe','Moto Bleue','Rail Rivage','Drone Phare'],companions:['Faucon Courage','Cheval Carthage','Chat Bleu','Loup Rivage','Gardien Rouge'],weapons:['Lame Carthage','Bâton Courage','Arc Rivage','Bouclier Bleu','Lance Phare'],skins:['Carthage Matrix','Sidi Bleu','Olivier Or','Courage Rouge','Rivage Blanc'],decor:['Porte bleue','Mosaïque Carthage','Olivier lumière','Fontaine marine','Lampe rivage']},
 turquie:{vehicles:['Coupé Bosphore','Navette Crescent','Moto Astrolabe','Rail Deux Rives','Drone Dôme'],companions:['Loup Foi','Faucon Bosphore','Cheval Cappadoce','Chat Bazar','Gardien Lune'],weapons:['Lame Astrolabe','Bâton Foi','Arc Crescent','Bouclier Dôme','Lance Bosphore'],skins:['Bosphore Matrix','Cappadoce Cuivre','Foi Lune','Bazar Nuit','Deux Rives Or'],decor:['Lanterne étoilée','Dôme miniature','Astrolabe','Fontaine lune','Tapis lumière']},
 espagne:{vehicles:['Coupé Sol','Navette Passion','Moto Azulejo','Rail Andalousie','Drone Phare'],companions:['Taureau Passion','Faucon Sol','Cheval Andalou','Lynx Crépuscule','Gardien Rouge-Or'],weapons:['Lame Sol','Bâton Passion','Arc Azulejo','Bouclier Phare','Lance Crépuscule'],skins:['Patio Matrix','Sol Or','Andalousie Rouge','Passion Nuit','Azulejo Bleu'],decor:['Fontaine solaire','Patio lumière','Azulejo cinétique','Moulin miniature','Olivier rouge']},
 italie:{vehicles:['Coupé Infinito','Navette Toscana','Moto Loggia','Rail Renaissance','Drone Dôme'],companions:['Lévrier Espoir','Faucon Toscana','Loup Marbre','Chat Loggia','Gardien Émeraude'],weapons:['Lame Infinito','Bâton Espoir','Arc Loggia','Bouclier Marbre','Lance Renaissance'],skins:['Loggia Matrix','Marbre Or','Toscana Verte','Espoir Blanc','Renaissance Nuit'],decor:['Fontaine marbre','Pergola lumineuse','Colonne cinétique','Vigne or','Dôme miniature']},
 estonie:{vehicles:['Coupé Boréal','Navette Baltique','Moto Aurore','Rail Tallinn','Drone Nord'],companions:['Loup Sagesse','Hibou Boréal','Renard Nord','Chien Baltique','Gardien Argent'],weapons:['Lame Boréale','Bâton Sagesse','Arc Aurore','Bouclier Nord','Lance Baltique'],skins:['Aurore Matrix','Nord Argent','Tallinn Nuit','Sagesse Glace','Baltique Bleu'],decor:['Cristal aurore','Borne lumière','Banc nordique','Rune digitale','Pin argent']}
};
export const COLLECTIBLE_KITS=Object.fromEntries(Object.entries(DATA).map(([country,groups])=>[country,Object.fromEntries(Object.entries(groups).map(([family,names])=>[family,names.map((name,index)=>({id:`${country}-${family}-${index+1}`,country,family,name,tier:index+1}))]))]));
export function collectibles(country,family){return COLLECTIBLE_KITS[country]?.[family]||[];}
