import {COMBAT_TICK} from './field-combat.js';

// One deliberate press can bridge the last part of recovery. No repeated
// attacks, simulated ticks or damage are generated by this presentation queue.
export const COMBAT_BUFFER_MS=260;
const actions=new Set(['strike','power','guard','dodge','trap','support','resonance']);
const defensive=kind=>kind==='guard'||kind==='dodge';
export function canBufferCombat(encounter,kind){
 const f=encounter?.field;
 return !!f&&!encounter.result&&!encounter.pact&&actions.has(kind)&&f.cooldown<=COMBAT_BUFFER_MS;
}
export function createFieldCombatBuffer(){
 let pending=null;
 return{
  push(kind,encounter,now){
   if(!Number.isFinite(now)||!canBufferCombat(encounter,kind))return false;
   if(pending&&now>pending.expires)pending=null;
   if(pending&&defensive(pending.kind)&&!defensive(kind))return false;
   pending={kind,expires:now+COMBAT_BUFFER_MS+COMBAT_TICK};return true;
  },
  take(encounter,now){
   if(!pending)return null;
   if(!encounter?.field||encounter.result||encounter.pact||now>pending.expires){pending=null;return null;}
   // The canonical engine decrements recovery before evaluating the button.
   if(encounter.field.cooldown>COMBAT_TICK)return null;
   const kind=pending.kind;pending=null;return kind;
  },
  clear(){pending=null;},
  get kind(){return pending?.kind||null;},
 };
}
