import {masteryLevel} from './frontier.js';
import React,{useMemo,useState} from 'react';
import {CHARACTERS,CARDS,COUNTRIES,cardById,cardSlot,craftPrice} from './catalog.js';
import {ArenaStage} from '../arena/ArenaStage.jsx';
import {portraitArt} from './portraits.js';
import {chapterState} from './chapters.js';

export const ROLE_NAMES={protecteur:'Protecteur',soigneur:'Soigneur',éclaireur:'Éclaireur',mystique:'Mystique',assaillant:'Assaillant'};
export const TALENT_NAMES={terrain:'Endurance',ambiance:'Aura',fragment:'Impact',pierre:'Protection',trap:'Entrave',support:'Soin',energy:'Concentration'};
export function CompanionPortrait({id}){const art=portraitArt(id);return <span className="companion-portrait">{art?<svg viewBox={art.portrait.join(' ')} preserveAspectRatio="xMidYMid slice" aria-hidden="true"><image href={art.src} width={art.width} height={art.height}/></svg>:<span>✦</span>}</span>;}
export function CompanionRow({person,owned,onClick,active}){return <button className={'companion-row'+(active?' is-active':'')} onClick={onClick}><CompanionPortrait id={person.id}/><span><strong>{person.name}</strong><small>{ROLE_NAMES[person.role]} · {person.countryName}</small><em>{owned?'Lien établi':'À rencontrer'}</em></span><span aria-hidden="true">↗</span></button>;}

export function Companions({save,act,initialTab='people'}){
 const[tab,setTab]=useState(initialTab),[query,setQuery]=useState(''),[country,setCountry]=useState('all'),[only,setOnly]=useState(false),[page,setPage]=useState(0),[selected,setSelected]=useState(null);
 const roster=useMemo(()=>CHARACTERS.filter(p=>(country==='all'||p.country===country)&&(!only||save.collection[p.id])&&(p.name+' '+p.role).toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))),[country,only,query,save.collection]);
 const following=save.adventure.companion||save.team[0]||save.leader;
 function filter(set,value){set(value);setPage(0);}
 if(selected){const p=cardById[selected],owned=!!save.collection[p.id],inTeam=[save.leader,...save.team].includes(p.id);return <div className="companion-detail"><button className="world-link" onClick={()=>setSelected(null)}>← Tous les personnages</button><div className="companion-detail-grid"><ArenaStage cardId={p.id}/><div><span className="world-kicker">{p.countryName} · {ROLE_NAMES[p.role]}</span><h3>{p.name}</h3><p>{p.trait}</p><div className="world-stat-row"><span>Puissance <b>{p.attack}</b></span><span>Vitalité <b>{p.health}</b></span><span>Affinité <b>{save.collection[p.id]||0}</b></span><span>Maîtrise <b>{masteryLevel(save.adventure.mastery?.[p.id])}</b></span></div>{owned?<div className="world-actions"><button className="world-primary" disabled={following===p.id} onClick={()=>act({type:'companion',id:p.id})}>{following===p.id?'Voyage à tes côtés':'Voyager avec ce compagnon'}</button><button disabled={save.leader===p.id} onClick={()=>act({type:'equip',id:p.id,leader:true})}>{save.leader===p.id?'Compagnon principal':'Choisir comme compagnon principal'}</button><button disabled={save.leader===p.id||!inTeam&&(save.team.length>=3||p.country==='3b'&&[save.leader,...save.team].some(id=>cardById[id].country==='3b'))} onClick={()=>act({type:'equip',id:p.id})}>{save.team.includes(p.id)?'Retirer du groupe':'Ajouter au groupe'}</button></div>:<p className="world-rule">{p.category==='Carte unique'?'Libère ce gardien dans son pays pour gagner sa confiance.':p.country==='3b'?'Reconstruis les liens entre les pays et libère leurs gardiens.':'Rencontre ce personnage dans son pays. Aide-le ou apaise-le, puis réponds à ses besoins pour établir un lien. Certains apparaissent après deux souvenirs retrouvés.'}</p>}<p className="companion-note">Ton avatar reste ton personnage. Le compagnon choisi marche à tes côtés ; les membres du groupe apportent leurs aptitudes au combat.</p></div></div></div>;}
 return <><div className="companion-tabs" role="tablist" aria-label="Compagnons et aptitudes"><button role="tab" aria-selected={tab==='people'} onClick={()=>setTab('people')}>Personnages & créatures <span>{CHARACTERS.filter(p=>save.collection[p.id]).length}/{CHARACTERS.length}</span></button><button role="tab" aria-selected={tab==='talents'} onClick={()=>setTab('talents')}>Pouvoirs & objets</button></div>
 {tab==='people'?<><p>Rencontre les habitants, créatures et gardiens des huit pays. Gagne leur confiance et compose ton groupe.</p><div className="world-filters"><label>Rechercher un personnage<input value={query} placeholder="Nom ou rôle…" onChange={e=>filter(setQuery,e.target.value)}/></label><label>Pays<select value={country} onChange={e=>filter(setCountry,e.target.value)}><option value="all">Tous les pays</option>{COUNTRIES.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}<option value="3b">L’Union</option></select></label><label className="world-check"><input type="checkbox" checked={only} onChange={e=>filter(setOnly,e.target.checked)}/> Liens établis</label></div><div className="companion-roster">{roster.slice(page*12,(page+1)*12).map(p=><CompanionRow key={p.id} person={p} owned={save.collection[p.id]} active={following===p.id} onClick={()=>setSelected(p.id)}/>)}</div>{!roster.length&&<p>Aucun personnage ne correspond à ta recherche.</p>}<nav className="world-pages" aria-label="Pages des personnages"><button disabled={!page} onClick={()=>setPage(page-1)}>Précédent</button><span>{roster.length} personnages · {page+1}/{Math.max(1,Math.ceil(roster.length/12))}</span><button disabled={(page+1)*12>=roster.length} onClick={()=>setPage(page+1)}>Suivant</button></nav></>:<><p>Les enseignements des habitants et les objets retrouvés renforcent tes aptitudes. Un pouvoir actif par famille, et trois entraves au maximum.</p><div className="talent-families">{Object.entries(TALENT_NAMES).map(([slot,name])=>{const list=CARDS.filter(p=>cardSlot(p)===slot&&(save.collection[p.id]||save.visited.includes(p.country)||p.country==='3b'));return <details key={slot}><summary>{name}<span>{list.filter(p=>save.collection[p.id]).length} acquis</span></summary>{list.map(p=>{const known=!!save.collection[p.id],equipped=save.loadout[slot]===p.id||save.loadout.traps.includes(p.id);return <article className="talent-row" key={p.id}><span><strong>{p.name}</strong><small>{p.trait.replace(/^Terrain :/,'Endurance :').replace(/^Ambiance :/,'Aura :').replace('du Leader','du compagnon principal')}</small></span><button disabled={known?slot==='trap'&&!equipped&&save.loadout.traps.length>=3:save.shards<craftPrice(p)} onClick={()=>act({type:known?'equip':'craft',id:p.id})}>{known?equipped?'Désactiver':'Activer':`Acquérir · ${craftPrice(p)} éclats`}</button></article>;})}</details>;})}</div><p>{save.shards} éclats disponibles. Les savoirs nécessaires aux quêtes sont transmis gratuitement par les habitants.</p></>}
 </>;
}

export function Sanctuary({save,act,onClose,onNavigate}){const s=chapterState(save,save.region),workshop=s.choice==='workshop',prepared=save.adventure.preparation===save.region;return <div className="sanctuary-panel"><span className="sanctuary-emblem">{workshop?'⚒':'❧'}</span><h3>{s.restored<2?'Un lieu à faire revivre':workshop?'L’atelier des compagnons':'Le jardin du repos'}</h3><p>{s.restored<2?'Retrouve les souvenirs et reconstruis ce quartier avec son habitant. Il accueillera ensuite ton groupe avant les expéditions.':workshop?'Les artisans préparent les armes de ton groupe : +4 de puissance pour la prochaine rencontre.':'Ton groupe se repose près de l’eau : +16 de vitalité pour la prochaine rencontre.'}</p>{s.restored>=2?<><button className="world-primary" disabled={prepared} onClick={()=>act({type:'prepare'})}>{prepared?'Ton groupe est prêt':'Préparer le groupe · gratuit'}</button><p>Une seule préparation à la fois. Elle se consomme au début de la prochaine rencontre et ne s’applique pas à l’arène.</p><button onClick={onClose}>Reprendre l’expédition</button></>:<button className="world-primary" onClick={()=>onNavigate(save.region+':story')}>Rejoindre l’habitant</button>}</div>;}
