export const COUNTRY_WORLDS={
 france:{guardian:'Céliane',value:'Justice',capital:'Les Passages de Paris 3B',rural:'Vergers de Loire',wild:'Crêtes alpines',landmarks:['Tour de lumière','Galerie des Verrières','Pont des mémoires'],story:'Les noms disparaissent des façades et des archives. Rétablis la mémoire publique avant que la ville ne perde son histoire.',missions:['Retrouver les noms effacés','Rouvrir la bibliothèque vivante','Libérer le Gardien de Justice'],secrets:['Archives sous la gare','Atelier 16-18','Jardin des ouvriers','Passage bleu','Toit des relieurs','Crypte des noms','Train fantôme','Fragment du Cercle']},
 italie:{guardian:'Alessio',value:'Espoir',capital:'Florence Verticale',rural:'Terrasses de Toscane',wild:'Lagune suspendue',landmarks:['Dôme solaire','Tour inclinée cinétique','Pont des ateliers'],story:'Les jardins suspendus cessent de communiquer. Rétablis les chemins de graines et la lumière entre les terrasses.',missions:['Porter les semences','Relier les terrasses','Réveiller le Gardien de l’Espoir'],secrets:['Serre zéro','Atelier du cuir','Canal céleste','Clocher mécanique','Vigne dorée','Cour des tailleurs','Tunnel de marbre','Fragment du Cercle']},
 estonie:{guardian:'Eira',value:'Sagesse',capital:'Tallinn Boréale',rural:'Lisière de Lahemaa',wild:'Forêt des aurores',landmarks:['Tour des archives','Mur des aurores','Port baltique'],story:'Les chemins de la forêt ont perdu leurs repères. Les aurores doivent reconnecter les archives de la ville.',missions:['Rallumer les lanternes','Retrouver le sentier boréal','Éveiller la Gardienne de Sagesse'],secrets:['Bunker de données','Lac miroir','Tour de glace','Cabane des cartographes','Port silencieux','Pierre runique','Observatoire forestier','Fragment du Cercle']},
 turquie:{guardian:'Émir',value:'Foi',capital:'Istanbul des Deux Rives',rural:'Bazars périphériques',wild:'Vallées de Cappadoce',landmarks:['Dôme des lunes','Pont des deux rives','Observatoire des astrolabes'],story:'Les astrolabes regardent des ciels différents. Réunis leurs constellations sans effacer leurs différences.',missions:['Récupérer les lentilles','Aligner les trois ciels','Éveiller le Gardien de Foi'],secrets:['Citerne holographique','Atelier des tapis','Cheminée de fée bleue','Bazar nocturne','Quai caché','Bibliothèque du ciel','Dôme souterrain','Fragment du Cercle']},
 algerie:{guardian:'Yliane',value:'Loyauté',capital:'Alger des Terrasses',rural:'Villages des Hauts Plateaux',wild:'Sahara des fragments',landmarks:['Casbah verticale','Jardin des sources','Tour de l’oasis'],story:'L’eau s’arrête avant les jardins et les quartiers se coupent les uns des autres. Rétablis le courant de mémoire.',missions:['Dégager la source','Reconnecter les canaux','Éveiller la Gardienne de Loyauté'],secrets:['Passage de la Casbah','Garage des anciens','Oasis noire','Train des plateaux','Atelier cuivre','Bibliothèque blanche','Dune chantante','Fragment du Cercle']},
 tunisie:{guardian:'Soraya',value:'Courage',capital:'Carthage Nouvelle',rural:'Oliveraies du rivage',wild:'Falaises méditerranéennes',landmarks:['Port des retrouvailles','Cour de Carthage','Phare des marées'],story:'La mer recouvre les marches de la mémoire. Trouve le rythme des écluses et ramène les habitants au rivage.',missions:['Ramener la voile','Régler les écluses','Éveiller la Gardienne de Courage'],secrets:['Villa bleue','Citerne punique futuriste','Atelier céramique','Olivier ancien','Tunnel du port','Marché blanc','Épave lumineuse','Fragment du Cercle']},
 maroc:{guardian:'Naël',value:'Noblesse',capital:'Marrakech des Lumières',rural:'Villages de l’Atlas',wild:'Cimes et désert',landmarks:['Minaret solaire','Halle des artisans','Jardin zellige'],story:'Le vent ne transporte plus les messages entre les vallées. Réaccorde les cloches et les routes de l’Atlas.',missions:['Attacher les rubans','Accorder les cloches','Éveiller le Gardien de Noblesse'],secrets:['Riad Matrix','Tannerie chromatique','Col de l’Atlas','Source cachée','Souk souterrain','Jardin nocturne','Caravane oubliée','Fragment du Cercle']},
 espagne:{guardian:'Diego',value:'Passion',capital:'Séville Crépusculaire',rural:'Oliviers d’Andalousie',wild:'Falaises atlantiques',landmarks:['Phare cinétique','Patio des azulejos','Moulins orbitaux'],story:'Les mécanismes du pays tournent chacun à leur rythme. Accorde-les pour rallumer le phare commun.',missions:['Retrouver l’engrenage','Accorder les moulins','Éveiller le Gardien de Passion'],secrets:['Patio rouge','Atelier guitare','Tunnel du phare','Olivier millénaire','Station balnéaire abandonnée','Tour du vent','Arène de lumière','Fragment du Cercle']},
};

export const COUNTRY_IDS=Object.keys(COUNTRY_WORLDS);
export function countryWorld(id){return COUNTRY_WORLDS[id]||null;}
