export const COUNTRY_ASSET_KITS={
 france:{architecture:['Tour de l’Union','Maison des Verrières','Atelier des Ouvriers','Gare Lumière','Bibliothèque Justice','Résidence Haussmann Matrix'],materials:['pierre claire','acier bleu','verre champagne'],vegetation:['tilleul','platane','vigne'],vehicles:['Coupé Tricolore','Navette Hexagone'],companion:'Faucon Justice',weapon:'Lame Lumière',decor:['réverbère Matrix','banc verrière','fontaine fleur-de-lys abstraite']},
 algerie:{architecture:['Citadelle du Fennec','Terrasse d’Alger','Maison Casbah Verticale','Atelier des Sources','Tour Oasis','Gare des Plateaux'],materials:['pierre blanche','cuivre','verre vert'],vegetation:['palmier','olivier','figuier'],vehicles:['Roadster Sahara','Navette Casbah'],companion:'Fennec Loyauté',weapon:'Lame des Sources',decor:['moucharabieh futuriste','fontaine oasis','lanterne cuivre']},
 maroc:{architecture:['Palais du Lion','Riad Matrix','Maison Atlas','Halle des Artisans','Tour Zellige','Jardin Suspendu'],materials:['terre ocre','zellige abstrait','or champagne'],vegetation:['palmier','oranger','cèdre'],vehicles:['Coupé Atlas','Navette Médina'],companion:'Lion Noblesse',weapon:'Lame Atlas',decor:['arc géométrique','fontaine zellige','lanterne dorée']},
 tunisie:{architecture:['Phare de Carthage','Maison Bleue','Cour des Oliviers','Atelier du Rivage','Tour des Marées','Port Lumière'],materials:['pierre blanche','bleu méditerranée','métal rouge'],vegetation:['olivier','bougainvillier','palmier'],vehicles:['Coupé Carthage','Navette du Golfe'],companion:'Faucon Courage',weapon:'Lame Carthage',decor:['porte bleue abstraite','mosaïque futuriste','fontaine marine']},
 turquie:{architecture:['Tour Crescent','Dôme des Deux Rives','Maison Bosphore','Atelier Astrolabe','Observatoire Cappadoce','Bazar Vertical'],materials:['pierre chaude','cuivre rouge','verre nuit'],vegetation:['cyprès','tulipe','pin'],vehicles:['Coupé Bosphore','Navette Crescent'],companion:'Loup Foi',weapon:'Lame Astrolabe',decor:['lanterne étoilée','fontaine dôme','arc céleste']},
 espagne:{architecture:['Arène del Sol','Maison Patio','Tour du Vent','Atelier Passion','Phare Cinétique','Galerie Azulejo'],materials:['pierre sable','métal rouge','or solaire'],vegetation:['olivier','oranger','palmier'],vehicles:['Coupé Sol','Navette Passion'],companion:'Taureau Passion',weapon:'Lame Sol',decor:['patio futuriste','fontaine solaire','mosaïque rouge-or']},
 italie:{architecture:['Torre dell’Infinito','Maison Loggia','Atelier Renaissance','Galerie du Marbre','Jardin Vertical','Dôme Espoir'],materials:['marbre clair','bronze','verre doré'],vegetation:['cyprès','vigne','olivier'],vehicles:['Coupé Infinito','Navette Toscana'],companion:'Lévrier Espoir',weapon:'Lame Infinito',decor:['colonnade futuriste','fontaine marbre','pergola lumineuse']},
 estonie:{architecture:['Forteresse du Nord','Maison Boréale','Tour des Données','Atelier des Aurores','Port Baltique','Observatoire Sagesse'],materials:['pierre sombre','acier noir','verre bleu glace'],vegetation:['pin','bouleau','sapin'],vehicles:['Coupé Boréal','Navette Baltique'],companion:'Loup Sagesse',weapon:'Lame Boréale',decor:['borne lumineuse','cristal d’aurore','banc nordique']},
 international:{architecture:['Nexus 3B','Tour des Alliances','Maison du Monde','Centre des Créateurs','Agora Internationale','Observatoire Héritage'],materials:['noir profond','or champagne','verre Matrix'],vegetation:['jardin des huit','arbre lumière','mur végétal'],vehicles:['3B One','Navette Nexus'],companion:'Gardien 3B',weapon:'Lame du Cercle',decor:['globe holographique','cercle brisé','borne des huit valeurs']},
};
export const ASSET_COUNTRIES=Object.keys(COUNTRY_ASSET_KITS);
