import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,Compass,Footprints,Map,Maximize,Pause,Play,Shield,Sparkles,Users,X,Download,RotateCcw,Volume2,VolumeX} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {useGameRewards} from '../loyalty/useGameRewards.js';
import {CARDS,CHARACTERS,COUNTRIES,CATEGORIES,SOURCE,cardById,countryById,cardSlot,craftPrice} from './catalog.js';
import {blankSave,normalizeSave,levelFor,nextLevelXP,gain,discover,beacon,recruit,seal,teamStats,guardianReady,makeEncounter,battleTurn,worldItems,craft,equip,awardMissions,encounterCards} from './rules.js';
import {loadWorld,saveWorld,writeLocal} from './save.js';
import {createWalkTracker} from './gps.js';
import {createWorldScene} from './scene.js';
import {ORIGINAL_ART,ART_SOURCE} from './art.js';
import './world.css';

function Modal({title,onClose,children,wide=false}){
 const ref=useRef(null);
 useEffect(()=>{const dialog=ref.current,previous=document.activeElement;dialog.showModal();return()=>{dialog.close();previous?.focus?.({preventScroll:true});};},[]);
 return <dialog ref={ref} className={'world-dialog'+(wide?' world-dialog-wide':'')} onCancel={e=>{e.preventDefault();onClose();}} aria-label={title}>
  <header><div><span className="world-kicker">3B WORLD · LES 8 PORTES</span><h2>{title}</h2></div><button aria-label="Fermer" className="world-icon" onClick={onClose}><X size={20}/></button></header>
  {children}
 </dialog>;
}
function OriginalArt({card,full=false}){
 const art=ORIGINAL_ART[card.id];
 return <svg className="world-original-art" viewBox={(full?art.frame:art.portrait).join(' ')} preserveAspectRatio={full?'xMidYMid meet':'xMidYMin slice'} aria-hidden="true"><image href={art.src} width={art.width} height={art.height}/></svg>;
}
function Art({card,className=''}){
 const index=Math.max(0,COUNTRIES.findIndex(c=>c.id===card.country)),country=COUNTRIES[index];
 if(ORIGINAL_ART[card.id])return <div className={'world-card-art world-original '+className} aria-hidden="true"><OriginalArt card={card}/></div>;
 if(card.country==='3b')return <div className={'world-card-art world-neutral '+className} aria-hidden="true"><b>3B</b><span>LES GARDIENS DE L’UNION</span></div>;
 return <div className={'world-card-art '+className} style={{'--art-x':(index%4)/3*100+'%','--art-y':index<4?'0%':'100%','--country-color':country.color}} aria-hidden="true"><div/><span>{card.country==='3b'?'3B':country.name.toUpperCase()}</span></div>;
}
function Card({card,owned,onClick}){
 return <button className={'world-card'+(owned?' is-owned':'')} onClick={onClick} style={{'--country-color':countryById[card.country]?.color||'#eddbb0'}}>
  <Art card={card}/><div className="world-card-top"><span>{card.id}</span><span>{card.rarity}</span></div><div className="world-card-copy"><small>{card.category}</small><strong>{card.name}</strong><span>{owned?'◆ Dans ta collection':'◇ À découvrir'}</span></div>
 </button>;
}
function Collection({save,onChange,notice}){
 const[query,setQuery]=useState(''),[country,setCountry]=useState('all'),[category,setCategory]=useState('all'),[ownedOnly,setOwnedOnly]=useState(false),[page,setPage]=useState(0),[selected,setSelected]=useState(null);
 const filtered=useMemo(()=>CARDS.filter(c=>(country==='all'||c.country===country)&&(category==='all'||c.category===category)&&(!ownedOnly||save.collection[c.id])&&((c.name+' '+c.id+' '+c.power).toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')))),[query,country,category,ownedOnly,save.collection]);
 useEffect(()=>{setPage(0);},[query,country,category,ownedOnly]);
 if(selected){const c=cardById[selected],owned=save.collection[c.id],slot=cardSlot(c),equipped=save.leader===c.id||save.team.includes(c.id)||Object.values(save.loadout).includes(c.id)||save.loadout.traps.includes(c.id);return <div className="world-card-detail">
  <button className="world-link" onClick={()=>setSelected(null)}><ArrowLeft size={16}/> Toutes les cartes</button>
  <div className="world-card-detail-grid"><Card card={c} owned={owned} onClick={()=>{}}/><div><span className="world-kicker">{c.id} · {c.countryName}</span><h3>{c.name}</h3><p>{c.character?c.role:c.category} · {c.rarity}{owned?' · Affinité '+owned:''}</p>
   <div className="world-rule"><strong>Dans le monde</strong><p>{c.trait}</p></div>
   {c.character&&<div className="world-stat-row"><span>Puissance <b>{c.attack}</b></span><span>Vitalité <b>{c.health}</b></span></div>}
   {owned&&c.character&&<div className="world-actions"><button className="world-primary" disabled={save.leader===c.id} onClick={()=>{onChange(s=>equip(s,c.id,true));notice('Leader sélectionné.');}}>{save.leader===c.id?'Leader actif':'Choisir comme Leader'}</button><button disabled={save.leader===c.id||(!save.team.includes(c.id)&&(save.team.length===3||(c.country==='3b'&&[save.leader,...save.team].some(id=>cardById[id].country==='3b'))))} onClick={()=>{onChange(s=>equip(s,c.id));notice('Équipe mise à jour.');}}>{save.team.includes(c.id)?'Retirer des Alliés':'Ajouter aux Alliés'}</button></div>}
   {owned&&slot&&<button className="world-primary" disabled={slot==='trap'&&!equipped&&save.loadout.traps.length===3} onClick={()=>{onChange(s=>equip(s,c.id));notice('Équipement mis à jour.');}}>{equipped?'Déséquiper':'Équiper cette carte'}</button>}
   {!owned&&slot&&<><p>Atelier : <b>{craftPrice(c)} éclats</b>. {save.visited.includes(c.country)||c.country==='3b'?'Assemble cette carte avec les éclats gagnés en jouant.':'Visite d’abord ce pays.'}</p><button className="world-primary" disabled={save.shards<craftPrice(c)||(!save.visited.includes(c.country)&&c.country!=='3b')} onClick={()=>{onChange(s=>craft(s,c.id));notice('Carte assemblée dans ta collection.');}}>Assembler · {craftPrice(c)} éclats</button></>}
   {!owned&&!slot&&<p className="world-rule">{c.category==='Carte unique'?'Bats le gardien de ce pays pour recevoir sa carte unique.':c.category==='Personnage neutre 3B'?'Récompense des paliers de 1, 3, 5 et 8 sceaux.':c.character?'Rencontre cet écho dans son pays. Les personnages rares apparaissent après deux souvenirs retrouvés.':c.category==='Mission'?'Complète les objectifs du Journal pour recevoir cette carte.':c.category==='Passeport'?'Traverse la porte de ce pays pour recevoir son Passeport.':'Bats le gardien de ce pays pour recevoir sa Porte.'}</p>}
   {ORIGINAL_ART[c.id]&&<details><summary>Voir la carte illustrée d’origine</summary><div className="world-original-full"><OriginalArt card={c} full/></div><p>Illustration du projet 3B, extraite de ta planche française. Les valeurs imprimées appartiennent au prototype visuel ; les valeurs jouables sont celles indiquées dans cette fiche.</p></details>}
   <details><summary>Règle du jeu de cartes V4</summary><p>{c.effect}</p><p>{c.condition}</p><p>Coût : {c.cost??'—'} · Puissance : {c.originalAttack??'—'} · Défense : {c.originalDefense??'—'}</p><small>{c.source}</small></details>
  </div></div></div>;}
 return <><p className="world-subtitle">{Object.keys(save.collection).length} / 368 cartes · {save.shards} éclats pour l’Atelier. Sélectionne une carte pour comprendre son rôle et l’équiper.</p>
  <div className="world-filters"><label>Rechercher<input placeholder="Nom, pouvoir ou C001…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Pays<select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">Tous les pays</option>{COUNTRIES.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}<option value="3b">3B International</option></select></label><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Toutes les catégories</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="world-check"><input type="checkbox" checked={ownedOnly} onChange={e=>setOwnedOnly(e.target.checked)}/> Mes cartes</label></div>
  <div className="world-collection">{filtered.slice(page*16,(page+1)*16).map(c=><Card key={c.id} card={c} owned={save.collection[c.id]} onClick={()=>setSelected(c.id)}/>)}</div>
  {!filtered.length&&<p>Aucune carte ne correspond à ces filtres.</p>}
  <nav className="world-pages" aria-label="Pages de collection"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>{filtered.length} cartes · page {page+1} / {Math.max(1,Math.ceil(filtered.length/16))}</span><button disabled={(page+1)*16>=filtered.length} onClick={()=>setPage(p=>p+1)}>Suivant</button></nav>
  <details><summary>Origine des cartes et adaptation</summary><p>Les 368 fiches viennent du dossier partagé « Les 8 Portes », version V4 reconstruite. Le statut d’origine de chaque fiche est conservé. Les 20 personnages français utilisent les illustrations du <a href={ART_SOURCE} target="_blank" rel="noreferrer">partage des cartes originales</a>. Pour les autres fiches, des emblèmes régionaux accompagnent l’exploration.</p><p>Le mode exploration adapte les effets pour des rencontres rapides. Le jeu de table V4 prévoit un deck de 50 cartes et une main de 7 ; ses règles sont consultables dans chaque fiche.</p></details>
 </>;
}
function Encounter({initial,onClose,onReward,onActivity}){
 const[enc,setEnc]=useState(initial),[pact,setPact]=useState(false),[hits,setHits]=useState(0),[attempts,setAttempts]=useState(0),[phase,setPhase]=useState(0),[finished,setFinished]=useState(false),[feedback,setFeedback]=useState(''),sent=useRef(false),lastTap=useRef(0),start=useRef(performance.now()),phaseRef=useRef(0);
 const card=cardById[enc.card];
 useEffect(()=>{if(enc.result==='victory'&&!sent.current){sent.current=true;onReward('victory',card.id);setFinished(true);}},[enc.result]);
 useEffect(()=>{if(!pact||finished)return;let raf;const tick=now=>{const p=(Math.sin((now-start.current)/1100*Math.PI)*.5+.5);phaseRef.current=p;setPhase(p);raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[pact,finished]);
 function pulse(){if(finished||performance.now()-lastTap.current<550)return;lastTap.current=performance.now();onActivity();const good=Math.abs(phaseRef.current-.5)<enc.stats.window,nextHits=hits+(good?1:0),nextAttempts=attempts+1;setHits(nextHits);setAttempts(nextAttempts);setFeedback(good?'Résonance juste.':'Trop tôt ou trop tard. Observe le rythme.');if(nextHits>=3){setFinished(true);if(!sent.current){sent.current=true;onReward('pact',card.id);}}else if(nextAttempts>=6){setFinished(true);setFeedback('Le lien s’est dissipé. Tu pourras rencontrer cet écho à nouveau.');}}
 return <div className="world-encounter"><div className="world-encounter-art"><Art card={card}/><div><span className="world-kicker">{enc.boss?'DÉFI DU GARDIEN':'RENCONTRE · '+card.rarity.toUpperCase()}</span><h3>{card.name}</h3><p>{card.countryName} · {card.role}</p></div></div>
  {finished?<div className="world-result"><Sparkles size={30}/><h3>{enc.result==='victory'?'Sceau retrouvé !':hits>=3?'Pacte réussi !':'L’écho s’éloigne'}</h3><p>{enc.result==='victory'?'La carte unique et la Porte rejoignent ta collection.':hits>=3?'La carte rejoint ta collection. Les doublons renforcent son affinité.':feedback}</p><button className="world-primary" onClick={onClose}>Continuer l’exploration</button></div>:pact?<div className="world-pact"><h3>Tisser un lien</h3><p>Touche « Résonner » quand la lumière traverse la zone dorée. Réussis 3 fois en 6 essais.</p><div className="world-resonance"><span style={{left:(50-enc.stats.window*100)+'%',width:enc.stats.window*200+'%'}}/><i style={{left:phase*100+'%'}}/></div><div className="world-stat-row"><span>{hits} / 3 liens</span><span>{attempts} / 6 essais</span></div><button className="world-primary" onClick={pulse}>Résonner</button><p role="status">{feedback||'Écoute le rythme de la lumière.'}</p></div>:<div className="world-battle">
   <div className="world-health"><label>Ton équipe <b>{enc.hp} / {enc.maxHP}</b></label><progress max={enc.maxHP} value={enc.hp}/><label>{enc.boss?'Gardien':'Écho'} <b>{enc.enemy} / {enc.enemyMax}</b></label><progress className="enemy" max={enc.enemyMax} value={enc.enemy}/></div>
   <p className="world-intent">{enc.result==='defeat'?'Retraite · aucune carte perdue':enc.result==='calm'?'L’écho est prêt à te rejoindre':enc.intent==='rituel'?'Prochain mouvement : rituel · frappe plus fort maintenant':enc.intent==='percée'?'Prochain mouvement : percée · ta garde sera moins efficace':'Prochain mouvement : frappe · la garde réduit les dégâts'}</p>
   <p role="status">{enc.log}</p>
   {!enc.result&&<><div className="world-actions world-battle-actions"><button onClick={()=>{onActivity();setEnc(e=>battleTurn(e,'strike'));}}>Frapper <small>+1 concentration</small></button><button onClick={()=>{onActivity();setEnc(e=>battleTurn(e,'guard'));}}>Garder <small>Protège et soigne</small></button><button className="world-primary" disabled={enc.focus<2} onClick={()=>{onActivity();setEnc(e=>battleTurn(e,'power'));}}>Pouvoir <small>{enc.focus} / 2 concentration</small></button></div><div className="world-actions">{enc.traps>0&&<button onClick={()=>{onActivity();setEnc(e=>battleTurn(e,'trap'));}}>Piège · {enc.traps} restant{enc.traps>1?'s':''}</button>}{enc.support&&<button onClick={()=>{onActivity();setEnc(e=>battleTurn(e,'support'));}}>Soutien · +24 vitalité</button>}</div></>}
   {!enc.boss&&(enc.result==='calm'||(!enc.result&&enc.enemy<=enc.enemyMax*.35))&&<button className="world-primary" onClick={()=>{setPact(true);start.current=performance.now();}}>Proposer un pacte</button>}
   {enc.result==='defeat'&&<button className="world-primary" onClick={onClose}>Revenir au monde · vitalité restaurée</button>}
  </div>}
 </div>;
}
export default function WorldPage({goTo}){const account=useLoyalty();return account.loading?<div className="world-loading">Ouverture du Monde 3B…</div>:<WorldSession key={account.user?.id||'guest'} uid={account.user?.id} goTo={goTo}/>;}

function WorldSession({uid,goTo}){
 const[save,setSave]=useState(blankSave),[loaded,setLoaded]=useState(false),[snapshot,setSnapshot]=useState({region:'hub',position:{x:0,z:9}}),[panel,setPanel]=useState(null),[encounter,setEncounter]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saveMessage,setSaveMessage]=useState('Chargement de la sauvegarde…'),[gps,setGPS]=useState(false),[gpsMessage,setGPSMessage]=useState('Le GPS est désactivé.'),[walkSession,setWalkSession]=useState(0),[outdoorEchoes,setOutdoorEchoes]=useState(0),[sound,setSound]=useState(false);
 const canvas=useRef(null),shell=useRef(null),scene=useRef(null),saveRef=useRef(save),callbacks=useRef({}),ready=useRef(false),paused=useRef(false),activity=useRef(0),rewardEngine=useRef({status:'playing'}),watch=useRef(null),tracker=useRef(createWalkTracker()),walkRef=useRef(0),audio=useRef(null),dirty=useRef(false),saveTimer=useRef(null),noticeTimer=useRef(null);
 saveRef.current=save;
 const rewardMessage=useGameRewards('world',rewardEngine,paused,ready,activity);
 const announce=useCallback(text=>{setNotice(text);clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),4500);},[]);
 const change=useCallback(update=>{setSave(previous=>{const next=normalizeSave(typeof update==='function'?update(previous):update);saveRef.current=next;writeLocal(uid,next);dirty.current=true;return next;});},[uid]);
 function chime(){if(!sound)return;try{const ctx=audio.current||(audio.current=new(window.AudioContext||window.webkitAudioContext)());ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(440,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(880,ctx.currentTime+.17);g.gain.setValueAtTime(.055,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.45);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.46);}catch{}}
 async function sync(){if(!loaded)return;const current=saveRef.current;dirty.current=false;const result=await saveWorld(uid,current);if(result.pending)dirty.current=true;setSaveMessage(result.message);if(result.data&&saveRef.current===current){saveRef.current=result.data;setSave(result.data);}}
 function stopGPS(message='Le GPS est désactivé.') {if(watch.current!==null)navigator.geolocation?.clearWatch(watch.current);watch.current=null;tracker.current.reset();setGPS(false);setGPSMessage(message);}
 function startGPS(){
  if(!navigator.geolocation){setGPSMessage('Ce navigateur ne propose pas le GPS. Le monde virtuel reste disponible.');return;}
  stopGPS('Recherche du signal GPS…');setGPS(true);
  watch.current=navigator.geolocation.watchPosition(position=>{
   const result=tracker.current.accept(position);setGPSMessage(result.status);
   if(result.metres>0){activity.current=Date.now();const previous=walkRef.current;walkRef.current+=result.metres;setWalkSession(Math.floor(walkRef.current));if(Math.floor(walkRef.current/100)>Math.floor(previous/100)){setOutdoorEchoes(n=>n+1);announce('Tes pas ont révélé un écho. Arrête-toi pour le rencontrer.');}change(s=>gain(s,{walked:s.walked+Math.round(result.metres)}));}
  },e=>{if(e.code===1)stopGPS('Permission refusée. Tu peux l’autoriser dans les réglages du navigateur puis réessayer.');else setGPSMessage(e.code===3?'Signal trop lent · attends un endroit dégagé.':'GPS indisponible pour le moment.');},{enableHighAccuracy:true,maximumAge:0,timeout:15000});
 }
 function travel(id){change(s=>id==='hub'?gain(s,{region:'hub'}):discover(s,id));scene.current?.travel(id);setPanel(null);chime();announce(id==='hub'?'Retour à la Place des huit portes.':countryById[id].name+' · Passeport ajouté à ta collection.');}
 function interact(item){
  if(item.type==='portal'){travel(item.id);return;}
  if(item.type==='final'){if(saveRef.current.seals.length<5){announce('Retrouve 5 sceaux pour ouvrir le Portail final.');return;}if(!saveRef.current.finalOpened)change(s=>gain(s,{finalOpened:true,xp:s.xp+500,shards:s.shards+250}));setPanel('final');chime();return;}
  if(item.type==='beacon'){if(saveRef.current.beacons.includes(item.id)){announce('Ce souvenir a déjà été retrouvé.');return;}change(s=>awardMissions(beacon(s,item.id)));chime();announce('Souvenir retrouvé · +45 XP monde · +15 éclats · une carte d’équipement.');return;}
  if(item.type==='guardian'&&!guardianReady(saveRef.current,snapshot.region)){announce('Retrouve les 3 souvenirs de ce pays et ajoute un Allié à ton équipe.');return;}
  scene.current?.cooldown(item.id);setEncounter({...makeEncounter(cardById[item.card],saveRef.current,item.type==='guardian'),origin:item.id,region:snapshot.region});setPanel('encounter');
 }
 callbacks.current={interact};
 useEffect(()=>{let live=true;loadWorld(uid).then(result=>{if(!live)return;setSave(result.data);saveRef.current=result.data;dirty.current=!!result.needsSave;setSaveMessage(result.message);setLoaded(true);});return()=>{live=false;};},[uid]);
 useEffect(()=>{
  if(!loaded)return;
  try{scene.current=createWorldScene(canvas.current,{save:saveRef.current,onSnapshot:setSnapshot,onInteract:item=>callbacks.current.interact(item),onActivity:()=>{activity.current=Date.now();},onError:setError});ready.current=true;}
  catch{setError('Le navigateur n’a pas pu ouvrir la 3D. Active l’accélération graphique ou essaie un autre navigateur. Ta sauvegarde est conservée.');}
  return()=>{ready.current=false;scene.current?.destroy();scene.current=null;};
 },[loaded]);
 useEffect(()=>{paused.current=(!!panel&&!['encounter','gps'].includes(panel))||!!error;scene.current?.setPaused(!!panel||!!error);},[panel,error,loaded]);
 useEffect(()=>{scene.current?.setSave(save);if(!loaded||!dirty.current)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(sync,1200);return()=>clearTimeout(saveTimer.current);},[save,loaded]);
 useEffect(()=>{
  const hidden=()=>{if(document.hidden){stopGPS('GPS arrêté en arrière-plan. Réactive-le pour une nouvelle sortie.');if(dirty.current)saveWorld(uid,saveRef.current);} };
  document.addEventListener('visibilitychange',hidden);
  const timer=setInterval(()=>{if(ready.current&&dirty.current)sync();},20000);
  return()=>{document.removeEventListener('visibilitychange',hidden);clearInterval(timer);clearTimeout(noticeTimer.current);clearTimeout(saveTimer.current);if(watch.current!==null)navigator.geolocation?.clearWatch(watch.current);if(dirty.current)saveWorld(uid,saveRef.current);audio.current?.close();};
 },[uid,loaded]);
 const country=countryById[snapshot.region],stats=teamStats(save),regionItems=worldItems(snapshot.region,save),near=snapshot.near;
 function navigate(item){scene.current?.waypoint(item,true);setPanel(null);announce('En route vers '+item.name+'. Glisse le doigt pour reprendre la main.');}
 function exportSave(){const blob=new Blob([JSON.stringify(saveRef.current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='3b-monde-sauvegarde.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function importSave(event){const file=event.target.files?.[0];if(!file)return;try{if(file.size>300000)throw Error();const raw=JSON.parse(await file.text());if(raw.version!==1||!raw.collection)throw Error();const restored=normalizeSave(raw);change(restored);scene.current?.travel(restored.region);announce('Ta copie de sauvegarde a été restaurée.');}catch{announce('Ce fichier n’est pas une sauvegarde du Monde 3B valide.');}event.target.value='';}
 return <section ref={shell} className="world-shell" aria-label="Le Monde du 3B">
  <canvas ref={canvas} className="world-canvas" tabIndex={0} aria-label="Monde 3D. Glisse pour déplacer Kaïs, ou utilise les flèches. E pour interagir."/>
  <div className="world-vignette"/>
  <header className="world-topbar"><button className="world-icon" aria-label="Retour à l’application" onClick={()=>goTo('home')}><ArrowLeft size={21}/></button><div className="world-brand"><b>3B<span>WORLD</span></b><small>LES HUIT PORTES</small></div><div className="world-mode"><i/> {gps?'EXPLORATION DEHORS':'MONDE VIRTUEL'}</div><button className="world-icon" aria-label="Pause et options" onClick={()=>setPanel('pause')}><Pause size={19}/></button></header>
  <div className="world-location"><span className="world-kicker">{country?country.name.toUpperCase():'LE NEXUS'}</span><h1>{country?country.title:'La Place des huit portes'}</h1><p>{country?country.lore:'Huit horizons. Des centaines de liens à créer.'}</p></div>
  <button className="world-minimap" aria-label="Ouvrir l’atlas et les itinéraires" onClick={()=>setPanel('atlas')}><svg viewBox="-82 -82 164 164" role="img" aria-label="Position de Kaïs et points d’intérêt"><circle r="77" fill="#142936" stroke="#627471" strokeWidth="1"/><circle r="50" fill="none" stroke="#ffffff19"/><path d="M0 -75V75 M-75 0H75" stroke="#ffffff10"/>{regionItems.map(i=><g key={i.id}><circle cx={i.x} cy={i.z} r={i.type==='portal'?4:3} fill={i.done?'#64736c':i.color}/>{i.type==='portal'&&<text x={i.x} y={i.z-7} textAnchor="middle" fontSize="8" fill="#e8dfc6">{i.id==='hub'?'3B':i.name.slice(0,2).toUpperCase()}</text>}</g>)}<circle cx={snapshot.position.x} cy={snapshot.position.z} r="4.5" fill="white" stroke="#dfc687" strokeWidth="2"/></svg><span><Compass size={12}/> ATLAS</span></button>
  <div className="world-objective"><span className="world-kicker">{country?'QUÊTE DU PAYS':'L’APPEL DES PORTES'}</span><strong>{country?`${save.beacons.filter(id=>id.startsWith(country.id+':')).length} / 3 souvenirs retrouvés`:`${save.seals.length} / 8 sceaux retrouvés`}</strong><p>{country?(save.seals.includes(country.id)?'Sceau obtenu · continue la collection.':'Crée un lien, retrouve les souvenirs et défie le gardien.'):'Traverse une porte pour découvrir son monde.'}</p><button onClick={()=>setPanel('journal')}>Voir le journal <ArrowUpRight size={14}/></button></div>
  {snapshot.waypoint&&<button className="world-waypoint" onClick={()=>scene.current?.waypoint(snapshot.waypoint,true)}><Compass size={16}/>{snapshot.waypoint.name} · {snapshot.remaining} m</button>}
  {gps&&<div className="world-gps-pill"><Footprints size={16}/>{walkSession} m · prochain écho dans {100-walkSession%100} m {outdoorEchoes>0&&<button onClick={()=>setPanel('gps')}>{outdoorEchoes} écho{outdoorEchoes>1?'s':''}</button>}</div>}
  <div className="world-player"><div className="world-avatar">K<span>{levelFor(save.xp)}</span></div><div><strong>Kaïs <small>Niv. {levelFor(save.xp)}</small></strong><progress aria-label="Progression du niveau monde" max={nextLevelXP(save.xp)-(levelFor(save.xp)-1)**2*90} value={save.xp-(levelFor(save.xp)-1)**2*90}/><span>{save.xp} XP monde · {save.shards} éclats</span></div></div>
  <div className="world-controls"><button onClick={()=>setPanel('collection')}><BookOpen size={21}/><span>Collection</span><small>{Object.keys(save.collection).length}/368</small></button><button onClick={()=>setPanel('team')}><Users size={21}/><span>Équipe</span><small>1 + {save.team.length}</small></button><button onClick={()=>setPanel('atlas')}><Map size={21}/><span>Atlas</span><small>8 pays</small></button><button onClick={()=>setPanel('gps')}><Footprints size={21}/><span>Dehors</span><small>{gps?'GPS actif':'GPS'}</small></button></div>
  <div className="world-interact">{near?<button className="world-primary" onClick={()=>scene.current?.interact()}><Sparkles size={19}/>{near.type==='portal'?'Traverser · ':near.type==='echo'?'Rencontrer · ':''}{near.name}<kbd>E</kbd></button>:<p>Glisse le doigt pour avancer · touche le sol pour t’y rendre</p>}</div>
  {snapshot.joystick&&<div className="world-joystick" style={{left:snapshot.joystick.x,top:snapshot.joystick.y}}><i style={{transform:`translate(${snapshot.joystick.dx}px,${snapshot.joystick.dy}px)`}}/></div>}
  {notice&&<div className="world-notice" role="status">{notice}</div>}
  {!loaded&&<div className="world-loading">Ouverture des huit portes…</div>}
  {error&&<div className="world-failure" role="alert"><h2>Reprendre l’exploration</h2><p>{error}</p><button className="world-primary" onClick={()=>location.reload()}>Recharger le monde</button><button onClick={()=>goTo('home')}>Retour à l’application</button></div>}
  {panel&&<Modal title={({collection:'Le Codex des liens',team:'Ton équipe',atlas:'L’Atlas des huit portes',journal:'Journal d’exploration',gps:'Les échos du dehors',pause:'Une pause dans le voyage',encounter:'Un écho te rencontre',final:'Le Portail de l’Union'})[panel]} onClose={()=>setPanel(null)} wide={['collection','atlas'].includes(panel)}>
   {panel==='collection'&&<Collection save={save} onChange={change} notice={announce}/>}
   {panel==='encounter'&&encounter&&<Encounter initial={encounter} onClose={()=>setPanel(null)} onActivity={()=>{activity.current=Date.now();}} onReward={(kind,id)=>{change(s=>kind==='victory'?seal(s,encounter.region):recruit(s,id));chime();}}/>}
   {panel==='team'&&<><p>Un Leader et trois Alliés. Leurs rôles se combinent. Un seul personnage neutre 3B peut faire partie de l’équipe.</p><div className="world-team-grid">{[save.leader,...save.team].map((id,i)=><div key={id}><span className="world-kicker">{i===0?'LEADER':'ALLIÉ '+i}</span><Card card={cardById[id]} owned onClick={()=>setPanel('collection')}/><p>{cardById[id].trait}</p>{i>0&&<button onClick={()=>change(s=>equip(s,id))}>Retirer</button>}</div>)}{save.team.length<3&&<button className="world-team-empty" onClick={()=>setPanel('collection')}>＋<strong>Ajouter un Allié</strong><span>Crée un pacte puis équipe sa carte.</span></button>}</div><div className="world-stat-row"><span>Vitalité <b>{stats.health}</b></span><span>Frappe <b>{stats.attack+stats.affinity}</b></span><span>Garde <b>+{stats.heal+8} vitalité</b></span></div><h3>Équipements actifs</h3><div className="world-equipment">{['terrain','ambiance','fragment','pierre','support','energy'].map(slot=><div key={slot}><small>{({energy:'Énergie',support:'Soutien'})[slot]||slot}</small><strong>{cardById[save.loadout[slot]]?.name||'Emplacement libre'}</strong>{save.loadout[slot]&&<button aria-label={'Déséquiper '+slot} onClick={()=>change(s=>equip(s,s.loadout[slot]))}><X size={15}/></button>}</div>)}<div><small>Pièges</small><strong>{save.loadout.traps.length} / 3 équipés</strong></div></div><button className="world-primary" onClick={()=>setPanel('collection')}>Ouvrir la collection et l’Atelier</button></>}
   {panel==='atlas'&&<><p>Les portes sont dispersées autour du Nexus. Choisis un itinéraire pour que Kaïs rejoigne la porte, puis traverse-la.</p><div className="world-atlas-grid">{(country?[{id:'hub',name:'Retour au Nexus',color:'#e4cd94'},...COUNTRIES]:COUNTRIES).map(c=><button key={c.id} style={{'--country-color':c.color}} onClick={()=>{if(snapshot.region!=='hub'){if(c.id==='hub')navigate(regionItems.find(i=>i.id==='hub'));else{announce('Rejoins d’abord la porte du Nexus pour changer de pays.');navigate(regionItems.find(i=>i.id==='hub'));}}else navigate(regionItems.find(i=>i.id===c.id));}}><span>{c.symbol||'◈'}</span><div><strong>{c.name}</strong><small>{save.seals.includes(c.id)?'◆ Sceau obtenu':save.visited.includes(c.id)?'Monde découvert':'À explorer'}</small></div><ArrowUpRight size={18}/></button>)}</div>{country&&<><h3>Points d’intérêt proches</h3><div className="world-point-list">{regionItems.filter(i=>i.type!=='portal').map(i=><button key={i.id} onClick={()=>navigate(i)}>{i.type==='beacon'?'◇ ':i.type==='guardian'?'♜ ':'✦ '}{i.name}<ArrowUpRight size={15}/></button>)}</div></>}</>}
   {panel==='journal'&&<><p>Les cinq premiers sceaux ouvrent le Portail final au centre du Nexus. Retrouve les huit pour achever le voyage.</p><div className="world-stat-row"><span>Sceaux <b>{save.seals.length}/8</b></span><span>Cartes <b>{Object.keys(save.collection).length}/368</b></span><span>Pactes et victoires <b>{save.wins}</b></span></div>{COUNTRIES.map(c=><article className="world-journal-country" key={c.id}><h3>{c.name} {save.seals.includes(c.id)?'◆':''}</h3><p>{save.visited.includes(c.id)?'✓ Pays découvert':'○ Traverser sa porte'} · {save.beacons.filter(id=>id.startsWith(c.id+':')).length}/3 souvenirs · {CARDS.filter(card=>card.country===c.id&&card.character&&save.collection[card.id]).length}/21 personnages nationaux</p><small>Missions d’exploration : obtenir un Fragment · réunir 3 personnages du pays · retrouver 3 souvenirs · obtenir un Terrain et une Ambiance du pays.</small></article>)}<p>Une nouvelle carte donne 100 XP monde et 25 éclats. Un doublon donne 35 XP et 12 éclats, puis renforce l’affinité tous les trois doublons. Un premier sceau donne 250 XP et 100 éclats.</p></>}
   {panel==='gps'&&<><div className="world-outdoor-icon"><Footprints size={38}/></div><h3>Le monde vient à ta rencontre.</h3><p>Marche où tu le souhaites. Tous les 100 mètres validés, un écho apparaît dans le pays que tu explores. Arrête-toi dans un endroit sûr pour jouer la rencontre.</p><p className="world-rule">Le décor affiché est virtuel. Aucune destination réelle n’est imposée. Tes coordonnées restent sur cet appareil et ne sont ni enregistrées ni envoyées au compte ; seule la distance totale est sauvegardée. Le GPS s’arrête quand tu quittes cet écran pour une autre application.</p><div className="world-stat-row"><span>Cette sortie <b>{walkSession} m</b></span><span>Total <b>{save.walked} m</b></span><span>Échos <b>{outdoorEchoes}</b></span></div><p role="status">{gpsMessage}</p><div className="world-actions"><button className="world-primary" onClick={gps?()=>stopGPS():startGPS}>{gps?'Arrêter le GPS':'Activer le GPS'}</button>{outdoorEchoes>0&&<button onClick={()=>{if(!country){announce('Traverse d’abord la porte d’un pays. Tes échos restent disponibles pour cette sortie.');return;}setOutdoorEchoes(n=>n-1);setEncounter({...makeEncounter(encounterCards(country.id,save)[0],save),region:country.id});setPanel('encounter');}}>Je suis à l’arrêt · rencontrer un écho</button>}</div><small>Les positions imprécises, les bonds de GPS et les déplacements trop rapides ne comptent pas. Garde le navigateur ouvert pendant la marche.</small></>}
   {panel==='pause'&&<><p className="world-save-status" role="status">{saveMessage}</p><p>{rewardMessage}</p><p>Les XP monde renforcent ton aventure. Les XP et points de fidélité sont gagnés par le temps de jeu actif, avec les plafonds partagés de ton compte.</p><div className="world-options"><button onClick={()=>setPanel(null)}><Play size={19}/> Reprendre</button><button onClick={()=>{shell.current?.requestFullscreen?.().catch(()=>announce('Le plein écran n’est pas disponible dans ce navigateur.'));setPanel(null);}}><Maximize size={19}/> Plein écran</button><button onClick={()=>setSound(s=>!s)}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>} Sons {sound?'activés':'désactivés'}</button><button onClick={sync}><RotateCcw size={19}/> Synchroniser</button><button onClick={exportSave}><Download size={19}/> Télécharger ma sauvegarde</button><label className="world-import">Restaurer une copie<input type="file" accept=".json,application/json" onChange={importSave}/></label><button onClick={()=>goTo('member')}><Users size={19}/>{uid?'Mon compte 3B':'Relier au compte 3B'}</button></div><details><summary>Commandes et état du rendu</summary><p>Glisse depuis n’importe quel endroit du décor pour déplacer Kaïs. Un toucher court définit une destination. Au clavier : flèches, ZQSD ou WASD ; E pour interagir ; Maj pour courir.</p><p>{snapshot.fps||'—'} images/s · {snapshot.drawCalls||'—'} appels de rendu. La performance dépend de ton appareil.</p></details><details><summary>Règles du dossier d’origine</summary>{SOURCE.rules.map(([name,text])=><p key={name}><b>{name} :</b> {text}</p>)}</details></>}
   {panel==='final'&&<div className="world-result"><Sparkles size={46}/><h3>Les portes se souviennent de toi.</h3><p>Le Portail de l’Union est éveillé. Ta première ouverture ajoute 500 XP monde et 250 éclats à ta progression.</p><p>{save.seals.length===8?'Les huit sceaux sont réunis. Continue à créer des liens et complète les 368 cartes.':`Il reste ${8-save.seals.length} gardien${8-save.seals.length>1?'s':''} à rencontrer pour réunir les huit sceaux.`}</p><button className="world-primary" onClick={()=>setPanel(null)}>Poursuivre le voyage</button></div>}
  </Modal>}
 </section>;
}
