import CompactCard from '../components/CompactCard.jsx';
import {useEffect,useState} from 'react';
import {ArrowUpRight,RefreshCw,Trophy} from 'lucide-react';
import {ECOSYSTEM_URL} from '../lib/ecosystem.js';
import {SPORTS} from '../../supabase/functions/ecosystem/sports.js';
import './sport.css';
export default function SportPage({goTo}){
 const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[sport,setSport]=useState('Tous'),[language,setLanguage]=useState('all');
 useEffect(()=>{const controller=new AbortController();let live=true,pending=false;const load=async()=>{if(pending||document.hidden)return;pending=true;setBusy(true);try{const r=await fetch(ECOSYSTEM_URL+'?section=sports',{signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Le flux est indisponible.');if(live){setData(d);setError('');}}catch(e){if(live)setError(e.message);}finally{pending=false;if(live)setBusy(false);}};load();const timer=setInterval(load,300000);document.addEventListener('visibilitychange',load);return()=>{live=false;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',load);};},[reload]);
 const articles=(data?.articles||[]).filter(a=>(sport==='Tous'||a.category===sport)&&(language==='all'||a.language===language));
 return <section className="editorial-page sport-page"><div className="sport-heading"><div className="editorial-heading"><p className="eyebrow">LE SPORT, AU QUOTIDIEN</p><h1>La passion<br/><em>n’a pas de frontières.</em></h1><p>L’actualité multisports, les idées de défis et les collaborations du collectif 3B.</p></div><Trophy className="sport-trophy" size={100} strokeWidth={.8}/></div><div className="sport-news-header"><div><span className="status-pill">{data?.stale?'Dernier flux conservé':busy?'Actualisation…':'Actualités'}</span><p>{data?.updatedAt?'Sources vérifiées le '+new Date(data.updatedAt).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'}):'Chargement des sources sportives…'}</p></div><button className="quiet-button" disabled={busy} onClick={()=>setReload(n=>n+1)}><RefreshCw size={16}/>Actualiser</button></div>
 <div className="sport-filters"><label>Discipline<select value={sport} onChange={e=>setSport(e.target.value)}>{SPORTS.map(s=><option key={s}>{s}</option>)}</select></label><label>Langue des articles<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="all">Français et anglais</option><option value="fr">Français</option><option value="en">Anglais</option></select></label><span>France 24 · BBC Sport</span></div>
 {error&&<p className="surface-notice" role="alert">{error}</p>}{data?.stale&&<p className="surface-notice">Les sources ne répondent pas actuellement. Les articles ci-dessous proviennent de la dernière actualisation réussie.</p>}{data?.partial&&<p className="muted-copy">Une source est indisponible ou ne fournit pas de titres récents. Les autres articles restent accessibles.</p>}
 <div className="sport-news-grid">{articles.map((a,i)=><a key={a.url} href={a.url} target="_blank" rel="noopener noreferrer" className={'sport-article '+(i===0?'sport-article-lead':'')}><div><span>{a.category}</span><span>{a.language==='fr'?'FR':'EN'}</span></div><h2>{a.title}</h2><footer><span>{a.source}<small>{new Date(a.publishedAt).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'})}</small></span><ArrowUpRight size={22}/></footer></a>)}</div>
 {data&&!articles.length&&<div className="surface-panel"><h2>Aucun article dans ce filtre pour le moment.</h2><p>Change de discipline ou de langue pour lire les autres actualités.</p><button className="quiet-button" onClick={()=>{setSport('Tous');setLanguage('all');}}>Voir toutes les actualités</button></div>}
 <p className="muted-copy">Les titres des sept derniers jours sont actualisés automatiquement et s’ouvrent sur le site de leur éditeur. La couverture dépend des sujets publiés par les sources. Les scores minute par minute ne sont pas encore proposés.</p>
 <div className="sport-community"><CompactCard title="Propose un défi" description="Lieu, date et niveau : prépare une rencontre dans le collectif." eyebrow="BOUGER ENSEMBLE" icon={<Trophy/>} onClick={()=>goTo('community')}/><CompactCard title="Imagine une collaboration" description="Crée un maillot et partage ton projet avec les membres." eyebrow="CRÉER UNE ÉQUIPE" icon={<Trophy/>} onClick={()=>goTo('ia-textile')}/></div></section>;
}

