import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Layers3,Shirt,Sparkles,Send,Mic,Square} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {ecosystem,ecosystemPublic} from '../lib/ecosystem.js';
import CompactCard from '../components/CompactCard.jsx';
import TextileStudio from './TextileStudio.jsx';
import './studio.css';
function useCapabilities(){const[caps,setCaps]=useState(null);useEffect(()=>{const c=new AbortController();ecosystemPublic('capabilities',{signal:c.signal}).then(setCaps).catch(()=>setCaps({}));return()=>c.abort();},[]);return caps;}
function TrioChat({goTo,caps}){
 const account=useLoyalty(),[input,setInput]=useState(''),[turns,setTurns]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[listening,setListening]=useState(false);const lock=useRef(false),recognition=useRef(null),inputRef=useRef(null);
 const ready=!!(caps?.gpt||caps?.claude||caps?.gemini),canSpeak=typeof window!=='undefined'&&!!(window.SpeechRecognition||window.webkitSpeechRecognition);
 useEffect(()=>()=>{if(recognition.current){recognition.current.onend=null;recognition.current.onerror=null;recognition.current.onresult=null;recognition.current.abort();}},[]);
 function dictate(){if(listening){recognition.current?.stop();return;}const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API)return;const r=new API();recognition.current=r;r.lang='fr-FR';r.interimResults=false;r.continuous=false;r.onresult=e=>{const words=Array.from(e.results).map(x=>x[0].transcript).join(' ');setInput(v=>(v+' '+words).trim().slice(0,4000));};r.onerror=e=>{setListening(false);setNotice(e.error==='not-allowed'?'Le microphone n’est pas autorisé dans ce navigateur. Tu peux écrire ton message.':'La dictée s’est interrompue. Tu peux réessayer.');};r.onend=()=>setListening(false);try{r.start();setListening(true);setNotice('Dictée du navigateur activée. Ton message ne sera envoyé qu’après appui sur Envoyer.');}catch{setListening(false);setNotice('La dictée est indisponible dans ce navigateur.');}}
 async function send(e){e.preventDefault();if(!account.user){goTo('member');return;}if(lock.current||!input.trim())return;const prompt=input.trim();lock.current=true;setBusy(true);recognition.current?.stop();setNotice('');try{const context=turns.slice(-4).flatMap(t=>[{role:'user',content:t.prompt.slice(0,1500)},{role:'assistant',content:t.answer.slice(0,1500)}]);const result=await ecosystem('chat-ai',{messages:[...context,{role:'user',content:prompt}]});setTurns(t=>[...t,{prompt,...result}]);setInput('');}catch(e){setNotice(e.message);}finally{lock.current=false;setBusy(false);}}
 return <div className="trio-workspace trio-simple"><div className="trio-toolbar"><p className="eyebrow">UNE QUESTION. UNE RÉPONSE CLAIRE.</p><button className="quiet-button" disabled={busy||!turns.length} onClick={()=>{setTurns([]);setNotice('');inputRef.current?.focus();}}>Nouvelle conversation</button></div>{!turns.length&&<div className="trio-empty"><Sparkles size={28}/><h2>Que veux-tu explorer ?</h2><p>Écris ou dicte ta question. Les IA disponibles travaillent ensemble automatiquement.</p><div className="compact-list">{['Aide-moi à imaginer une collection 3B.','Explique-moi un sujet simplement.','Transforme mon idée en plan concret.'].map(p=><CompactCard key={p} title={p} action="" onClick={()=>{setInput(p);inputRef.current?.focus();}}/>)}</div></div>}<div className="trio-turns" aria-live="polite">{turns.map((t,i)=><section key={i}><h2>{t.prompt}</h2><article className="trio-answer"><p>{t.answer}</p>{t.partial&&<small>Un service n’a pas répondu ; la réponse utilise les services disponibles.</small>}{t.synthesized===false&&t.contributors?.length>1&&<small>La synthèse est indisponible ; la réponse du premier service disponible est affichée.</small>}</article></section>)}</div>{notice&&<p className="surface-notice" role="status">{notice}</p>}<form className="trio-composer" onSubmit={send}><label htmlFor="trio-question">Ta question</label><textarea ref={inputRef} id="trio-question" required maxLength={4000} rows={3} disabled={busy} value={input} onChange={e=>setInput(e.target.value)} placeholder="Pose ta question, simplement…"/><div className="trio-send-row">{canSpeak&&<button className="quiet-button" type="button" disabled={busy} aria-pressed={listening} onClick={dictate}>{listening?<Square size={16}/>:<Mic size={16}/>} {listening?'Arrêter la dictée':'Parler'}</button>}<button className="surface-button" disabled={!ready||busy||!input.trim()}><Send size={17}/>{busy?'Réponse en cours…':'Envoyer'}</button></div><p>{ready?'Ton texte est transmis aux services IA disponibles pour préparer la réponse.':'L’espace est prêt. Les services IA attendent leur activation ; tu peux préparer ta question.'}</p></form><details className="studio-options"><summary>Comment utiliser Mode 3 IA ?</summary><p>Donne ton objectif, le contexte et le résultat souhaité. Tu peux demander une explication, comparer des idées ou construire un plan, puis préciser ta demande dans la même conversation.</p><p>GPT, Claude et Gemini sont intégrés sans réglage à effectuer. Après activation, les services disponibles répondent et une synthèse est préparée. Ils peuvent se tromper et ne disposent pas ici d’une recherche web en direct.</p><p>Jusqu’à 20 demandes par jour et par membre. La conversation reste dans cet onglet et disparaît au rechargement. La dictée dépend du navigateur et demande ton autorisation pour le microphone. Selon le navigateur, l’audio peut être transmis à son service de reconnaissance vocale.</p></details></div>;
}
export default function AiPage({page,goTo}){
 const caps=useCapabilities(),textile=page==='ia-textile',trio=page==='ia-trio',detail=textile||trio;
 return <section className="editorial-page studio-page">{detail&&<button className="quiet-button" onClick={()=>goTo('ia')}><ArrowLeft size={16}/>Espace IA</button>}<div className="editorial-heading"><p className="eyebrow">L’INTELLIGENCE AU SERVICE DES IDÉES</p><h1>{textile?'L’atelier 3B.':trio?'Mode 3 IA.':'Imagine la suite.'}</h1><p>{textile?'Dessine un vrai maillot. Du concept au brief atelier.':trio?'Écris ou parle. On s’occupe de la suite.':'Deux entrées simples pour créer et avancer.'}</p></div>{!detail&&<div className="compact-list"><CompactCard title="IA textile" eyebrow="ATELIER & CRÉATIONS" description="Maillots premium : coupe, patronage, couleurs, identité, production et rendu IA." icon={<Shirt size={25}/>} onClick={()=>goTo('ia-textile')}/><CompactCard title="Mode 3 IA" eyebrow="TON ASSISTANT" description="Pose ta question. GPT, Claude et Gemini sont intégrés automatiquement." icon={<Layers3 size={25}/>} onClick={()=>goTo('ia-trio')}/></div>}{textile&&<TextileStudio goTo={goTo} caps={caps}/>} {trio&&<TrioChat goTo={goTo} caps={caps}/>}</section>;
}

