import {placementsFor,selectGarment} from './studio-options.js';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Layers3,Shirt,Sparkles,Send,Download,Mic,Square,Check} from 'lucide-react';
import {GARMENT_GROUPS,GARMENTS,MATERIAL_GROUPS,MATERIALS,CUTS,PATTERNS,TECHNIQUES,DEFAULT_DESIGN,garmentFamily,textilePrompt,validateDesign} from '../../shared/studio.js';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {ECOSYSTEM_URL,ecosystem} from '../lib/ecosystem.js';
import CompactCard from '../components/CompactCard.jsx';
import DesignPreview from './DesignPreview.jsx';
import './studio.css';
function useCapabilities(){const[caps,setCaps]=useState(null);useEffect(()=>{const c=new AbortController();fetch(ECOSYSTEM_URL+'?section=capabilities',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setCaps).catch(()=>setCaps({}));return()=>c.abort();},[]);return caps;}
function readDraft(){try{const saved=JSON.parse(localStorage.getItem('3b-studio-config')||'null');return saved?{design:validateDesign(saved.design||saved),idea:typeof saved.idea==='string'?saved.idea.slice(0,2000):''}:{design:DEFAULT_DESIGN,idea:''};}catch{return {design:DEFAULT_DESIGN,idea:''};}}
function GroupOptions({groups}){return Object.entries(groups).map(([label,options])=><optgroup label={label} key={label}>{options.map(x=><option key={x}>{x}</option>)}</optgroup>);}
const PRESETS={Essentiel:{material:'Coton épais',pattern:'Uni',techniques:['Broderie'],color:'#14191e',accent:'#e4c17b'},Sport:{material:'Jersey technique',pattern:'Rayures',techniques:['Sublimation'],color:'#142e45',accent:'#e4c17b'},Signature:{material:'Jacquard',pattern:'Monogramme',techniques:['Jacquard tissé'],color:'#172523',accent:'#cfba83'}};
function TextileStudio({goTo,caps}){
 const account=useLoyalty(),[saved]=useState(readDraft),[design,setDesign]=useState(saved.design),[idea,setIdea]=useState(saved.idea),[step,setStep]=useState(0),[family,setFamily]=useState(()=>garmentFamily(saved.design.garment)),[generated,setGenerated]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const lock=useRef(false),stepTitle=useRef(null);
 function change(key,value){setDesign(d=>key==='garment'?selectGarment(d,value):({...d,[key]:value}));setGenerated(null);}
 function next(value){setStep(value);setTimeout(()=>stepTitle.current?.focus({preventScroll:true}),0);}
 function save(){try{localStorage.setItem('3b-studio-config',JSON.stringify({design,idea}));setNotice('Concept enregistré sur cet appareil.');}catch{setNotice('Sauvegarde indisponible. Exporte ton brief pour le conserver.');}}
 function exportBrief(){const url=URL.createObjectURL(new Blob([textilePrompt(design,idea)],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='3b-brief-creation.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function generate(){if(!account.user){goTo('member');return;}if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{setGenerated(await ecosystem('generate',{design,idea}));setNotice('Visuel prêt. Tu peux préparer ta publication.');}catch(e){setNotice(e.message);}finally{lock.current=false;setBusy(false);}}
 function share(){try{sessionStorage.setItem('3b-studio-share',JSON.stringify({design,idea,assetPath:generated?.assetPath}));goTo('community');}catch{setNotice('Le partage est indisponible. Exporte le brief pour le conserver.');}}
 return <><nav className="studio-steps" aria-label="Étapes de création">{['Pièce','Style','Finaliser'].map((name,i)=><button key={name} disabled={busy} aria-current={step===i?'step':undefined} onClick={()=>next(i)}><span>{i+1}</span>{name}</button>)}</nav><div className="studio-layout studio-simple"><div className="studio-preview-panel"><div className="studio-preview-top"><span>{design.customGarment||design.garment}</span><span>{generated?'VISUEL IA':'APERÇU DU CONCEPT'}</span></div>{generated?<img className="studio-generated" src={generated.imageUrl} alt={'Concept IA de '+design.garment}/>:<DesignPreview design={design}/>}<div className="surface-tabs" aria-label="Vue de la pièce">{['Face','Dos'].map(view=><button key={view} disabled={busy} aria-pressed={design.view===view} onClick={()=>change('view',view)}>{view}</button>)}</div></div>
 <section className="surface-panel surface-form studio-step-panel"><h2 ref={stepTitle} tabIndex={-1}>{['Choisis ta pièce.','Donne-lui ton style.','Ton concept est prêt.'][step]}</h2>
 {step===0&&<><p>Commence par une famille, puis choisis ta pièce. Tout reste modifiable.</p><label>Famille<select value={family} onChange={e=>{const f=e.target.value;setFamily(f);change('garment',GARMENT_GROUPS[f][0]);}}>{Object.keys(GARMENT_GROUPS).map(f=><option key={f}>{f}</option>)}</select></label><label>Pièce<select value={design.garment} onChange={e=>change('garment',e.target.value)}>{GARMENT_GROUPS[family].map(g=><option key={g}>{g}</option>)}</select></label>{design.garment==='Autre pièce'&&<label>Quelle pièce imagines-tu ?<input maxLength={160} value={design.customGarment} onChange={e=>change('customGarment',e.target.value)} placeholder="Décris ta pièce sur mesure"/></label>}<p className="muted-copy">{GARMENTS.length} modèles de départ, de la pièce unique à la tenue complète.</p></>}
 {step===1&&<><p>Trois pistes pour commencer, puis les couleurs de ton choix.</p><div className="studio-presets">{Object.entries(PRESETS).map(([label,values])=><button className="quiet-button" key={label} onClick={()=>{setDesign(d=>({...d,...values}));setGenerated(null);}}>{label}</button>)}</div><div className="studio-colors"><label>Couleur principale<input type="color" value={design.color} onChange={e=>change('color',e.target.value)}/></label><label>Couleur des détails<input type="color" value={design.accent} onChange={e=>change('accent',e.target.value)}/></label></div><label>Motif<select value={design.pattern} onChange={e=>change('pattern',e.target.value)}>{PATTERNS.map(x=><option key={x}>{x}</option>)}</select></label><details className="studio-options"><summary>Matière, coupe et finitions <span>Personnaliser</span></summary><div className="surface-form"><label>Matière<select value={design.material} onChange={e=>change('material',e.target.value)}><GroupOptions groups={MATERIAL_GROUPS}/></select></label><label>Mélange ou autre matière<input maxLength={160} value={design.customMaterial} onChange={e=>change('customMaterial',e.target.value)} placeholder="Facultatif · composition, doublure…"/></label><label>Coupe<select value={design.cut} onChange={e=>change('cut',e.target.value)}>{CUTS.map(x=><option key={x}>{x}</option>)}</select></label><label>Logo 3B<select value={design.placement} onChange={e=>change('placement',e.target.value)}>{placementsFor(design.garment).map(x=><option key={x}>{x}</option>)}</select></label><label>Ajouter une technique<select value="" disabled={design.techniques.length>=8} onChange={e=>{if(e.target.value)change('techniques',[...new Set([...design.techniques,e.target.value])]);}}><option value="">Choisir parmi {TECHNIQUES.length} techniques</option>{TECHNIQUES.filter(t=>!design.techniques.includes(t)).map(t=><option key={t}>{t}</option>)}</select></label><div className="technique-chips">{design.techniques.map(t=><button key={t} className="quiet-button" aria-label={'Retirer '+t} onClick={()=>change('techniques',design.techniques.filter(x=>x!==t))}>{t} ×</button>)}</div><label>Autre technique ou finition<input maxLength={160} value={design.customTechnique} onChange={e=>change('customTechnique',e.target.value)} placeholder="Facultatif · ton idée précise"/></label><label>Nom, numéro ou inscription<input maxLength={160} value={design.personalization} onChange={e=>change('personalization',e.target.value)} placeholder="Facultatif · exemple : KAÏS 03"/></label></div></details></>}
 {step===2&&<><dl className="design-summary"><div><dt>Pièce</dt><dd>{design.customGarment||design.garment}</dd></div><div><dt>Style</dt><dd>{design.pattern} · {design.cut}</dd></div><div><dt>Matière</dt><dd>{design.material}{design.customMaterial?' · '+design.customMaterial:''}</dd></div><div><dt>Finitions</dt><dd>{design.techniques.join(', ')||'À définir'}</dd></div></dl><label>Un détail à ajouter ?<textarea rows={2} maxLength={2000} value={idea} disabled={busy} onChange={e=>{setIdea(e.target.value);setGenerated(null);}} placeholder="Tailles souhaitées, inspirations, usage…"/></label><button className="surface-button" disabled={busy} onClick={share}>Proposer à la communauté <ArrowRight size={17}/></button><div className="studio-actions"><button className="quiet-button" disabled={busy} onClick={save}><Check size={16}/>Sauvegarder</button><button className="quiet-button" onClick={exportBrief}><Download size={16}/>Exporter le brief</button></div><details className="studio-options"><summary>Créer un visuel avec l’IA</summary><p>{caps?.image?'Ton brief sera transmis à OpenAI. Jusqu’à 3 générations par jour et par membre.':'La génération de visuels attend l’activation du service IA. Ton concept et son partage sont disponibles.'}</p><button className="surface-button" disabled={busy||!caps?.image} onClick={generate}><Sparkles size={17}/>{busy?'Création du visuel…':'Générer le visuel'}</button></details><details className="studio-options"><summary>Lire mon brief complet</summary><p className="studio-brief">{textilePrompt(design,idea)}</p></details></>}
 <div className="studio-step-actions">{step>0&&<button className="quiet-button" disabled={busy} onClick={()=>next(step-1)}><ArrowLeft size={16}/>Retour</button>}{step<2&&<button className="surface-button" onClick={()=>next(step+1)}>Continuer <ArrowRight size={16}/></button>}</div></section></div>{notice&&<p className="surface-notice" role="status">{notice}</p>}<p className="muted-copy studio-fabrication-note">{MATERIALS.length} matières et {TECHNIQUES.length} techniques pour explorer. L’aperçu est schématique ; les associations, tailles et finitions seront étudiées par un atelier avant fabrication. Les votes de la communauté peuvent faire émerger une future pièce 3B.</p></>;
}
function TrioChat({goTo,caps}){
 const account=useLoyalty(),[input,setInput]=useState(''),[turns,setTurns]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[listening,setListening]=useState(false);const lock=useRef(false),recognition=useRef(null),inputRef=useRef(null);
 const ready=!!(caps?.gpt||caps?.claude||caps?.gemini),canSpeak=typeof window!=='undefined'&&!!(window.SpeechRecognition||window.webkitSpeechRecognition);
 useEffect(()=>()=>{if(recognition.current){recognition.current.onend=null;recognition.current.onerror=null;recognition.current.onresult=null;recognition.current.abort();}},[]);
 function dictate(){if(listening){recognition.current?.stop();return;}const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API)return;const r=new API();recognition.current=r;r.lang='fr-FR';r.interimResults=false;r.continuous=false;r.onresult=e=>{const words=Array.from(e.results).map(x=>x[0].transcript).join(' ');setInput(v=>(v+' '+words).trim().slice(0,4000));};r.onerror=e=>{setListening(false);setNotice(e.error==='not-allowed'?'Le microphone n’est pas autorisé dans ce navigateur. Tu peux écrire ton message.':'La dictée s’est interrompue. Tu peux réessayer.');};r.onend=()=>setListening(false);try{r.start();setListening(true);setNotice('Dictée du navigateur activée. Ton message ne sera envoyé qu’après appui sur Envoyer.');}catch{setListening(false);setNotice('La dictée est indisponible dans ce navigateur.');}}
 async function send(e){e.preventDefault();if(!account.user){goTo('member');return;}if(lock.current||!input.trim())return;const prompt=input.trim();lock.current=true;setBusy(true);recognition.current?.stop();setNotice('');try{const context=turns.slice(-4).flatMap(t=>[{role:'user',content:t.prompt.slice(0,1500)},{role:'assistant',content:t.answer.slice(0,1500)}]);const result=await ecosystem('chat-ai',{messages:[...context,{role:'user',content:prompt}]});setTurns(t=>[...t,{prompt,...result}]);setInput('');}catch(e){setNotice(e.message);}finally{lock.current=false;setBusy(false);}}
 return <div className="trio-workspace trio-simple"><div className="trio-toolbar"><p className="eyebrow">UNE QUESTION. UNE RÉPONSE CLAIRE.</p><button className="quiet-button" disabled={busy||!turns.length} onClick={()=>{setTurns([]);setNotice('');inputRef.current?.focus();}}>Nouvelle conversation</button></div>{!turns.length&&<div className="trio-empty"><Sparkles size={28}/><h2>Que veux-tu explorer ?</h2><p>Écris ou dicte ta question. Les IA disponibles travaillent ensemble automatiquement.</p><div className="compact-list">{['Aide-moi à imaginer une collection 3B.','Explique-moi un sujet simplement.','Transforme mon idée en plan concret.'].map(p=><CompactCard key={p} title={p} action="" onClick={()=>{setInput(p);inputRef.current?.focus();}}/>)}</div></div>}<div className="trio-turns" aria-live="polite">{turns.map((t,i)=><section key={i}><h2>{t.prompt}</h2><article className="trio-answer"><p>{t.answer}</p>{t.partial&&<small>Un service n’a pas répondu ; la réponse utilise les services disponibles.</small>}{t.synthesized===false&&t.contributors?.length>1&&<small>La synthèse est indisponible ; la réponse du premier service disponible est affichée.</small>}</article></section>)}</div>{notice&&<p className="surface-notice" role="status">{notice}</p>}<form className="trio-composer" onSubmit={send}><label htmlFor="trio-question">Ta question</label><textarea ref={inputRef} id="trio-question" required maxLength={4000} rows={3} disabled={busy} value={input} onChange={e=>setInput(e.target.value)} placeholder="Pose ta question, simplement…"/><div className="trio-send-row">{canSpeak&&<button className="quiet-button" type="button" disabled={busy} aria-pressed={listening} onClick={dictate}>{listening?<Square size={16}/>:<Mic size={16}/>} {listening?'Arrêter la dictée':'Parler'}</button>}<button className="surface-button" disabled={!ready||busy||!input.trim()}><Send size={17}/>{busy?'Réponse en cours…':'Envoyer'}</button></div><p>{ready?'Ton texte est transmis aux services IA disponibles pour préparer la réponse.':'L’espace est prêt. Les services IA attendent leur activation ; tu peux préparer ta question.'}</p></form><details className="studio-options"><summary>Comment utiliser Mode 3 IA ?</summary><p>Donne ton objectif, le contexte et le résultat souhaité. Tu peux demander une explication, comparer des idées ou construire un plan, puis préciser ta demande dans la même conversation.</p><p>GPT, Claude et Gemini sont intégrés sans réglage à effectuer. Après activation, les services disponibles répondent et une synthèse est préparée. Ils peuvent se tromper et ne disposent pas ici d’une recherche web en direct.</p><p>Jusqu’à 20 demandes par jour et par membre. La conversation reste dans cet onglet et disparaît au rechargement. La dictée dépend du navigateur et demande ton autorisation pour le microphone. Selon le navigateur, l’audio peut être transmis à son service de reconnaissance vocale.</p></details></div>;
}
export default function AiPage({page,goTo}){
 const caps=useCapabilities(),textile=page==='ia-textile',trio=page==='ia-trio',detail=textile||trio;
 return <section className="editorial-page studio-page">{detail&&<button className="quiet-button" onClick={()=>goTo('ia')}><ArrowLeft size={16}/>Espace IA</button>}<div className="editorial-heading"><p className="eyebrow">L’INTELLIGENCE AU SERVICE DES IDÉES</p><h1>{textile?'L’atelier 3B.':trio?'Mode 3 IA.':'Imagine la suite.'}</h1><p>{textile?'Une pièce. Ton style. Trois étapes.':trio?'Écris ou parle. On s’occupe de la suite.':'Deux entrées simples pour créer et avancer.'}</p></div>{!detail&&<div className="compact-list"><CompactCard title="IA textile" eyebrow="ATELIER & CRÉATIONS" description="Vêtements, sacs et accessoires. Crée ton concept en trois étapes." icon={<Shirt size={25}/>} onClick={()=>goTo('ia-textile')}/><CompactCard title="Mode 3 IA" eyebrow="TON ASSISTANT" description="Pose ta question. GPT, Claude et Gemini sont intégrés automatiquement." icon={<Layers3 size={25}/>} onClick={()=>goTo('ia-trio')}/></div>}{textile&&<TextileStudio goTo={goTo} caps={caps}/>} {trio&&<TrioChat goTo={goTo} caps={caps}/>}</section>;
}

