export const KEY_RACE_URL='https://troisb-course-des-cles-demo.stetienne86pp.chatgpt.site/';
export const GAME_CATALOG=[
  {id:'penalty-rush',number:'01',title:'PENALTY RUSH',genre:'FOOT · DUEL 1V1',time:'En ligne',text:'Affronte un autre joueur en duel : dribbles, feintes, tirs, gardien jouable, carrière et sélections 3B.',control:'Deux zones tactiles : déplacement à gauche, gestes contextuels à droite.',action:'Jouer'},
  {id:'arena',number:'02',title:'Kaïs contre les Ombres',genre:'SURVIE · ACTION',time:'5–10 min',text:'Esquive les ombres. Assemble tes pouvoirs. Libère les huit gardiens.',control:'Glisse le doigt dans la zone de jeu pour bouger. Relâche pour arrêter. Bouton Esquive ou Espace ; flèches / ZQSD / WASD au clavier.',action:'Esquive'},
  {id:'tower',number:'03',title:'La Porte interdite',genre:'ACTION 3D · EXPLORATION',time:'100 niveaux',text:'Incarne Kaïs. Explore les ruines, maîtrise Fracture Matrix et affronte le Gardien du Cercle Brisé.',control:'Flèches / ZQSD / WASD ou joystick : déplacement. J : frappe, K maintenu : charge, Espace : esquive, R : Fracture Matrix, F : parade, E : interaction.',action:'Frapper'},
  {id:'maze',number:'04',title:'Le Labyrinthe de l’Oubli',genre:'EXPLORATION · INFILTRATION',time:'100 niveaux',text:'100 niveaux, dix chapitres. Retrouve les sceaux, maîtrise l’ombre et renforce ta lumière.',control:'Retrouve les trois sceaux, puis reviens au portail. Glisse pour marcher, ou utilise les flèches / ZQSD / WASD. L’éclat de lumière (E ou Espace) repousse l’ombre proche et dessine un chemin. La carte (M) met le jeu en pause. Les murs te cachent ; les lanternes rechargent ta lumière.',action:'Éclat de lumière'},
  {id:'key-race',number:'05',title:'La course des clés',genre:'LA PREMIÈRE AVENTURE',time:'Accès libre',text:'Retrouve l’aventure originale de la course des clés.',href:KEY_RACE_URL},
  {id:'dada3b',number:'06',title:'DADA 3B — Le Cercle des 8 Portes',genre:'STRATÉGIE · PLATEAU',time:'2–8 joueurs',text:'Le jeu de dada réinventé pour les huit pays 3B : écuries, dé serveur, Sanctuaires, Boucliers et course jusqu’au Nexus.',control:'Appuie sur le dé. Un 6 ouvre l’écurie et donne un nouveau lancer. Quand plusieurs Totems peuvent bouger, choisis celui qui brille.',action:'Lancer le dé'},
  {id:'power3b',number:'07',title:'Power 3B',genre:'STRATÉGIE · CONQUÊTE',time:'8 nations · 45–90 min',text:'Programme cinq ordres, commande terre, mer et air, augmente ton Power et conquiers les sept QG adverses.',control:'Sélectionne tes unités, programme jusqu’à cinq ordres puis exécute la manche. Les huit commandements jouent simultanément.',action:'Exécuter'},
];
