import React,{useState} from 'react';
import {Lock,Play,Star,Check,ArrowUpRight,KeyRound} from 'lucide-react';
import {DOOR_CHAPTERS,DOOR_PERKS,doorUnlocked} from './door-campaign.js';

export function DoorCampaign({game,profile,onSelect,onStart,onBenefits}){
 const [chapter,setChapter]=useState(Math.floor((game.stageNumber-1)/10)),c=game.campaign,unlocked=doorUnlocked(c),next=DOOR_PERKS.find(p=>p.at>c.completed.length);
 return <div className="door-campaign">
  <div className="door-campaign-hero"><div><span className="door-eyebrow">L’AVENTURE DE KAÏS · 100 NIVEAUX</span><h2>Chaque porte<br/>a son secret.</h2><p>Lis les signes. Défie les gardiens.<br/>Rassemble les sceaux et ouvre la Porte interdite.</p></div><span className="door-hero-emblem" aria-hidden="true"><KeyRound size={42}/></span></div>
  <div className="door-campaign-body">
   <div className="door-progress-title"><strong>Ton voyage</strong><span>{c.completed.length} / 100 niveaux</span><span><Star size={14}/>{Object.values(c.best).reduce((n,b)=>n+b.stars,0)} / 300</span></div>
   <div className="door-progress" role="progressbar" aria-label="Campagne terminée" aria-valuemin={0} aria-valuemax={100} aria-valuenow={c.completed.length}><i style={{width:c.completed.length+'%'}}/></div>
   <nav className="door-chapters" aria-label="Chapitres de La Porte interdite">{DOOR_CHAPTERS.map((name,i)=><button key={name} aria-pressed={chapter===i} aria-label={`Chapitre ${i+1} : ${name}`} onClick={()=>setChapter(i)}>{String(i+1).padStart(2,'0')}</button>)}</nav>
   <p className="door-chapter-title">{DOOR_CHAPTERS[chapter]} <span>Niveaux {chapter*10+1}–{chapter*10+10}</span></p>
   <div className="door-levels" aria-label="Choisir un niveau">{Array.from({length:10},(_,i)=>chapter*10+i+1).map(n=><button key={n} disabled={n>unlocked} aria-pressed={game.stageNumber===n} aria-label={`Niveau ${n}${n>unlocked?' · verrouillé':c.best[n]?' · '+c.best[n].stars+' étoiles':''}`} onClick={()=>onSelect(n)} data-boss={n%10===0}><strong>{n}</strong>{n>unlocked?<Lock size={13}/>:c.best[n]?<small>{'★'.repeat(c.best[n].stars)}</small>:<Play size={13}/>}</button>)}</div>
   <div className="door-level-summary"><span>Niveau {game.stageNumber} · {game.difficulty.label}</span><span>{game.difficulty.rooms} sceaux{game.difficulty.boss?' + gardien du chapitre':''}</span></div>
   <button className="door-primary door-start" onClick={onStart}><Play size={18}/>{game.time>0?`Reprendre le niveau ${game.stageNumber}`:`Entrer dans le niveau ${game.stageNumber}`}</button>
   <div className="door-campaign-extras"><div><span className="door-eyebrow">TES TALENTS</span><strong>{next?next.title:'Tous les talents débloqués'}</strong><p>{next?`${next.text} · après ${next.at} niveaux réussis.`:'Vitalité, frappe, concentration et réserve renforcées.'}</p><div className="door-perk-marks">{DOOR_PERKS.map(p=><span key={p.at} title={p.title+' : '+p.text} data-earned={c.completed.length>=p.at}>{c.completed.length>=p.at?<Check size={12}/>:<Lock size={12}/>} {p.at}</span>)}</div></div><div><span className="door-eyebrow">XP & AVANTAGES 3B</span><strong>{profile?profile.xp.toLocaleString('fr-FR')+' XP':'20 XP + 1 point / minute active'}</strong><p>Les étoiles et les talents suivent ton aventure. Ton compte 3B cumule les récompenses.</p><button className="door-link" onClick={onBenefits}>{profile?'Voir mes avantages':'Relier mon compte'}<ArrowUpRight size={14}/></button></div></div>
   <details className="door-rules"><summary>Comprendre le jeu et les récompenses</summary><p>À chaque salle, choisis une épreuve : combat tactique, énigme de runes ou mécanisme de précision. Chaque réussite donne un sceau et une bénédiction. Réunis tous les sceaux pour ouvrir la Porte. Tous les dix niveaux, un gardien final protège le passage.</p><p>Trois étoiles : terminer le niveau, ne commettre aucune erreur et ne boire aucun élixir. Une frappe contre une garde ou un assaut chargé encore actif compte comme une erreur, comme une réponse de runes ou un verrouillage incorrect. Les talents des niveaux 10, 25, 50 et 75 sont permanents.</p><p>Les seuils et bénédictions sont sauvegardés automatiquement. Quitter une épreuve ramène au dernier seuil. Clavier : 1, 2, 3 pour les portes et actions de combat, Entrée pour confirmer, Espace pour verrouiller, P ou Échap pour la pause. Toutes les actions sont aussi tactiles.</p><p>Sur le compte 3B : 20 XP et 1 point par minute active, dans les plafonds quotidiens de 600 XP et 20 points. Les scores, étoiles et sauvegardes importées ne créditent pas d’XP. Les invités conservent leur campagne.</p></details>
  </div>
 </div>;
}

export function DoorResult({game,onNext,onReplay,onLevels}){
 return <section className="door-moment door-result"><span className="door-moment-symbol" aria-hidden="true"><KeyRound size={46}/></span><span className="door-eyebrow">NIVEAU {game.stageNumber} / 100</span><h2>{game.won?game.stageNumber===100?'Le dernier secret.':'La Porte est ouverte.':'Le seuil te résiste.'}</h2><p>{game.message}</p>{game.won&&<div className="door-stars" aria-label={game.stars+' étoiles'}>{[1,2,3].map(n=><Star key={n} size={31} fill={n<=game.stars?'currentColor':'none'} opacity={n<=game.stars?1:.25}/>)}</div>}<div className="door-result-details"><span><strong>{game.score}</strong>fragments</span><span><strong>{game.mistakes}</strong>erreur{game.mistakes!==1?'s':''}</span><span><strong>{game.usedElixirs}</strong>élixir{game.usedElixirs!==1?'s':''}</span></div>{game.won&&<p className="door-muted">{game.firstClear?'Ta progression est sauvegardée.':'Ton meilleur résultat reste conservé.'}</p>}{game.won&&game.stageNumber<100&&<button className="door-primary" onClick={onNext}>Continuer · niveau {game.stageNumber+1}<Play size={17}/></button>}<button className={game.won?'door-secondary':'door-primary'} onClick={onReplay}>Rejouer ce niveau</button><button className="door-link" onClick={onLevels}>Les 100 niveaux</button></section>;
}
