import React from 'react';
import {Sword,Shield,ShieldOff,Sun,Moon,Star,Flame,Leaf,ArrowRight,Undo2,Heart,Sparkles,KeyRound,Check,Focus} from 'lucide-react';
import {INTENTS} from './tower.js';
const ICONS={sun:Sun,moon:Moon,star:Star,flame:Flame,leaf:Leaf};
export function Rune({id,size=24}){const Icon=ICONS[id];return Icon?<Icon size={size}/>:<span>·</span>;}
export function DoorChoices({game:g,invoke}){
 const selected=g.doors[g.selectedDoor];
 return <section className="door-choices"><div className="door-scene-heading"><span className="door-eyebrow">SEUIL {g.passed+1} / {g.difficulty.rooms}</span><h2>Choisis ton épreuve.</h2><p>Trois chemins. Un sceau à retrouver.</p></div><div className="door-cards">{g.doors.map((d,i)=><button key={d.type} className="door-card" aria-pressed={g.selectedDoor===i} onClick={()=>invoke('selectDoor',i)}><span className="door-card-picture" style={{backgroundPosition:(d.art*50)+'% 12%'}}><small>{String(i+1).padStart(2,'0')}</small><span>{d.type==='combat'?<Sword/>:d.type==='runes'?<Sun/>:<Focus/>}</span></span><span className="door-card-copy"><strong>{d.title}</strong><span>{d.hint}</span><small>{d.reward} fragments</small></span></button>)}</div><div className="door-inspect"><p>{selected?selected.detail:'Sélectionne une porte pour lire son indice.'}</p><button className="door-primary" disabled={!selected} onClick={()=>invoke('door')}>Franchir cette porte<ArrowRight size={18}/></button></div></section>;
}
export function DoorCombat({game:g,invoke,canvasRef}){
 const e=g.enemy,intent=INTENTS[e.intent],power=16+g.perks.attack+g.bonusAttack+(g.counter?8:0);
 return <section className="door-combat"><div className="door-enemy-label"><span className="door-eyebrow">{e.boss?'GARDIEN DU CHAPITRE':'DUEL AU TOUR PAR TOUR'}</span><strong>{e.boss?'Le Veilleur du seuil':'La Sentinelle de bronze'}</strong><div className="door-enemy-health"><i style={{width:e.hp/e.maxHp*100+'%'}}/></div><small>{e.hp} / {e.maxHp} vitalité</small></div><canvas ref={canvasRef} className="door-battle-canvas" aria-label="Kaïs face à la sentinelle de bronze"/><div className="door-combat-console"><div className="door-intent" data-intent={e.intent}><span className="door-intent-icon">{e.intent==='guard'?<Shield size={28}/>:e.intent==='heavy'?<Flame size={28}/>:<Sword size={28}/>}</span><div><span className="door-eyebrow">{g.busy>0?'ACTION EN COURS':'SON INTENTION'}</span><strong>{intent.name}</strong><p>{intent.hint}</p></div><small>Ensuite : {INTENTS[e.pattern[(e.turn+1)%e.pattern.length]].name}</small></div>{g.counter&&<p className="door-counter"><Sparkles size={15}/>Riposte prête · +8 à la prochaine frappe</p>}<div className="door-tactics"><button disabled={!g.canAct||g.focus<1} onClick={()=>invoke('attack')}><Sword size={23}/><strong>Frapper</strong><span>{power} dégâts · 1 concentration</span><small>1</small></button><button disabled={!g.canAct} onClick={()=>invoke('guard')}><Shield size={23}/><strong>Se protéger</strong><span>Réduit les dégâts · +2 concentration</span><small>2</small></button><button disabled={!g.canAct||g.focus<2} onClick={()=>invoke('breakGuard')}><ShieldOff size={23}/><strong>Briser</strong><span>Perce / interrompt · 2 concentration</span><small>3</small></button></div><p className="door-combat-help">Le gardien attend ton choix. Les dégâts de Frapper sont réduits contre sa garde.</p></div></section>;
}
export function DoorRunes({game:g,invoke}){
 const p=g.puzzle;
 return <section className="door-puzzle"><div className="door-scene-heading"><span className="door-eyebrow">L’ÉPREUVE DE L’ESPRIT</span><h2>L’ordre des runes.</h2><p>Relie les indices pour reconstruire la séquence.</p></div><div className="door-rune-tablet"><Sun size={35} className="door-tablet-mark"/><ol className="door-clues">{p.clues.map(clue=><li key={clue}>{clue}</li>)}</ol><div className="door-rune-sequence" aria-label="Séquence choisie">{p.order.map((_,i)=><span key={i} data-filled={!!p.chosen[i]} aria-label={p.options.find(r=>r.id===p.chosen[i])?.name||'Emplacement '+(i+1)}><Rune id={p.chosen[i]}/><small>{i+1}</small></span>)}</div><div className="door-rune-options">{p.options.map(r=><button key={r.id} disabled={p.chosen.includes(r.id)} onClick={()=>invoke('chooseRune',r.id)}><Rune id={r.id}/><span>{r.name}</span></button>)}</div><div className="door-puzzle-actions"><button className="door-secondary" disabled={!p.chosen.length} onClick={()=>invoke('undoRune')}><Undo2 size={17}/>Annuler</button><button className="door-primary" disabled={p.chosen.length!==p.order.length} onClick={()=>invoke('checkRunes')}>Valider les runes<Check size={18}/></button></div><p className="door-muted">Aucune limite de temps · Une erreur coûte {g.difficulty.errorDamage} vitalité.</p></div></section>;
}
export function DoorMechanism({game:g,invoke,needleRef}){
 const l=g.lock,d=g.difficulty;
 return <section className="door-mechanism"><div className="door-scene-heading"><span className="door-eyebrow">L’ÉPREUVE DE PRÉCISION</span><h2>Le cœur du verrou.</h2><p>Arrête l’aiguille à l’intérieur de la zone dorée.</p></div><div className="door-lock-body"><div className="door-lock-emblem" aria-hidden="true"><span/><span/><KeyRound size={45}/></div><div className="door-lock-rounds" aria-label={l.round+' crans alignés sur '+d.lockRounds}>{Array.from({length:d.lockRounds},(_,i)=><span key={i} data-aligned={i<l.round}>{i<l.round?<Check size={17}/>:i+1}</span>)}</div><div className="door-lock-track" aria-label="Zone de précision"><div className="door-lock-zone" style={{left:(l.target-d.lockWidth/2)*100+'%',width:d.lockWidth*100+'%'}}><span>ZONE</span></div><i ref={needleRef} className="door-lock-needle"/></div><button className="door-primary door-lock-button" disabled={l.hold>0} onClick={()=>invoke('stopMechanism')}><Focus size={19}/>{l.hold>0?'Préparation du prochain passage…':'Verrouiller'}<kbd>Espace</kbd></button><p className="door-muted">Cran {Math.min(l.round+1,d.lockRounds)} / {d.lockRounds} · Une erreur coûte {d.errorDamage} vitalité.</p></div></section>;
}
export function DoorBoon({game:g,invoke}){
 return <section className="door-moment"><span className="door-moment-symbol"><KeyRound size={43}/></span><span className="door-eyebrow">SCEAU {g.passed} / {g.difficulty.rooms}</span><h2>Un secret révélé.</h2><p>{g.rewardChosen?'Ta bénédiction t’accompagne jusqu’à la fin du niveau.':'Choisis une bénédiction pour poursuivre l’aventure.'}</p><div className="door-boons">{[{id:'vitality',Icon:Heart,title:'Vitalité',text:'+22 vitalité'},{id:'focus',Icon:Sparkles,title:'Clarté',text:'Concentration restaurée'},{id:'power',Icon:Sword,title:'Puissance',text:'+2 dégâts pour ce niveau'}].map(({id,Icon,title,text})=><button key={id} disabled={g.rewardChosen} onClick={()=>invoke('chooseReward',id)}><Icon size={24}/><strong>{title}</strong><span>{text}</span></button>)}</div><button className="door-primary" disabled={!g.rewardChosen} onClick={()=>invoke('next')}>{g.passed===g.difficulty.rooms?'Rejoindre la Porte':'Vers le prochain seuil'}<ArrowRight size={18}/></button><small className="door-muted">Progression sauvegardée à ce seuil.</small></section>;
}
export function DoorGate({game:g,invoke}){return <section className={'door-moment door-gate '+(g.room==='opening'?'is-opening':'')}><div className="door-final-portal" aria-hidden="true"><KeyRound size={48}/></div><span className="door-eyebrow">LES SCEAUX SONT RÉUNIS</span><h2>{g.difficulty.boss?'Le Veilleur t’attend.':'La Porte interdite.'}</h2><p>{g.difficulty.boss?'Le gardien du chapitre protège encore le passage. Prépare ta vitalité et ta concentration.':'Chaque épreuve a révélé une partie du secret. Le passage est à toi.'}</p><button className="door-primary" disabled={!g.canAct} onClick={()=>invoke('openGate')}>{g.room==='opening'?'La Porte s’ouvre…':g.difficulty.boss?'Défier le Veilleur':'Ouvrir la Porte'}<KeyRound size={18}/></button></section>;}
