import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ArrowLeft,Play,Pause,Volume2,VolumeX,Maximize,RotateCcw,X,ArrowUp,ArrowDown,ArrowRight,Download,Upload} from 'lucide-react';
import {Arena} from './arena.js';
import {Tower} from './tower.js';
import {Maze} from './maze.js';
import {Refuge} from './refuge.js';
import {Cities} from './cities.js';
import {recordGame,freshProgress,validateProgress} from './save.js';
import {loadAssets,render} from './render.js';
import {W,H,COUNTRIES} from './core.js';
import {DragControl} from './touchControls.js';
import {loadGameProgress,saveGameProgress} from './memberSave.js';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {useGameRewards} from '../loyalty/useGameRewards.js';
import {themeFor} from '../../shared/loyalty.js';
import './games.css';
export const GAME_LIST=[
 {id:'arena',number:'01',title:'Kaïs contre les Ombres',genre:'SURVIE · ACTION',time:'5–10 min',text:'Esquive les ombres. Assemble tes pouvoirs. Libère les huit gardiens.',control:'Glisse le doigt dans la zone de jeu pour bouger. Relâche pour arrêter. Bouton Esquive ou Espace ; flèches / ZQSD / WASD au clavier.',action:'Esquive',icon:'⚔',create:()=>new Arena()},
 {id:'tower',number:'02',title:'La Tour des portes interdites',genre:'EXPLORATION · RISQUE',time:'3–8 min',text:'Trois portes. Un indice. Jusqu’où oseras-tu emporter tes trouvailles ?',control:'Choisis les portes grâce aux indices. En combat, frappe et pare juste avant l’attaque.',action:'Frapper',icon:'♜',create:()=>new Tower()},
 {id:'maze',number:'03',title:'Le Labyrinthe de l’Oubli',genre:'MYSTÈRE · POURSUITE',time:'3–5 min',text:'Ta lampe faiblit. Retrouve les fragments avant que l’ombre ne te retrouve.',control:'Glisse le doigt pour explorer. Bouton Lumière pour repousser l’ombre ou activer un interrupteur proche. Flèches / ZQSD et E au clavier.',action:'Lumière',icon:'◈',create:()=>new Maze()},
 {id:'refuge',number:'04',title:'Le Dernier Refuge 3B',genre:'DÉFENSE · CONSTRUCTION',time:'Cycles de 5 min',text:'Bâtis le jour. Protège la nuit. Fais grandir un refuge qui garde ton histoire.',control:'Glisse le doigt pour déplacer Kaïs. Approche-toi puis touche Interagir pour récolter, réparer ou secourir. Flèches et E au clavier.',action:'Interagir',icon:'⛨',create:saved=>new Refuge(saved)},
 {id:'cities',number:'05',title:'Les Villes retrouvées',genre:'PUZZLE · CONTEMPLATION',time:'À ton rythme',text:'Relie les quartiers des huit pays. Chaque rue ramène un souvenir.',control:'Choisis une tuile. Flèches : case ; Entrée : poser ; E : tourner. Ou touche une case voisine. Relie 4 maisons, 2 jardins et 1 monument par des rues.',action:'Tourner',icon:'❋',create:saved=>new Cities(saved)},
];
function Sound(){let context;let enabled=false;return {set(v){enabled=v;if(v&&!context)try{context=new(window.AudioContext||window.webkitAudioContext)();}catch{}if(v)context?.resume().catch(()=>{});},note(freq=440){if(!enabled||!context)return;const o=context.createOscillator(),a=context.createGain();o.type='sine';o.frequency.setValueAtTime(freq,context.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,context.currentTime+.18);a.gain.setValueAtTime(.065,context.currentTime);a.gain.exponentialRampToValueAtTime(.001,context.currentTime+.22);o.connect(a);a.connect(context.destination);o.start();o.stop(context.currentTime+.24);},close(){context?.close().catch(()=>{});}};}
export default function GamesHub({goTo}){
 const account=useLoyalty(),user=account.user;
 const[active,setActive]=useState(null),[selection,setSelection]=useState('arena');
 const[progress,setProgress]=useState(freshProgress),[loading,setLoading]=useState(true),[saveMessage,setSaveMessage]=useState('Chargement de la progression…'),dataRef=useRef(progress),fileRef=useRef();
 useEffect(()=>{let live=true;loadGameProgress(user).then(result=>{if(!live)return;dataRef.current=result.data;setProgress(result.data);setSaveMessage(result.message);setLoading(false);if(result.online)saveGameProgress(result.data,user).then(m=>{if(live)setSaveMessage(m);});});return()=>{live=false;};},[]);
 const checkpoint=(g,id,record=false)=>{let next=dataRef.current;if(record)next=recordGame(next,id,g);else if(g.snapshot)next={...next,[id]:g.snapshot()};else return;dataRef.current=next;setProgress(next);saveGameProgress(next,user).then(setSaveMessage);};
 const exportSave=()=>{const blob=new Blob([JSON.stringify(dataRef.current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='3b-jeux-sauvegarde.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const importSave=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>180000)throw Error('Fichier trop volumineux.');const next=validateProgress(JSON.parse(await file.text()));dataRef.current=next;setProgress(next);setSaveMessage(await saveGameProgress(next,user));}catch(err){setSaveMessage(err.message||'Fichier de sauvegarde illisible.');}e.target.value='';};
 const selected=GAME_LIST.find(g=>g.id===selection)||GAME_LIST[0];
 const launch=()=>{if(!loading)setActive(selected);};
 return <section className="arcade" aria-labelledby="arcade-title">
  <div className="arcade-heading"><div><span className="arcade-eyebrow">LE MONDE DU 3B / JEUX</span><h1 id="arcade-title">Entre dans l’aventure.</h1></div><button className="arcade-back" onClick={()=>goTo('home')}><ArrowLeft size={18}/> Accueil</button></div>
  <div className="arcade-feature"><div className="arcade-feature-copy"><span className="arcade-tag">{selected.genre}</span><h2>{selected.title}</h2><p>{selected.text}</p><div className="arcade-meta"><span>◷ {selected.time}</span><span>Clavier & tactile</span><span>Sans compte</span></div><button className="arcade-primary" onClick={launch} disabled={loading}><Play size={19} fill="currentColor"/> {loading?'Chargement…':'Jouer maintenant'}</button></div><div className="arcade-portrait" aria-hidden="true"/></div>
  <div className="arcade-account-line"><span>{account.profile?`${account.profile.name} · ${account.profile.xp} XP · ${account.profile.points} points`:'Joue librement. Un compte 3B te permet de gagner des récompenses.'}</span><button onClick={()=>goTo(account.profile?'loyalty':'member')}>{account.profile?'Mes avantages':'Mon compte'}</button></div>
  <div className="game-progress"><p role="status">{saveMessage}</p><div><button onClick={exportSave}><Download size={15}/> Exporter la sauvegarde</button> <button onClick={()=>fileRef.current.click()} disabled={loading}><Upload size={15}/> Importer</button><input hidden ref={fileRef} type="file" accept=".json,application/json" onChange={importSave} aria-label="Importer une sauvegarde Jeux 3B"/></div></div>
  {progress.records[selection]&&<p className="arcade-stats">Record : {progress.records[selection].best} points · {progress.records[selection].wins} victoire(s)</p>}
  <div className="arcade-library" aria-label="Choisir un jeu">{GAME_LIST.map(g=><button key={g.id} className={'arcade-card '+(selection===g.id?'selected':'')} onClick={()=>setSelection(g.id)} aria-pressed={selection===g.id}><span className="arcade-card-top"><span>{g.number}</span><span>{g.time}</span></span><span className="arcade-card-icon" aria-hidden="true">{g.icon}</span><strong>{g.title}</strong><span className="arcade-card-genre">{g.genre}</span></button>)}</div>
  <a className="arcade-classic" href="https://troisb-course-des-cles-demo.stetienne86pp.chatgpt.site/" target="_blank" rel="noopener noreferrer"><span>LA PREMIÈRE AVENTURE</span><strong>La course des clés</strong><span>Jouer ↗</span></a>
  <p className="arcade-small">Les huit pays : {COUNTRIES.join(' · ')}.</p>
  {active&&createPortal(<GamePlayer key={active.id} config={active} saved={progress[active.id]} onCheckpoint={checkpoint} saveMessage={saveMessage} onClose={()=>setActive(null)}/>,document.body)}
 </section>;
}
function GamePlayer({config,onClose,saved,onCheckpoint,saveMessage}){
 const canvas=useRef(),shell=useRef(),engine=useRef(null),keys=useRef(new Set()),stick=useRef({x:0,y:0}),audio=useRef(null),pausedRef=useRef(false),readyRef=useRef(false),lastStatus=useRef('playing'),counted=useRef(false),checkpointRef=useRef(onCheckpoint);
 if(!engine.current)engine.current=config.create(saved);
 checkpointRef.current=onCheckpoint;
 const[view,setView]=useState(0),[paused,setPaused]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[sound,setSound]=useState(false),[notice,setNotice]=useState('');
 const game=engine.current;
 const activity=useRef(Date.now()),account=useLoyalty();
 const rewardMessage=useGameRewards(config.id,engine,pausedRef,readyRef,activity);
 game.auraColor=account.profile?themeFor(account.profile.theme,account.profile.xp).color:null;
 const drag=useRef(null),dragCapture=useRef(null);
 if(!drag.current)drag.current=new DragControl();
 const[gesture,setGesture]=useState(null);
 const canDrag=['arena','maze','refuge'].includes(config.id);
 const clearMovement=(update=true)=>{
  keys.current.clear();stick.current={x:0,y:0};
  const id=drag.current.pointerId,target=dragCapture.current;
  drag.current.cancel();dragCapture.current=null;
  if(id!==null&&target?.hasPointerCapture(id))target.releasePointerCapture(id);
  if(update)setGesture(null);
 };
 const dragStart=e=>{
  if(!canDrag||!readyRef.current||pausedRef.current||engine.current.status!=='playing'||e.target.closest('.game-overlay')||(e.pointerType==='mouse'&&e.button!==0))return;
  if(!drag.current.begin(e.pointerId,e.clientX,e.clientY))return;
  e.preventDefault();activity.current=Date.now();stick.current={x:0,y:0};
  e.currentTarget.setPointerCapture(e.pointerId);dragCapture.current=e.currentTarget;
  setGesture(drag.current.visual());
 };
 const dragMove=e=>{if(drag.current.move(e.pointerId,e.clientX,e.clientY)){activity.current=Date.now();e.preventDefault();setGesture(drag.current.visual());}};
 const dragEnd=e=>{if(drag.current.end(e.pointerId)){dragCapture.current=null;setGesture(null);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}};
 const refresh=()=>setView(v=>v+1);
 const pause=()=>{pausedRef.current=!pausedRef.current;setPaused(pausedRef.current);clearMovement();};
 const action=()=>{if(readyRef.current&&!pausedRef.current){activity.current=Date.now();engine.current.action?.();audio.current?.note(520);refresh();}};
 const invoke=(name,...args)=>{if(!pausedRef.current){activity.current=Date.now();engine.current[name]?.(...args);audio.current?.note(570);refresh();}};
 const retry=()=>{setError('');loadAssets().then(()=>{readyRef.current=true;setReady(true);}).catch(e=>setError(e.message));};
 useEffect(()=>{audio.current=Sound();retry();const previous=document.activeElement;const persist=(record=false)=>{if(record&&(counted.current||engine.current.time<.15))return;if(record)counted.current=true;checkpointRef.current(engine.current,config.id,record);};const saveTimer=setInterval(()=>persist(false),12000);const pagehide=()=>persist(false);window.addEventListener('pagehide',pagehide);const root=document.getElementById('root');if(root)root.inert=true;const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';shell.current.focus();let frame,last=0,hud=0;const c=canvas.current.getContext('2d');
  const resize=()=>{clearMovement();const stage=canvas.current.parentElement.getBoundingClientRect();const worldW=config.id==='cities'?620:config.id==='maze'&&stage.width<600?440:W,width=Math.min(stage.width,stage.height*worldW/H);engine.current.viewWidth=worldW;canvas.current.style.width=width+'px';canvas.current.style.height=width*H/worldW+'px';const rect=canvas.current.getBoundingClientRect();const dpr=Math.min(devicePixelRatio||1,2);canvas.current.width=Math.max(1,Math.round(rect.width*dpr));canvas.current.height=Math.max(1,Math.round(rect.height*dpr));};const ro=new ResizeObserver(resize);ro.observe(canvas.current.parentElement);resize();
  function loop(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;const g=engine.current;const k=keys.current;if(readyRef.current&&!pausedRef.current){if(k.size||stick.current.x||stick.current.y||drag.current.input.x||drag.current.input.y)activity.current=Date.now();g.update(dt,{x:(k.has('ArrowRight')||k.has('d')?1:0)-(k.has('ArrowLeft')||k.has('a')||k.has('q')?1:0)+stick.current.x+drag.current.input.x,y:(k.has('ArrowDown')||k.has('s')?1:0)-(k.has('ArrowUp')||k.has('w')||k.has('z')?1:0)+stick.current.y+drag.current.input.y});if(g.status!==lastStatus.current){if(g.status!=='playing')clearMovement();audio.current?.note(g.status==='ended'?220:760);lastStatus.current=g.status;if(g.status==='ended')persist(true);}}if(readyRef.current)render(c,g,config.id,canvas.current);hud+=dt;if(hud>.1){hud=0;setView(v=>v+1);}frame=requestAnimationFrame(loop);}frame=requestAnimationFrame(loop);
  const down=e=>{const interactive=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if(interactive)return;if(e.key==='Tab'){const buttons=[...shell.current.querySelectorAll('button:not(:disabled),a[href],input')].filter(el=>el.getClientRects().length);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===shell.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' ','Escape','p','P','e','E','z','q','s','d','w','a'].includes(e.key)){e.preventDefault();if(e.repeat)return;activity.current=Date.now();if(['Escape','p','P'].includes(e.key)){pausedRef.current=!pausedRef.current;setPaused(pausedRef.current);clearMovement();}else if(e.key==='Enter'){if(!pausedRef.current)engine.current.confirm?.();}else if([' ','e','E'].includes(e.key)){if(!pausedRef.current&&readyRef.current)engine.current.action?.();}else keys.current.add(e.key);}};
  const up=e=>keys.current.delete(e.key);const blur=()=>{clearMovement();if(engine.current.status==='playing'){pausedRef.current=true;setPaused(true);}};const visibility=()=>{if(document.hidden)blur();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
  return()=>{clearMovement(false);persist(true);clearInterval(saveTimer);window.removeEventListener('pagehide',pagehide);cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);audio.current?.close();document.body.style.overflow=oldOverflow;if(root)root.inert=false;previous?.focus();};
 },[config.id]);
 const reset=()=>{const width=engine.current.viewWidth;engine.current=config.create(config.id==='refuge'?engine.current.snapshot():undefined);engine.current.viewWidth=width;clearMovement();counted.current=false;lastStatus.current='playing';pausedRef.current=false;setPaused(false);refresh();};
 const dpad=(x,y,label,Icon)=><button aria-label={label} onPointerDown={e=>{e.preventDefault();if(!readyRef.current||pausedRef.current||engine.current.status!=='playing')return;clearMovement();e.currentTarget.setPointerCapture(e.pointerId);stick.current={x,y};}} onPointerUp={()=>stick.current={x:0,y:0}} onPointerCancel={()=>stick.current={x:0,y:0}} onLostPointerCapture={()=>stick.current={x:0,y:0}}><Icon size={23}/></button>;
 return <div className="game-shell" ref={shell} tabIndex={-1} role="dialog" aria-modal="true" aria-label={config.title} data-game={config.id} data-state={paused?'paused':game.status} data-revision={view}>
  <header className="game-header"><button onClick={onClose} aria-label="Quitter le jeu"><X size={21}/></button><strong>{config.title}</strong><div className="game-header-actions"><button aria-label={sound?'Couper le son':'Activer le son'} onClick={()=>{setSound(!sound);audio.current.set(!sound);audio.current.note();}}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button aria-label="Plein écran" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else shell.current.requestFullscreen?.().catch(()=>setNotice('Le plein écran n’est pas disponible ici.'));}}><Maximize size={19}/></button><button aria-label={paused?'Reprendre':'Pause'} onClick={pause}>{paused?<Play size={20}/>:<Pause size={20}/>}</button></div></header>
  <div className="game-hud">{game.hud().map(([title,value])=><div key={title}><span>{title}</span><strong>{value}</strong></div>)}</div>
  <div className={"game-stage"+(canDrag?" game-drag-area":"")} onPointerDown={dragStart} onPointerMove={dragMove} onPointerUp={dragEnd} onPointerCancel={dragEnd} onLostPointerCapture={dragEnd}><canvas ref={canvas} aria-label={config.title+' — zone de jeu'} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();invoke('click',(e.clientX-r.left)/r.width*(config.id==='cities'?620:W),(e.clientY-r.top)/r.height*H);}}/>
   {canDrag&&ready&&!paused&&game.status==='playing'&&<><div className="game-drag-hint" aria-hidden="true">Glisse où tu veux pour bouger · relâche pour arrêter</div>{gesture&&<div className="game-joystick" aria-hidden="true" style={{left:gesture.x,top:gesture.y}}><span style={{transform:'translate('+gesture.dx+'px,'+gesture.dy+'px)'}}/></div>}</>}
   {!ready&&<div className="game-overlay"><div><h2>{error?'Chargement interrompu':'Ouverture de la porte…'}</h2><p>{error||'Préparation du décor et de Kaïs.'}</p>{error&&<button onClick={retry}>Réessayer</button>}</div></div>}
   {ready&&game.status==='upgrade'&&!paused&&<div className="game-overlay"><div className="game-upgrade"><span className="arcade-eyebrow">NIVEAU {game.level}</span><h2>Choisis ton pouvoir.</h2><div className="game-power-choices">{game.choices.map(p=><button key={p.id} onClick={()=>invoke('choose',p.id)}><span>{p.icon}</span><strong>{p.name}</strong><small>Niveau {(game.powers[p.id]||0)+1}</small><p>{p.desc}</p></button>)}</div></div></div>}
   {paused&&game.status!=='ended'&&<div className="game-overlay"><div><span className="arcade-eyebrow">PRENDS TON TEMPS</span><h2>Partie en pause</h2><p>{config.control}</p><button className="arcade-primary" onClick={pause}><Play size={18}/> Reprendre</button><button className="game-text-button" onClick={onClose}>Retour aux jeux</button></div></div>}
   {game.status==='ended'&&<div className="game-overlay"><div><span className="arcade-eyebrow">{game.won?'LUMIÈRE RETROUVÉE':'LA NUIT N’A PAS TOUT EFFACÉ'}</span><h2>{game.won?'Victoire !':'Fin de partie'}</h2><p>{game.message}</p><p className="game-result-score">{game.score} points</p><button className="arcade-primary" onClick={reset}><RotateCcw size={18}/> Rejouer</button><button className="game-text-button" onClick={onClose}>Retour aux jeux</button></div></div>}
  </div>
  {config.id==='tower'&&game.status==='playing'&&<div className="game-subpanel"><p className="game-log" role="status">{game.message||'Écoute les indices derrière chaque porte.'}</p>{game.room==='doors'&&<div className="game-door-choices">{game.doors.map((d,i)=><button key={i} disabled={paused} onClick={()=>invoke('door',i)}><strong>Porte {i+1}</strong><small>{d.hint}</small></button>)}</div>}<div className="game-options">{game.room==='combat'?<><button onClick={()=>invoke('attack')} disabled={paused||game.strike>0}>Frapper</button><button onClick={()=>invoke('guard')} disabled={paused||game.blockCooldown>0}>Parer {game.block>0?'· levée':''}</button></>:<><button onClick={()=>invoke('bank')} disabled={paused}>Sortir avec le butin</button>{game.room==='resolved'&&<button onClick={()=>invoke('next')} disabled={paused}>{game.floor===15?'Atteindre le sommet':'Monter à l’étage suivant'}</button>}</>}</div></div>}
  {config.id==='refuge'&&game.status==='playing'&&<div className="game-subpanel"><p className="game-log">{game.message}</p><div className="game-options">{game.phase==='day'&&<><button onClick={()=>invoke('build','turret')} disabled={paused||game.wood<45||game.turrets>=4}>Poste de tir · 45 matériaux ({game.turrets}/4)</button><button onClick={()=>invoke('build','home')} disabled={paused||game.wood<35||game.homes>=6}>Abri · 35 matériaux</button><button onClick={()=>invoke('startNight')} disabled={paused}>Commencer la nuit</button></>}<span className="game-saving">{saveMessage}</span></div></div>}
  {config.id==='cities'&&<div className="game-subpanel"><p className="game-log" role="status">{game.message}{game.restored?' Ville restaurée ! Tu peux continuer ou choisir un autre pays.':''}</p><div className="game-tiles">{game.hand.map((t,i)=><button key={i} className={game.selected===i?'selected':''} aria-pressed={game.selected===i} disabled={paused} onClick={()=>invoke('select',i)}>{t.type==='road'?(t.shape==='straight'?'Rue droite':'Rue en angle'):t.type==='house'?'Maison':t.type==='garden'?'Jardin':'Monument'}{game.selected===i?' · '+game.rot*90+'°':''}</button>)}<button onClick={()=>invoke('undo')} disabled={paused||!game.history.length}>Annuler la pose</button></div><div className="game-options">{COUNTRIES.map((country,i)=><button key={country} onClick={()=>invoke('changeCountry',i)} disabled={paused} aria-pressed={game.countryIndex===i}>{game.completed.includes(i)?'✓ ':''}{country}</button>)}{game.board.every(Boolean)&&!game.restored&&<button onClick={()=>invoke('restartCity')} disabled={paused}>Recommencer cette ville</button>}</div></div>}
  <footer className="game-footer"><span className="game-reward-status" role="status">{rewardMessage}</span><p className="game-mobile-help">{{arena:'Glisse où tu veux pour bouger. Attaques automatiques.',maze:'Glisse pour explorer. Trouve 3 fragments, puis la porte.',tower:'Frappe, puis pare quand l’ombre prépare son attaque.',refuge:'Glisse pour bouger. Interagir : récolter, réparer, secourir.',cities:'Choisis une tuile puis touche une case. Tourner change son sens.'}[config.id]}</p><div className="game-dpad" style={{display:['tower','cities'].includes(config.id)?'none':undefined}}>{dpad(0,-1,'Aller en haut',ArrowUp)}{dpad(-1,0,'Aller à gauche',ArrowLeft)}{dpad(0,1,'Aller en bas',ArrowDown)}{dpad(1,0,'Aller à droite',ArrowRight)}</div><div className="game-hints"><p>{config.control}</p><span>{notice||game.message||'Reste en mouvement.'}</span><br/><span className="game-saving">{saveMessage}</span></div><button className="game-action" style={{display:config.id==='tower'?'none':undefined}} onClick={action} disabled={!ready||paused||game.status!=='playing'||game.dash>0}>{game.dash>0?game.dash.toFixed(1)+' s':config.action}<small className="game-key-label">Espace / E</small><small className="game-touch-label">Toucher</small></button></footer>
 </div>;
}
