import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ArrowLeft,Play,Pause,Volume2,VolumeX,Maximize,RotateCcw,X,ArrowUp,ArrowDown,ArrowRight,Download,Upload} from 'lucide-react';
import {Arena} from './arena.js';
import {Tower} from './tower.js';
import {Maze} from './maze.js';
import {recordGame,freshProgress,validateProgress} from './save.js';
import {loadAssets,render} from './render.js';
import {W,H,COUNTRIES} from './core.js';
import {DragControl} from './touchControls.js';
import {loadGameProgress,saveGameProgress} from './memberSave.js';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {useGameRewards} from '../loyalty/useGameRewards.js';
import {themeFor} from '../../shared/loyalty.js';
import {createStepper,actionState} from './runtime.js';
import {createGameAudio} from './audio.js';
import './games.css';
import './premium.css';
import './labyrinth.css';
import {GAME_CATALOG} from './catalog.js';
export const GAME_LIST=GAME_CATALOG.map(g=>({...g,create:{arena:()=>new Arena(),tower:()=>new Tower(),maze:()=>new Maze()}[g.id]}));
export default function GamesHub({goTo}){
 const account=useLoyalty(),user=account.user;
 const[active,setActive]=useState(null),[selection,setSelection]=useState('arena');
 const[progress,setProgress]=useState(freshProgress),[loading,setLoading]=useState(true),[saveMessage,setSaveMessage]=useState('Chargement de la progression…'),dataRef=useRef(progress),fileRef=useRef();
 useEffect(()=>{let live=true;setLoading(true);loadGameProgress(user).then(result=>{if(!live)return;dataRef.current=result.data;setProgress(result.data);setSaveMessage(result.message);setLoading(false);if(result.online)saveGameProgress(result.data,user).then(m=>{if(live)setSaveMessage(m);});});return()=>{live=false;};},[user?.id]);
 const checkpoint=(g,id,record=false)=>{let next=dataRef.current;if(record)next=recordGame(next,id,g);else if(g.snapshot)next={...next,[id]:g.snapshot()};else return;dataRef.current=next;setProgress(next);saveGameProgress(next,user).then(setSaveMessage);};
 const exportSave=()=>{const blob=new Blob([JSON.stringify(dataRef.current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='3b-jeux-sauvegarde.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const importSave=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>180000)throw Error('Fichier trop volumineux.');const next=validateProgress(JSON.parse(await file.text()));dataRef.current=next;setProgress(next);setSaveMessage(await saveGameProgress(next,user));}catch(err){setSaveMessage(err.message||'Fichier de sauvegarde illisible.');}e.target.value='';};
 return <section className="arcade" aria-labelledby="arcade-title">
  <div className="arcade-heading"><div><span className="arcade-eyebrow">LE MONDE DU 3B / JEUX</span><h1 id="arcade-title">Entre dans l’aventure.</h1></div><button className="arcade-back" onClick={()=>goTo('home')}><ArrowLeft size={18}/> Accueil</button></div>
  <div className="arcade-account-line"><span>{account.profile?`${account.profile.name} · ${account.profile.xp} XP · ${account.profile.points} points`:'Joue librement. Un compte 3B te permet de gagner des récompenses.'}</span><button onClick={()=>goTo(account.profile?'loyalty':'member')}>{account.profile?'Mes avantages':'Mon compte'}</button></div>
  {progress.records[selection]&&<p className="arcade-stats">Record : {progress.records[selection].best} points · {progress.records[selection].wins} victoire(s)</p>}
  <div className="premium-library" aria-label="Choisir un jeu">{GAME_LIST.map(g=>{const Card=g.href?'a':'button';return <Card className="premium-game-card" data-game={g.id} key={g.id} {...(g.href?{href:g.href,target:'_blank',rel:'noopener noreferrer'}:{disabled:loading,onClick:()=>{setSelection(g.id);setActive(g);}})}><span className="premium-card-art" aria-hidden="true"><span className="premium-card-number">{g.number}</span><span className="premium-card-sprite"/></span><span className="premium-card-copy"><span className="premium-card-genre">{g.genre} · {g.time}</span><strong>{g.title}</strong><span className="premium-card-description">{g.text}</span><span className="premium-card-bottom"><span>{g.href?'S’ouvre dans un nouvel onglet':progress.records[g.id]?'Record · '+progress.records[g.id].best+' pts':'À découvrir'}</span><span className="premium-card-play"><Play size={15}/>Jouer</span></span></span></Card>;})}</div>
  <details className="game-progress"><summary>Sauvegarde et progression</summary><p role="status">{saveMessage}</p><div><button onClick={exportSave}><Download size={15}/> Exporter la sauvegarde</button> <button onClick={()=>fileRef.current.click()} disabled={loading}><Upload size={15}/> Importer</button><input hidden ref={fileRef} type="file" accept=".json,application/json" onChange={importSave} aria-label="Importer une sauvegarde Jeux 3B"/></div></details>
  <p className="arcade-small">Les huit pays : {COUNTRIES.join(' · ')}.</p>
  {active&&createPortal(<GamePlayer key={active.id} config={active} saved={progress[active.id]} onCheckpoint={checkpoint} saveMessage={saveMessage} onClose={()=>setActive(null)}/>,document.body)}
 </section>;
}
function GamePlayer({config,onClose,saved,onCheckpoint,saveMessage}){
 const canvas=useRef(),shell=useRef(),engine=useRef(null),keys=useRef(new Set()),stick=useRef({x:0,y:0}),audio=useRef(null),pausedRef=useRef(false),readyRef=useRef(false),lastStatus=useRef('playing'),counted=useRef(false),checkpointRef=useRef(onCheckpoint);
 if(!engine.current)engine.current=config.create(saved);
 checkpointRef.current=onCheckpoint;
 const[started,setStarted]=useState(false);
 const[view,setView]=useState(0),[paused,setPaused]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[sound,setSound]=useState(false),[notice,setNotice]=useState('');
 const game=engine.current,ability=actionState(game,config.id);
 const begin=()=>{pausedRef.current=false;setPaused(false);readyRef.current=true;setStarted(true);shell.current.focus();};
 const activity=useRef(Date.now()),account=useLoyalty();
 const rewardMessage=useGameRewards(config.id,engine,pausedRef,readyRef,activity);
 game.auraColor=account.profile?themeFor(account.profile.theme,account.profile.xp).color:null;
 const drag=useRef(null),dragCapture=useRef(null);
 if(!drag.current)drag.current=new DragControl();
 const[gesture,setGesture]=useState(null);
 const canDrag=['arena','maze'].includes(config.id);
 const clearMovement=(update=true)=>{
  keys.current.clear();stick.current={x:0,y:0};
  const id=drag.current.pointerId,target=dragCapture.current;
  drag.current.cancel();dragCapture.current=null;
  if(id!==null&&target?.hasPointerCapture(id))target.releasePointerCapture(id);
  if(update)setGesture(null);
 };
 const dragStart=e=>{
  if(!canDrag||!readyRef.current||pausedRef.current||engine.current.status!=='playing'||e.target.closest('.game-overlay')||(e.pointerType==='mouse'&&e.button!==0))return;
  if(!drag.current.begin(e.pointerId,e.clientX,e.clientY))return;
  e.preventDefault();activity.current=Date.now();stick.current={x:0,y:0};
  e.currentTarget.setPointerCapture(e.pointerId);dragCapture.current=e.currentTarget;
  setGesture(drag.current.visual());
 };
 const dragMove=e=>{if(drag.current.move(e.pointerId,e.clientX,e.clientY)){activity.current=Date.now();e.preventDefault();setGesture(drag.current.visual());}};
 const dragEnd=e=>{if(drag.current.end(e.pointerId)){dragCapture.current=null;setGesture(null);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}};
 const refresh=()=>setView(v=>v+1);
 const pause=()=>{if(!readyRef.current)return;pausedRef.current=!pausedRef.current;setPaused(pausedRef.current);clearMovement();};
 const action=()=>{if(readyRef.current&&!pausedRef.current){activity.current=Date.now();engine.current.action?.();refresh();}};
 const invoke=(name,...args)=>{if(readyRef.current&&!pausedRef.current){activity.current=Date.now();engine.current[name]?.(...args);refresh();}};
 const retry=()=>{setError('');loadAssets().then(()=>{setReady(true);}).catch(e=>setError(e.message));};
 useEffect(()=>{audio.current=createGameAudio();retry();const previous=document.activeElement;const persist=(record=false)=>{if(record&&(counted.current||engine.current.time<.15))return;if(record)counted.current=true;checkpointRef.current(engine.current,config.id,record);};const saveTimer=setInterval(()=>persist(false),12000);const pagehide=()=>persist(false);window.addEventListener('pagehide',pagehide);const root=document.getElementById('root');if(root)root.inert=true;const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';shell.current.focus();let frame,last=0,hud=0,lastFeedback=0;const stepper=createStepper(),motion=window.matchMedia('(prefers-reduced-motion: reduce)');const c=canvas.current.getContext('2d');
  const resize=()=>{clearMovement();const stage=canvas.current.parentElement.getBoundingClientRect();const wideMaze=config.id==='maze'&&stage.height<360&&stage.width>600;const worldW=config.id==='maze'&&stage.width<600?440:['arena'].includes(config.id)&&stage.width<600?620:W,worldH=wideMaze?stage.height*worldW/stage.width:H,width=Math.min(stage.width,stage.height*worldW/worldH);engine.current.viewWidth=worldW;engine.current.viewHeight=worldH;canvas.current.style.width=width+'px';canvas.current.style.height=width*worldH/worldW+'px';const rect=canvas.current.getBoundingClientRect();const dpr=Math.min(devicePixelRatio||1,2);canvas.current.width=Math.max(1,Math.round(rect.width*dpr));canvas.current.height=Math.max(1,Math.round(rect.height*dpr));render(c,engine.current,config.id,canvas.current);};const ro=new ResizeObserver(resize);ro.observe(canvas.current.parentElement);resize();
  function loop(now){const dt=Math.min(.2,(now-last)/1000||0);last=now;const g=engine.current;g.reducedMotion=motion.matches;const k=keys.current;if(readyRef.current&&!pausedRef.current){if(k.size||stick.current.x||stick.current.y||drag.current.input.x||drag.current.input.y)activity.current=Date.now();stepper.advance(dt,step=>{g.update(step,{x:(k.has('ArrowRight')||k.has('d')?1:0)-(k.has('ArrowLeft')||k.has('a')||k.has('q')?1:0)+stick.current.x+drag.current.input.x,y:(k.has('ArrowDown')||k.has('s')?1:0)-(k.has('ArrowUp')||k.has('w')||k.has('z')?1:0)+stick.current.y+drag.current.input.y});return g.status==='playing';});if(g.feedbackId!==lastFeedback){lastFeedback=g.feedbackId;audio.current?.note(g.feedback);}if(g.status!==lastStatus.current){if(g.status!=='playing')clearMovement();if(g.status==='ended'||g.status==='upgrade')audio.current?.note(g.status==='ended'?(g.won?'victory':'damage'):'upgrade');lastStatus.current=g.status;if(g.status==='ended')persist(true);}}else stepper.reset();if(canvas.current.width)render(c,g,config.id,canvas.current);hud+=dt;if(hud>.1){hud=0;setView(v=>v+1);}frame=requestAnimationFrame(loop);}frame=requestAnimationFrame(loop);
  const down=e=>{const interactive=/INPUT|TEXTAREA|SELECT/.test(e.target.tagName);if(interactive)return;if(e.target.closest('button')&&['Enter',' '].includes(e.key))return;const normalized=e.key.length===1?e.key.toLowerCase():e.key;if(readyRef.current&&!pausedRef.current&&config.id==='maze'&&normalized==='m'){e.preventDefault();if(!e.repeat)engine.current.toggleMap();return;}if(readyRef.current&&!pausedRef.current&&config.id==='tower'){if(['1','2','3'].includes(e.key)){e.preventDefault();if(!e.repeat)engine.current.door(Number(e.key)-1);return;}if(normalized==='f'){e.preventDefault();if(!e.repeat)engine.current.guard();return;}}if(e.key==='Tab'){const buttons=[...shell.current.querySelectorAll('button:not(:disabled),a[href],input')].filter(el=>el.getClientRects().length);const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===shell.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' ','Escape','p','P','e','E','z','q','s','d','w','a'].includes(normalized)){e.preventDefault();if(e.repeat)return;activity.current=Date.now();if(['Escape','p','P'].includes(e.key)){if(!readyRef.current)return;pausedRef.current=!pausedRef.current;setPaused(pausedRef.current);clearMovement();}else if(e.key==='Enter'){if(readyRef.current&&!pausedRef.current)engine.current.confirm?.();}else if([' ','e','E'].includes(e.key)){if(!pausedRef.current&&readyRef.current)engine.current.action?.();}else keys.current.add(normalized);}};
  const up=e=>keys.current.delete(e.key.length===1?e.key.toLowerCase():e.key);const blur=()=>{clearMovement();if(engine.current.status==='playing'){pausedRef.current=true;setPaused(true);}};const visibility=()=>{if(document.hidden)blur();};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
  return()=>{clearMovement(false);persist(true);clearInterval(saveTimer);window.removeEventListener('pagehide',pagehide);cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);audio.current?.close();document.body.style.overflow=oldOverflow;if(root)root.inert=false;previous?.focus();};
 },[config.id]);
 const reset=()=>{const width=engine.current.viewWidth,height=engine.current.viewHeight;engine.current=config.create();engine.current.viewWidth=width;engine.current.viewHeight=height;clearMovement();counted.current=false;lastStatus.current='playing';pausedRef.current=false;setPaused(false);refresh();};
 const dpad=(x,y,label,Icon)=><button aria-label={label} onPointerDown={e=>{e.preventDefault();if(!readyRef.current||pausedRef.current||engine.current.status!=='playing')return;clearMovement();e.currentTarget.setPointerCapture(e.pointerId);stick.current={x,y};}} onPointerUp={()=>stick.current={x:0,y:0}} onPointerCancel={()=>stick.current={x:0,y:0}} onLostPointerCapture={()=>stick.current={x:0,y:0}}><Icon size={23}/></button>;
 return <div className="game-shell" ref={shell} tabIndex={-1} role="dialog" aria-modal="true" aria-label={config.title} data-game={config.id} data-state={!started?'intro':paused?'paused':game.status} data-revision={view}>
  <header className="game-header"><button onClick={onClose} aria-label="Quitter le jeu"><X size={21}/></button><strong>{config.title}</strong><div className="game-header-actions"><button aria-label={sound?'Couper le son':'Activer le son'} onClick={()=>{setSound(!sound);audio.current.set(!sound);audio.current.note();}}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button aria-label="Plein écran" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});else shell.current.requestFullscreen?.().catch(()=>setNotice('Le plein écran n’est pas disponible ici.'));}}><Maximize size={19}/></button><button aria-label={paused?'Reprendre':'Pause'} disabled={!started} onClick={pause}>{paused?<Play size={20}/>:<Pause size={20}/>}</button></div></header>
  <div className="game-hud">{game.hud().map(([title,value])=><div key={title}><span>{title}</span><strong>{value}</strong></div>)}</div>
  <div className={"game-stage"+(canDrag?" game-drag-area":"")} onPointerDown={dragStart} onPointerMove={dragMove} onPointerUp={dragEnd} onPointerCancel={dragEnd} onLostPointerCapture={dragEnd}><canvas ref={canvas} aria-label={config.title+' — zone de jeu'} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();invoke('click',(e.clientX-r.left)/r.width*(engine.current.viewWidth||W),(e.clientY-r.top)/r.height*(engine.current.viewHeight||H));}}/>
   {canDrag&&started&&ready&&!paused&&game.status==='playing'&&<><div className="game-drag-hint" aria-hidden="true">Glisse où tu veux pour bouger · relâche pour arrêter</div>{gesture&&<div className="game-joystick" aria-hidden="true" style={{left:gesture.x,top:gesture.y}}><span style={{transform:'translate('+gesture.dx+'px,'+gesture.dy+'px)'}}/></div>}</>}
   {!ready&&<div className="game-overlay"><div><h2>{error?'Chargement interrompu':'Ouverture de la porte…'}</h2><p>{error||'Préparation du décor et de Kaïs.'}</p>{error&&<button onClick={retry}>Réessayer</button>}</div></div>}
   {ready&&!started&&<div className="game-overlay premium-intro"><div><span className="arcade-eyebrow">{config.genre} · {config.time}</span><h2>{config.title}</h2><p>{config.text}</p><div className="premium-controls">{config.control}</div><button className="arcade-primary" onClick={begin}><Play size={18}/>{saved?'Reprendre l’aventure':'Commencer l’aventure'}</button><p className="premium-intro-tip">Pause à tout moment · Son au choix</p></div></div>}
   {ready&&started&&game.status==='upgrade'&&!paused&&<div className="game-overlay"><div className="game-upgrade"><span className="arcade-eyebrow">NIVEAU {game.level}</span><h2>Choisis ton pouvoir.</h2><div className="game-power-choices">{game.choices.map(p=><button key={p.id} onClick={()=>invoke('choose',p.id)}><span>{p.icon}</span><strong>{p.name}</strong><small>Niveau {(game.powers[p.id]||0)+1}</small><p>{p.desc}</p></button>)}</div></div></div>}
   {started&&paused&&game.status!=='ended'&&<div className="game-overlay"><div><span className="arcade-eyebrow">PRENDS TON TEMPS</span><h2>Partie en pause</h2><p>{config.control}</p><button className="arcade-primary" onClick={pause}><Play size={18}/> Reprendre</button><button className="game-text-button" onClick={onClose}>Retour aux jeux</button></div></div>}
   {game.status==='ended'&&<div className="game-overlay"><div><span className="arcade-eyebrow">{game.won?'LUMIÈRE RETROUVÉE':'LA NUIT N’A PAS TOUT EFFACÉ'}</span><h2>{game.won?'Victoire !':'Fin de partie'}</h2><p>{game.message}</p><p className="game-result-score">{game.score} points</p>{config.id==='maze'&&<p className="maze-result-detail">{game.collected} sceaux · {game.explored}% exploré · {game.switches.filter(s=>s.used).length} passages ouverts</p>}<button className="arcade-primary" onClick={reset}><RotateCcw size={18}/> Rejouer</button><button className="game-text-button" onClick={onClose}>Retour aux jeux</button></div></div>}
  </div>
  {started&&config.id==='tower'&&game.status==='playing'&&<div className="game-subpanel"><p className="game-log" role="status">{game.message||'Écoute les indices derrière chaque porte.'}</p>{game.room==='doors'&&<div className="game-door-choices">{game.doors.map((d,i)=><button key={i} disabled={paused} onClick={()=>invoke('door',i)}><strong>Porte {i+1}</strong><small>{d.hint}</small><span className="door-risk">{{treasure:'Butin · risque faible',trap:'Piège · vie contre fragments',combat:'Combat · butin élevé',secret:'Souvenir · attaque renforcée',rest:'Repos · restaure la vie'}[d.type]}</span></button>)}</div>}<div className="game-options">{game.room==='combat'?<><button onClick={()=>invoke('attack')} disabled={paused||game.strike>0}>{game.counter>0?'Contre-attaquer ×2':'Frapper · Espace'}</button><button onClick={()=>invoke('guard')} disabled={paused||game.blockCooldown>0}>Parer · F {game.block>0?'· levée':game.blockCooldown>0?'· '+game.blockCooldown.toFixed(1)+' s':''}</button></>:<><button onClick={()=>invoke('bank')} disabled={paused}>Sortir avec le butin</button>{game.room==='resolved'&&<button onClick={()=>invoke('next')} disabled={paused}>{game.floor===15?'Atteindre le sommet':'Monter à l’étage suivant'}</button>}</>}</div></div>}
  {started&&config.id==='maze'&&game.status!=='ended'&&<div className="game-subpanel maze-toolbar"><div className="maze-seals" aria-label="Sceaux retrouvés">{game.fragments.map(f=><span key={f.name} data-found={f.collected} style={{'--seal':f.color}}><b>{f.collected?'✓':f.symbol}</b>{f.name}</span>)}</div><button className="maze-map-button" onClick={()=>invoke('toggleMap')} disabled={paused} aria-pressed={game.mapOpen}>{game.mapOpen?'Revenir au jeu':'Carte'}<small>M</small></button><p className="maze-journal" role="status">{game.messageTime>0?game.message:game.mapOpen?'Le temps est suspendu. Seules les zones découvertes sont dessinées.':game.sanctuary()?'Sanctuaire · l’ombre ne peut pas entrer ici.':game.shadowMode==='hunt'?'Brise sa ligne de vue avec les murs, ou utilise ton éclat.':game.collected===3?'Les trois sceaux sont réunis. Retourne au portail du sanctuaire.':'Explore les couloirs. Un éclat révèle le début du chemin vers un sceau.'}</p></div>}
  <footer className="game-footer"><span className="game-reward-status" role="status">{rewardMessage}</span><p className="game-mobile-help">{{arena:'Glisse où tu veux pour bouger. Attaques automatiques.',maze:'Glisse ou utilise les flèches. Éclat : repousser et trouver ton chemin.',tower:'Frappe, puis pare quand l’ombre prépare son attaque.'}[config.id]}</p><div className="game-dpad" style={{display:config.id==='tower'?'none':undefined}}>{dpad(0,-1,'Aller en haut',ArrowUp)}{dpad(-1,0,'Aller à gauche',ArrowLeft)}{dpad(0,1,'Aller en bas',ArrowDown)}{dpad(1,0,'Aller à droite',ArrowRight)}</div><div className="game-hints"><p>{config.control}</p><span>{notice||game.message||'Reste en mouvement.'}</span><br/><span className="game-saving">{saveMessage}</span></div><button className="game-action" onClick={action} disabled={!ready||!started||paused||game.status!=='playing'||ability.remaining>0||ability.unavailable} style={{display:config.id==='tower'?'none':undefined,'--cooldown':Math.max(0,1-ability.remaining/ability.duration)*100+'%'}}>{ability.remaining>0?ability.label+' · '+ability.remaining.toFixed(1)+' s':ability.label}<small className="game-key-label">Espace / E</small><small className="game-touch-label">Toucher</small></button></footer>
 </div>;
}

