import {BaseGame,shuffle,clamp} from './core.js';
export const DIRS=[[0,-1],[1,0],[0,1],[-1,0]];
export function paths(grid,start){const rows=grid.length,cols=grid[0].length,dist=Array(rows*cols).fill(-1),parent=Array(rows*cols).fill(-1),q=[start.y*cols+start.x];dist[q[0]]=0;for(let k=0;k<q.length;k++){const at=q[k],x=at%cols,y=Math.floor(at/cols);for(const[dx,dy]of DIRS){const nx=x+dx,ny=y+dy,i=ny*cols+nx;if(nx<0||ny<0||nx>=cols||ny>=rows||grid[ny][nx]||dist[i]>=0)continue;dist[i]=dist[at]+1;parent[i]=at;q.push(i);}}return{dist,parent,q};}
export function makeMaze(cols,rows,random){const grid=Array.from({length:rows},()=>Array(cols).fill(1)),stack=[[1,1]];grid[1][1]=0;while(stack.length){const[x,y]=stack.at(-1);const d=shuffle(DIRS,random).find(([dx,dy])=>{const nx=x+dx*2,ny=y+dy*2;return nx>0&&ny>0&&nx<cols-1&&ny<rows-1&&grid[ny][nx]===1;});if(!d){stack.pop();continue;}grid[y+d[1]][x+d[0]]=0;grid[y+d[1]*2][x+d[0]*2]=0;stack.push([x+d[0]*2,y+d[1]*2]);}return grid;}
export class Maze extends BaseGame {
 constructor(seed){super(seed);this.cols=25;this.rows=17;this.grid=makeMaze(this.cols,this.rows,this.random);this.cell={x:1,y:1};this.lamp=210;this.vision=4.4;this.collected=0;this.moveClock=0;this.shadowClock=0;this.flash=0;this.flashCooldown=0;this.seen=Array(this.cols*this.rows).fill(false);const route=paths(this.grid,this.cell);const sorted=route.q.sort((a,b)=>route.dist[a]-route.dist[b]);const point=i=>({x:i%this.cols,y:Math.floor(i/this.cols)});this.exit=point(sorted.at(-1));this.shadow=point(sorted[Math.floor(sorted.length*.85)]);this.fragments=[.3,.56,.83].map(n=>({...point(sorted[Math.floor(sorted.length*n)]),collected:false}));this.lamps=[.22,.7].map(n=>({...point(sorted[Math.floor(sorted.length*n)]),collected:false}));this.switches=[.4,.64].map(n=>({...point(sorted[Math.floor(sorted.length*n)]),used:false}));this.message='Trois fragments, puis la porte. Les petits halos verts rechargent la lampe.';this.reveal();}
 reveal(){for(let y=0;y<this.rows;y++)for(let x=0;x<this.cols;x++)if(Math.hypot(x-this.cell.x,y-this.cell.y)<this.vision)this.seen[y*this.cols+x]=true;}
 action(){if(this.status!=='playing')return;const sw=this.switches.find(s=>!s.used&&Math.abs(s.x-this.cell.x)+Math.abs(s.y-this.cell.y)<=1);if(sw){sw.used=true;let opened=false;for(let r=1;r<8&&!opened;r++)for(let y=Math.max(1,sw.y-r);y<Math.min(this.rows-1,sw.y+r);y++)for(let x=Math.max(1,sw.x-r);x<Math.min(this.cols-1,sw.x+r);x++){if(!opened&&this.grid[y][x]===1&&((!this.grid[y-1][x]&&!this.grid[y+1][x])||(!this.grid[y][x-1]&&!this.grid[y][x+1]))){this.grid[y][x]=0;opened=true;}}this.message='Un mur coulisse. Un passage secret vient de s’ouvrir.';this.score+=80;this.reveal();return;}if(this.flashCooldown<=0&&this.lamp>12){this.lamp-=12;this.flash=3;this.flashCooldown=15;this.message='Éclat de lumière : l’ombre est immobilisée pendant 3 secondes.';}}
 update(dt,input={}){if(this.status!=='playing')return;this.tick(dt);this.lamp-=dt;this.flash=Math.max(0,this.flash-dt);this.flashCooldown=Math.max(0,this.flashCooldown-dt);this.vision=clamp(3+this.lamp/100,3,5.2);this.moveClock-=dt;
 if(this.moveClock<=0&&(input.x||input.y)){const dx=Math.abs(input.x)>=Math.abs(input.y)?Math.sign(input.x):0,dy=dx?0:Math.sign(input.y);const nx=this.cell.x+dx,ny=this.cell.y+dy;if(this.grid[ny]?.[nx]===0){this.cell={x:nx,y:ny};this.reveal();}this.moveClock=.135;}
 for(const f of this.fragments)if(!f.collected&&f.x===this.cell.x&&f.y===this.cell.y){f.collected=true;this.collected++;this.lamp=Math.min(250,this.lamp+28);this.score+=150;this.message=`Fragment ${this.collected} / 3 retrouvé. ${this.collected===3?'Rejoins la porte !':'La lampe retrouve de la force.'}`;}
 for(const l of this.lamps)if(!l.collected&&l.x===this.cell.x&&l.y===this.cell.y){l.collected=true;this.lamp=Math.min(250,this.lamp+45);this.message='Lanterne retrouvée : +45 secondes de lumière.';}
 this.shadowClock-=dt;if(this.time>12&&this.shadowClock<=0&&this.flash<=0){const route=paths(this.grid,this.cell),pos=this.shadow.y*this.cols+this.shadow.x;const next=route.parent[pos];if(next>=0)this.shadow={x:next%this.cols,y:Math.floor(next/this.cols)};this.shadowClock=Math.max(.26,.55-this.time*.001);}
 if(this.flash<=0&&this.shadow.x===this.cell.x&&this.shadow.y===this.cell.y){this.finish(false,'L’ombre t’a retrouvé. Un nouveau labyrinthe t’attend.');return;}
 if(this.collected===3&&this.exit.x===this.cell.x&&this.exit.y===this.cell.y){this.score+=Math.round(this.lamp*3);this.finish(true,'Tu as ramené les trois fragments hors de l’Oubli.');return;}
 if(this.lamp<=0){this.lamp=0;this.finish(false,'La lampe s’est éteinte. Cherche les lanternes et les raccourcis à la prochaine traversée.');}}
 hud(){return [['Fragments',`${this.collected} / 3`],['Lampe',`${Math.ceil(this.lamp)} s`],['Éclat',this.flashCooldown>0?`${Math.ceil(this.flashCooldown)} s`:'Prêt'],['Secrets',`${this.switches.filter(s=>s.used).length} / 2`]];}
}
