import {BaseGame,W,H,distance,movePlayer,clamp} from './core.js';
const NAMES=['Nour','Lina','Sami','Inès','Adam','Maya','Yanis','Amel'];
export class Refuge extends BaseGame {
 constructor(saved,seed){super(seed);this.day=1;this.phase='day';this.phaseTime=0;this.wood=35;this.gate=100;this.turrets=0;this.homes=1;this.people=2;this.rescued=[];this.enemies=[];this.bullets=[];this.spawnClock=3;this.shotClock=0;this.invulnerable=0;this.interact=0;this.resident=null;this.nodes=this.makeNodes();if(saved){Object.assign(this,saved);this.effects=[];this.enemies=saved.enemies||[];this.bullets=[];}this.message='Le jour dure 2 min 30. Récupère des matériaux et prépare tes défenses.';}
 makeNodes(){return[{x:140,y:130,amount:35},{x:760,y:140,amount:35},{x:180,y:470,amount:35},{x:740,y:465,amount:35}];}
 action(){if(this.status!=='playing'||this.interact>0)return;const p=this.player;this.interact=.35;
 if(this.resident&&distance(p,this.resident)<85){if(this.people>=this.homes*3){this.message='Construis un abri pour accueillir cet habitant.';return;}const name=NAMES[this.rescued.length%NAMES.length];this.people++;this.rescued.push(name);this.resident=null;this.score+=150;this.message=name+' a rejoint le refuge.';this.effect(p.x,p.y,'#efd58b','Habitant sauvé');return;}
 if(distance(p,{x:450,y:360})<115&&this.gate<100){if(this.wood<5){this.message='Il faut 5 matériaux pour réparer.';return;}this.wood-=5;this.gate=Math.min(100,this.gate+20);this.message='Porte réparée : +20 solidité.';return;}
 const node=this.nodes.find(n=>n.amount>0&&distance(p,n)<85);if(node&&this.phase==='day'){const n=Math.min(10,node.amount);this.wood+=n;node.amount-=n;this.effect(node.x,node.y,'#edce87','+'+n);this.message='Matériaux récupérés.';return;}this.message='Approche des matériaux, de la porte ou de l’habitant à secourir.';}
 build(type){if(this.status!=='playing'||this.phase!=='day')return;const cost=type==='turret'?45:35;if(this.wood<cost){this.message=`Il manque ${cost-this.wood} matériaux.`;return;}if(type==='turret'&&this.turrets>=4){this.message='Les quatre postes de défense sont construits.';return;}if(type==='home'&&this.homes>=6){this.message='Le refuge possède déjà six abris.';return;}this.wood-=cost;if(type==='turret')this.turrets++;else this.homes++;this.score+=50;this.message=type==='turret'?'Un poste de tir défendra la porte cette nuit.':'Un nouvel abri peut accueillir trois habitants.';}
 startNight(){if(this.status!=='playing'||this.phase!=='day')return;this.phase='night';this.phaseTime=0;this.spawnClock=3;this.resident={x:this.random()>.5?100:800,y:310};this.message='La nuit commence. Secours l’habitant et protège la porte.';}
 shoot(origin,damage){let e=this.enemies.reduce((best,n)=>!best||distance(origin,n)<distance(origin,best)?n:best,null);if(!e)return;const a=Math.atan2(e.y-origin.y,e.x-origin.x);this.bullets.push({x:origin.x,y:origin.y,vx:Math.cos(a)*440,vy:Math.sin(a)*440,damage,life:2});}
 update(dt,input={}){if(this.status!=='playing')return;this.tick(dt);this.phaseTime+=dt;this.interact=Math.max(0,this.interact-dt);this.invulnerable=Math.max(0,this.invulnerable-dt);movePlayer(this.player,input,dt,220);
 if(this.phase==='day'){this.player.hp=Math.min(100,this.player.hp+dt*1.2);if(this.phaseTime>=150)this.startNight();return;}
 this.spawnClock-=dt;if(this.spawnClock<=0){if(this.enemies.length<65){const angle=this.random()*Math.PI*2;this.enemies.push({x:450+Math.cos(angle)*470,y:310+Math.sin(angle)*320,hp:32+this.day*9,speed:25+this.day*3,type:Math.floor(this.random()*3),hit:0});}this.spawnClock=Math.max(.6,3-this.day*.19);}
 this.shotClock-=dt;if(this.shotClock<=0){this.shoot(this.player,26);for(let i=0;i<this.turrets;i++)this.shoot({x:315+i%2*270,y:220+Math.floor(i/2)*170},22);this.shotClock=.7;}
 for(const b of this.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of this.enemies)if(e.hp>0&&distance(e,b)<20){e.hp-=b.damage;e.hit=.16;b.life=0;break;}}this.bullets=this.bullets.filter(b=>b.life>0);
 for(const e of this.enemies){if(e.hp<=0)continue;const target=distance(e,this.player)<115?this.player:{x:450,y:355};const d=distance(e,target);if(d>24){e.x+=(target.x-e.x)/d*e.speed*dt;e.y+=(target.y-e.y)/d*e.speed*dt;}else if(target===this.player){if(this.invulnerable<=0){this.player.hp-=9;this.invulnerable=.75;}}else this.gate-=dt*(1.3+this.day*.2);e.hit=Math.max(0,e.hit-dt);}
 for(const e of this.enemies.filter(e=>e.hp<=0)){this.score+=15;this.wood+=2;this.effect(e.x,e.y,'#9ab6c5');}this.enemies=this.enemies.filter(e=>e.hp>0);
 if(this.gate<=0||this.player.hp<=0){this.gate=Math.max(0,this.gate);this.player.hp=Math.max(0,this.player.hp);this.finish(false,'Le refuge a cédé cette nuit. Tes constructions restent : reprends au matin pour préparer une meilleure défense.');return;}
 if(this.phaseTime>=150){this.day++;this.phase='day';this.phaseTime=0;this.enemies=[];this.bullets=[];this.nodes=this.makeNodes();this.wood+=20+this.people*4;this.gate=clamp(this.gate+15,0,100);this.player.hp=100;this.score+=250;this.message=`Jour ${this.day}. Les habitants ont préparé ${20+this.people*4} matériaux. Le refuge grandit.`;}}
 snapshot(){const keys=['day','phase','phaseTime','wood','gate','turrets','homes','people','rescued','nodes','score','player','resident','enemies','time'];const s=Object.fromEntries(keys.map(k=>[k,structuredClone(this[k])]));if(this.status==='ended')Object.assign(s,{phase:'day',phaseTime:0,gate:100,player:{...s.player,hp:100,x:450,y:310},enemies:[],nodes:this.makeNodes(),wood:Math.max(s.wood,30)});return s;}
 hud(){return [['Cycle',`Jour ${this.day} · ${this.phase==='day'?'☀':'☾'} ${Math.ceil(150-this.phaseTime)} s`],['Porte',`${Math.ceil(this.gate)} %`],['Kaïs',Math.ceil(this.player.hp)+' ♥'],['Matériaux',this.wood],['Habitants',`${this.people} / ${this.homes*3}`]];}
}
