import {W,H,COLORS} from './core.js';
const images={},frames=[],loading={};
export const loadAssets=()=>Promise.all(['kais-run.webp','objects.webp','night-plaza.webp','ground-atlas.webp','city-sprites.webp'].map(name=>{
 if(images[name])return Promise.resolve();if(loading[name])return loading[name];
 loading[name]=new Promise((resolve,reject)=>{const im=new Image(),timer=setTimeout(()=>{delete loading[name];reject(new Error('Le chargement prend trop de temps. Réessaie.'));},20000);
 im.onload=()=>{clearTimeout(timer);images[name]=im;if(name==='kais-run.webp'){frames.length=0;for(let i=0;i<8;i++)frames.push([(i%4)*im.width/4+im.width*.076,Math.floor(i/4)*im.height/2,im.width*.15,im.height/2]);}resolve();};im.onerror=()=>{clearTimeout(timer);delete loading[name];reject(new Error('Une image du jeu ne s’est pas chargée. Réessaie.'));};im.src='/games/'+name;});return loading[name];}));
function circle(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill();}
export function label(c,text,x,y,color='#eed175',size=18){c.font=`600 ${size}px system-ui`;c.textAlign='center';c.fillStyle=color;c.fillText(text,x,y);}
function sprite(c,kind,x,y,h=50,time=0,facing=1){c.save();c.shadowColor=kind==='kais'?'#69aeef':'#567c97';c.shadowBlur=kind==='kais'?7:3;c.translate(x,y+10);c.scale(facing,1);if(kind==='kais'){const im=images['kais-run.webp'],r=frames[Math.floor(time*10)%8];if(im&&r)c.drawImage(im,...r,-h*.31,-h,h*.62,h);}else if(['house','garden','monument','watchtower'].includes(kind)){const im=images['city-sprites.webp'];const r={house:[0,0,627,585],garden:[627,0,627,605],monument:[0,585,627,669],watchtower:[627,605,627,649]}[kind];if(im)c.drawImage(im,...r,-h*.5,-h,h,h);}else{const im=images['objects.webp'];const cells={monster:[1024,470,512,554],portal:[0,470,512,554],gem:[1024,0,512,470],barrier:[0,0,512,470],rubble:[512,0,512,470],key:[512,470,512,554]};if(im)c.drawImage(im,...cells[kind],-h*.5,-h,h,h);}c.restore();}
export function render(c,g,kind,canvas){const worldW=g.viewWidth||(kind==='cities'?620:W),sx=canvas.width/worldW,sy=canvas.height/H;c.setTransform(sx,0,0,sy,0,0);c.clearRect(0,0,W,H);c.fillStyle='#0a1018';c.fillRect(0,0,W,H);const bg=images['night-plaza.webp'];if(bg)c.drawImage(bg,0,0,W,H);c.fillStyle='rgba(4,10,16,.22)';c.fillRect(0,0,W,H);
  if(kind==='arena'||kind==='refuge'){
    if(kind==='refuge')drawRefuge(c,g);
    const p=g.player;if(g.powers?.frost){circle(c,p.x,p.y,105+g.powers.frost*14,'#70d8ef1a');c.strokeStyle='#a4efff77';c.lineWidth=1;c.beginPath();c.arc(p.x,p.y,105+g.powers.frost*14,0,Math.PI*2);c.stroke();}
    for(const gem of g.gems||[])sprite(c,'gem',gem.x,gem.y,27);
    for(const e of [...g.enemies].sort((a,b)=>a.y-b.y)){c.globalAlpha=e.hit>0?.55:1;if(e.ring){c.strokeStyle='#f19486';c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,120*e.ring,0,Math.PI*2);c.stroke();}circle(c,e.x,e.y+6,e.boss?26:16,'#03060899');sprite(c,'monster',e.x,e.y,e.boss?105:55+e.type*3);c.globalAlpha=1;if(e.boss){label(c,e.country,e.x,e.y-96,COLORS[e.index],15);c.fillStyle='#171a21';c.fillRect(e.x-45,e.y-84,90,5);c.fillStyle=COLORS[e.index];c.fillRect(e.x-45,e.y-84,90*Math.max(0,e.hp/e.maxHp),5);}}
    if(g.powers?.ghost){c.globalAlpha=.4;sprite(c,'kais',p.x+38,p.y-20,70,g.time);c.globalAlpha=1;}
    if(g.powers?.blades)for(let i=0;i<2+g.powers.blades;i++){const a=g.time*3+i*Math.PI*2/(2+g.powers.blades);c.save();c.translate(p.x+Math.cos(a)*67,p.y+Math.sin(a)*67);c.rotate(a);c.fillStyle='#edf8fe';c.fillRect(-3,-14,6,28);c.restore();}
    for(const b of g.hazards||[]){if(b.warn>0){c.strokeStyle='#f69789';c.lineWidth=2;c.beginPath();c.arc(b.x,b.y,17,0,Math.PI*2);c.stroke();}else{circle(c,b.x,b.y,9,'#ff78534d');circle(c,b.x,b.y,4,'#ffb191');}}
    for(const b of g.bullets){circle(c,b.x,b.y,7,'#e6bc5140');circle(c,b.x,b.y,3,'#fff3a3');}
    circle(c,p.x,p.y+9,17,'#0008');c.strokeStyle='#e9cf86';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y+9,22,10,0,0,Math.PI*2);c.stroke();c.globalAlpha=g.invulnerable>0?.65:1;sprite(c,'kais',p.x,p.y,70,p.moving?g.time:0,p.facing);c.globalAlpha=1;
    if(kind==='arena'&&g.time<8)label(c,'Ramasse les fragments. Tes attaques sont automatiques.',W/2,H-35,'#f0e7cc',18);
  }else if(kind==='tower')drawTower(c,g);else if(kind==='maze')drawMaze(c,g);else if(kind==='cities')drawCities(c,g);
  for(const e of g.effects){c.globalAlpha=Math.min(1,e.life*2);if(e.bolt){c.strokeStyle=e.color;c.lineWidth=3;c.beginPath();c.moveTo(e.x2,e.y2);c.lineTo((e.x+e.x2)/2+12,(e.y+e.y2)/2);c.lineTo(e.x,e.y);c.stroke();}else if(e.text)label(c,e.text,e.x,e.y-(.65-e.life)*38,e.color,18);else{for(let i=0;i<6;i++){const a=i*Math.PI/3;circle(c,e.x+Math.cos(a)*(1-e.life)*30,e.y+Math.sin(a)*(1-e.life)*30,2,e.color);}}}c.globalAlpha=1;
}
function drawTower(c,g){c.fillStyle='#090712b8';c.fillRect(0,0,W,H);label(c,'ÉTAGE '+g.floor,W/2,60,'#eed175',24);if(g.room==='combat'){sprite(c,'monster',W*.62,H*.61,210);sprite(c,'kais',W*.3,H*.7,155,g.time);label(c,g.enemy.windup<.7?'L’ombre prépare son attaque !':'Trouve une ouverture',W/2,120,g.enemy.windup<.7?'#f49b98':'#c6d4e5',22);c.fillStyle='#1e1f2b';c.fillRect(W*.45,155,300,10);c.fillStyle='#d48c91';c.fillRect(W*.45,155,300*g.enemy.hp/g.enemy.maxHp,10);}else{for(let i=0;i<3;i++){const x=185+i*265;sprite(c,'portal',x,400,270);label(c,String(i+1).padStart(2,'0'),x,465,'#eed175',27);label(c,g.doors?.[i]?.hint||'',x,505,'#dde1ed',17);}sprite(c,'kais',W/2,595,75,g.time*.25);}}
function drawMaze(c,g){c.fillStyle='#080b10';c.fillRect(0,0,W,H);const s=Math.min(36,(W-44)/g.cols,(H-40)/g.rows),ox=(W-g.cols*s)/2,oy=(H-g.rows*s)/2;g.layout={s,ox,oy};const p=g.cell;c.save();const zoom=1.65;c.translate((g.viewWidth||W)/2-(ox+(p.x+.5)*s)*zoom,H/2-(oy+(p.y+.5)*s)*zoom);c.scale(zoom,zoom);for(let y=0;y<g.rows;y++)for(let x=0;x<g.cols;x++){const d=Math.hypot(x-p.x,y-p.y),seen=g.seen[y*g.cols+x];if(!seen&&d>g.vision)continue;const wall=g.grid[y][x]===1;c.fillStyle=wall?(d<g.vision?'#303e4d':'#171f2b'):(d<g.vision?'#111f2c':'#0b1119');c.fillRect(ox+x*s,oy+y*s,s-1,s-1);if(d<g.vision&&images['ground-atlas.webp']){const im=images['ground-atlas.webp'],tw=im.width/4,th=im.height/2;c.globalAlpha=wall?.65:.18;c.drawImage(im,wall?0:tw,wall?0:th,tw,th,ox+x*s,oy+y*s,s-1,s-1);c.globalAlpha=1;}if(wall&&d<g.vision){c.fillStyle='#61718344';c.fillRect(ox+x*s,oy+y*s,s-1,2);}}
  const at=o=>[ox+(o.x+.5)*s,oy+(o.y+.65)*s];for(const o of g.fragments)if(!o.collected&&g.seen[o.y*g.cols+o.x]){const [x,y]=at(o);sprite(c,'gem',x,y,s*1.12);}for(const o of g.lamps)if(!o.collected&&g.seen[o.y*g.cols+o.x]){const[x,y]=at(o);circle(c,x,y-5,6,'#8ef2df');}for(const o of g.switches)if(g.seen[o.y*g.cols+o.x]){const[x,y]=at(o);label(c,o.used?'✓':'⊕',x,y,o.used?'#748488':'#dab8ef',s*.75);}
  if(g.seen[g.exit.y*g.cols+g.exit.x]){const[x,y]=at(g.exit);sprite(c,'portal',x,y,s*1.6);}
  if(Math.hypot(g.shadow.x-p.x,g.shadow.y-p.y)<g.vision+1){const[x,y]=at(g.shadow);sprite(c,'monster',x,y,s*1.6);}const[x,y]=at(p);circle(c,x,y-5,s*.52,'#e6d49522');sprite(c,'kais',x,y,s*1.5,g.time);c.restore();}
function drawRefuge(c,g){if(g.phase==='night'){c.fillStyle='#08172a66';c.fillRect(0,0,W,H);}c.strokeStyle='#cab478';c.lineWidth=3;c.strokeRect(330,210,240,190);c.fillStyle='#132135cc';c.fillRect(335,215,230,180);sprite(c,'monument',450,305,125);for(let i=0;i<g.homes;i++)sprite(c,'house',370+i%3*80,350+Math.floor(i/3)*50,58);label(c,'REFUGE 3B',450,370,'#eed175',20);c.fillStyle='#253243';c.fillRect(345,405,210,8);c.fillStyle='#92d8b8';c.fillRect(345,405,210*g.gate/100,8);for(const n of g.nodes)if(n.amount>0){sprite(c,'rubble',n.x,n.y,65);label(c,'E · '+n.amount,n.x,n.y+30,'#d8dfe7',15);}for(let i=0;i<g.turrets;i++){const x=315+(i%2)*270,y=220+Math.floor(i/2)*170;sprite(c,'watchtower',x,y,90);}if(g.resident){sprite(c,'kais',g.resident.x,g.resident.y,58,g.time*.5);label(c,'À secourir · E',g.resident.x,g.resident.y-62,'#efd68f',17);}label(c,g.phase==='day'?'Approche des matériaux et appuie sur E.':'Protège le refuge. E pour réparer ou secourir.',W/2,H-27,'#d2deeb',17);}
export const TILE_ICONS={road:'╋',house:'⌂',garden:'❋',monument:'♜'};
function drawCities(c,g){c.fillStyle='#0d2025d9';c.fillRect(0,0,W,H);const cityW=620,s=76,ox=(cityW-s*7)/2,oy=42;g.layout={s,ox,oy};for(let y=0;y<7;y++)for(let x=0;x<7;x++){const t=g.board[y*7+x],px=ox+x*s,py=oy+y*s;c.fillStyle=t?{road:'#484737',house:'#315055',garden:'#28533f',monument:'#645338'}[t.type]:'#172e35';c.fillRect(px+2,py+2,s-4,s-4);if(t){if(t.type==='road'){c.save();c.translate(px+s/2,py+s/2);c.rotate(t.rot*Math.PI/2);c.strokeStyle='#e3cf9d';c.lineWidth=9;c.beginPath();c.moveTo(0,0);c.lineTo(0,-s/2);c.moveTo(0,0);c.lineTo(t.shape==='straight'?0:s/2,t.shape==='straight'?s/2:0);c.stroke();c.restore();}else{c.globalAlpha=g.connected?.includes(y*7+x)?1:.6;sprite(c,t.type,px+s/2,py+s*.79,s*.92);c.globalAlpha=1;}if(g.connected?.includes(y*7+x)){c.strokeStyle='#dcca8a99';c.lineWidth=1;c.strokeRect(px+4,py+4,s-8,s-8);}}else if(g.canPlace(x,y)){label(c,'+',px+s/2,py+s*.62,'#718e94',23);}}
  if(g.cursor){c.strokeStyle='#91d7e9';c.lineWidth=3;c.strokeRect(ox+g.cursor.x*s+2,oy+g.cursor.y*s+2,s-4,s-4);}
  label(c,g.country+' · '+g.cityName,cityW/2,27,'#e8d29a',24);label(c,'Relie les quartiers par les rues.',cityW/2,H-15,'#c6d9d8',19);}

