import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Building2,CarFront,Coins,Eye,Globe2,Map as MapIcon,Package,Settings2,Shirt,Trash2,X} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {CITY_COUNTRIES,CITY_VALUES,city3bRequest} from '../city/city3b-client.js';
import '../styles/city-3b.css';
const TABS=[['city','Ville',Building2],['build','Construire',Building2],['districts','Quartiers',MapIcon],['collection','Collection',Package],['visit','Visiter',Globe2]];
const reqId=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
export default function City3BPortal(props){
 const account=useLoyalty();
 return <City3BPortalSession key={account.user?.id||'guest'} {...props} account={account}/>;
}
function City3BPortalSession({open,onClose,account}){
 const uid=account.user?.id,dialog=useRef(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const country=account.passport?.userId===uid?account.passport.country:'';const[data,setData]=useState(null),[tab,setTab]=useState('city'),[busy,setBusy]=useState(false),[error,setError]=useState('');const[name,setName]=useState('Ma ville 3B');
 const call=async(action,body={})=>{setBusy(true);setError('');try{const v=await city3bRequest(action,body,uid);if(!mounted.current)return null;setData(v);return v}catch(e){if(mounted.current)setError(e.message);return null}finally{if(mounted.current)setBusy(false)}};
 useEffect(()=>{if(open&&uid){setTab('city');call('sync_world')}else if(open&&!account.loading){setData(null);setError('')}},[open,uid,account.loading]);if(!open)return null;const city=data?.city,profile=account.profile||{},needsLogin=!account.loading&&!uid;
 return createPortal(<dialog ref={dialog} open className="city3b-dialog" aria-label="Crée ta ville 3B"><div className="city3b-shell"><header className="city3b-top"><div className="city3b-brand"><b>3B</b><span>CRÉE TA VILLE</span></div><div className="city3b-stats"><span className="city3b-chip">NIV. {city?.city_level||1}</span><span className="city3b-chip"><Coins size={13}/> {Number(data?.wallet?.coins||0)} Coins</span><span className="city3b-chip">Terrain {city?.land_tier||1}/10</span></div><button className="city3b-close" onClick={onClose} aria-label="Fermer"><X size={20}/></button></header><main className="city3b-main">{error&&<div className="city3b-error" role="alert">{error}</div>}{account.loading?<div className="city3b-loading">VÉRIFICATION DU PASSEPORT…</div>:needsLogin?<LoginRequired/>:!data&&!error?<div className="city3b-loading">SYNCHRONISATION VILLE 3B…</div>:!city?<CreateCity name={name} setName={setName} country={country} busy={busy} create={()=>call('create',{name:name.trim(),country})}/>:<CityContent tab={tab} setTab={setTab} data={data} uid={uid} busy={busy} call={call}/>}</main>{city&&<nav className="city3b-nav" aria-label="Navigation Ville 3B">{TABS.map(([id,label,Icon])=><button key={id} aria-current={tab===id} onClick={()=>setTab(id)}><Icon size={18}/><br/>{label}</button>)}</nav>}</div></dialog>,document.body)
}
function LoginRequired(){return <section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">PASSEPORT 3B REQUIS</p><h2>Connecte ton <em>espace membre.</em></h2><p>Ta ville, tes constructions et ta collection sont liées à ton compte 3B. Connecte-toi d’abord depuis l’Espace membre, puis rouvre le Passeport.</p></div></section>}
function CreateCity({name,setName,country,busy,create}){return <section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">DE ZÉRO À TA PROPRE CITÉ</p><h2>Crée ta <em>ville 3B.</em></h2><p>Une ville permanente. Huit quartiers. Aucun reset, aucune saison.</p><div className="city3b-form"><input aria-label="Nom de la ville" value={name} maxLength={40} onChange={e=>setName(e.target.value)}/><label>Pays d’origine · lié au Passeport 3B<input aria-label="Pays d’origine" value={country} readOnly placeholder="Complète ton Passeport"/></label><button className="city3b-btn primary" disabled={busy||name.trim().length<2||!country} onClick={create}>{busy?'Création…':'Fonder ma ville'}</button></div></div></section>}
function CityContent({tab,setTab,data,uid,busy,call}){const c=data.city;if(tab==='city')return <CityHome data={data} call={call} setTab={setTab} busy={busy}/>;if(tab==='build')return <BuildPanel data={data} busy={busy} call={call}/>;if(tab==='districts')return <Districts data={data} busy={busy} call={call}/>;if(tab==='collection')return <Collection data={data} busy={busy} call={call}/>;if(tab==='settings')return <CitySettings city={c} busy={busy} call={call} setTab={setTab}/>;return <Discovery uid={uid}/>}
function CityHome({data,call,setTab,busy}){const c=data.city;return <>{data.synced&&(data.synced.minted>0||data.synced.unlocked>0)&&<section className="city3b-panel"><h3>Monde 3B synchronisé</h3><p>{data.synced.unlocked||0} quartier(s) lié(s) · {data.synced.minted||0} récompense(s) permanente(s) ajoutée(s) à ta collection.</p></section>}<section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">{c.origin_country?.toUpperCase()} · {CITY_VALUES[c.origin_country]}</p><h2>{c.name}</h2><p>Niveau {c.city_level} · {c.city_xp} XP ville · {c.visitors} visites</p><div className="city3b-progress"><i style={{width:`${Math.min(100,(c.city_xp%1000)/10)}%`}}/></div><div className="city3b-actions"><button className="city3b-btn primary" onClick={()=>setTab('build')}>Construire</button><button className="city3b-btn blue" disabled={busy} onClick={()=>call('recalculate')}>Actualiser</button><button className="city3b-btn" onClick={()=>setTab('settings')}><Settings2 size={15}/> Paramètres</button></div></div></section><section className="city3b-panel"><h3>Ma cité</h3><div className="city3b-cards"><article className="city3b-card"><strong>{data.placements?.length||0}</strong><small>constructions</small></article><article className="city3b-card"><strong>{data.districts?.filter(x=>x.unlocked).length||1}/8</strong><small>quartiers</small></article><article className="city3b-card"><strong>{data.items?.length||0}</strong><small>objets permanents</small></article><article className="city3b-card"><strong>{c.day_mode} · {c.weather}</strong><small>{c.ambience}</small></article></div></section>{data.placements?.length>0&&<section className="city3b-panel"><h3>Bâtiments placés</h3><div className="city3b-cards">{data.placements.slice(-12).map(p=><article key={p.id} className="city3b-card"><strong>{p.building_code}</strong><small>Parcelle {p.x}, {p.z} · {p.rotation}°</small><button className="city3b-btn danger" disabled={busy} onClick={()=>call('remove',{placement:p.id})}><Trash2 size={14}/> Retirer</button></article>)}</div></section>}</>}
function BuildPanel({data,busy,call}){const[selected,setSelected]=useState(null),[x,setX]=useState(0),[z,setZ]=useState(0),[rotation,setRotation]=useState(0);const build=()=>selected&&call('place',{building:selected.code,x:Number(x),z:Number(z),rotation:Number(rotation),request:reqId()});return <section className="city3b-panel"><h3>Construire</h3><p>Choisis un bâtiment, puis une parcelle. Le serveur contrôle niveau, quartier, collisions et Coins.</p><div className="city3b-cards">{(data.buildings||[]).map(b=><button key={b.code} className="city3b-card" aria-pressed={selected?.code===b.code} onClick={()=>setSelected(b)}><strong>{b.name}</strong><span>{b.cost_coins} Coins</span><small>Niveau {b.unlock_level}{b.country?` · ${b.country}`:''}</small></button>)}</div>{selected&&<div className="city3b-placement"><strong>{selected.name}</strong><label>X<input type="number" min="-500" max="500" value={x} onChange={e=>setX(e.target.value)}/></label><label>Z<input type="number" min="-500" max="500" value={z} onChange={e=>setZ(e.target.value)}/></label><label>Rotation<select value={rotation} onChange={e=>setRotation(e.target.value)}><option>0</option><option>90</option><option>180</option><option>270</option></select></label><button className="city3b-btn primary" disabled={busy} onClick={build}>{busy?'Validation…':`Construire · ${selected.cost_coins} Coins`}</button></div>}</section>}
function Districts({data,busy,call}){return <section className="city3b-panel"><h3>Les huit quartiers</h3><div className="city3b-cards">{(data.districts||[]).map(d=><article key={d.country} className="city3b-card" data-locked={!d.unlocked}><strong>{d.country}</strong><span>{CITY_VALUES[d.country]}</span><small>{d.unlocked?`Quartier niveau ${d.level}`:'À débloquer avec ta progression'}</small>{!d.unlocked&&<button className="city3b-btn" disabled={busy} onClick={()=>call('unlock_district',{country:d.country})}>Débloquer</button>}</article>)}</div></section>}
function Collection({data,busy,call}){const defs=useMemo(()=>new Map((data.definitions||[]).map(d=>[d.code,d])),[data.definitions]);const displayed=new Set((data.displays||[]).map(d=>d.item_instance_id));return <section className="city3b-panel"><h3>Collection permanente</h3><p>Expose tes objets dans la ville, ou range les véhicules et tenues dans les espaces dédiés.</p>{!data.items?.length?<div className="city3b-empty">Aucun objet permanent dans ton inventaire.</div>:<div className="city3b-cards">{data.items.map((item,index)=>{const d=defs.get(item.item_code)||{};return <article key={item.id} className="city3b-card"><strong>{d.name||item.item_code}</strong><span>{d.rarity||'3B'} · #{item.serial_no}</span><small>{d.item_type||'collectible'}</small>{displayed.has(item.id)?<button className="city3b-btn" disabled={busy} onClick={()=>call('remove_display',{item:item.id})}>Retirer de la ville</button>:<button className="city3b-btn blue" disabled={busy} onClick={()=>call('display',{item:item.id,x:20+(index%8)*2,z:20+Math.floor(index/8)*2,rotation:0})}><Eye size={14}/> Exposer</button>}{d.item_type==='vehicle'&&<button className="city3b-btn" disabled={busy} onClick={()=>call('asset_set',{asset:'GARAGE_3B',slot:(index%8)+1,item:item.id})}><CarFront size={14}/> Garage</button>}{d.item_type==='outfit'&&<button className="city3b-btn" disabled={busy} onClick={()=>call('asset_set',{asset:'DRESSING_3B',slot:(index%20)+1,item:item.id})}><Shirt size={14}/> Dressing</button>}</article>})}</div>}</section>}
function Discovery({uid}){const[rows,setRows]=useState(null),[visit,setVisit]=useState(null),[notice,setNotice]=useState('');useEffect(()=>{city3bRequest('discover',{},uid).then(v=>setRows(v.cities||[])).catch(()=>setRows([]))},[uid]);const open=async c=>{setNotice('');try{const v=await city3bRequest('visit',{city:c.city_id},uid);setVisit(v)}catch(e){setNotice(e.message)}};return <section className="city3b-panel"><h3>Découvrir les villes 3B</h3>{notice&&<div className="city3b-error">{notice}</div>}{visit&&<div className="city3b-visit"><strong>{visit.city?.name}</strong><span>{visit.city?.origin_country} · niveau {visit.city?.city_level}</span><small>{visit.placements?.length||0} bâtiments · {visit.displays?.length||0} objets exposés</small><button className="city3b-btn" onClick={()=>setVisit(null)}>Retour à la liste</button></div>}{!visit&&(!rows?<div className="city3b-empty">Recherche…</div>:rows.length===0?<div className="city3b-empty">Les premières villes publiques apparaîtront ici.</div>:<div className="city3b-cards">{rows.map(c=><article key={c.city_id} className="city3b-card"><strong>{c.name}</strong><span>{c.origin_country} · niv. {c.level}</span><small>{c.visitors} visites</small><button className="city3b-btn blue" onClick={()=>open(c)}>Visiter</button><button className="city3b-btn" onClick={()=>city3bRequest('favorite',{city:c.city_id,add:true},uid)}>☆ Favori</button></article>)}</div>)}</section>}
function CitySettings({city,busy,call,setTab}){const[n,setN]=useState(city.name),[visibility,setVisibility]=useState(city.visibility),[day,setDay]=useState(city.day_mode),[weather,setWeather]=useState(city.weather),[ambience,setAmbience]=useState(city.ambience);return <section className="city3b-panel"><h3><Settings2 size={18}/> Paramètres de la ville</h3><div className="city3b-form"><input value={n} maxLength={40} onChange={e=>setN(e.target.value)}/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">Privée</option><option value="friends">Amis</option><option value="public">Publique</option></select><button className="city3b-btn primary" disabled={busy} onClick={()=>call('settings',{name:n,visibility})}>Enregistrer l’identité</button><select value={day} onChange={e=>setDay(e.target.value)}><option value="auto">Jour/nuit automatique</option><option value="day">Jour</option><option value="night">Nuit</option></select><select value={weather} onChange={e=>setWeather(e.target.value)}><option value="clear">Clair</option><option value="rain">Pluie</option><option value="fog">Brouillard</option><option value="snow">Neige</option><option value="storm">Tempête</option></select><select value={ambience} onChange={e=>setAmbience(e.target.value)}><option value="matrix">Matrix</option><option value="gold">Or</option><option value="urban">Urbaine</option><option value="cinematic">Cinéma</option><option value="calm">Calme</option></select><button className="city3b-btn blue" disabled={busy} onClick={()=>call('environment',{day,weather,ambience})}>Appliquer l’ambiance</button><button className="city3b-btn" onClick={()=>setTab('city')}>← Retour à ma ville</button></div></section>}
