import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Building2,CarFront,Coins,Eye,Flag,Globe2,Map as MapIcon,Package,Settings2,Shirt,Sparkles,Trash2,X} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {CITY_COUNTRIES,CITY_VALUES,city3bRequest} from '../city/city3b-client.js';
import City3BBuilder,{City3BPrivatePreview} from '../city/City3BBuilder.jsx';
import {cityMapUrbanScore} from '../city/city3b-map.js';
import DigitalStorePanel from '../store/DigitalStorePanel.jsx';
import {loadDigitalStore} from '../store/digital-store-client.js';
import {ownedPremiumCodes} from '../store/premium-effects.js';
import {citySimulationSnapshot} from '../city/city3b-simulation.js';
import City3BCampaign,{City3BCampaignPreview} from '../city/City3BCampaign.jsx';
import '../styles/city-3b.css';
const TABS=[['city','Carte',MapIcon],['build','Construire',Building2],['missions','Missions',Flag],['preview','Aperçu',Eye],['districts','Quartiers',MapIcon],['premium','Premium',Sparkles],['collection','Collection',Package],['visit','Visiter',Globe2]];
export default function City3BPortal(props){
 const account=useLoyalty();
 return <City3BPortalSession key={account.user?.id||'guest'} {...props} account={account}/>;
}
function City3BPortalSession({open,onClose,account}){
 const uid=account.user?.id,dialog=useRef(null),mounted=useRef(true),pending=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!open)return;const element=dialog.current,previous=document.activeElement;if(element&&!element.open)element.showModal();return()=>{element?.close();if(previous?.isConnected)previous.focus?.();};},[open]);
 const country=account.passport?.userId===uid?account.passport.country:'';const[data,setData]=useState(null),[tab,setTab]=useState('city'),[busy,setBusy]=useState(false),[error,setError]=useState('');const[name,setName]=useState('Ma ville 3B');const[premiumCodes,setPremiumCodes]=useState(()=>new Set());const[builderFocus,setBuilderFocus]=useState(null),[notice,setNotice]=useState('');
 const followAction=action=>{if(action?.tab==='build')setBuilderFocus({...action,requestedAt:Date.now()});setTab(['build','districts','collection','settings'].includes(action?.tab)?action.tab:'build');};
 const call=async(action,body={})=>{if(pending.current)return null;pending.current=true;setBusy(true);setError('');setNotice('');try{const v=await city3bRequest(action,body,uid);if(!mounted.current)return null;setData(v);if(v.reward){setNotice(v.reward.alreadyClaimed?'Cette récompense a déjà été reçue.':`Mission accomplie · +${v.reward.coins} Coins et +${v.reward.cityXp} XP ville.`);}if(['mission_claim','create','place'].includes(action))account.refresh?.();return v}catch(e){if(mounted.current)setError(e.message);return null}finally{pending.current=false;if(mounted.current)setBusy(false)}};
 useEffect(()=>{if(open&&uid){setTab('city');call('snapshot');loadDigitalStore('city').then(store=>{if(mounted.current)setPremiumCodes(ownedPremiumCodes(store));}).catch(()=>{if(mounted.current)setPremiumCodes(new Set());});}else if(open&&!account.loading){setData(null);setPremiumCodes(new Set());setError('')}},[open,uid,account.loading]);if(!open)return null;const city=data?.city,profile=account.profile||{},needsLogin=!account.loading&&!uid;
 return createPortal(<dialog ref={dialog} className="city3b-dialog" aria-modal="true" aria-label="Crée ta ville 3B" onCancel={event=>{event.preventDefault();onClose();}}><div className="city3b-shell"><header className="city3b-top"><div className="city3b-brand"><b>3B</b><span>CRÉE TA VILLE</span></div><div className="city3b-stats"><span className="city3b-chip">NIV. {city?.city_level||1}</span><span className="city3b-chip"><Coins size={13}/> {Number(data?.wallet?.coins||0)} Coins</span><span className="city3b-chip">Terrain {city?.land_tier||1}/10</span></div><button className="city3b-close" onClick={onClose} aria-label="Fermer"><X size={20}/></button></header><main className="city3b-main">{notice&&<div className="city3b-campaign-notice" role="status">{notice}</div>}{error&&<div className="city3b-error" role="alert">{error}</div>}{account.loading?<div className="city3b-loading">VÉRIFICATION DU PASSEPORT…</div>:needsLogin?<LoginRequired/>:!data&&!error?<div className="city3b-loading">CHARGEMENT VILLE 3B…</div>:!city?<CreateCity name={name} setName={setName} country={country} busy={busy} create={()=>call('create',{name:name.trim(),country})}/>:<CityContent tab={tab} setTab={setTab} data={data} uid={uid} busy={busy} call={call} premiumCodes={premiumCodes} onPremiumStore={store=>setPremiumCodes(ownedPremiumCodes(store))} builderFocus={builderFocus} onAction={followAction}/>}</main>{city&&<nav className="city3b-nav" aria-label="Navigation Ville 3B">{TABS.map(([id,label,Icon])=><button key={id} aria-current={tab===id} onClick={()=>setTab(id)}><Icon size={18}/><br/>{label}</button>)}</nav>}</div></dialog>,document.body)
}
function LoginRequired(){return <section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">PASSEPORT 3B REQUIS</p><h2>Connecte ton <em>espace membre.</em></h2><p>Ta ville, tes constructions et ta collection sont liées à ton compte 3B. Connecte-toi d’abord depuis l’Espace membre, puis ouvre Créer ma Ville depuis le menu.</p></div></section>}
function CreateCity({name,setName,country,busy,create}){return <section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">DE ZÉRO À TA PROPRE CITÉ</p><h2>Crée ta <em>ville 3B.</em></h2><p>Une ville permanente. Huit quartiers. Aucun reset, aucune saison. Construis librement ou suis les 24 missions et 8 demandes des habitants.</p><div className="city3b-form"><input aria-label="Nom de la ville" value={name} maxLength={40} onChange={e=>setName(e.target.value)}/><label>Pays d’origine · lié au Passeport 3B<input aria-label="Pays d’origine" value={country} readOnly placeholder="Complète ton Passeport"/></label><button className="city3b-btn primary" disabled={busy||name.trim().length<2||!country} onClick={create}>{busy?'Création…':'Fonder ma ville'}</button></div></div></section>}
function CityContent({tab,setTab,data,uid,busy,call,premiumCodes,onPremiumStore,builderFocus,onAction}){const c=data.city;if(tab==='city')return <CityHome data={data} call={call} setTab={setTab} busy={busy} premiumCodes={premiumCodes} onAction={onAction}/>;if(tab==='build')return <BuildPanel data={data} busy={busy} call={call} premiumCodes={premiumCodes} focus={builderFocus}/>;if(tab==='missions')return <City3BCampaign campaign={data.campaign} busy={busy} onClaim={mission=>call('mission_claim',{mission})} onAction={onAction} onRefresh={()=>call('snapshot')}/>;if(tab==='preview')return <City3BPrivatePreview data={data} premiumCodes={premiumCodes}/>;if(tab==='districts')return <Districts data={data} busy={busy} call={call}/>;if(tab==='premium')return <DigitalStorePanel scope="city" onStoreChange={onPremiumStore}/>;if(tab==='collection')return <Collection data={data} busy={busy} call={call}/>;if(tab==='settings')return <CitySettings city={c} busy={busy} call={call} setTab={setTab}/>;return <Discovery uid={uid} savedFavorites={data.favorites}/>}
function CityHome({data,call,setTab,busy,premiumCodes,onAction}){const c=data.city,urban=cityMapUrbanScore(data),simulation=citySimulationSnapshot(data);return <><section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">{c.origin_country?.toUpperCase()} · {CITY_VALUES[c.origin_country]}</p><h2>{c.name}</h2><p>Niveau {c.city_level} · {c.city_xp} XP ville · {c.visitors} visites</p><div className="city3b-progress"><i style={{width:`${Math.min(100,(c.city_xp%1000)/10)}%`}}/></div><div className="city3b-actions"><button className="city3b-btn primary" onClick={()=>setTab('build')}>Construire la ville</button><button className="city3b-btn blue" disabled={busy} onClick={()=>call('recalculate')}>Recalculer ma progression</button><button className="city3b-btn" onClick={()=>setTab('settings')}><Settings2 size={15}/> Paramètres</button></div></div></section><City3BCampaignPreview campaign={data.campaign} busy={busy} onOpen={()=>setTab('missions')} onAction={onAction} onRefresh={()=>call('snapshot')}/><City3BPrivatePreview data={data} premiumCodes={premiumCodes}/><section className="city3b-panel"><h3>Ma cité</h3><div className="city3b-cards"><article className="city3b-card"><strong>{data.placements?.filter(x=>x.placement_state!=='stored').length||0}</strong><small>constructions</small></article><article className="city3b-card"><strong>{data.districts?.filter(x=>x.unlocked).length||1}/8</strong><small>quartiers ouverts</small></article><article className="city3b-card"><strong>{urban.score}%</strong><small>équilibre urbain</small></article><article className="city3b-card"><strong>{urban.customRoads}</strong><small>axes routiers créés</small></article><article className="city3b-card"><strong>{simulation.residents}</strong><small>habitants simulés</small></article><article className="city3b-card"><strong>{simulation.satisfaction}%</strong><small>satisfaction · {simulation.status}</small></article></div></section>{data.placements?.length>0&&<section className="city3b-panel"><h3>Bâtiments placés</h3><div className="city3b-cards">{data.placements.filter(p=>p.placement_state!=='stored').slice(-12).map(p=><article key={p.id} className="city3b-card"><strong>{p.building_code}</strong><small>Parcelle {p.x}, {p.z} · {p.rotation}°</small><button className="city3b-btn danger" disabled={busy} onClick={()=>call('remove',{placement:p.id})}><Trash2 size={14}/> Ranger</button></article>)}</div></section>}</>}
function BuildPanel({data,busy,call,premiumCodes,focus}){return <City3BBuilder data={data} busy={busy} call={call} premiumCodes={premiumCodes} focus={focus}/>} 
function Districts({data}){return <section className="city3b-panel"><h3>Les huit quartiers</h3><p>Les quartiers se débloquent automatiquement grâce au niveau de ta ville : constructions, routes distinctes, objets exposés, fréquentation et XP des missions font avancer ta progression. Les services publics comptent comme constructions. La progression de la Ville reste indépendante du Monde du 3B.</p><div className="city3b-cards">{(data.districts||[]).map(d=><article key={d.country} className="city3b-card" data-locked={!d.unlocked}><strong>{d.country}</strong><span>{CITY_VALUES[d.country]}</span><small>{d.unlocked?`Ouvert · quartier niveau ${d.level}`:'Verrouillé · développe ta ville pour l’ouvrir'}</small></article>)}</div></section>}
function Collection({data,busy,call}){const defs=useMemo(()=>new Map((data.definitions||[]).map(d=>[d.code,d])),[data.definitions]);const displayed=new Set((data.displays||[]).map(d=>d.item_instance_id));return <section className="city3b-panel"><h3>Collection permanente</h3><p>Expose tes objets dans la ville, ou range les véhicules et tenues dans les espaces dédiés.</p>{!data.items?.length?<div className="city3b-empty">Aucun objet permanent dans ton inventaire.</div>:<div className="city3b-cards">{data.items.map((item,index)=>{const d=defs.get(item.item_code)||{};return <article key={item.id} className="city3b-card"><strong>{d.name||item.item_code}</strong><span>{d.rarity||'3B'} · #{item.serial_no}</span><small>{d.item_type||'collectible'}</small>{displayed.has(item.id)?<button className="city3b-btn" disabled={busy} onClick={()=>call('remove_display',{item:item.id})}>Retirer de la ville</button>:<button className="city3b-btn blue" disabled={busy} onClick={()=>call('display',{item:item.id,x:20+(index%8)*2,z:20+Math.floor(index/8)*2,rotation:0})}><Eye size={14}/> Exposer</button>}{d.item_type==='vehicle'&&<button className="city3b-btn" disabled={busy} onClick={()=>call('asset_set',{asset:'GARAGE_3B',slot:(index%8)+1,item:item.id})}><CarFront size={14}/> Garage</button>}{d.item_type==='outfit'&&<button className="city3b-btn" disabled={busy} onClick={()=>call('asset_set',{asset:'DRESSING_3B',slot:(index%20)+1,item:item.id})}><Shirt size={14}/> Dressing</button>}</article>})}</div>}</section>}
function Discovery({uid,savedFavorites=[]}){
 const[rows,setRows]=useState(null),[visit,setVisit]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[favorites,setFavorites]=useState(()=>new Set(savedFavorites.map(f=>f.city_id)));
 useEffect(()=>{let live=true;city3bRequest('discover',{},uid).then(v=>{if(live)setRows(v.cities||[])}).catch(e=>{if(live){setRows([]);setNotice(e.message)}});return()=>{live=false};},[uid]);
 const open=async c=>{setNotice('');setBusy(true);try{setVisit(await city3bRequest('visit',{city:c.city_id},uid))}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const favorite=async c=>{setNotice('');setBusy(true);const add=!favorites.has(c.city_id);try{await city3bRequest('favorite',{city:c.city_id,add},uid);setFavorites(previous=>{const next=new Set(previous);if(add)next.add(c.city_id);else next.delete(c.city_id);return next});setNotice(add?'Ville ajoutée aux favoris.':'Ville retirée des favoris.')}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 return <section className="city3b-panel"><h3>Découvrir les villes 3B</h3>{notice&&<div className="city3b-error" role="status">{notice}</div>}{visit&&<><div className="city3b-visit"><strong>{visit.city?.name}</strong><span>{visit.city?.origin_country} · niveau {visit.city?.city_level}</span><small>{visit.placements?.length||0} bâtiments · {visit.displays?.length||0} objets exposés</small><button className="city3b-btn" onClick={()=>setVisit(null)}>Retour à la liste</button></div><City3BPrivatePreview data={visit} publicVisit/></>}{!visit&&(!rows?<div className="city3b-empty">Recherche…</div>:rows.length===0?<div className="city3b-empty">{notice?'La liste est momentanément indisponible.':'Les premières villes publiques apparaîtront ici.'}</div>:<div className="city3b-cards">{rows.map(c=><article key={c.city_id} className="city3b-card"><strong>{c.name}</strong><span>{c.origin_country} · niv. {c.level}</span><small>{c.visitors} visites</small><button className="city3b-btn blue" disabled={busy} onClick={()=>open(c)}>Visiter</button><button className="city3b-btn" aria-pressed={favorites.has(c.city_id)} disabled={busy} onClick={()=>favorite(c)}>{favorites.has(c.city_id)?'★ Favori':'☆ Favori'}</button></article>)}</div>)}</section>;
}
function CitySettings({city,busy,call,setTab}){const[n,setN]=useState(city.name),[visibility,setVisibility]=useState(city.visibility),[day,setDay]=useState(city.day_mode),[weather,setWeather]=useState(city.weather),[ambience,setAmbience]=useState(city.ambience);return <section className="city3b-panel"><h3><Settings2 size={18}/> Paramètres de la ville</h3><div className="city3b-form"><input aria-label="Nom de la ville" value={n} maxLength={40} onChange={e=>setN(e.target.value)}/><select aria-label="Visibilité de la ville" value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="private">Privée</option><option value="friends">Amis</option><option value="public">Publique</option></select><button className="city3b-btn primary" disabled={busy} onClick={()=>call('settings',{name:n,visibility})}>Enregistrer l’identité</button><select aria-label="Jour et nuit" value={day} onChange={e=>setDay(e.target.value)}><option value="auto">Jour/nuit automatique</option><option value="day">Jour</option><option value="night">Nuit</option></select><select aria-label="Météo" value={weather} onChange={e=>setWeather(e.target.value)}><option value="clear">Clair</option><option value="rain">Pluie</option><option value="fog">Brouillard</option><option value="snow">Neige</option><option value="storm">Tempête</option></select><select aria-label="Ambiance" value={ambience} onChange={e=>setAmbience(e.target.value)}><option value="matrix">Matrix</option><option value="gold">Or</option><option value="urban">Urbaine</option><option value="cinematic">Cinéma</option><option value="calm">Calme</option></select><button className="city3b-btn blue" disabled={busy} onClick={()=>call('environment',{day,weather,ambience})}>Appliquer l’ambiance</button><button className="city3b-btn" onClick={()=>setTab('city')}>← Retour à ma ville</button></div></section>}
