import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Building2,Coins,Globe2,Map,Package,X} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import {CITY_COUNTRIES,CITY_VALUES,city3bRequest} from '../city/city3b-client.js';
import '../styles/city-3b.css';
const TABS=[['city','Ville',Building2],['build','Construire',Building2],['districts','Quartiers',Map],['collection','Collection',Package],['visit','Visiter',Globe2]];
export default function PassportNexus({open,onClose}){
 const account=useLoyalty(),uid=account.user?.id,dialog=useRef(null);const[data,setData]=useState(null),[tab,setTab]=useState('city'),[busy,setBusy]=useState(false),[error,setError]=useState('');const[name,setName]=useState('Ma ville 3B'),[country,setCountry]=useState('France');
 const call=async(action,body={})=>{setBusy(true);setError('');try{const v=await city3bRequest(action,body,uid);setData(v);return v}catch(e){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{if(open&&uid)call('snapshot')},[open,uid]);if(!open)return null;const city=data?.city,profile=account.profile||{};
 return createPortal(<dialog ref={dialog} open className="city3b-dialog" aria-label="Crée ta ville 3B"><div className="city3b-shell"><header className="city3b-top"><div className="city3b-brand"><b>3B</b><span>CRÉE TA VILLE</span></div><div className="city3b-stats"><span className="city3b-chip">NIV. {city?.city_level||1}</span><span className="city3b-chip"><Coins size={13}/> {profile.points||0} Coins</span><span className="city3b-chip">Terrain {city?.land_tier||1}/10</span></div><button className="city3b-close" onClick={onClose} aria-label="Fermer"><X size={20}/></button></header><main className="city3b-main">{error&&<div className="city3b-error">{error}</div>}{!data&&!error?<div className="city3b-loading">SYNCHRONISATION VILLE 3B…</div>:!city?<section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">DE ZÉRO À TA PROPRE CITÉ</p><h2>Crée ta <em>ville 3B.</em></h2><p>Une ville permanente. Huit quartiers. Aucun reset, aucune saison.</p><div className="city3b-form"><input value={name} maxLength={40} onChange={e=>setName(e.target.value)}/><select value={country} onChange={e=>setCountry(e.target.value)}>{CITY_COUNTRIES.map(c=><option key={c}>{c}</option>)}</select><button className="city3b-btn primary" disabled={busy||name.trim().length<2} onClick={()=>call('create',{name:name.trim(),country})}>{busy?'Création…':'Fonder ma ville'}</button></div></div></section>:<CityContent tab={tab} data={data} profile={profile} busy={busy} call={call}/>}</main>{city&&<nav className="city3b-nav">{TABS.map(([id,label,Icon])=><button key={id} aria-current={tab===id} onClick={()=>setTab(id)}><Icon size={18}/><br/>{label}</button>)}</nav>}</div></dialog>,document.body)
}
function CityContent({tab,data,profile,busy,call}){const c=data.city;if(tab==='city')return <><section className="city3b-hero"><div className="city3b-grid"/><div className="city3b-horizon"/><div className="city3b-hero-copy"><p className="city3b-kicker">{c.origin_country?.toUpperCase()} · {CITY_VALUES[c.origin_country]}</p><h2>{c.name}</h2><p>Niveau {c.city_level} · {c.city_xp} XP · {c.visitors} visites</p></div></section><section className="city3b-panel"><h3>Ma cité</h3><div className="city3b-cards"><article className="city3b-card"><strong>{data.placements?.length||0}</strong><small>constructions</small></article><article className="city3b-card"><strong>{data.districts?.filter(x=>x.unlocked).length||1}/8</strong><small>quartiers</small></article><article className="city3b-card"><strong>{data.displays?.length||0}</strong><small>objets exposés</small></article></div></section></>;if(tab==='build')return <section className="city3b-panel"><h3>Construire</h3><div className="city3b-cards">{(data.buildings||[]).map(b=><button key={b.code} className="city3b-card" disabled={busy} onClick={()=>call('place',{building:b.code,x:Math.floor(Math.random()*20)-10,z:Math.floor(Math.random()*20)-10,rotation:0,request:crypto.randomUUID()})}><strong>{b.name}</strong><span>{b.cost_coins} Coins</span><small>Niveau {b.unlock_level}{b.country?` · ${b.country}`:''}</small></button>)}</div></section>;if(tab==='districts')return <section className="city3b-panel"><h3>Les huit quartiers</h3><div className="city3b-cards">{(data.districts||[]).map(d=><article key={d.country} className="city3b-card" data-locked={!d.unlocked}><strong>{d.country}</strong><span>{CITY_VALUES[d.country]}</span><small>{d.unlocked?`Niveau ${d.level}`:'Verrouillé'}</small>{!d.unlocked&&<button className="city3b-btn" onClick={()=>call('unlock_district',{country:d.country})}>Débloquer</button>}</article>)}</div></section>;if(tab==='collection')return <section className="city3b-panel"><h3>Collection</h3><p>Garage, dressing et vitrines utilisent tes objets permanents 3B.</p><div className="city3b-empty">{data.displays?.length||0} objet(s) actuellement exposé(s).</div></section>;return <Discovery call={call}/>}
function Discovery({call}){const[rows,setRows]=useState(null);useEffect(()=>{city3bRequest('discover').then(v=>setRows(v.cities||[])).catch(()=>setRows([]))},[]);return <section className="city3b-panel"><h3>Découvrir les villes 3B</h3>{!rows?<div className="city3b-empty">Recherche…</div>:<div className="city3b-cards">{rows.map(c=><article key={c.city_id} className="city3b-card"><strong>{c.name}</strong><span>{c.origin_country} · niv. {c.level}</span><small>{c.visitors} visites</small><button className="city3b-btn" onClick={()=>call('favorite',{city:c.city_id,add:true})}>☆ Favori</button></article>)}</div>}</section>}
