import CompanionPowerPanel from './CompanionPowerPanel.jsx';
import CompanionConcepts from './CompanionConcepts.jsx';
import ArsenalEvolution from './ArsenalEvolution.jsx';
import WeaponEmblem from './WeaponEmblem.jsx';
import React,{useState} from 'react';
import {WEAPONS,COMPANIONS,getWeapon,weaponAction} from '../arsenal.js';
import {ACTIONS} from './combat.js';
export default function Armory({draft,change,xp,companion}){
 const [filter,setFilter]=useState('all');const w=getWeapon(draft.weapon),light=weaponAction(ACTIONS.light,draft,xp),heavy=weaponAction(ACTIONS.heavy,draft,xp);
 if(companion)return <section className="armory"><p>Ton compagnon explore à tes côtés et peut chercher une piste ou tenir un sceau. Ces trois choix sont des variantes du loup animé existant.</p><div className="armory-grid">{COMPANIONS.map(c=><button type="button" key={c.id} aria-pressed={draft.companion===c.id} onClick={()=>change({companion:c.id})} style={{'--weapon-color':c.color}}><span aria-hidden="true">◈</span><strong>{c.name}</strong><small>{c.description}</small></button>)}</div><p>Appelle-le avec la commande du compagnon. Aucun compagnon ne combat automatiquement à ta place.</p><CompanionPowerPanel draft={draft}/><CompanionConcepts/></section>;
 return <section className="armory"><ArsenalEvolution draft={draft} change={change} xp={xp}/><p>Choisis ton style de combat. Toutes les origines peuvent manier toutes les armes.</p><label>Collection<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toutes les armes · 16</option><option value="signature">Les huit signatures</option><option value="3b">Armes du voyageur</option></select></label><div className="armory-grid">{WEAPONS.filter(a=>filter==='all'||(filter==='signature'?a.country!=='3b':a.country==='3b')).map(a=><button type="button" key={a.id} aria-pressed={w.id===a.id} onClick={()=>change({weapon:a.id,weaponForm:0})} style={{'--weapon-color':a.color}}><WeaponEmblem weapon={a}/><small>{a.country.toUpperCase()} · {a.kind}</small><strong>{a.name}</strong></button>)}</div><article className="armory-detail" style={{'--weapon-color':w.color}}><h4>{w.name}</h4><p>{w.description}</p><dl><dt>Attaque rapide</dt><dd>{light.damage.toFixed(1)} dégâts · {light.duration.toFixed(2)} s · {light.cost} endurance</dd><dt>Attaque puissante</dt><dd>{heavy.damage.toFixed(1)} dégâts · {heavy.cost} endurance avant amélioration artisan</dd><dt>Portée rapide</dt><dd>{light.range.toFixed(1)} m</dd><dt>Protection passive</dt><dd>{Math.round(w.defense*100)} % des dégâts reçus</dd></dl></article></section>;
}
