import React,{useEffect,useState} from 'react';
import {ArenaStage} from '../../arena/ArenaStage.jsx';
import {normalizeAvatar,blankAvatar,SKINS,OUTFITS} from '../avatar-rules.js';
import {LOOKS} from '../wardrobe.js';
import {COUNTRIES} from '../catalog.js';
import '../../arena/arena.css';
import './creator.css';
const STEPS=['Identité','Physique','Visage','Tenue','Accessoires'];
export default function CharacterCreator({avatar,looks=[],onSave,onCancel}){
 const [draft,setDraft]=useState(()=>normalizeAvatar(avatar)),[preview,setPreview]=useState(draft),[step,setStep]=useState(0),[saved,setSaved]=useState(looks),[history,setHistory]=useState([]),[pose,setPose]=useState('idle'),[angle,setAngle]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const t=setTimeout(()=>setPreview(draft),180);return()=>clearTimeout(t);},[draft]);
 function change(values){setHistory(h=>[...h.slice(-29),draft]);setDraft(d=>({...d,...values}));}
 function undo(){if(!history.length)return;setDraft(history.at(-1));setHistory(h=>h.slice(0,-1));}
 const select=(key,label,options)=><label>{label}<select value={draft[key]} onChange={e=>change({[key]:typeof options[0][0]==='number'?Number(e.target.value):e.target.value})}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;
 const range=(key,label,min,max,step=.01)=><label>{label}<span className="creator-range"><input type="range" min={min} max={max} step={step} value={draft[key]} onChange={e=>change({[key]:Number(e.target.value)})}/><output>{min<0?(draft[key]===0?'Neutre':(draft[key]>0?'+':'')+Math.round(draft[key]*100)):Math.round(draft[key]*100)+' %'}</output></span></label>;
 const color=(key,label,fallback)=><label className="creator-color">{label}<input type="color" value={draft[key]||fallback} onChange={e=>change({[key]:e.target.value})}/></label>;
 function random(){const look=LOOKS[Math.floor(Math.random()*LOOKS.length)],{id,name,...style}=look;change(style);}
 async function submit(e){e.preventDefault();if(!draft.name.trim()){setStep(0);setError('Donne un nom à ton personnage.');return;}setBusy(true);setError('');try{await onSave(normalizeAvatar({...draft,created:true}),saved);}catch(e){setError('Impossible d’appliquer le personnage. Tes choix restent ici : '+e.message);}finally{setBusy(false);}}
 return <form className="creator" onSubmit={submit}>
  <div className="creator-stage"><ArenaStage avatar={preview} focus={step===2?'face':'body'} pose={pose} angle={angle}/><div className="creator-caption"><strong>{draft.name||'Ton personnage'}</strong><span>Glisse sur le personnage pour le tourner</span></div><div className="creator-tools">{[[0,'Face'],[Math.PI/2,'Profil'],[Math.PI,'Dos']].map(([value,label])=><button type="button" key={label} onClick={()=>setAngle(value)}>{label}</button>)}<button type="button" aria-pressed={pose==='walk'} onClick={()=>setPose(p=>p==='walk'?'idle':'walk')}>{pose==='walk'?'Arrêter la marche':'Voir en marche'}</button><button type="button" onClick={random}>Proposer une tenue</button><button type="button" onClick={undo} disabled={!history.length}>Annuler le dernier choix</button></div></div>
  <div className="creator-edit"><nav aria-label="Étapes de personnalisation">{STEPS.map((label,i)=><button type="button" key={label} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><span>{i+1}</span>{label}</button>)}</nav>
  <div className="creator-fields"><h3>{STEPS[step]}</h3>
   {step===0&&<><p>Ton histoire commence avec toi. Tu peux changer ton apparence plus tard.</p><label>Nom du personnage<input maxLength={20} value={draft.name} onChange={e=>change({name:e.target.value})}/></label><div className="creator-pair">{['homme','femme'].map(body=><button type="button" key={body} aria-pressed={draft.body===body} onClick={()=>change({body})}>{body==='homme'?'Homme':'Femme'}</button>)}</div><label>Pays et origines personnelles<input maxLength={50} placeholder="Tous les pays, toutes les origines" value={draft.nationality} onChange={e=>change({nationality:e.target.value})}/></label>{select('origin','Pays de cœur',[['3b','Union des huit portes'],...COUNTRIES.map(c=>[c.id,c.name])])}<p className="creator-note">Tes origines sont libres et ne limitent ni ton apparence ni tes rencontres.</p></>}
   {step===1&&<>{select('shape','Silhouette',[['equilibre','Équilibrée'],['elance','Élancée'],['solide','Solide']])}{range('height','Taille',.9,1.1)}{range('build','Corpulence',.88,1.15)}<fieldset><legend>Teint de départ</legend><div className="creator-swatches">{SKINS.map((c,i)=><button type="button" key={c} style={{background:c}} aria-label={'Teint '+(i+1)} aria-pressed={draft.skin===i&&!draft.skinColor} onClick={()=>change({skin:i,skinColor:null})}/>)}</div></fieldset>{color('skinColor','Nuance de peau personnalisée',SKINS[draft.skin])}<p className="creator-note">Les proportions restent dans une plage compatible avec les animations. La taille ne change pas la portée des attaques.</p></>}
   {step===2&&<>{select('hair','Coiffure', ['Rasé','Coupe courte','Chignons','Raie souple','Cheveux longs','Court texturé','Barbe et crâne rasé'].map((n,i)=>[i,n]))}{color('hairColor','Couleur des cheveux','#352a24')}{draft.headwear==='hood'&&<p>La capuche masque les cheveux. Retire-la dans Accessoires pour vérifier ta coiffure.</p>}{range('face','Largeur du visage',-1,1,.05)}{range('jaw','Mâchoire',-1,1,.05)}{range('nose','Nez',-1,1,.05)}</>}
   {step===3&&<><fieldset><legend>Partir d’un style</legend><div className="creator-looks">{LOOKS.map(({id,name,...values})=><button type="button" key={id} onClick={()=>change(values)}><i style={{background:values.fabricColor,borderColor:values.accentColor}}/>{name}</button>)}</div></fieldset>{select('style','Coupe',[['voyageur','Voyageur'],['sentinelle','Sentinelle'],['mystique','Résonance']])}{select('fabric','Finition du tissu',[['cotton','Coton mat'],['linen','Lin sec'],['satin','Satin lumineux'],['leather','Cuir souple']])}<div className="creator-pair">{color('fabricColor','Tissu',OUTFITS[draft.color])}{color('accentColor','Détails','#d7bd83')}{color('trouserColor','Pantalon','#77644d')}{color('bootColor','Chaussures','#695239')}</div>{select('pattern','Motif',[['uni','Uni'],['bandes','Rayures'],['damier','Damier'],['insigne','Signature 3B'],['broderie','Broderie']])}{draft.pattern!=='uni'&&range('patternScale','Densité du motif',.5,3,.1)}</>}
   {step===4&&<>{select('headwear','Couvre-chef',[['none','Aucun'],['beret','Béret'],['brim','Chapeau de voyage'],['hood','Capuche']])}{draft.headwear==='hood'&&range('hoodFit','Ampleur de la capuche',.9,1.15)}{select('outer','Accessoire de tenue',[['none','Aucun'],['cape','Cape'],['scarf','Écharpe'],['apron','Tablier']])}{draft.outer==='cape'&&range('capeLength','Longueur de cape',.7,1.25)}{color('outerColor','Couleur cape, écharpe ou tablier',draft.fabricColor||OUTFITS[draft.color])}{color('metalColor','Métal des boucles et bijoux','#c9ad75')}{select('belt','Ceinture',[['none','Aucune'],['simple','Cuir et boucle'],['utility','Ceinture à pochettes']])}<label className="creator-check"><input type="checkbox" checked={draft.pendant} onChange={e=>change({pendant:e.target.checked})}/>Pendentif du voyageur</label>{select('boots','Chaussures',[[0,'Voyage'],[1,'Exploration'],[2,'Garde']])}<label className="creator-check"><input type="checkbox" checked={draft.bag} onChange={e=>change({bag:e.target.checked})}/>Sac de voyage</label><p className="creator-note">Ces choix d’apparence sont cosmétiques. Ton équipement d’aventure et tes progrès sont conservés.</p></>}
   <details><summary>Mes créations · {saved.length}/6</summary><p>Conserve plusieurs apparences et retrouve-les ici.</p><button type="button" disabled={saved.length>=6} onClick={()=>setSaved(v=>[...v,normalizeAvatar(draft)])}>Garder cette création</button>{saved.map((look,i)=><div className="creator-pair" key={i}><button type="button" onClick={()=>change(look)}>{i+1}. {look.name} · {look.body}</button><button type="button" aria-label={'Supprimer la création '+(i+1)} onClick={()=>setSaved(v=>v.filter((_,j)=>j!==i))}>Supprimer</button></div>)}</details>
  </div><footer><div className="creator-pair"><button type="button" disabled={step===0||busy} onClick={()=>setStep(s=>s-1)}>Précédent</button>{step<4&&<button type="button" onClick={()=>setStep(s=>s+1)}>Suivant</button>}</div>{error&&<p role="alert">{error}</p>}<button className="origins-primary" type="submit" disabled={busy}>{busy?'Application du personnage…':'Enregistrer et jouer'}</button><button type="button" disabled={busy} onClick={onCancel}>Retour sans enregistrer</button><small>Personnage et créations sauvegardés sur cet appareil.</small></footer></div>
 </form>;
}
