import {HERITAGE} from '../heritage.js';
// Art direction for playable regional districts; these are stylised places, not city replicas.
export const COUNTRIES={
 algerie:{name:'Algérie',district:'Terrasses des Liens',architecture:'façades claires, cours et galeries',stone:'#e5d9bb',paving:'#c9b793',sky:'#428fc4',haze:'#ead9b8',tree:'Palm',seed:11,layout:'terraces',welcome:'Bienvenue aux Terrasses des Liens. Les galeries protègent la place du soleil ; les jardins commencent derrière les maisons.',craft:'Nous réparons les portes et entretenons les cours. Dans le Monde 3B, un quartier tient grâce aux gens qui y reviennent.'},
 maroc:{name:'Maroc',district:'Cour des Jardins',architecture:'murs de terre ocre, patios et passages',stone:'#bd8261',paving:'#cbb28a',sky:'#5598bd',haze:'#e6c9a4',tree:'Palm',seed:23,layout:'courts',welcome:'Entre dans la Cour des Jardins. Les passages tournent autour des patios : prends le temps de regarder derrière les façades.',craft:'La terre, le bois et les motifs des portes donnent son rythme au quartier. Nous gardons les traces de ceux qui ont vécu ici.'},
 tunisie:{name:'Tunisie',district:'Place des Voiles',architecture:'volumes blancs, portes bleues et terrasses',stone:'#f2e8d2',paving:'#d8c6a3',sky:'#328ccb',haze:'#d5e6df',tree:'Olive',seed:37,layout:'terraces',welcome:'Tu es sur la Place des Voiles. Les façades blanches et les portes bleues bordent le chemin des oliviers.',craft:'Nous entretenons les seuils, les volets et la fontaine. Un lieu doit rester accueillant, même après le passage de l’Oubli.'},
 espagne:{name:'Espagne',district:'Plaza des Rencontres',architecture:'arcades, enduits chauds et toits de tuile',stone:'#d7b587',paving:'#c8a887',sky:'#508fcc',haze:'#ecddc4',tree:'Olive',seed:41,layout:'plaza',welcome:'La Plaza des Rencontres est faite pour s’arrêter et discuter. Les arcades relient les maisons à la promenade des oliviers.',craft:'Les ateliers donnent sur la place. Ici, restaurer un bâtiment commence par écouter ceux qui l’utilisent.'},
 italie:{name:'Italie',district:'Piazza des Ateliers',architecture:'loggias, pierre claire et toitures de terre cuite',stone:'#d9c19a',paving:'#bcb39e',sky:'#659ed1',haze:'#e2dfc9',tree:'Cypress',seed:53,layout:'plaza',welcome:'Bienvenue sur la Piazza des Ateliers. Les loggias encadrent la place ; une allée de cyprès mène aux jardins.',craft:'Nous travaillons la pierre et le bois. Les façades portent les réparations successives : leur histoire reste visible.'},
 turquie:{name:'Turquie',district:'Passage des Artisans',architecture:'galeries, balcons et silhouettes de coupoles',stone:'#d9c6a7',paving:'#b9ad98',sky:'#5d93b8',haze:'#e0d9bf',tree:'Cypress',seed:67,layout:'courts',welcome:'Le Passage des Artisans relie les cours et les galeries. Suis les lanternes pour retrouver la place centrale.',craft:'Les ateliers échangent leurs techniques. Le Cercle Brisé nous rappelle que les liens se construisent aussi dans les gestes quotidiens.'},
 estonie:{name:'Estonie',district:'Quartier des Pins',architecture:'pignons, pierre froide et toitures pentues',stone:'#c7c4b4',paving:'#9faaa5',sky:'#6f9bb4',haze:'#cadcdb',tree:'Pine',seed:79,layout:'lanes',welcome:'Tu es dans le Quartier des Pins. Les toitures découpent le ciel ; derrière les maisons, la forêt reprend sa place.',craft:'Nous protégeons le bois et consolidons les murs. Les habitants gardent la mémoire des chemins, même quand l’Oubli efface les noms.'},
};
export const isCountry=zone=>Object.hasOwn(COUNTRIES,zone);
export function countryNextStop(zone,visit){const id=['resident','atelier','refuge'][Math.max(0,Math.floor(visit))%3];return countryLayout(zone)?.points.find(p=>p.id===id);}
const cache=new Map();
export function countryLayout(zone){
 if(cache.has(zone))return cache.get(zone);const c=COUNTRIES[zone];if(!c)return null;
 const centres={algerie:[-12,0],maroc:[-18,-8],tunisie:[10,0],espagne:[0,-7],italie:[12,-15],turquie:[-12,-20],estonie:[-16,3]},[cx,cz]=centres[zone];
 const centre={x:cx,z:cz},landmark={x:50,z:-78},garden={x:-45,z:-67},encounter={x:-48,z:-35};
 const roads=[[[0,30],[cx/2,18],[cx,cz],[cx-6,cz-17],[-30,-51],[-45,-67]],[[cx,cz],[cx+20,cz-8],[38,-31],[50,-49]],[[cx,cz],[-37,cz+5],[-66,cz-7],[-68,-33],[-48,-35]],[[cx+4,cz+4],[38,12],[65,-2],[65,-27],[50,-49]]];
 if(zone==='espagne'||zone==='italie')roads.push([[cx-19,cz-10],[cx-17,cz+15],[cx+17,cz+15],[cx+20,cz-12],[cx-19,cz-10]]);
 const points=[{id:'country-return',x:0,z:30,name:'Porte du Sanctuaire'},{id:'resident',x:cx+3,z:cz+7,name:'Parler à la guide'},{id:'atelier',x:cx-10,z:cz-2,name:'Atelier · améliorer la tenue'},{id:'refuge',x:cx+12,z:cz+8,name:'Refuge · se reposer'},{id:'walker1',x:cx-5,z:cz+8,name:'Parler à un habitant'},{id:'walker2',x:cx+7,z:cz-12,name:'Parler à une habitante'},{id:'country-garden',...garden,name:'Jardin · récolter ou restaurer'},{id:'country-encounter',...encounter,name:'Épreuve · repousser l’Oubli'},{id:'country-landmark',x:50,z:-49,name:HERITAGE[zone].name}];
 const segments=roads.flatMap(r=>r.slice(1).map((p,i)=>[r[i],p]));
 const dist=(x,z,a,b)=>{const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[1])*dz)/(dx*dx+dz*dz||1)));return Math.hypot(x-a[0]-t*dx,z-a[1]-t*dz);};
 const candidates=[];for(let z=-65;z<25;z+=12)for(let x=-76;x<80;x+=13){const d=Math.min(...segments.map(([a,b])=>dist(x,z,a,b)));if(d<8||d>22||Math.hypot(x-landmark.x,z-landmark.z)<34||Math.hypot(x-encounter.x,z-encounter.z)<16||points.some(p=>Math.hypot(p.x-x,p.z-z)<10)||Math.hypot(x-cx,z-cz)<15)continue;candidates.push({x,z,score:Math.sin(x*.12+z*.15+c.seed)});}
 candidates.sort((a,b)=>a.score-b.score);const buildings=candidates.slice(0,24).map((p,i)=>({id:zone+'-'+i,x:p.x,z:p.z,width:10,depth:7.5,angle:zone==='estonie'?Math.sin(i)*.12:0,level:1+(i+c.seed)%3}));
 const result={buildings,roads,points,centre,landmark,garden,encounter};cache.set(zone,result);return result;
}
export function countryDialogue(zone,id,topic='welcome'){
 const c=COUNTRIES[zone];if(!c)return null;
 const speakers={resident:'Guide du quartier',atelier:'Artisan du quartier',refuge:'Hôte du refuge',walker1:'Habitant',walker2:'Habitante'};
 if(!speakers[id])return null;
 const text=topic==='history'?'Le Cercle Brisé relie nos huit pays. Ici, nous gardons les souvenirs en habitant les lieux et en prenant soin des autres.':topic==='directions'?'La carte indique la porte du Sanctuaire, le refuge et l’atelier. Récolte au jardin, repousse l’Oubli dans la clairière et aide-nous à restaurer ce quartier.':id==='atelier'?c.craft:id==='refuge'?'Pose-toi près de la fontaine. Tu peux retrouver les autres habitants sur la place ou rejoindre la promenade des jardins.':id.startsWith('walker')?'Je passe par la place pour prendre des nouvelles. Parle à la guide si tu cherches ton chemin.':c.welcome;
 return {speaker:speakers[id],text,choices:[...(id==='atelier'?[{id,topic:'upgrade',label:'Renforcer la tenue · 2 matériaux'}]:id==='refuge'?[{id,topic:'rest',label:'Se reposer · gratuit'}]:[]),{id,topic:'garden',label:'Me guider aux jardins'},{id,topic:'directions',label:'Où aller ?'},{id,topic:'history',label:'Le Cercle Brisé'},{id,topic:'welcome',label:'Ce quartier'}]};
}
