import {useRef,useState} from 'react';
import {ArrowUpRight,Download,Printer,ShoppingBag,Check,Lock,Gift} from 'lucide-react';
import {SHOP_TIERS,shopTierFor,nextShopTier} from '../../shared/loyalty.js';
import {useLoyalty} from './LoyaltyContext.jsx';
import BoutiqueCard,{downloadBoutiqueCard} from './BoutiqueCard.jsx';
import XpCollection from './XpCollection.jsx';
import CompactCard from '../components/CompactCard.jsx';
import './loyalty.css';
import './boutique-loyalty.css';
export {RewardStats} from './XpCollection.jsx';
const number=n=>new Intl.NumberFormat('fr-FR').format(n||0);
export default function LoyaltyPage({goTo}){
 const[view,setView]=useState('boutique');
 return <section className="loyalty-page boutique-loyalty-page"><header className="loyalty-intro"><span className="loyalty-eyebrow">3B INTERNATIONAL / TES CARTES</span><button onClick={()=>goTo('guide')}>Le guide <ArrowUpRight size={16}/></button></header>
 <div className="loyalty-view-switch" role="group" aria-label="Choisir une collection"><button aria-pressed={view==='boutique'} onClick={()=>setView('boutique')}><ShoppingBag size={17}/> Fidélité boutique</button><button aria-pressed={view==='xp'} onClick={()=>setView('xp')}>Collection XP</button></div>
 {view==='boutique'?<BoutiqueLoyalty goTo={goTo}/>:<XpCollection goTo={goTo}/>}</section>;
}
function BoutiqueLoyalty({goTo}){
 const account=useLoyalty(),{profile}=account,stage=useRef(null);
 const[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const pointEvents=account.events.filter(e=>e.points!==0);
 const current=shopTierFor(profile?.points),next=nextShopTier(profile?.points),shown=SHOP_TIERS.find(t=>t.id===selected)||current,preview=shown.id!==current.id;
 const progress=next?Math.max(0,Math.min(100,((profile?.points||0)-current.points)/(next.points-current.points)*100)):100;
 function register(){try{sessionStorage.setItem('3b-auth-intent','register');}catch{}goTo('member');}
 async function download(printable){setBusy(true);setNotice('');try{await downloadBoutiqueCard(profile,printable);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 return <div><div className="boutique-card-hero"><div className="boutique-page-heading"><p className="loyalty-kicker">LE STYLE A SES AVANTAGES</p><h1>Ta fidélité.<br/><em>Ton vestiaire 3B.</em></h1><p>Vêtements, maillots, sacs, chaussures et accessoires : tes achats font grandir tes avantages.</p><div className="boutique-category-line">VÊTEMENTS <span>·</span> MAROQUINERIE <span>·</span> ACCESSOIRES</div><div className="boutique-earning"><strong>1 € = 10 points</strong><span>sur les articles payés, après réduction et hors livraison</span></div></div>
 <div className="boutique-card-stage" ref={stage}><BoutiqueCard tier={shown} profile={preview?null:profile}/><p className="boutique-stage-caption" aria-live="polite">{preview?<><Lock size={14}/> Aperçu {shown.name} · {number(shown.points)} points</>:profile?<><Check size={14}/> Ta carte {current.name} · nominative</>:<>Carte Club · offerte dès l’inscription</>}</p>{preview&&<button className="quiet-button" onClick={()=>setSelected(null)}>Revenir à {profile?'ma carte':'la carte Club'}</button>}</div></div>
 {(notice||account.error)&&<p role="status" className="loyalty-notice">{notice||account.error}</p>}
 <div className="boutique-wallet"><div><span>MES POINTS FIDÉLITÉ</span><strong>{number(profile?.points)} <small>points</small></strong></div><div><span>MON AVANTAGE ACTUEL</span><strong>{current.percent?'−'+current.percent+' %':'Club'}</strong></div><div className="boutique-progress"><span>{next?number(Math.max(0,next.points-(profile?.points||0)))+' points avant la carte '+next.name:'Le meilleur avantage est débloqué'}</span><progress value={progress} max="100" aria-label="Progression de la fidélité boutique"/><small>Les points se cumulent ; ils ne sont pas dépensés.</small></div></div>
 <div className="boutique-actions">{!profile&&<button className="loyalty-primary" onClick={register}>Obtenir ma carte gratuite <ArrowUpRight size={17}/></button>}{profile&&<><button className="loyalty-primary" disabled={busy} onClick={()=>download(false)}><Download size={16}/> Télécharger ma carte {current.name}</button><button disabled={busy} onClick={()=>download(true)}><Printer size={16}/> Version à imprimer</button></>}<button onClick={()=>goTo('shop')}><ShoppingBag size={16}/> Voir la boutique</button></div>
 <p className="boutique-opening"><span/> La boutique prépare son ouverture. Les cartes sont disponibles ; les achats et remises seront utilisables à l’ouverture des ventes.</p>
 <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">01 / LES CARTES BOUTIQUE</span><h2>Quatre cartes. De vrais avantages.</h2></div><p>Touche une carte pour voir son dessin. Ton statut évolue automatiquement avec tes points.</p></div>
 <div className="boutique-tier-list">{SHOP_TIERS.map(t=><CompactCard key={t.id} className="boutique-tier-choice" aria-pressed={shown.id===t.id} title={'Carte '+t.name} eyebrow={t.points?number(t.points)+' points':'Offerte à l’inscription'} description={t.percent?'−'+t.percent+' % sur les articles éligibles':'Ta carte nominative pour commencer à cumuler.'} action="Voir" icon={<BoutiqueCard tier={t} small/>} onClick={()=>{setSelected(t.id);stage.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}}/>)}</div>
 <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">02 / SIMPLE À UTILISER</span><h2>Tu portes le 3B. On te remercie.</h2></div></div>
 <ol className="boutique-how"><li><span>01</span><div><h3>Ta carte est gratuite.</h3><p>Crée ton compte et retrouve ta carte Club, ton nom et ton numéro de membre.</p></div></li><li><span>02</span><div><h3>Tes achats rapportent.</h3><p>Connecte-toi avant de payer. 50 € d’articles payés donnent 500 points. Les frais de livraison ne comptent pas.</p></div></li><li><span>03</span><div><h3>Ta remise suit ton compte.</h3><p>Argent : −5 %, Or : −8 %, Noire : −10 %. Le meilleur taux est appliqué au paiement, sans code à saisir.</p></div></li></ol>
 <details className="boutique-rules"><summary>Conditions, bonus et version imprimée</summary><p>Tous les articles éligibles de la boutique 3B participent, qu’il s’agisse de vêtements ou d’accessoires. Le taux dépend de tes points fidélité, pas de ton niveau XP. Les bonus de jeux, d’exploration et du rendez-vous quotidien peuvent aussi compléter tes points : leurs règles restent dans le guide.</p><p>Les réductions ne se cumulent pas avec une autre remise et ne portent pas sur la livraison. Un remboursement retire les gains correspondants et peut modifier ton statut. Les points n’ont pas de valeur monétaire et ne sont pas transférables. Les achats effectués sans compte connecté ou en mode test ne sont pas crédités.</p><p>La version à imprimer contient deux faces au format 85,6 × 53,98 mm. Le statut est toujours vérifié dans ton compte au paiement en ligne. La carte imprimée n’active pas un terminal ou un service en magasin.</p></details>
 <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">03 / MES DERNIERS POINTS</span><h2>Un historique, en toute clarté.</h2></div>{profile&&<button onClick={account.refresh}>Actualiser</button>}</div>
 {!profile?<div className="loyalty-empty"><p>Ton compte conserve ta fidélité sur tous tes appareils.</p></div>:pointEvents.length?<div className="loyalty-history">{pointEvents.slice(0,12).map(event=><div key={event.id}><span><strong>{event.label}</strong><small>{new Date(event.created_at).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'})}</small></span><span className={event.points<0?'negative':''}>{event.points>=0?'+':''}{number(event.points)} points</span></div>)}</div>:<div className="loyalty-empty">Tes prochaines opérations de fidélité apparaîtront ici.</div>}
 <CompactCard className="boutique-guide-link" title="Le guide des points et des avantages" description="Retrouve les règles complètes et les bonus disponibles." icon={<Gift/>} onClick={()=>goTo('guide')}/></div>;
}
