import React,{useState} from 'react';
import {ArrowUpRight,Download,Check,Lock,Gamepad2,ShoppingBag,Sparkles,Gift} from 'lucide-react';
import {TIERS,DISCOUNTS,tierFor,nextTier,themeFor} from '../../shared/loyalty.js';
import {useLoyalty} from './LoyaltyContext.jsx';
import {memberRequest} from './client.js';
import MemberCard,{downloadCard} from './MemberCard.jsx';
import './loyalty.css';
const number=n=>new Intl.NumberFormat('fr-FR').format(n||0);
export function RewardStats({profile}){const t=tierFor(profile?.xp),next=nextTier(profile?.xp||0),progress=next?Math.round(((profile?.xp||0)-t.xp)/(next.xp-t.xp)*100):100;return <div className="loyalty-progress"><div><span>{t.name}</span><strong>{next?number(next.xp-(profile?.xp||0))+' XP avant '+next.name:'Toutes les cartes débloquées'}</strong></div><progress max="100" value={progress} aria-label="Progression vers la prochaine carte"/><small>{number(profile?.xp)} XP au total · Les XP ne se dépensent pas.</small></div>;}
export default function LoyaltyPage({goTo}){
 const account=useLoyalty(),{profile}=account;
 const[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const tier=TIERS.find(t=>t.id===selected)||themeFor(profile?.theme,profile?.xp||0),unlocked=!!profile&&tier.xp<=profile.xp;
 const act=async(action,body={})=>{setBusy(true);setNotice('');try{const result=await memberRequest(action,body,account.user.id);account.accept(result);setNotice(action==='daily'?(result.awarded?'+10 XP et +2 points ajoutés à ton compte.':'Ton bonus du jour est déjà récupéré.'):'Ta carte et ton aura de jeu sont équipées.');}catch(e){setNotice(e.message);}finally{setBusy(false);}};
 return <section className="loyalty-page"><header className="loyalty-intro"><span className="loyalty-eyebrow">3B INTERNATIONAL / LE CERCLE</span><button onClick={()=>goTo('member')}>{profile?'Mon compte':'Rejoindre le Cercle'} <ArrowUpRight size={16}/></button></header>
  <div className="loyalty-hero"><div className="loyalty-hero-copy"><span className="loyalty-kicker">UNE CARTE. TOUT TON UNIVERS.</span><h1>Ton histoire<br/>mérite sa carte<span>.</span></h1><p>Joue, explore et porte le 3B. Tes aventures font évoluer ta carte ; tes points te donnent des avantages sur tes prochains achats.</p><div className="loyalty-numbers"><div><span>EXPÉRIENCE</span><strong>{number(profile?.xp)} <small>XP</small></strong></div><div><span>FIDÉLITÉ</span><strong>{number(profile?.points)} <small>points</small></strong></div></div>{profile?<RewardStats profile={profile}/>:<button className="loyalty-primary" onClick={()=>goTo('member')}>Créer mon compte gratuit <ArrowUpRight size={18}/></button>}</div>
   <div className="loyalty-hero-card"><MemberCard tier={tier} profile={profile}/><div className="loyalty-card-caption"><span>{unlocked?<><Check size={14}/> Carte débloquée</>:<><Lock size={14}/>{tier.xp===0?"Offerte à l’inscription":number(tier.xp)+" XP pour cette carte"}</>}</span><span>Digitale · Personnelle · Gratuite</span></div></div>
  </div>
  {(account.error||notice)&&<p className="loyalty-notice" role="status">{notice||account.error}</p>}
  <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">01 / TA COLLECTION</span><h2>Cinq cartes. Une progression.</h2></div><p>Touche une carte pour découvrir son design et ses avantages.</p></div>
  <div className="loyalty-collection">{TIERS.map((t,i)=><button key={t.id} className={'loyalty-tier '+(tier.id===t.id?'selected':'')} aria-pressed={tier.id===t.id} onClick={()=>{setSelected(t.id);setNotice('');}}><span className={'loyalty-tier-art member-card-'+t.id} style={{'--card-accent':t.color}}><b>3B</b><i>{String(i+1).padStart(2,'0')}</i><strong>{t.name}</strong></span><span>{t.xp===0?'Dès l’inscription':number(t.xp)+' XP'}{profile&&profile.xp>=t.xp?<Check size={16}/>:<Lock size={13}/>}</span></button>)}</div>
  <div className="loyalty-card-detail"><div><span className="loyalty-eyebrow">{tier.name.toUpperCase()}</span><h3>{tier.benefit}</h3><p>Toutes les cartes identifient ton compte 3B. Les designs débloqués sont téléchargeables et leur couleur accompagne Kaïs dans « Kaïs contre les Ombres » et « Le Dernier Refuge ». Choisir un design ne retire aucun XP ni point.</p></div><div className="loyalty-detail-actions"><button className="loyalty-primary" disabled={!unlocked||busy||profile?.theme===tier.id} onClick={()=>act('theme',{theme:tier.id})}>{profile?.theme===tier.id?'Carte équipée':unlocked?'Équiper cette carte':'Carte à débloquer'}</button><button disabled={!unlocked} onClick={()=>downloadCard(profile,tier)}><Download size={16}/> Télécharger ma carte</button></div></div>
  <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">02 / COMMENT GAGNER</span><h2>Chaque aventure compte.</h2></div></div>
  <div className="loyalty-earn-grid"><article><Gamepad2/><h3>Jouer</h3><strong>20 XP + 1 point / minute</strong><p>Sur les cinq jeux intégrés. Seul le temps actif en ligne compte, par tranches de 30 secondes pour les XP et d’une minute pour les points. Maximum : 600 XP et 20 points par jour.</p><button onClick={()=>goTo('games')}>Choisir un jeu <ArrowUpRight size={15}/></button></article><article><ShoppingBag/><h3>Porter le 3B</h3><strong>10 XP + 10 points / 1 €</strong><p>Sur les articles payés, après réduction et hors livraison. Connecte-toi avant le paiement. Un remboursement ajuste les gains ; les paiements de test ne comptent pas.</p><button onClick={()=>goTo('shop')}>Découvrir la boutique <ArrowUpRight size={15}/></button></article><article><Sparkles/><h3>Explorer</h3><strong>20 XP + 2 points / découverte</strong><p>Découvre le passeport, le manga et les huit pays. Chaque section te récompense une fois après quelques secondes de visite.</p><button onClick={()=>goTo('world3b')}>Explorer les huit pays <ArrowUpRight size={15}/></button></article><article><Gift/><h3>Revenir</h3><strong>10 XP + 2 points / jour</strong><p>Un rendez-vous quotidien à récupérer ici. Le bonus se renouvelle à minuit, heure de Paris. Aucune série perdue si tu fais une pause.</p><button disabled={busy} onClick={()=>profile?act('daily'):goTo('member')}>{profile?'Récupérer mon bonus':'Me connecter'}</button></article></div>
  <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">03 / TES AVANTAGES BOUTIQUE</span><h2>Ta fidélité a de la valeur.</h2></div><p>Les points se cumulent. Ils ne se dépensent pas.</p></div>
  <div className="loyalty-perks">{DISCOUNTS.map(d=><article key={d.percent} className={profile?.points>=d.points?'unlocked':''}><span>{profile?.points>=d.points?'AVANTAGE DÉBLOQUÉ':'OBJECTIF FIDÉLITÉ'}</span><strong>−{d.percent}<small>%</small></strong><h3>{number(d.points)} points</h3><p>{profile?.points>=d.points?'Appliqué automatiquement à tes achats éligibles.':number(Math.max(0,d.points-(profile?.points||0)))+' points pour y accéder.'}</p></article>)}</div>
  <p className="loyalty-footnote">Le meilleur taux disponible s’applique aux articles de la boutique 3B, hors frais de livraison, sans cumul avec une autre réduction. Il est calculé au début du paiement. Les avantages boutique seront utilisables dès l’ouverture des ventes. Les XP et points n’ont pas de valeur monétaire et ne sont ni transférables ni remboursables. Les gains commencent avec ton compte connecté ; les anciens scores ne sont pas convertis.</p>
  <div className="loyalty-section-heading"><div><span className="loyalty-eyebrow">04 / TON HISTORIQUE</span><h2>Tout est dans ton compte.</h2></div>{profile&&<button onClick={account.refresh}>Actualiser</button>}</div>
  {!profile?<div className="loyalty-empty"><p>Un compte 3B permet de retrouver tes cartes, points et sauvegardes sur tes appareils. Tu peux toujours jouer librement sans compte.</p><button onClick={()=>goTo('member')}>Ouvrir mon compte</button></div>:account.events.length?<div className="loyalty-history">{account.events.slice(0,12).map(event=><div key={event.id}><span><strong>{event.label}</strong><small>{new Date(event.created_at).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'})}</small></span><span className={event.points<0?'negative':''}>{event.xp>=0?'+':''}{event.xp} XP <b>{event.points>=0?'+':''}{event.points} points</b></span></div>)}</div>:<div className="loyalty-empty">Ta première récompense t’attend. Lance une partie ou récupère ton bonus quotidien.</div>}
 </section>;
}
