import {buildingById,canPlace} from './build-catalog.js';
export const CITY_SAVE_VERSION=1,MAX_PLACEMENTS=5000;
export const blankCity=(cityId='local')=>({version:CITY_SAVE_VERSION,cityId,revision:0,level:1,xp:0,currency:500,placements:[],roads:[],unlocked:['3b-road-straight','3b-road-curve','3b-home-small','3b-atelier','3b-park','3b-market'],theme:'origin',updatedAt:Date.now()});
const finite=(n,min,max)=>Number.isFinite(Number(n))?Math.max(min,Math.min(max,Number(n))):0;
export function normalizeCity(input){const base=blankCity(typeof input?.cityId==='string'?input.cityId:'local');if(!input||input.version!==CITY_SAVE_VERSION)return base;const seen=new Set();const placements=[];for(const raw of Array.isArray(input.placements)?input.placements:[]){if(placements.length>=MAX_PLACEMENTS||typeof raw?.id!=='string'||seen.has(raw.id)||!buildingById[raw.building])continue;seen.add(raw.id);placements.push({id:raw.id.slice(0,80),building:raw.building,x:finite(raw.x,-500,500),z:finite(raw.z,-500,500),rotation:Math.round(finite(raw.rotation,0,359)/15)*15%360,level:Math.max(1,Math.min(10,Math.floor(Number(raw.level)||1)))});}return{...base,revision:Math.max(0,Math.floor(Number(input.revision)||0)),level:Math.max(1,Math.min(50,Math.floor(Number(input.level)||1)),xp:Math.max(0,Math.floor(Number(input.xp)||0)),currency:Math.max(0,Math.floor(Number(input.currency)||0)),placements,roads:Array.isArray(input.roads)?input.roads.slice(0,MAX_PLACEMENTS):[],unlocked:[...new Set(Array.isArray(input.unlocked)?input.unlocked.filter(id=>buildingById[id]):base.unlocked)],theme:typeof input.theme==='string'?input.theme.slice(0,32):'origin',updatedAt:finite(input.updatedAt,0,Number.MAX_SAFE_INTEGER)||Date.now()};}
export function placeBuilding(city,buildingId,x,z,rotation=0,id=crypto.randomUUID?.()||`p-${Date.now()}-${Math.random()}`){const c=normalizeCity(city),building=buildingById[buildingId];if(!building||c.placements.length>=MAX_PLACEMENTS||!c.unlocked.includes(buildingId)||c.currency<building.cost||!canPlace(c,building,x,z,rotation))return c;return{...c,currency:c.currency-building.cost,placements:[...c.placements,{id,building:buildingId,x,z,rotation:Math.round(rotation/15)*15%360,level:1}],updatedAt:Date.now()};}
export function moveBuilding(city,id,x,z,rotation){const c=normalizeCity(city),current=c.placements.find(p=>p.id===id);if(!current)return c;const without={...c,placements:c.placements.filter(p=>p.id!==id)},building=buildingById[current.building];if(!canPlace(without,building,x,z,rotation))return c;return{...c,placements:c.placements.map(p=>p.id===id?{...p,x,z,rotation:Math.round(rotation/15)*15%360}:p),updatedAt:Date.now()};}
export function removeBuilding(city,id){const c=normalizeCity(city),current=c.placements.find(p=>p.id===id);if(!current)return c;const refund=Math.floor((buildingById[current.building]?.cost||0)*.5);return{...c,currency:c.currency+refund,placements:c.placements.filter(p=>p.id!==id),updatedAt:Date.now()};}
export function applyCityOps(city,ops=[]){return ops.slice(0,200).reduce((c,op)=>op?.type==='place'?placeBuilding(c,op.building,op.x,op.z,op.rotation,op.id):op?.type==='move'?moveBuilding(c,op.id,op.x,op.z,op.rotation):op?.type==='remove'?removeBuilding(c,op.id):c,normalizeCity(city));}
