import React from 'react';
import {ArrowUpCircle,Move3D,Trash2} from 'lucide-react';
import {MEGA_BY_ID} from './mega-catalog.js';
import {constructionPrice,constructionRequirement} from '../economy/world-economy-links.js';
function refundFor(def,level){if(!def)return 0;let total=Math.floor(def.cost*.5);for(let i=1;i<level;i++)total+=Math.floor(Math.round(def.cost*Math.pow(1.55,i))*.5);return total;}
export default function NexusPlacedBuildings({placements=[],wallet={},movingId,onMove,onUpgrade,onRemove}){
 if(!placements.length)return <section className="nexus-placed"><div className="nexus-placed-title"><span>VILLE</span><strong>Aucun bâtiment placé</strong></div><p className="nexus-placed-empty">Choisis un bâtiment puis touche une case verte du terrain.</p></section>;
 return <section className="nexus-placed" aria-label="Bâtiments déjà placés"><div className="nexus-placed-title"><span>VILLE</span><strong>{placements.length} construction{placements.length>1?'s':''}</strong></div><div className="nexus-placed-list">{placements.slice(-80).reverse().map(p=>{const def=MEGA_BY_ID[p.building_code],level=Math.max(1,Math.min(5,Number(p.upgrade_level||1))),next=Math.min(5,level+1),price=def&&level<5?constructionPrice(def.id,next):null,required=def&&level<5?constructionRequirement(def.id,next):null,canUpgrade=!!def&&level<5&&(wallet.level||1)>=required&&(wallet.coins||0)>=price,refund=refundFor(def,level);return <article key={p.id} className={movingId===p.id?'is-moving':''}><div><strong>{def?.name||p.building_code}</strong><small>Niveau {level}/5 · {def?.country||'3B'}</small>{level<5&&def&&<em>Amélioration : {price.toLocaleString('fr-FR')} Coins · niv. {required}</em>}<em>Retrait : remboursement serveur estimé {refund.toLocaleString('fr-FR')} Coins</em></div><div className="nexus-placed-actions"><button type="button" onClick={()=>onMove?.(p)} className={movingId===p.id?'is-active':''}><Move3D size={15}/>{movingId===p.id?'Déplacement actif':'Déplacer'}</button><button type="button" disabled={!canUpgrade} onClick={()=>onUpgrade?.(p)}><ArrowUpCircle size={15}/>{level>=5?'MAX':'Améliorer'}</button><button type="button" className="danger" onClick={()=>onRemove?.(p)}><Trash2 size={15}/>Retirer</button></div></article>;})}</div>{placements.length>80&&<p className="nexus-catalog-more">80 constructions récentes affichées sur {placements.length}.</p>}</section>;
}
