import React,{useEffect,useRef} from 'react';
import * as THREE from 'three';
import {sceneBuildingById} from './scene-building-adapter.js';
import {createProceduralBuildingMesh} from './procedural-building-mesh.js';

const CELL=6,GRID=40,HALF=GRID/2;
function rotatedFootprint(def,rotation=0){const [w,d]=def.footprint,rad=THREE.MathUtils.degToRad(((rotation%360)+360)%360),c=Math.abs(Math.cos(rad)),s=Math.abs(Math.sin(rad));return[Math.max(1,Math.ceil(w*c+d*s)),Math.max(1,Math.ceil(w*s+d*c))];}
function collides(city,candidate){const def=sceneBuildingById(candidate.buildingId,candidate.upgradeLevel||1);if(!def)return true;const[aw,ad]=rotatedFootprint(def,candidate.rotation||0);if(Math.abs(candidate.x)+aw/2>HALF||Math.abs(candidate.z)+ad/2>HALF)return true;return city.some(item=>{if(item.id&&candidate.id&&item.id===candidate.id)return false;const other=sceneBuildingById(item.buildingId,item.upgradeLevel||1);if(!other)return false;const[bw,bd]=rotatedFootprint(other,item.rotation||0);return Math.abs(item.x-candidate.x)<(aw+bw)/2&&Math.abs(item.z-candidate.z)<(ad+bd)/2;});}
function clampCell(v){return Math.max(-HALF+1,Math.min(HALF-1,Math.round(v)));}
export default function NexusCitySceneV2({city=[],started=false,selectedBuilding,onPlace,rotation=0}){
 const canvasRef=useRef(null),placeRef=useRef(onPlace),selectedRef=useRef(selectedBuilding),cityRef=useRef(city),rotationRef=useRef(rotation);placeRef.current=onPlace;selectedRef.current=selectedBuilding;cityRef.current=city;rotationRef.current=rotation;
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setPixelRatio(Math.min(1.5,window.devicePixelRatio||1));const scene=new THREE.Scene();scene.background=new THREE.Color('#02050a');scene.fog=new THREE.Fog('#07101c',150,430);const camera=new THREE.PerspectiveCamera(48,1,.1,650);let yaw=.72,pitch=.72,distance=135,target=new THREE.Vector3(0,0,0);const updateCamera=()=>{camera.position.set(target.x+Math.cos(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,target.z+Math.sin(yaw)*Math.cos(pitch)*distance);camera.lookAt(target.x,5,target.z);};updateCamera();
 const hemi=new THREE.HemisphereLight('#8bdcff','#160f0a',1.1),sun=new THREE.DirectionalLight('#ffe4ad',3.1),rim=new THREE.PointLight('#2ac9ff',35,180,2);sun.position.set(70,120,45);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-100,right:100,top:100,bottom:-100,near:1,far:300});sun.shadow.camera.updateProjectionMatrix();rim.position.set(-65,30,-55);scene.add(hemi,sun,rim);
 const groundMat=new THREE.MeshStandardMaterial({color:'#08121b',roughness:.94,metalness:.05}),roadMat=new THREE.MeshStandardMaterial({color:'#111923',roughness:.8,metalness:.16}),gold=new THREE.MeshBasicMaterial({color:'#d7b56d'}),blue=new THREE.MeshBasicMaterial({color:'#2ac9ff'});const ground=new THREE.Mesh(new THREE.PlaneGeometry(GRID*CELL,GRID*CELL),groundMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(GRID*CELL,GRID,'#2ac9ff','#162d3d');grid.position.y=.03;grid.material.transparent=true;grid.material.opacity=started?.22:.08;scene.add(grid);
 for(let i=-HALF;i<=HALF;i+=5){const rx=new THREE.Mesh(new THREE.PlaneGeometry(1.8,GRID*CELL),roadMat);rx.rotation.x=-Math.PI/2;rx.position.set(i*CELL,.015,0);const rz=rx.clone();rz.rotation.z=Math.PI/2;rz.position.set(0,.017,i*CELL);scene.add(rx,rz);}
 const nexus=new THREE.Group();for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(7+i*.9,.12,10,72),i===1?blue:gold);ring.rotation.set(Math.PI/2+i*.25,i*.5,.15*i);ring.position.y=12;nexus.add(ring);}const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.8,2),new THREE.MeshStandardMaterial({color:'#0d2036',emissive:'#2ac9ff',emissiveIntensity:1.8,metalness:.7,roughness:.2}));core.position.y=12;nexus.add(core);nexus.position.set(0,0,-HALF*CELL+18);scene.add(nexus);
 const buildings=new THREE.Group();scene.add(buildings);const disposeBuildings=()=>{while(buildings.children.length){const child=buildings.children.pop();child.traverse?.(o=>{o.geometry?.dispose?.();const mats=Array.isArray(o.material)?o.material:[o.material];mats.filter(Boolean).forEach(m=>m.dispose?.());});}};const renderCity=()=>{disposeBuildings();for(const entry of cityRef.current){const def=sceneBuildingById(entry.buildingId,entry.upgradeLevel||1);if(!def)continue;const built=createProceduralBuildingMesh(def);if(!built)continue;built.group.position.set(entry.x*CELL,0,entry.z*CELL);built.group.rotation.y=THREE.MathUtils.degToRad(entry.rotation||0);buildings.add(built.group);}};renderCity();
 const ghostMatOk=new THREE.MeshBasicMaterial({color:'#55e38a',transparent:true,opacity:.24,depthWrite:false}),ghostMatBad=new THREE.MeshBasicMaterial({color:'#ff6b6b',transparent:true,opacity:.24,depthWrite:false}),ghost=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),ghostMatOk);ghost.visible=false;scene.add(ghost);let ghostCell={x:0,z:0,valid:false};const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();const locate=e=>{const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height*2-1));ray.setFromCamera(pointer,camera);if(!ray.ray.intersectPlane(plane,hit))return null;return{x:clampCell(hit.x/CELL),z:clampCell(hit.z/CELL)};};const updateGhost=e=>{if(!started||!selectedRef.current){ghost.visible=false;return;}const p=locate(e);if(!p)return;const def=sceneBuildingById(selectedRef.current,1);if(!def)return;const candidate={buildingId:selectedRef.current,x:p.x,z:p.z,rotation:rotationRef.current};const valid=!collides(cityRef.current,candidate);ghostCell={...p,valid};ghost.visible=true;ghost.material=valid?ghostMatOk:ghostMatBad;ghost.scale.set(def.footprint[0]*CELL*.86,Math.max(2,def.height*2),def.footprint[1]*CELL*.86);ghost.position.set(p.x*CELL,ghost.scale.y/2,p.z*CELL);ghost.rotation.y=THREE.MathUtils.degToRad(rotationRef.current||0);};
 let held=null,moved=false;const down=e=>{held={id:e.pointerId,x:e.clientX,y:e.clientY};moved=false;canvas.setPointerCapture?.(e.pointerId);};const move=e=>{if(held?.id===e.pointerId){const dx=e.clientX-held.x,dy=e.clientY-held.y;if(Math.hypot(dx,dy)>5)moved=true;if(moved){yaw-=dx*.006;pitch=Math.max(.25,Math.min(1.18,pitch+dy*.004));held.x=e.clientX;held.y=e.clientY;updateCamera();ghost.visible=false;return;}}updateGhost(e);};const up=e=>{if(held?.id!==e.pointerId)return;const wasMoved=moved;held=null;moved=false;if(!wasMoved&&started){updateGhost(e);if(ghostCell.valid)placeRef.current?.({buildingId:selectedRef.current,x:ghostCell.x,z:ghostCell.z,rotation:rotationRef.current||0});}};const wheel=e=>{e.preventDefault();distance=Math.max(45,Math.min(220,distance+e.deltaY*.08));updateCamera();};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});
 let raf,last=performance.now();const observer=new ResizeObserver(()=>{const w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();});observer.observe(canvas);const tick=now=>{const dt=Math.min(.05,(now-last)/1000);last=now;nexus.rotation.y+=dt*.18;core.rotation.x+=dt*.35;core.rotation.y+=dt*.5;renderer.render(scene,camera);raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);
 return()=>{cancelAnimationFrame(raf);observer.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);canvas.removeEventListener('wheel',wheel);disposeBuildings();scene.traverse(o=>{o.geometry?.dispose?.();const mats=Array.isArray(o.material)?o.material:[o.material];mats.filter(Boolean).forEach(m=>m.dispose?.());});renderer.dispose();};},[started]);
 return <canvas ref={canvasRef} className="nexus-city-canvas" aria-label="Constructeur 3D Nexus · glisse pour tourner, molette ou pincement système pour zoomer, touche le terrain pour placer"/>;
}
