import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Play,RotateCcw,RotateCw,Save,Sparkles,UserRound} from 'lucide-react';
import {useLoyalty} from '../loyalty/LoyaltyContext.jsx';
import NexusCitySceneV2 from './NexusCitySceneV2.jsx';
import NexusEconomyHUD from './NexusEconomyHUD.jsx';
import NexusCatalogPanel from './NexusCatalogPanel.jsx';
import {MEGA_CATALOG,MEGA_BY_ID} from './mega-catalog.js';
import {ensureNexusCity,loadNexusState,buyNexusBuilding} from './nexus-state-client.js';
import {levelFromXp} from '../economy/threeb-economy.js';
import './nexus-city.css';
import './nexus-city-v2.css';
const SCALE=12,LOCAL_KEY='3b_nexus_v2_intro';
function scenePlacements(rows=[]){return rows.map(p=>({id:p.id,buildingId:p.building_code,x:Math.round(Number(p.x||0)/SCALE),z:Math.round(Number(p.z||0)/SCALE),rotation:Number(p.rotation||0),upgradeLevel:Number(p.upgrade_level||1)}));}
export default function NexusCityPageV2({goTo}){const account=useLoyalty();const[started,setStarted]=useState(()=>{try{return localStorage.getItem(LOCAL_KEY)==='1';}catch{return false;}}),[state,setState]=useState(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[rotation,setRotation]=useState(0),[selected,setSelected]=useState('mega-international-001');const logged=!!account.user;const wallet=useMemo(()=>{const w=state?.wallet||{xp:0,coins:0};return{...w,level:levelFromXp(w.xp||0)};},[state]);const city=useMemo(()=>scenePlacements(state?.placements),[state]);const selectedDef=MEGA_BY_ID[selected]||MEGA_CATALOG[0];const sceneRevision=state?.city?.revision||0;
 const refresh=useCallback(async()=>{if(!logged)return;setLoading(true);try{await ensureNexusCity(account.profile?.country||account.profile?.origin_country||'International');const next=await loadNexusState();if(!next?.ok)throw Error('Ville Nexus indisponible');setState(next);}catch(e){setNotice(e.message||'Synchronisation Nexus indisponible.');}finally{setLoading(false);}},[logged,account.profile?.country,account.profile?.origin_country]);
 useEffect(()=>{refresh();},[refresh]);
 function begin(){setStarted(true);try{localStorage.setItem(LOCAL_KEY,'1');}catch{}}
 function rotate(delta){setRotation(r=>(r+delta+360)%360);}
 async function place(entry){if(!logged){setNotice('Connecte-toi à ton compte 3B pour construire et sauvegarder ta ville.');return;}const def=MEGA_BY_ID[entry.buildingId];if(!def){setNotice('Bâtiment inconnu.');return;}if(def.level>wallet.level){setNotice(`Niveau ${def.level} requis.`);return;}if(def.cost>wallet.coins){setNotice(`Il te manque ${(def.cost-wallet.coins).toLocaleString('fr-FR')} 3B Coins.`);return;}setLoading(true);setNotice('Validation du placement…');try{const result=await buyNexusBuilding({buildingCode:def.id,x:entry.x*SCALE,z:entry.z*SCALE,rotation:entry.rotation});if(!result?.ok)throw Error('Placement refusé par le serveur.');await refresh();setNotice(`${def.name} construit · sauvegarde serveur confirmée.`);}catch(e){const code=e?.message||'';setNotice(code.includes('placement_blocked')?'Cet emplacement est déjà occupé.':code.includes('insufficient_coins')?'Solde 3B Coins insuffisant.':code.includes('level_required')?'Niveau insuffisant pour ce bâtiment.':'Construction refusée · la ville n’a pas été débitée.');}finally{setLoading(false);}}
 return <section className={`nexus-city-page nexus-city-v2 ${started?'is-building':'is-intro'}`}>
  <NexusCitySceneV2 key={`nexus-scene-${sceneRevision}-${city.length}`} city={city} started={started} selectedBuilding={selected} rotation={rotation} onPlace={place}/><div className="nexus-city-vignette" aria-hidden="true"/>
  {!started?<div className="nexus-city-intro nexus-v2-intro"><button className="nexus-back" type="button" onClick={()=>goTo('world3b')}><ArrowLeft size={18}/> Retour au Monde du 3B</button><div className="nexus-city-copy"><p className="nexus-kicker"><Sparkles size={14}/> NEXUS · MODE VILLE 3B</p><h1>Crée ta ville <span>3B</span>.</h1><p>Le Nexus est un mode séparé du voyage principal. Construis une ville futuriste avec les identités de France, Algérie, Maroc, Tunisie, Turquie, Espagne, Italie, Estonie et 3B International.</p><div className="nexus-v2-numbers"><span><strong>960</strong> constructions</span><span><strong>9</strong> identités architecturales</span><span><strong>5</strong> niveaux d’amélioration</span></div><button className="nexus-start" type="button" onClick={begin}><Play size={20} fill="currentColor"/> COMMENCER</button>{!logged&&<button className="nexus-login-link" onClick={()=>goTo('member')}><UserRound size={17}/> Se connecter pour sauvegarder</button>}</div><div className="nexus-intro-card"><span>3B CITY / NEXUS</span><strong>TA VILLE. TON HÉRITAGE.</strong><em>NOIR · OR CHAMPAGNE · BLEU MATRIX</em></div></div>:<>
   <header className="nexus-builder-topbar nexus-v2-top"><button type="button" onClick={()=>goTo('world3b')}><ArrowLeft size={18}/> Monde 3B</button><NexusEconomyHUD wallet={wallet}/><div className="nexus-v2-actions"><button type="button" onClick={()=>rotate(-15)} title="Tourner à gauche"><RotateCcw size={17}/> -15°</button><strong>{rotation}°</strong><button type="button" onClick={()=>rotate(15)} title="Tourner à droite"><RotateCw size={17}/> +15°</button><button type="button" onClick={refresh} disabled={!logged||loading}><Save size={17}/> {loading?'Sync…':'Synchroniser'}</button></div></header>
   <aside className="nexus-v2-panel"><div className="nexus-v2-selected"><span>SÉLECTION</span><strong>{selectedDef.name}</strong><small>Niveau {selectedDef.level} · {selectedDef.cost.toLocaleString('fr-FR')} 3B Coins · rotation {rotation}°</small></div><NexusCatalogPanel wallet={wallet} selected={selected} onSelect={item=>{setSelected(item.id);setNotice(`${item.name} sélectionné.`);}}/>{notice&&<p className="nexus-builder-notice" role="status">{notice}</p>}</aside>
   <div className="nexus-build-hint">Glisse pour tourner la caméra · choisis un bâtiment · touche une case verte pour construire.</div>
  </>}
 </section>;}
