create table if not exists public.secret3b_campaigns (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  intro text not null default '',
  status text not null default 'draft' check (status in ('draft','active','closed')),
  prize_count integer not null default 5 check (prize_count between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.secret3b_slots (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.secret3b_campaigns(id) on delete cascade,
  sequence_no integer not null check (sequence_no > 0),
  publish_at timestamptz not null,
  label text not null default 'Transmission',
  created_at timestamptz not null default now(),
  unique (campaign_id, sequence_no)
);

create table if not exists public.secret3b_clues (
  slot_id bigint primary key references public.secret3b_slots(id) on delete cascade,
  kicker text not null default 'SIGNAL 3B',
  title text not null,
  body text not null,
  number_tokens text[] not null default '{}',
  footer text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists secret3b_slots_campaign_publish_idx
  on public.secret3b_slots (campaign_id, publish_at, sequence_no);

alter table public.secret3b_campaigns enable row level security;
alter table public.secret3b_slots enable row level security;
alter table public.secret3b_clues enable row level security;

revoke all on table public.secret3b_campaigns from anon, authenticated;
revoke all on table public.secret3b_slots from anon, authenticated;
revoke all on table public.secret3b_clues from anon, authenticated;

grant select on table public.secret3b_campaigns to anon, authenticated;
grant select on table public.secret3b_slots to anon, authenticated;
grant select on table public.secret3b_clues to anon, authenticated;

grant select, insert, update, delete on table public.secret3b_campaigns to service_role;
grant select, insert, update, delete on table public.secret3b_slots to service_role;
grant select, insert, update, delete on table public.secret3b_clues to service_role;

create policy "secret3b campaigns public read"
  on public.secret3b_campaigns
  for select
  to anon, authenticated
  using (status in ('active','closed'));

create policy "secret3b schedule public read"
  on public.secret3b_slots
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.secret3b_campaigns c
      where c.id = campaign_id
        and c.status in ('active','closed')
    )
  );

create policy "secret3b released clues public read"
  on public.secret3b_clues
  for select
  to anon, authenticated
  using (
    enabled
    and exists (
      select 1
      from public.secret3b_slots s
      join public.secret3b_campaigns c on c.id = s.campaign_id
      where s.id = slot_id
        and s.publish_at <= now()
        and c.status in ('active','closed')
    )
  );

insert into public.secret3b_campaigns (slug, title, intro, status, prize_count)
values (
  'telephone-secret-3b',
  'Le Téléphone Secret 3B',
  'Des transmissions chiffrées apparaîtront ici aux dates prévues. Assemble les indices. Le secret ne sera publié nulle part ailleurs.',
  'active',
  5
)
on conflict (slug) do nothing;
