create table if not exists public.secret3b_phone_contests (
  campaign_id bigint primary key references public.secret3b_campaigns(id) on delete cascade,
  enabled boolean not null default false,
  question_text text not null default '',
  option_1_text text not null default '',
  option_2_text text not null default '',
  correct_digit text check (correct_digit in ('1','2')),
  max_winners integer not null default 5 check (max_winners between 1 and 100),
  opens_at timestamptz,
  closes_at timestamptz,
  intro_text text not null default 'Tu as trouvé le numéro secret 3B.',
  winner_text text not null default 'Réponse correcte. Tu fais partie des cinq premiers gagnants.',
  wrong_text text not null default 'Réponse incorrecte. La transmission est terminée.',
  late_text text not null default 'Réponse correcte, mais les cinq gagnants ont déjà été validés.',
  duplicate_text text not null default 'Ce numéro a déjà participé à cette transmission.',
  updated_at timestamptz not null default now(),
  check (closes_at is null or opens_at is null or closes_at > opens_at)
);

create table if not exists public.secret3b_phone_attempts (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.secret3b_campaigns(id) on delete cascade,
  call_sid text not null,
  caller_hash text not null,
  digit text check (digit in ('1','2')),
  outcome text not null check (outcome in ('wrong','winner','correct_too_late')),
  winner_rank integer,
  created_at timestamptz not null default now(),
  unique (campaign_id, call_sid),
  unique (campaign_id, caller_hash),
  check ((outcome = 'winner' and winner_rank is not null) or (outcome <> 'winner' and winner_rank is null))
);

create unique index if not exists secret3b_phone_winner_rank_unique
  on public.secret3b_phone_attempts(campaign_id, winner_rank)
  where winner_rank is not null;

create index if not exists secret3b_phone_attempts_campaign_created_idx
  on public.secret3b_phone_attempts(campaign_id, created_at);

create table if not exists public.secret3b_phone_winners (
  attempt_id bigint primary key references public.secret3b_phone_attempts(id) on delete cascade,
  campaign_id bigint not null references public.secret3b_campaigns(id) on delete cascade,
  winner_rank integer not null,
  claim_token_hash text not null unique,
  caller_ciphertext text,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (campaign_id, winner_rank)
);

create index if not exists secret3b_phone_winners_campaign_idx
  on public.secret3b_phone_winners(campaign_id, created_at);

alter table public.secret3b_phone_contests enable row level security;
alter table public.secret3b_phone_attempts enable row level security;
alter table public.secret3b_phone_winners enable row level security;

revoke all on table public.secret3b_phone_contests from anon, authenticated;
revoke all on table public.secret3b_phone_attempts from anon, authenticated;
revoke all on table public.secret3b_phone_winners from anon, authenticated;

grant select, insert, update, delete on table public.secret3b_phone_contests to service_role;
grant select, insert, update, delete on table public.secret3b_phone_attempts to service_role;
grant select, insert, update, delete on table public.secret3b_phone_winners to service_role;
grant usage, select on sequence public.secret3b_phone_attempts_id_seq to service_role;

insert into public.secret3b_phone_contests(campaign_id, enabled, max_winners)
select id, false, 5
from public.secret3b_campaigns
where slug = 'telephone-secret-3b'
on conflict (campaign_id) do nothing;

create or replace function public.secret3b_claim_phone_answer(
  p_campaign_slug text,
  p_call_sid text,
  p_caller_hash text,
  p_digit text,
  p_claim_token_hash text,
  p_caller_ciphertext text default null
)
returns table(result text, winner_rank integer, max_winners integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_campaign_id bigint;
  v_status text;
  v_enabled boolean;
  v_correct_digit text;
  v_max_winners integer;
  v_opens_at timestamptz;
  v_closes_at timestamptz;
  v_existing public.secret3b_phone_attempts%rowtype;
  v_winner_count integer;
  v_attempt_id bigint;
  v_rank integer;
begin
  if coalesce(length(trim(p_campaign_slug)),0) = 0
     or coalesce(length(trim(p_call_sid)),0) = 0
     or coalesce(length(trim(p_caller_hash)),0) = 0
     or p_digit not in ('1','2') then
    return query select 'invalid'::text, null::integer, null::integer;
    return;
  end if;

  select c.id, c.status, pc.enabled, pc.correct_digit, pc.max_winners, pc.opens_at, pc.closes_at
    into v_campaign_id, v_status, v_enabled, v_correct_digit, v_max_winners, v_opens_at, v_closes_at
  from public.secret3b_campaigns c
  join public.secret3b_phone_contests pc on pc.campaign_id = c.id
  where c.slug = p_campaign_slug
  for update of pc;

  if not found then
    return query select 'unavailable'::text, null::integer, null::integer;
    return;
  end if;

  select * into v_existing
  from public.secret3b_phone_attempts
  where campaign_id = v_campaign_id and call_sid = p_call_sid;

  if found then
    return query select v_existing.outcome::text, v_existing.winner_rank, v_max_winners;
    return;
  end if;

  select * into v_existing
  from public.secret3b_phone_attempts
  where campaign_id = v_campaign_id and caller_hash = p_caller_hash;

  if found then
    return query select 'duplicate'::text, v_existing.winner_rank, v_max_winners;
    return;
  end if;

  if v_status <> 'active'
     or not v_enabled
     or v_correct_digit is null
     or (v_opens_at is not null and now() < v_opens_at)
     or (v_closes_at is not null and now() >= v_closes_at) then
    return query select 'unavailable'::text, null::integer, v_max_winners;
    return;
  end if;

  if p_digit <> v_correct_digit then
    insert into public.secret3b_phone_attempts(campaign_id, call_sid, caller_hash, digit, outcome)
    values(v_campaign_id, p_call_sid, p_caller_hash, p_digit, 'wrong');
    return query select 'wrong'::text, null::integer, v_max_winners;
    return;
  end if;

  select count(*)::integer into v_winner_count
  from public.secret3b_phone_attempts
  where campaign_id = v_campaign_id and outcome = 'winner';

  if v_winner_count >= v_max_winners then
    insert into public.secret3b_phone_attempts(campaign_id, call_sid, caller_hash, digit, outcome)
    values(v_campaign_id, p_call_sid, p_caller_hash, p_digit, 'correct_too_late');
    return query select 'correct_too_late'::text, null::integer, v_max_winners;
    return;
  end if;

  if coalesce(length(trim(p_claim_token_hash)),0) = 0 then
    return query select 'invalid'::text, null::integer, v_max_winners;
    return;
  end if;

  v_rank := v_winner_count + 1;

  insert into public.secret3b_phone_attempts(campaign_id, call_sid, caller_hash, digit, outcome, winner_rank)
  values(v_campaign_id, p_call_sid, p_caller_hash, p_digit, 'winner', v_rank)
  returning id into v_attempt_id;

  insert into public.secret3b_phone_winners(attempt_id, campaign_id, winner_rank, claim_token_hash, caller_ciphertext)
  values(v_attempt_id, v_campaign_id, v_rank, p_claim_token_hash, p_caller_ciphertext);

  return query select 'winner'::text, v_rank, v_max_winners;
end;
$$;

revoke all on function public.secret3b_claim_phone_answer(text,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.secret3b_claim_phone_answer(text,text,text,text,text,text) to service_role;
