begin;
create or replace function public.nexus_city_settings(p_user uuid,p_name text,p_visibility text) returns boolean language plpgsql security invoker set search_path='' as $$begin if p_visibility not in ('private','friends','public') then raise exception 'Visibilité invalide';end if;if length(trim(p_name))<2 or length(trim(p_name))>40 then raise exception 'Nom invalide';end if;update public.nexus_cities set name=trim(p_name),visibility=p_visibility,revision=revision+1,updated_at=now() where user_id=p_user;if not found then raise exception 'Ville introuvable';end if;return true;end;$$;
create or replace function public.nexus_city_unlock_district(p_user uuid,p_country text) returns boolean language plpgsql security invoker set search_path='' as $$declare cid uuid;xp bigint;threshold bigint;begin if p_country not in ('France','Italie','Estonie','Turquie','Algérie','Tunisie','Maroc','Espagne') then raise exception 'Quartier invalide';end if;select city_id into cid from public.nexus_cities where user_id=p_user for update;if cid is null then raise exception 'Ville introuvable';end if;select m.xp into xp from public.member_profiles m where m.user_id=p_user for update;threshold=case p_country when 'France' then 0 when 'Italie' then 1000 when 'Estonie' then 2000 when 'Turquie' then 3000 when 'Algérie' then 4000 when 'Tunisie' then 5000 when 'Maroc' then 6000 else 7000 end;if xp<threshold then raise exception 'XP insuffisante pour ce quartier';end if;update public.nexus_city_districts set unlocked=true,level=greatest(level,1),updated_at=now() where city_id=cid and country=p_country;update public.nexus_cities set revision=revision+1,updated_at=now() where city_id=cid;return true;end;$$;
create or replace function public.nexus_city_remove_display(p_user uuid,p_item uuid) returns boolean language plpgsql security invoker set search_path='' as $$declare cid uuid;begin select city_id into cid from public.nexus_cities where user_id=p_user for update;if cid is null then raise exception 'Ville introuvable';end if;delete from public.nexus_city_collectible_displays where city_id=cid and item_instance_id=p_item;if not found then raise exception 'Objet non exposé';end if;update public.nexus_cities set revision=revision+1,updated_at=now() where city_id=cid;return true;end;$$;
create or replace function public.nexus_city_visit(p_visitor uuid,p_city uuid) returns boolean language plpgsql security invoker set search_path='' as $$declare owner uuid;vis text;begin select user_id,visibility into owner,vis from public.nexus_cities where city_id=p_city for update;if owner is null or vis<>'public' then raise exception 'Ville non accessible';end if;if owner=p_visitor then return true;end if;insert into public.nexus_city_visits(city_id,visitor_id) values(p_city,p_visitor) on conflict(city_id,visitor_id) do update set visits=public.nexus_city_visits.visits+1,last_visit=now();update public.nexus_cities set visitors=visitors+1 where city_id=p_city;return true;end;$$;
revoke all on function public.nexus_city_settings(uuid,text,text),public.nexus_city_unlock_district(uuid,text),public.nexus_city_remove_display(uuid,uuid),public.nexus_city_visit(uuid,uuid) from public,anon,authenticated;grant execute on function public.nexus_city_settings(uuid,text,text),public.nexus_city_unlock_district(uuid,text),public.nexus_city_remove_display(uuid,uuid),public.nexus_city_visit(uuid,uuid) to service_role;
create or replace view public.nexus_city_discovery with(security_invoker=true) as select city_id,user_id,name,origin_country,visitors,updated_at,coalesce((city->>'level')::integer,1) level from public.nexus_cities where visibility='public';revoke all on public.nexus_city_discovery from public,anon;grant select on public.nexus_city_discovery to authenticated,service_role;
create index if not exists nexus_city_visits_recent_idx on public.nexus_city_visits(city_id,last_visit desc);
commit;
