begin;
alter table public.nexus_cities add column if not exists city_xp bigint not null default 0 check(city_xp>=0);alter table public.nexus_cities add column if not exists city_level integer not null default 1 check(city_level between 1 and 50);alter table public.nexus_cities add column if not exists land_tier integer not null default 1 check(land_tier between 1 and 10);alter table public.nexus_cities add column if not exists day_mode text not null default 'auto' check(day_mode in ('auto','day','night'));alter table public.nexus_cities add column if not exists weather text not null default 'clear' check(weather in ('clear','rain','fog','snow','storm'));alter table public.nexus_cities add column if not exists ambience text not null default 'matrix' check(ambience in ('matrix','gold','urban','cinematic','calm'));
create table if not exists public.nexus_city_journal(id bigint generated always as identity primary key,city_id uuid not null references public.nexus_cities(city_id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,action text not null,reference_id uuid,coins bigint not null default 0,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.nexus_city_favorites(user_id uuid not null references auth.users(id) on delete cascade,city_id uuid not null references public.nexus_cities(city_id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,city_id));
create table if not exists public.nexus_city_assets(code text primary key,asset_type text not null check(asset_type in ('garage','wardrobe','showcase','monument')),required_item_type text,required_rarity text,capacity integer not null default 1 check(capacity between 1 and 100),unlock_level integer not null default 1 check(unlock_level between 1 and 50),active boolean not null default true,metadata jsonb not null default '{}'::jsonb);
insert into public.nexus_city_assets values ('GARAGE_3B','garage','vehicle',null,8,4,true,'{}'),('DRESSING_3B','wardrobe','outfit',null,20,3,true,'{}'),('SHOWCASE_RARE','showcase',null,'rare',8,3,true,'{}'),('SHOWCASE_LEGENDARY','showcase',null,'legendary',5,6,true,'{}'),('SHOWCASE_UNIQUE','showcase',null,'unique',1,10,true,'{}') on conflict(code) do nothing;
insert into public.nexus_city_buildings(code,name,category,country,unlock_level,cost_coins,metadata) values
('HOME_MATRIX','Maison Matrix','home',null,2,120,'{"variants":["black","white","gold"]}'),('TOWER_3B','Tour 3B','home',null,7,1200,'{"variants":["matrix","champagne"]}'),('GARAGE_3B','Garage 3B','decoration',null,4,450,'{"asset":"garage"}'),('DRESSING_3B','Dressing 3B','decoration',null,3,350,'{"asset":"wardrobe"}'),('SHOWCASE_3B','Galerie Collection','culture',null,3,400,'{"asset":"showcase"}'),('BRIDGE_MATRIX','Pont Matrix','road',null,4,300,'{}'),('STADIUM_3B','Stade 3B','sport',null,9,2200,'{}'),('COMMUNITY_CENTER','Maison de la Communauté','community',null,5,700,'{}'),('FOUNTAIN_UNITY','Fontaine de l’Unité','decoration',null,4,500,'{}'),('GOLD_GATE_3B','Porte Or 3B','monument',null,7,1100,'{}'),('TREE_MATRIX','Arbre Matrix','nature',null,2,75,'{"variants":["blue","gold"]}'),('LIGHT_3B','Lampadaire 3B','decoration',null,2,50,'{"variants":["matrix","gold"]}') on conflict(code) do nothing;
update public.nexus_city_buildings set metadata=metadata||jsonb_build_object('permanent',true,'seasonal',false,'refundable_on_remove',false);
alter table public.nexus_city_journal enable row level security;alter table public.nexus_city_favorites enable row level security;alter table public.nexus_city_assets enable row level security;revoke all on public.nexus_city_journal,public.nexus_city_favorites,public.nexus_city_assets from public,anon,authenticated;grant select on public.nexus_city_journal,public.nexus_city_favorites,public.nexus_city_assets to authenticated;grant all on public.nexus_city_journal,public.nexus_city_favorites,public.nexus_city_assets to service_role;
create policy nexus_city_journal_own on public.nexus_city_journal for select to authenticated using(user_id=(select auth.uid()));create policy nexus_city_favorites_own on public.nexus_city_favorites for select to authenticated using(user_id=(select auth.uid()));create policy nexus_city_assets_read on public.nexus_city_assets for select to authenticated using(active=true);
create index if not exists nexus_city_journal_city_created_idx on public.nexus_city_journal(city_id,created_at desc);create index if not exists nexus_city_favorites_city_idx on public.nexus_city_favorites(city_id);
commit;
